### ISSUE TITLE
German Language Pack version number doesn't match VS Code version number

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode-loc#100]
Latest Visual Studio Code version is 1.37.1. The German Language Pack version is 1.38.0 and cannot be used when downloaded for offline install via VSIX file.

**Comment by janbaltus** [comment]
If you are using Vscode Insider you could use the 1.38.0 version.
For offical release please install extension from Extensions.
It will work with no issues.

**Comment by SetTrend** [comment]
@janbaltus :

I'm working for a governmental customer where development machines have no Internet access.

So, I can neither install an "unsafe" Insider build nor can I install extensions from the Extensions panel. I need to install extensions manually, after having them downloaded from another machine and verified.

This situation is true for many development environments in high security environments.

Please make sure the language pack version available for download always matches the current VS Code production build. Or provide a "download other version" link on Visual Studio Code Marketplace to be able to download older versions.

**Comment by janbaltus** [comment]
@weeteckt the way we publish LP is this. 3x per release and before oficial release we publish 2 versions of LP.
I am not aware of option how to publish new version of LP and still be able to let user choose the old one.

**Comment by weeteckt** [comment]
@SetTrend try this:

Ctrl+Shift+X
Right-Click on German Language Pack and you should see the option "Install Another Version..."



![LP_Version](https://user-images.githubusercontent.com/25108435/63604060-b9c93300-c57f-11e9-925d-22395ace09d0.PNG)

**Comment by weeteckt** [comment]
@SetTrend 

Alternatively, you could do this. Just modify the version to the one you need for example 1.37.5 as shown below.

https://marketplace.visualstudio.com/_apis/public/gallery/publishers/MS-CEINTL/vsextensions/vscode-language-pack-de/1.37.5/vspackage

**Comment by SetTrend** [comment]
@weeteckt:

- Try to unplug your LAN cable and disconnect your WLAN, then retry your [first suggestion](#issuecomment-524358491)
  Please read [my previous comment](#issuecomment-523926698).
- Are you going to publish the appropriate version number along with each release of Visual Studio Code in the future? Otherwise your [second comment](#issuecomment-524397334) is not a solution to the issue.

**Comment by SetTrend** [comment]
Thank you @weeteckt . Yes your second suggestion worked as a remedy for me.

Do you want me to close this issue or to keep it open as a reminder?
