### ISSUE TITLE
[de] Incorrect Iconography for Git SCM Commit button

### ISSUE THREAD

**Issue by LinqLover** [microsoft/vscode-loc#1005]
The git commit button looks like this:

![image](https://user-images.githubusercontent.com/38782922/185612109-76c6aded-e6be-437b-9958-b9372f133dd3.png)

Instead, the checkmark should be displayed on the left of the button without enclosing quotes.

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 694039).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 694039)
