### ISSUE TITLE
German Translation errors for remove conditional breakpoint dialog in JavaScript/TypeScript debugger

### ISSUE THREAD

**Issue by LinqLover** [microsoft/vscode-loc#1008]
> The following strings are incorrect and need to be replaced:
> 
> * `haltepunkt` -> `Haltepunkt` (has to start with first letter everywhere)
> * `Deaktivieren Haltepunkt` -> `Haltepunkt deaktivieren`

> > [Window Title]
> > Visual Studio Code
> > [Content]
> > Dieser haltepunkt hat eine Bedingung, die beim Entfernen verloren geht. Deaktivieren Sie stattdessen ggf. den haltepunkt.
> > ["Haltepunkt" entfernen] [Deaktivieren Haltepunkt] [Abbrechen]
> 
> ![image](https://user-images.githubusercontent.com/38782922/132558689-8fe72d55-32e8-45e8-b01b-c1d24978a0f3.png)
> 
> Raised when clicking on a disabled breakpoint that has a condition.

> * Culture: de-de
>   Current translation: "Dieser haltepunkt hat eine Bedingung, die beim Entfernen verloren geht. Deaktivieren Sie stattdessen ggf. den haltepunkt."
>   Requested translation: "Dieser Haltepunkt hat eine Bedingung, die beim Entfernen verloren geht. Deaktivieren Sie stattdessen ggf. den Haltepunkt."
> * Culture: de-de
>   Current translation: "Deaktivieren Haltepunkt"
>   Requested translation: "Haltepunkt deaktivieren"
> 
> String identifiers/English strings not known.

Originally reported in https://github.com/microsoft/vscode-loc/issues/223, but they could not help me, the strings are not in their database. So where are these strings from and could you please fix the translations? I could not even find them anywhere [on the entire Sourcegraph](https://sourcegraph.com/search?q=context:global+Dieser+haltepunkt+hat+eine+Bedingung&patternType=literal&case=yes)!

**Comment by TylerLeonhardt** [comment]
I’m transferring the string back to vscode-loc since we’ve located the string in question. Thanks @weinand!

**Comment by cristianosuzuki77** [comment]
This seems to be resolved in https://github.com/microsoft/vscode-loc-drop/blob/main/out/vscode-workbench/de/vs_workbench_contrib_debug.xlf#L25
