### ISSUE TITLE
[de-de] Wrong translation for "Continue"

### ISSUE THREAD

**Issue by TheVaan** [microsoft/vscode-loc#1019]
Hello,

this is the worst translation for "Continue", because "Weiterfahren" means continue driving a vehicle.
https://github.com/microsoft/vscode-loc/blob/d520357df3849af2ef4f7dcdfc873024faa39cd3/i18n/vscode-language-pack-de/translations/extensions/git.i18n.json#L12

It should be `{0} Fortsetzen` (same as in the tooltip):
https://github.com/microsoft/vscode-loc/blob/d520357df3849af2ef4f7dcdfc873024faa39cd3/i18n/vscode-language-pack-de/translations/extensions/git.i18n.json#L13

Additionally this one should be changed to:
https://github.com/microsoft/vscode-loc/blob/d520357df3849af2ef4f7dcdfc873024faa39cd3/i18n/vscode-language-pack-de/translations/extensions/git.i18n.json#L40
It should be something like:
`Erstellt ein Git-Repository unter '{0}'. Sind Sie sich sicher?`

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 698228).

**Comment by cristianosuzuki77** [comment]
698228 shows as fixed.
