### ISSUE TITLE
[zh-CN] Wrong translation git missing

### ISSUE THREAD

**Issue by zhangjian10** [microsoft/vscode-loc#1021]
The command [从市场]  does not work when git does not exist

`[从市场] 安装其他源代码管理提供程序(command:workbench.extensions.search?%22%40category%3A%5C%22scm%20providers%5C%22%22)` is incorrect and should be `[从市场] (command:workbench.extensions.search?%22%40category%3A%5C%22scm%20providers%5C%22%22) 安装其他源代码管理提供程序`

`view.workbench.scm.missing`  All have this problem

https://github.dev/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-zh-hans/translations/extensions/git.i18n.json#L572

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 701736).

**Comment by TylerLeonhardt** [comment]
It looks like this is addressed now from looking at [the strings](https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-zh-hans/translations/extensions/vscode.git.i18n.json#L546-L549).

I'll optimistically close this and if you still see issues, please reach out!
