### ISSUE TITLE
[fr] typo in miAuxiliaryBar

### ISSUE THREAD

**Issue by simonpct** [microsoft/vscode-loc#1026]
An `&` is missing in the mnemonic string **miAuxiliaryBar**.
```diff
			"hideAuxiliaryBar": "Masquer la barre latérale secondaire",
-			"miAuxiliaryBar": "Bar&re latérale secondaire",
+			"miAuxiliaryBar": "Bar&&re latérale secondaire",
			"miAuxiliaryBarNoMnemonic": "Afficher la barre latérale secondaire",
```
[https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-fr/translations/main.i18n.json#L2841](https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-fr/translations/main.i18n.json#L2841)

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 701739).

**Comment by cristianosuzuki77** [comment]
701739 shows as fixed.
