### ISSUE TITLE
[ru-RU] Incorrect translation for "Super" button

### ISSUE THREAD

**Issue by TeslaSesla** [microsoft/vscode-loc#1029]
The "Super" button don't need to be translated
At the moment it translated as "Превосходно"

![изображение](https://user-images.githubusercontent.com/32602991/187531287-9769d449-f1f3-4af4-bd33-a06b59076978.png)

https://github.dev/microsoft/vscode-loc/blob/577f9f8cfff7463752d72e1060528e87cdcf6448/i18n/vscode-language-pack-ru/translations/main.i18n.json#L160-L161

**Comment by TeslaSesla** [comment]
```
"superKey": "Super",
"superKey.long": "Super",
```

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 701740).
