### ISSUE TITLE
All entries in the Git menu turns English in v.1.38.2 in Traditional Chinese

### ISSUE THREAD

**Issue by MuTsunTsai** [microsoft/vscode-loc#103]
As shown; it wasn't the case in v.1.38.1

![1](https://user-images.githubusercontent.com/39870664/64288898-cb560600-cf95-11e9-8d4c-78e52ae2d02e.png)

Also the "Message (Ctrl + Enter to commit on 'master')" at the input field and the "CHANGES" underneath it was never translated.

**Comment by ckytx** [comment]
Chinese (Simplified) has same issue.
vscode version 1.38.0

**Comment by MuTsunTsai** [comment]
@ckytx It works indeed, which would imply that the same issue applies to all extensions, not just Git, and perhaps to more languages than just Chinese. This would certainly require a quick fix.

**Comment by janbaltus** [comment]
this is known issue and we are working on new LP.

**Comment by janbaltus** [comment]
please see https://github.com/microsoft/Localization/issues/77

**Comment by janbaltus** [comment]
please use 1.38.3 version of LP

**Comment by MuTsunTsai** [comment]
@janbaltus  v.1.38.3 is still the same; nothing changes in the Git menu.

**Comment by janbaltus** [comment]
Please try 1.38.4 version where this issue is fixed.

**Comment by MuTsunTsai** [comment]
> Please try 1.38.4 version where this issue is fixed.

Confirmed.
