### ISSUE TITLE
[ja] Incorrect translations

### ISSUE THREAD

**Issue by Uhucream** [microsoft/vscode-loc#1038]
Below translation is incorrect.

https://github.com/microsoft/vscode-loc/blob/567eeb26e1721dcb9c6d29d59cc9687dfc843114/i18n/vscode-language-pack-ja/translations/main.i18n.json#L3128

I think correct translation is below

```suggestion
"joinEditorInGroup": "グループ内のエディターを結合する", 
```

Because this string is used as command string which joins split 2 columns / rows editor into 1 group.

このコマンドを実行すると、2つに分割されていたエディターを1つに統合する挙動になるので、"参加" では不適切では、と思います。

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 702197).

**Comment by cristianosuzuki77** [comment]
702197 shows as fixed.
