### ISSUE TITLE
Turkish Language Pack Visual Studio Code 1.71 Support

### ISSUE THREAD

**Issue by FrozenOfficialGITHUB** [microsoft/vscode-loc#1039]
No support for Visual Studio Code 1.71

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 703614).

**Comment by cristianosuzuki77** [comment]
@TylerLeonhardt could you assist here please?

**Comment by TylerLeonhardt** [comment]
@FrozenOfficialGITHUB I see 1.71 builds published to the marketplace here:
https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-tr

**Comment by FrozenOfficialGITHUB** [comment]
Thanks!
