### ISSUE TITLE
简体中文中，1053行翻译错误

### ISSUE THREAD

**Issue by zhangzhonghe** [microsoft/vscode-loc#104]
在简体中文版中，第1053行的“背景颜色”应该翻译成”前景颜色“。

**Comment by zwuis** [comment]
Please speak English. @zhangzhonghe

**Comment by janbaltus** [comment]
Please provide English + screnshot from localized build

**Comment by zhangzhonghe** [comment]
![TIM图片20190917160015](https://user-images.githubusercontent.com/38434641/65023197-eb59d200-d964-11e9-9f55-16fa23ccc333.png)
As shown, just a small error

**Comment by lukaschal** [comment]
Fixed in a MLCP.
