### ISSUE TITLE
[ja] translation suggestion for "branch"

### ISSUE THREAD

**Issue by kagankan** [microsoft/vscode-loc#1042]
The translation file contains a mixture of 分岐 and ブランチ as translations of "branch" (git)

I propose to unify them into ブランチ which is more natural.

分岐 appears these lines:

https://github.com/microsoft/vscode-loc/blob/4d07ffe8f29f36b8c7ba5322e8a92b22f6afb602/i18n/vscode-language-pack-ja/translations/extensions/git.i18n.json#L77
https://github.com/microsoft/vscode-loc/blob/4d07ffe8f29f36b8c7ba5322e8a92b22f6afb602/i18n/vscode-language-pack-ja/translations/extensions/git.i18n.json#L78
https://github.com/microsoft/vscode-loc/blob/4d07ffe8f29f36b8c7ba5322e8a92b22f6afb602/i18n/vscode-language-pack-ja/translations/extensions/git.i18n.json#L325

My suggestion:

```json
"create branch": "新しいブランチの作成...",
```

```json
"create branch from": "新しいブランチの作成元...",
```

```json
"command.branch": "ブランチの作成...",
```

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 705153).

**Comment by csigs** [comment]
Resolved as Fixed & Verify.
