### ISSUE TITLE
[ja] translation suggestion for "stash"

### ISSUE THREAD

**Issue by kagankan** [microsoft/vscode-loc#1043]
"stash" (git) is currently translated to 一時退避
(This line is an example. There are many other lines containing 一時退避)

https://github.com/microsoft/vscode-loc/blob/4d07ffe8f29f36b8c7ba5322e8a92b22f6afb602/i18n/vscode-language-pack-ja/translations/extensions/git.i18n.json#L405

However, it seems unnatural.
I suggest to use スタッシュ as translation of "stash", instead of 一時退避

For example, Soucetree also uses スタッシュ as translation of "stash"

![image](https://user-images.githubusercontent.com/34136752/189480055-ffadbcfb-4972-44fd-87b3-34de5116b614.png)

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 705154).

**Comment by cristianosuzuki77** [comment]
This shows as resolved.
