### ISSUE TITLE
[fr] Small translation error of filter input placeholder

### ISSUE THREAD

**Issue by tcastanie** [microsoft/vscode-loc#1044]
Hello,

The `node_modules/` folder is literal translated.

![image](https://user-images.githubusercontent.com/4352517/189498207-b65d2263-bd7e-4eca-82fb-603570bed4b5.png)

https://github.com/microsoft/vscode-loc/blob/4d07ffe8f29f36b8c7ba5322e8a92b22f6afb602/i18n/vscode-language-pack-fr/translations/main.i18n.json#L6575

It should be :

```diff
-			"markers.panel.filter.placeholder": "Filtre (exemple : texte, **/*.ts, !**/modules_nœud/**)",
+			"markers.panel.filter.placeholder": "Filtre (exemple : texte, **/*.ts, !**/node_modules/**)",
```

Thanks for your work :)

**Comment by csigs** [comment]
Resolved as Fixed & Verify.
