### ISSUE TITLE
[es-es] Incorrect localization of config "Workbench Editor Wrap Tabs" description

### ISSUE THREAD

**Issue by pafernandez-oesia** [microsoft/vscode-loc#1057]
Hi,

The description for configuration option **Workbench > Editor: Wrap Tabs** has an incorrect localization in Spanish. The correct translation for "tabs" in this context is "pestañas", instead of "tabulaciones", which is used for tab characters.

Description in **VS Code 1.71.2**:
```
Controla si las tabulaciones deben ajustarse en varias líneas al superar el espacio disponible o si debe mostrarse una barra de desplazamiento en su lugar. Este valor se omite cuando "#workbench.editor.showTabs#" está deshabilitado.
```

Proposed translation:
```
Controla si las pestañas deben ajustarse en varias líneas al superar el espacio disponible o si debe mostrarse una barra de desplazamiento en su lugar. Este valor se omite cuando "#workbench.editor.showTabs#" está deshabilitado.
```

Translation string:
https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-es/translations/main.i18n.json#L3689

Regards,

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 711979).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 711979)

**Comment by pafernandez-oesia** [comment]
Thank you 😉
