### ISSUE TITLE
Add hindi language pack

### ISSUE THREAD

**Issue by ashusharmasigdev** [microsoft/vscode-loc#1058]
Hi,
There are very much **hindi speaking native peoples** that uses vscode, i am one of them, i want to see vscode in hindi also, but i can't find how can i create a locale package, following the readme, this repo will not accept any pull request, anyway i want to see hindi in vscode. may you add it, or let me do it.
Thanks.

**Comment by crsuzukimsft** [comment]
Thank you for your feedback and offer! We will review the ask for adding additional languages to VS Code.

**Comment by RanjeetSingh00** [comment]
@ashusharmasigdev  Right, I am also in the support of it (adding hindi locale),

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 711980)
