### ISSUE TITLE
[ja] translation suggestion for "files.autoSave.onWindowChange"

### ISSUE THREAD

**Issue by ba230t** [microsoft/vscode-loc#1065]
The following two lines have the same translation text which means:
> An editor with changes is automatically saved when the **EDITOR** loses focus.

https://github.com/microsoft/vscode-loc/blob/4d07ffe8f29f36b8c7ba5322e8a92b22f6afb602/i18n/vscode-language-pack-ja/translations/main.i18n.json#L6172-L6173

So, the latter (`"files.autoSave.onWindowChange"`) translation is more appropriate if changed as follows

wrong:
"files.autoSave.onWindowChange": "エディターがフォーカスを失うと、変更のあった**エディター**が自動的に保存されます。", 
correct:
"files.autoSave.onWindowChange": "エディターがフォーカスを失うと、変更のあった**ウィンドウ**が自動的に保存されます。",

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 714032).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 714032)
