### ISSUE TITLE
[fr] Bad translation for "Transform to Kebab Case"

### ISSUE THREAD

**Issue by QuentinLemCode** [microsoft/vscode-loc#1067]
Hello

The translation for "Transform to kebab case" in French is not accurate.

The english translation would mean "Transform to kebab management"

The good translation is **"Transformer en kebab case"**

![image](https://user-images.githubusercontent.com/3814031/192570264-4d8cf1d5-fe92-406c-9527-edb40fdfdefc.png)

**Comment by QuentinLemCode** [comment]
https://github.com/microsoft/vscode-loc/pull/1068

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 714490).

**Comment by crsuzukimsft** [comment]
Hello @QuentinLemCode Thank you for the suggestion for fix. As per readme file, translation updates must be done via ticket issue, instead of pr.
I am addressing your request internally but you may want to abandon this pr meanwhile.

**Comment by csigs** [comment]
Resolved as Duplicate.
