### ISSUE TITLE
Typo in pl/miViewTesting translation

### ISSUE THREAD

**Issue by Velciak** [microsoft/vscode-loc#1077]
There is typo in [`pl/miViewTesting`](https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-pl/translations/main.i18n.json#L9349) translation: ampersand character and reduntant `r` character.

**Currently:** `T&estrowanie`
**Should be:** `Testowanie`

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 716991).

**Comment by cristianosuzuki77** [comment]
716991 shows as fixed.
