### ISSUE TITLE
[zh-CN] inaccurate translation for "Create new branch"

### ISSUE THREAD

**Issue by phbice** [microsoft/vscode-loc#1084]
The option "Create new branch" in the command palette is translated into "正在创建新分支". That is inaccurate and should be translated into "创建新分支".
![image](https://user-images.githubusercontent.com/38395456/194248253-b9055589-72c6-4e49-9de1-a50c7afc43b7.png)

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 719450).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 719450)
