### ISSUE TITLE
[zh-TW] "Tag" should be translated into "標籤" instead of "標記".

### ISSUE THREAD

**Issue by hwhsu1231** [microsoft/vscode-loc#1086]
### Descriptions

There is a missing translation about **"Tag"**.

- English String: **Git: Delete Tag**
- Current Translation: **Git: 刪除標記**
- Suggested Translation: **Git: 刪除標籤**

### Versions

- Chinese (Traditional) Language Pack: **v1.72.10051006**

### Screenshots

![image](https://user-images.githubusercontent.com/71438617/194708368-4e0c9864-2a33-4d38-a731-1f969b73fcae.png)

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 720420).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 720420)
