### ISSUE TITLE
[fr] Edit Sessions

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-loc#1087]
In the feature "Edit Sessions", "Edit" is being used as a noun. In the French translation, it is translated inconsistently sometimes as a verb and sometimes with just different "synonyms".
<img width="450" alt="image" src="https://user-images.githubusercontent.com/6561887/194961111-e6566eb0-d5b2-4203-a10b-4186d4d25dc3.png">

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 721332).

**Comment by TylerLeonhardt** [comment]
@joyceerhl could you maybe add a comment for these commands that says that `Edit` is noun in this case?

**Comment by joyceerhl** [comment]
`Edit sessions` have all been renamed to `Cloud changes`, but maybe `changes` needs to be marked as a noun rather than verb here?

**Comment by TylerLeonhardt** [comment]
Ah ok so this is no longer valid. Let's close this out and just wait to see if someone reports `changes` being translated to a verb instead of a noun.
