### ISSUE TITLE
[IT] edit readme

### ISSUE THREAD

**Issue by lonasozo** [microsoft/vscode-loc#1094]
Hello everyone, checking README I'm here to propose few changes on text: 

https://github.com/microsoft/vscode-loc/blob/28304faae2c93581fdf2b2fa1b306c1d1526a0d6/i18n/vscode-language-pack-it/README.md?plain=1#L14

To this (Issue is the "technical" name of the function on Github, I think it's correct to mantain it):
```
Per un feedback sul miglioramento della traduzione, creare una issue nel repository [vscode-loc](https://github.com/microsoft/vscode-loc).
```

https://github.com/microsoft/vscode-loc/blob/28304faae2c93581fdf2b2fa1b306c1d1526a0d6/i18n/vscode-language-pack-it/README.md?plain=1#L16

To this:
```
Le stringhe di traduzione vengono gestite in Microsoft Localization Platform. È possibile apportare modifiche solo in Microsoft Localization Platform ed esportarle nel repository vscode-loc. Di conseguenza, le richieste pull non verranno accettate nel repository vscode-loc.
```

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 724390).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 724390)
