### ISSUE TITLE
[zh-hans] Missing "Release:" in the about dialog

### ISSUE THREAD

**Issue by Crystal-RainSlide** [microsoft/vscode-loc#1106]
This line:

https://github.com/microsoft/vscode-loc/blob/a3546bdf6409449e313c7583bb5061e27163953f/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L4005

Should become:
``` JSON
"aboutDetail": "版本: {0}\r\n发布版本: {1}\r\n提交: {2}\r\n日期: {3}\r\nElectron: {4}\r\nChromium: {5}\r\nNode.js: {6}\r\nV8: {7}\r\n操作系统: {8}\r\n沙盒化: {9}",
```

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 726679).

**Comment by v-mholloway** [comment]
@Crystal-RainSlide your suggested translation is missing the {1} placeholder.
If I look at the corresponding English string (below)... then your suggestion would use the 'version' value in for the 'commit' value.

can you confirm this is correct..?

Version: {0}
Commit: {1}
Date: {2}
Electron: {3}
Chromium: {4}
Node.js: {5}
V8: {6}
OS: {7}
Sandboxed: {8}

**Comment by Crystal-RainSlide** [comment]
My bad, corrected.
<table>
<thead><tr><th>Simplified Chinese</th><th>English</th></tr></thead>
<tbody><tr><td><pre>版本: {0}
发布版本: {1}
提交: {2}
日期: {3}
Electron: {4}
Chromium: {5}
Node.js: {6}
V8: {7}
操作系统: {8}
沙盒化: {9}</pre></td><td><pre>
Version: {0}
Release: {1}
Commit: {2}
Date: {3}
Electron: {4}
Chromium: {5}
Node.js: {6}
V8: {7}
OS: {8}
Sandboxed: {9}</pre></td></tr></tbody>
</table>
