### ISSUE TITLE
[zh-cn] Translation error for "Close to the Right"

### ISSUE THREAD

**Issue by YtotheWT** [microsoft/vscode-loc#1128]
The current translation "关闭到右侧" is difficult to understand. The suggested translation is "关闭右侧标签页".

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 732734).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 732734)
