### ISSUE TITLE
[ru] Wrong translation for "Copy" action

### ISSUE THREAD

**Issue by vanelizarov** [microsoft/vscode-loc#1129]
In Russian the word "Копирование" describes process of copying, not action itself. Better to say "Копировать" or "Скопировать"

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 733039).

**Comment by crsuzukimsft** [comment]
Thank you. Team will review it and later address it.

**Comment by csigs** [comment]
Resolved as Won't Fix.
