### ISSUE TITLE
[zh-CN]  MD syntax error on "html.format.indentInnerHtml"

### ISSUE THREAD

**Issue by islinxuan** [microsoft/vscode-loc#1130]
In html-language-features.i18n.json，

 ```
 "html.format.indentInnerHtml.desc": "缩进 \"<head>\" 和 \"<body>\" 部分。",
  ```
  
  make the result of **缩进 \"<head>\" 和 \"<body>\" 部分。**.

 It shoule be 

```
"html.format.indentInnerHtml.desc": "缩进 `<head>` 和 `<body>` 部分。",
```

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 733142).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 733142)
