### ISSUE TITLE
[ru] Add English versions of VS Code commands

### ISSUE THREAD

**Issue by yakovmanshin** [microsoft/vscode-loc#1145]
## Problem
Consider the following scenario:
1. You install VS Code, and it defaults to English;
2. You don’t speak English and want to install a language pack;
3. The [`README`](https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-ru/README.md) file gives you the instructions but lists the Russian command name («Настроить язык отображения»);
4. VS Code does not show up the command in search results unless the Russian language pack is already installed.

![](https://user-images.githubusercontent.com/4648742/200084383-50173eb9-bfc8-480f-a8fc-e9b7cbc1133a.png)

## Suggestion
Add the command name in English (“Configure Display Language”) after the name in Russian, so the user can try it instead.

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 737042).

**Comment by crsuzukimsft** [comment]
Hello @TylerLeonhardt , could you please review this ask?
