### ISSUE TITLE
Korean localization error

### ISSUE THREAD

**Issue by CookieHCl** [microsoft/vscode-loc#115]
Currently using Korean Language Pack for Visual Studio Code 1.38.4

-------------------------

**Korean Language Pack for Visual Studio Code**에 오타가 있습니다.
editor.**formatOnSaveTimeout** 설정 설명이

- 파일 저장 시 실행되는 서식 지정이 취소되기 전까의 제한 시간(밀리초)입니다.

라고 되어있는데

- 파일 저장 시 실행되는 서식 지정이 취소되기 전까**지**의 제한 시간(밀리초)입니다.

로 고쳐야 합니다.

-------------------------

There's a typo in **Korean Language Pack for Visual Studio Code**.
In Settings, currently explanation of editor.**formatOnSaveTimeout** is

- 파일 저장 시 실행되는 서식 지정이 취소되기 전까의 제한 시간(밀리초)입니다.

but you should change to

- 파일 저장 시 실행되는 서식 지정이 취소되기 전까**지**의 제한 시간(밀리초)입니다.

**Comment by lukaschal** [comment]
Fixed as suggested in a MLCP.
