### ISSUE TITLE
[zh-CN] The top menu "new folder" translated incorrect.

### ISSUE THREAD

**Issue by doubaozia** [microsoft/vscode-loc#1158]
![image](https://user-images.githubusercontent.com/12318032/201023334-5d96852f-8b14-4eae-8688-2994e4518f29.png)

**Comment by doubaozia** [comment]
![image](https://user-images.githubusercontent.com/12318032/201052479-9926d8e8-dd86-4f07-a298-aaf00fbad0a1.png)
When i change the "newFile" translation value, the UI show as above.
![image](https://user-images.githubusercontent.com/12318032/201052853-b767928d-3909-4f3e-b5ca-78832f34abc0.png)
But the en language shows as expected.

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 740849).

**Comment by doubaozia** [comment]
Updated: I update the theia core extensions from 1.19.0 to 1.20.0 and use vscode-loc 1.53.2 solved this problem, but some top menus are still not fully transformed.

**Comment by crsuzukimsft** [comment]
thank you [doubaozia](https://github.com/doubaozia). Could you list out what is not correct  and what would be the expected translation?

**Comment by doubaozia** [comment]
![image](https://user-images.githubusercontent.com/12318032/201866250-394cf168-7a83-42cf-820a-da4e41f76549.png)
As the image shows, top menus should end with a brackets and a letter，but some are not. Some submenus are not translated.
dependencies:
    "@theia/callhierarchy": "1.20.0",
    "@theia/console": "1.20.0",
    "@theia/core": "1.20.0",
    "@theia/debug": "1.20.0",
    "@theia/editor": "1.20.0",
    "@theia/editor-preview": "1.20.0",
    "@theia/file-search": "1.20.0",
    "@theia/filesystem": "1.20.0",
    "@theia/getting-started": "1.20.0",
    "@theia/git": "1.20.0",
    "@theia/keymaps": "1.20.0",
    "@theia/markers": "1.20.0",
    "@theia/messages": "1.20.0",
    "@theia/metrics": "1.20.0",
    "@theia/mini-browser": "1.20.0",
    "@theia/monaco": "1.20.0",
    "@theia/navigator": "1.20.0",
    "@theia/outline-view": "1.20.0",
    "@theia/output": "1.20.0",
    "@theia/preferences": "1.20.0",
    "@theia/preview": "1.20.0",
    "@theia/process": "1.20.0",
    "@theia/scm": "1.20.0",
    "@theia/search-in-workspace": "1.20.0",
    "@theia/task": "1.20.0",
    "@theia/terminal": "1.20.0",
    "@theia/typehierarchy": "1.20.0",
    "@theia/userstorage": "1.20.0",
    "@theia/variable-resolver": "1.20.0",
    "@theia/vsx-registry": "1.20.0",
    "@theia/workspace": "1.20.0",
    "@theia/plugin": "1.20.0",
    "@theia/plugin-ext": "1.20.0",
    "@theia/plugin-ext-vscode": "1.20.0",
vscode-language-pack-zh-hans version: 1.53.2.
I have tried several versions and the version 1.53.2 are the most matched one.

**Comment by crsuzukimsft** [comment]
@TylerLeonhardt Could you help with the last comment from this thread? It seems the hotkeys for certain menu items in zh-hans are not visible. I checked in the loc side for any hotkey missing in vs_platform.xlf but didn't find any. Thank you.

**Comment by TylerLeonhardt** [comment]
@doubaozia sorry, you mention Theia... Are you actually using Visual Studio Code or a different application? `vscode-language-pack-zh-hans` is made to work with VS Code. It's possible that these other items are contributed by this other software that you are using.

**Comment by cristianosuzuki77** [comment]
Unlinking this feedback with 740849. If this requires localization in msft, please open a new ticket with the actual hotkeys that need fixing.

**Comment by doubaozia** [comment]
I updated the version to 1.35.0 and use the newest loc-vscode solved this.

**Comment by TylerLeonhardt** [comment]
I'll go ahead and close this then. Let us know if you still see any issues.
