### ISSUE TITLE
the speed of downloading extension is too slow

### ISSUE THREAD

**Issue by goodnighteveryone** [microsoft/vscode-loc#116]
Issue Type: <b>Performance Issue</b>

I try to download java extension pack,but the speed of downloading is too slow,so what should I do to  improve speed?

Extension version: 1.39.3
VS Code version: Code 1.39.0 (9df03c6d6ce97c6645c5846f6dfa2a6a7d276515, 2019-10-09T06:58:04.439Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.14.105-19-0006

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (4.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 49.232.141.47|
|OS|Linux x64 4.14.105-19-0006|
|CPUs|Intel(R) Xeon(R) CPU E5-26xx v4 (1 x 2399)|
|Memory (System)|1.82GB (0.76GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    99	 13064	code main
    0	    59	  1752	   window (undefined)
    0	   138	  1768	   window (欢迎使用 - Visual Studio Code)
    0	    92	  7936	     extensionHost
    1	   140	  4608	   gpu-process
    0	    13	  7316	   electron-crash-reporter
    1	    70	  8096	   window (问题报告程序)
    2	   168	  8376	   window (Extension: Python Extension Pack - Visual Studio Code)
    0	     6	  1928	     winpty-process
    0	     8	  1968	       console-window-host (Windows internal process)
    0	     3	  2360	       C:\Windows\System32\cmd.exe /c (type "C:\Users\ZHAIBO~1\AppData\Local\Temp\vscode-linux-multi-line-command-49.232.141.47-254178403.sh" | ssh -T -D 49783 ubuntu@49.232.141.47 bash) & exit /b 0
    0	     9	 12992	         ssh  -T -D 49783 ubuntu@49.232.141.47 bash
    0	    82	 13232	     extensionHost
    0	    76	 12060	   shared-process

Remote: SSH: 49.232.141.47
CPU %	Mem MB	   PID	Process
    0	     0	  5078	remote agent
    0	     0	  5127	   extensionHost
    0	     0	  5267	     /home/ubuntu/.vscode-server/bin/9df03c6d6ce97c6645c5846f6dfa2a6a7d276515/node /home/ubuntu/.vscode-server/bin/9df03c6d6ce97c6645c5846f6dfa2a6a7d276515/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=5127
    0	     0	  5580	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  5581	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```

|  Remote: SSH: 49.232.141.47;
```

</details>

**Comment by janbaltus** [comment]
@goodnighteveryone  please log this request under https://github.com/Microsoft/vscode
This is repo for localization only.

**Comment by AmmarHasan688** [comment]
its late but for anyone have this probleme usgin cloud flare DNS would solve the probleme and get you the full speed
