### ISSUE TITLE
Broken link formatting in the Czech localisation of the Jupyter extension

### ISSUE THREAD

**Issue by mmotejlek** [microsoft/vscode-loc#1163]
The Czech localisation file package.nls.cs.json contains many links which have a space between the brackets containing text and the link address (e.g. `[protokolu] (command:jupyter.viewOutput)` instead of `[protokolu](command:jupyter.viewOutput)`), so they are not recognized as links and are incorrectly displayed (for example in error messages).

Jupyter Extension Version: 2022.9.1202862440

Czech Language Pack Version: 1.74.11100235

Original issue: https://github.com/microsoft/vscode-jupyter/issues/11937

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 740972).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 740972)
