### ISSUE TITLE
Error while installing 'Portuguese (Brazil) Language Pack for Visual Studio Code' extension. Please check the log for more details.

### ISSUE THREAD

**Issue by gui-lherme** [microsoft/vscode-loc#1169]
16/11/2022 02:38:09 - Microsoft VSIX Installer
16/11/2022 02:38:09 - -------------------------------------------
16/11/2022 02:38:09 - vsixinstaller.exe version:
16/11/2022 02:38:09 - 16.8.3036
16/11/2022 02:38:09 - -------------------------------------------
16/11/2022 02:38:09 - Command line parameters:
16/11/2022 02:38:09 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\usuario\Desktop\MS-CEINTL.vscode-language-pack-pt-BR-1.74.11100236.vsix
16/11/2022 02:38:09 - -------------------------------------------
16/11/2022 02:38:09 - Microsoft VSIX Installer
16/11/2022 02:38:09 - -------------------------------------------
16/11/2022 02:38:09 - Skipping product Microsoft.VisualStudio.Product.BuildTools (8a33a546) since it does not support extensions
16/11/2022 02:38:09 - Initializing Install...
16/11/2022 02:38:09 - Detalhes da Extensão...
16/11/2022 02:38:09 - 	Identifier         : vscode-language-pack-pt-BR
16/11/2022 02:38:09 - 	Name               : Portuguese (Brazil) Language Pack for Visual Studio Code
16/11/2022 02:38:09 - 	Author             : MS-CEINTL
16/11/2022 02:38:09 - 	Version            : 1.74.11100236
16/11/2022 02:38:09 - 	Description        : Language pack extension for Portuguese (Brazil)
16/11/2022 02:38:09 - 	Locale             : en-US
16/11/2022 02:38:09 - 	MoreInfoURL        : 
16/11/2022 02:38:09 - 	InstalledByMSI     : False
16/11/2022 02:38:09 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
16/11/2022 02:38:09 - 
16/11/2022 02:38:09 - 	SignatureState     : Unsigned
16/11/2022 02:38:09 - 	Produtos com Suporte : 
16/11/2022 02:38:09 - 		Microsoft.VisualStudio.Code
16/11/2022 02:38:09 - 			Version : 
16/11/2022 02:38:09 - 
16/11/2022 02:38:09 - 	Referências        : 
16/11/2022 02:38:09 - Detalhes da Assinatura…
16/11/2022 02:38:09 - 	Extension is not signed.
16/11/2022 02:38:09 - 
16/11/2022 02:38:09 - Pesquisando produtos aplicáveis...
16/11/2022 02:38:09 - Produto instalado encontrado - Local Global
16/11/2022 02:38:09 - VSIXInstaller.NoApplicableSKUsException: Uma ou mais extensões são para o Visual Studio Code. Tente instalá-las no Visual Studio Code.
   em VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   em VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   em VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   em VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   em VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   em VSIXInstaller.App.Initialize()
   em System.Threading.Tasks.Task`1.InnerInvoke()
   em System.Threading.Tasks.Task.Execute()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 742799).

**Comment by crsuzukimsft** [comment]
Hi @TylerLeonhardt , could you please check this ticket?

**Comment by csigs** [comment]
Investigated by Loc Team: It's not a translation issue. (Reference id: 742799)

**Comment by TylerLeonhardt** [comment]
@gui-lherme how are you installing this extension? It looks like you're trying to install the Visual Studio Code language pack in Visual Studio but that's a different application.

**Comment by gui-lherme** [comment]
> @gui-lherme how are you installing this extension? It looks like you're trying to install the Visual Studio Code language pack in Visual Studio but that's a different application.

Yes you're right. I was able to install it now.
