### ISSUE TITLE
Spelling inconsistencies:  Repository -> リポジトリ or レポジトリ

### ISSUE THREAD

**Issue by yutotnh** [microsoft/vscode-loc#1177]
This is the only sentence where the repository is translated as レポジトリ.

I would like to change レポジトリ to リポジトリ in the sentence below.

https://github.com/microsoft/vscode-loc/blob/fb96175e2c73351ee81fcfe2683428ec3df16e39/i18n/vscode-language-pack-ja/translations/extensions/vscode.git.i18n.json#L399

In other texts it is translated as リポジトリ.

https://github.com/microsoft/vscode-loc/blob/fb96175e2c73351ee81fcfe2683428ec3df16e39/i18n/vscode-language-pack-ja/translations/extensions/vscode.github.i18n.json#L23

https://github.com/microsoft/vscode-loc/blob/fb96175e2c73351ee81fcfe2683428ec3df16e39/i18n/vscode-language-pack-ja/translations/extensions/vscode.git.i18n.json#L400

The number of レポジトリ and リポジトリ in this repository is:
- レポジトリ: 1
- リポジトリ: 117

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 745317).

**Comment by csigs** [comment]
Resolved as Won't Fix.
