### ISSUE TITLE
[es-ES] Error de traducción en diálogo de enviar múltiples ficheros a la papelera de reciclaje

### ISSUE THREAD

**Issue by lgleznah** [microsoft/vscode-loc#1182]
¡Buenos días!

Estoy viendo un error de traducción similar al que ya reporté en #794, solo que esta vez ocurre con el diálogo de eliminar elementos moviéndolos a la papelera de reciclaje, no con el diálogo de eliminarlos permanentemente:

![imagen](https://user-images.githubusercontent.com/36040102/203616016-42701147-2ae9-43a2-8c42-c17ba02ab727.png)

De manera similar, el texto no debería ser "¿Está seguro de que desea eliminar los siguientes archivos 2?", sino "¿Está seguro de que desea eliminar los siguientes 2 archivos?

La solución, similarmente también, debería ser cambiar la entrada `confirmMoveTrashMessageMultiple` del archivo `main.i18n.json`, cambiándola de:

`¿Está seguro de que desea eliminar los siguientes archivos {0}?`

a:

`¿Está seguro de que desea eliminar los siguientes {} archivos?`

Muchas gracias de nuevo, ¡y un saludo 👋!

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 746207).

**Comment by v-mholloway** [comment]
@lgleznah Can you please provide your feedback in English so we can triage the request properly...?

**Comment by lgleznah** [comment]
Indeed!

I'm observing a mistranslation similar to the one I reported in #794, though this time it is present in the "move multiple elements to the recycling bin" prompt, instead of the "remove multiple elements permanently" prompt:

![](https://user-images.githubusercontent.com/36040102/203616016-42701147-2ae9-43a2-8c42-c17ba02ab727.png)

The solution, similarly too, would be to change the `confirmMoveTrashMessageMultiple` entry in the `main.i18n.json` file of the Spanish localization folder, changing its value from:

`¿Está seguro de que desea eliminar los siguientes archivos {0}?`

to:

`¿Está seguro de que desea eliminar los siguientes {0} archivos?`

Thanks a lot, and cheers 👋!

**Comment by csigs** [comment]
Resolved as Won't Fix.
