### ISSUE TITLE
[ja] "の" is enough to connect "とじしろ" and "折りたたみ".

### ISSUE THREAD

**Issue by yutotnh** [microsoft/vscode-loc#1186]
"の" is enough to connect "とじしろ" and "折りたたみ".

**Current (Wrong)**
![image](https://user-images.githubusercontent.com/57719497/204014773-6e4cc77b-3c22-4ef7-9ace-06c26782ed56.png)

**After (Correct)**
![image](https://user-images.githubusercontent.com/57719497/204013952-18e4fc7f-feff-4004-8417-cd35efc046f1.png)

Line 516 of `i18n/vscode-language-pack-ja/translations/main.i18n.json`

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 746908).

**Comment by csigs** [comment]
Resolved as Won't Fix.
