### ISSUE TITLE
[ru-RU] 2 ampersands in the menu item `View>Sticky Scroll`

### ISSUE THREAD

**Issue by rFLY** [microsoft/vscode-loc#1188]
![2ampersands](https://user-images.githubusercontent.com/1749404/204073268-f7917432-8db7-45f6-8a02-e03b36d4e9a4.png)
Maybe it's line 1293 of the main.i18n.json file:
`"vs/editor/contrib/stickyScroll/browser/stickyScrollActions": {
	"miStickyScroll": "&&&Залипание прокрутки",
	"toggleStickyScroll": "Переключить залипание прокрутки",
	"view": "Просмотр"
}
`

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 747016).
