### ISSUE TITLE
更新 vscode 1.74.0（最新版）后中文全部失效

### ISSUE THREAD

**Issue by CoffeeSwt** [microsoft/vscode-loc#1207]
更新 vscode 1.74.0（最新版）后中文全部失效
After updating vscode 1.74.0 (the latest version), all Chinese will become invalid
![image](https://user-images.githubusercontent.com/83854560/206676889-e5cf306a-e347-4632-81ed-155dd6fbf0e8.png)

VsCode版本信息 
VsCode version information
![image](https://user-images.githubusercontent.com/83854560/206677121-908876bd-8716-4d83-a973-af573f494810.png)

中文都失效了，请问我该如何解决？
Chinese is invalid, how can I solve it?

期待回复，非常感谢！
Looking forward to your reply, thank you very much!

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 752687).

**Comment by TylerLeonhardt** [comment]
It looks like you may be experiencing:
https://github.com/microsoft/vscode/issues/154417

If you make sure you have the latest version of the Chinese language pack, set the language to Chinese, and then restart VS Code, it should resolve.

**Comment by PromiseAll** [comment]
我也是更新遇到这个问题，不过   使用 ctrl+p   选 Configure Display Language   在弹出的语言中，选中zh-cn   然后重启vsCode就好了
