### ISSUE TITLE
[ko] Translation suggestion

### ISSUE THREAD

**Issue by quiple** [microsoft/vscode-loc#1210]
https://github.com/microsoft/vscode-loc/blob/4ce2e09a74bda39a843431201e5b79863ec14d05/i18n/vscode-language-pack-ko/translations/main.i18n.json#L4438

It's hard to understand what `"시작하여 해제하거나 [[표시 안 함]] 다시 시작합니다."` means.

It's like `"Start to dismiss or [[Don't show]], restart."`. The word "typing" is missing and the sentence is unnatural.

I propose `"[[언어 선택]] 또는 [[다른 편집기 열기]]를 선택하여 시작합니다.\r\n입력을 시작하여 해제하거나 이 메시지를 다시 [[표시하지 않습니다]]."`

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 753447).

**Comment by cristianosuzuki77** [comment]
753447 shows as fixed.
