### ISSUE TITLE
[ja] Typo in restarting dialog of display language

### ISSUE THREAD

**Issue by yu-miura** [microsoft/vscode-loc#1216]
There's a typo in "i18n/vscode-language-pack-ja/translations/main.i18n.json".

```
"vs/workbench/contrib/localization/electron-sandbox/localeService": {
                        // ...
			"restart": "と再起動(&R)",
```

"と" isn't needed.

![dialog_when_switching_display_language](https://user-images.githubusercontent.com/9346110/207851508-23f0a195-0cad-4d5b-b07c-3a575e79aa5f.png)

**Comment by cristianosuzuki77** [comment]
not repo.
