### ISSUE TITLE
Typos in french main.i18n.json

### ISSUE THREAD

**Issue by echoix** [microsoft/vscode-loc#122]
There are some typos in the already translated strings found in the file `i18n/vscode-language-pack-fr/translations/main.i18n.json`. Since it is a automatically generated file, I can't submit a pull request, I imagine there is another location where the database needs to be updated first.

1. `"editorOverviewRulerBorder": "Couleur de la bordure de la règle d'apperçu."` should be `"editorOverviewRulerBorder": "Couleur de la bordure de la règle d'aperçu."`
1. `"trimAutoWhitespace": "Supprimer l'espace blanc de fin inséré automatiquement."` should be `"trimAutoWhitespace": "Supprimer l'espace blanc de fin insérée automatiquement."`
1. `"editor.autoClosingQuotes.languageDefined": "Utilisez les configurations de langage pour déterminer quand fermer automatiquement les guillements."` should be  `"editor.autoClosingQuotes.languageDefined": "Utilisez les configurations de langage pour déterminer quand fermer automatiquement les guillemets."`
1. `"editor.autoClosingQuotes.beforeWhitespace": "Fermer automatiquement les guillements uniquement lorsque le curseur est à gauche de l’espace."` should be `"editor.autoClosingQuotes.beforeWhitespace": "Fermer automatiquement les guillemets uniquement lorsque le curseur est à gauche de l’espace."`
1. `"installExtension": "Installe ou met à jour l'extension. Utilisez l'argument '--force' pour éviter les messages de confirmation."` should be `"installExtension": "Installe ou mets à jour l'extension. Utilisez l'argument '--force' pour éviter les messages de confirmation."`
1. `"badgeBackground": "Couleur de fond des badges. Les badges sont de courts libelés d'information, ex. le nombre de résultats de recherche.",` should be `"badgeBackground": "Couleur de fond des badges. Les badges sont de courts libellés d'information, ex. le nombre de résultats de recherche.",`
1. `"badgeForeground": "Couleur des badges. Les badges sont de courts libelés d'information, ex. le nombre de résultats de recherche.",` should be `"badgeForeground": "Couleur des badges. Les badges sont de courts libellés d'information, ex. le nombre de résultats de recherche.",`
1. At the following keys, `liste/aborescence` should be ` liste/arborescence` (the third occurence is mispelled). Since each string are long, I will not repeat them.
   - `"listFocusBackground"`
   - `"listFocusForeground"`
   - `"listActiveSelectionForeground"`
   - `"listInactiveSelectionBackground"`
   - `"listInactiveSelectionForeground"`
   - `"listInactiveFocusBackground"`
1. `"sendWorkspaceInfo": "Inclure des metadonnées sur mon espace de travail ({0})",` should be `"sendWorkspaceInfo": "Inclure des métadonnées sur mon espace de travail ({0})",`
1. `"restoreWindows": "Contrôle la façon dont les fenêtres sont réouvertes après un redémarrage.",` should be `"restoreWindows": "Contrôle la façon dont les fenêtres sont rouvertes après un redémarrage.",`
1. Not a typo, but a bad translation, using windows as the operating system instead of a program's opened windows. In english, the text is `"Controls whether closing the last editor should also close the window. This setting only applies for windows that do not show folders.`. `"closeWhenEmpty": "Contrôle si la fermeture du dernier doit également fermer la fenêtre. Ce paramètre s’applique uniquement pour windows, qui n'affiche pas de dossiers.",` should be `"closeWhenEmpty": "Contrôle si la fermeture du dernier doit également fermer la fenêtre. Ce paramètre s’applique uniquement pour les fenêtres qui n'affichent pas de dossiers.",`.
1. Also a bad translation, where "opening settings" means to open the settings, instead of the settings that control the way something is opened. English text is `"Controls whether opening settings also opens an editor showing all default settings."`. `"openDefaultSettings": "Contrôle si les paramètres d’ouverture ouvre également un éditeur affichant tous les paramètres par défaut.",` should be `"openDefaultSettings": "Contrôle si ouvrir les paramètres ouvre également un éditeur affichant tous les paramètres par défaut.",`
1. `"statusBarNoFolderBorder": "Couleur de la bordure qui sépare la barre latérale et l’éditeur lorsque aucun dossier ne s’ouvre la barre d’état. La barre d’état s’affiche en bas de la fenêtre.",` should be `"statusBarNoFolderBorder": "Couleur de la bordure qui sépare la barre latérale et l’éditeur lorsqu’aucun dossier ne s’ouvre la barre d’état. La barre d’état s’affiche en bas de la fenêtre.",`
1. `"schema.folding.offSide": "Un langage adhère à la règle du hors-champ si les blocs dans ce langage sont exprimées par leur indentation. Si spécifié, les lignes vides appartiennent au bloc suivant.",` should be `"schema.folding.offSide": "Un langage adhère à la règle du hors-champ si les blocs dans ce langage sont exprimés par leur indentation. Si spécifié, les lignes vides appartiennent au bloc suivant.",`
1. I might be missing some context, but I don't think there is a reason for the second word to be capitalized. All other short strings with two words only have the first letter of the first word capitalized. So, `"loadedScripts": "Scripts Chargés",` should be `"loadedScripts": "Scripts chargés",`
1. The strings from the following keys seam incorrect when looking at the English string: `removeExcludeItem`, `editExcludeItem`, `editExcludeItemInSettingsJson`. However, I'm missing context to understand what is an "Exclude Item". What is for sure is that `exclude` in `"editExcludeItemInSettingsJson": "Modifier l'élément exclude dans settings.json",` is incorrect and should be `exclu` or `exclus`. It should be fixed by someone at the same time these three keys are updated.
1. Bad translation: `"JsonSchema._runner": "Le runner est dégradé. Utiliser la propriété runner officielle",` should be `"JsonSchema._runner": "Le runner est gradué. Utiliser la propriété runner officielle",`. However, even the English string is weirdly worded : `'The runner has graduated. Use the offical runner property'`
1. `"JsonSchema.tasks.quoting.escape": "Echappe les caractères à l’aide du caractère d’échappement du shell (par exemple: ` sous PowerShell et \\ sous bash).",` should be `"JsonSchema.tasks.quoting.escape": "Échappe les caractères à l’aide du caractère d’échappement du shell (par exemple: ` sous PowerShell et \\ sous bash).",`
1. `"terminal.ansiColor": "Couleur ansi '{0}' dans le terminal."` should be `"terminal.ansiColor": "Couleur ANSI '{0}' dans le terminal."`
1. `"vscode.extension.contributes.languages.mimetypes": "Types MIME associés au langue.",` should be `"vscode.extension.contributes.languages.mimetypes": "Types MIME associés au langage.",` to match the term used in the surrounding strings with a key starting with `vscode.extension.contributes.languages.`

I'm sorry for the formatting of this issue, but I think it is the easiest for you to fix when the complete line including the key is present.

This is not a full, in-deep proof-reading of the strings, it is only the most obvious typos I found by reading the full file and using advanced proofreading tools, like Antidote to spot problems.

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
Fixed as suggested.

**Comment by echoix** [comment]
Should next time I need to suggest changes like this, in an issue, or make a pull request of the .json file directly? Was this a format that was the easiest to fix? What is the best way adapted to your workflow?

**Comment by janbaltus** [comment]
UNfortunately the MLCP tool does not allow direct editing of localized strings. https://github.com/Microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project

**Comment by echoix** [comment]
> UNfortunately the MLCP tool does not allow direct editing of localized strings. https://github.com/Microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project

I don't see what that wiki page answers for this question, sorry. When there are some suggestions and edits in the already localized strings, should I enter them as an issue with a description like this, or I make a pull request and you try to pull the corrections from the diff?

**Comment by janbaltus** [comment]
Please log an issue for translation suggestions
