### ISSUE TITLE
[zh-TW] Suggest that "Source File/Code" be translated into "來源檔/碼".

### ISSUE THREAD

**Issue by hwhsu1231** [microsoft/vscode-loc#1220]
### Suggestion

* **English String:** Source File/Code
* **Current Translation:** 原始檔/碼
* **Suggest Translation:** 來源檔/碼

Although **"原始檔/碼"** is conventional and historical for translation of **"Source File/Code"** in zh-TW locale, I highly suggest that **"Source File/Code"**  be translated into **"來源檔/碼"**. The followings are the reasons:

1.  In Chinese, **"Source"** is more proper to be translated into **"來源"** instead of **"原始"**. For example:

    * Light Source: 光源
    * Data Source: 資料來源
    * Download Source: 下載來源

2.  I noticed that sometimes people in zh-TW locale may say **"開源軟體"** for **"Open Source Software"** because **"開放原始碼軟體"** is too long to say. However, **"開源"** is actually the term from zh-CN locale, and the term **"開源"** is short for **"開放源代碼"** or **"開放源碼"**. If **"Source File/Code"** can be translated into **"來源檔/碼"**, then it will be fine to say **"開源"** in zh-TW locale since we can think it as the short for **"開放來源碼"**.

3.  I noticed that **"File Explorer"** of Windows on zh-TW locale translates **"Source File"** into **"來源檔案"**.

    ![image](https://user-images.githubusercontent.com/71438617/208311436-f9239f5a-236b-45d2-b878-483cc9777e03.png)

4.  In VSCode, there is a function called **"Header/Source"**, which is translated into **"標頭/來源"** currently.

    ![image](https://user-images.githubusercontent.com/71438617/208311646-f30553c1-3858-4435-8f4a-67763f3ee7dc.png)

### Version

* **zh-TW:** `v1.74.12140936`

### Screenshots

![image](https://user-images.githubusercontent.com/71438617/208311747-7eb37e9b-bfb4-47c8-ab73-706f4aecf081.png)

**Comment by hwhsu1231** [comment]
Allow me to emphasize again. I understand that **"原始檔/碼"** is conventional and historial for **"Source File/Code"** in zh-TW locale. However, I just think that maybe it is time to replace this unproper translation.

**Comment by hwhsu1231** [comment]
BTW, I think that **"原始"** should be corresponded to **"Raw"** or **"Original"**. For example:

* Original Data: 原始資料
* Raw Socket: 原始套接字 or 原始插座
* Raw String: 原始字串

**Comment by cristianosuzuki77** [comment]
Tracking via 926541. Closing as this reference is not traceable back here.
