### ISSUE TITLE
中文翻译有误

### ISSUE THREAD

**Issue by zsynacl** [microsoft/vscode-loc#124]
![图片](https://user-images.githubusercontent.com/4392800/69914519-63259c00-1480-11ea-8bf5-d2e89eafb6c1.png)

此处的“关注链接”翻译有误

**Comment by lukaschal** [comment]
CHS. On review.

SRC: Follow link
TGT: 关注链接

**Comment by zsynacl** [comment]
“转到链接”更合适

**Comment by lukaschal** [comment]
Fixed.

new tgt: 转到链接
