### ISSUE TITLE
[zh-TW] Suggest that "Release Notes" be translated into "發行備註".

### ISSUE THREAD

**Issue by hwhsu1231** [microsoft/vscode-loc#1248]
### Suggestion

* **English String:** Release Notes
* **Current Translation:** 版本資訊
* **Suggested Translation:** 發行備註

The detailed reason is based on this article written by @zerng07:

* http://breezymove.blogspot.com/2023/01/release-note-candidate.html

Other reference:

* LibreOffice: https://zh-tw.libreoffice.org/download/release-notes/
* Debian: https://www.debian.org/releases/etch/releasenotes.zh-tw.html

BTW, if **"Release Note"** is translated into **"版本資訊"**, it is possible for users to translate it back to English into **"Version Information"**. It is because **"Version"** and **"Information"** are normally translated into **"版本"** and **"資訊"**, respectively. That is really confusing.

### Version

* **zh-TW:** `v1.74.12140936`

### Screenshots

![image](https://user-images.githubusercontent.com/71438617/211188441-88da6b7e-4ad0-44a3-b84f-b064a77a4b69.png)
![image](https://user-images.githubusercontent.com/71438617/211279782-ee2b93e5-fc05-4bd9-b701-142676be0e27.png)
![image](https://user-images.githubusercontent.com/71438617/211279802-665b09c4-14b7-44de-b906-20cb76c8db8a.png)

**Comment by cristianosuzuki77** [comment]
Tracking via 926538. Closing this ticket since the other reference is not traceable back here.
