### ISSUE TITLE
[ja] translation suggestion

### ISSUE THREAD

**Issue by gematsu** [microsoft/vscode-loc#125]
Issue Type: <b>Bug</b>

When the updater service finished downloading the patch and demand relaunching VS Code, we can choose [later].
Current Japanese translation of [later] feature is "後続", but it seems a bit strange. How about using "後で" or "今はしない" instead of using "後続"?

Extension version: 1.40.2
VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

**Comment by lukaschal** [comment]
On review.

src: Later
tgt: 後続

**Comment by lukaschal** [comment]
Fixed.

new tgt: 後で
