### ISSUE TITLE
[zh-TW] Suggest that "Preferences" be translated into "偏好設定".

### ISSUE THREAD

**Issue by hwhsu1231** [microsoft/vscode-loc#1259]
### Suggestion

* **English String:** Preferences
* **Current Translation:** 喜好設定
* **Suggested Translation:** 偏好設定

Honestly in terms of _meaning_, "Preferences" can be translated into "偏好" or "喜好".

The reason why I tend to use "偏好" is because the _prononciation_.

In 漢語拼音(HanYuPinYin), the prononciation of "偏(Pian)" is similar to "Preference". They all started with "P".

### Other References

* https://github.com/rogeraabbccdd/GitKraken-zh-tw/issues/17
* [467767: l10n(zh_TW): Fix translations of 'Preferences' | Qt Code Review](https://codereview.qt-project.org/c/qt-creator/qt-creator/+/467767)

### Version

* **zh-TW:** `v1.74.12140936`

### Screenshots

![image](https://user-images.githubusercontent.com/71438617/212457601-dd4b9895-851a-40f8-b170-de678e8b014b.png)

**Comment by hwhsu1231** [comment]
The followings are the list of software translating **"Preferences"** into **"偏好設定"** in zh-TW locale:

* Notepad++
* Typora
* Poedit
* PotPlayer
* Google Drive

### Screenshots

![image](https://user-images.githubusercontent.com/71438617/217239188-ea5e2c02-6079-4c28-87f5-135be69979c4.png)
![image](https://user-images.githubusercontent.com/71438617/217239214-47faf42c-c578-4f0d-833d-018bb1b1847c.png)
![image](https://user-images.githubusercontent.com/71438617/217239224-6cfc0162-d3e4-4004-a511-337c9a1b9a00.png)
![image](https://user-images.githubusercontent.com/71438617/217239238-ca110466-efb7-451b-9f79-c31523fc1889.png)
![image](https://user-images.githubusercontent.com/71438617/217239771-50842e50-fe4d-4a83-aadf-9a7c2b565b28.png)

**Comment by cristianosuzuki77** [comment]
Tracking via 926534. Since the item 926534 is not traceable from here, I'll close this ticket.

**Comment by cristianosuzuki77** [comment]
Per translators feedback, the current translation will be kept until further revision.
