### ISSUE TITLE
[ja] Incorrect translation for "restart"

### ISSUE THREAD

**Issue by somoriiin** [microsoft/vscode-loc#1263]
### Summary
I found this one on the pop-up window when I change Japanese language setting to English.

![image](https://user-images.githubusercontent.com/29141720/214084748-37ecdafc-9f07-4901-a648-cde4285525f9.png)

### Suggestion
i18n/vscode-language-pack-ja/translations/main.i18n.json
line.6738
`"restart": "と再起動(&R)",`

It should be like this: 
`"restart": "再起動",`

### Details 
VScode Version
> バージョン: 1.74.3 (user setup)
> コミット: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
>  日付: 2023-01-09T16:59:02.252Z
> Electron: 19.1.8
> Chromium: 102.0.5005.167
> Node.js: 16.14.2
> V8: 10.2.154.15-electron.0
> OS: Windows_NT x64 10.0.22000
> Sandboxed: No

#### Steps to find this issue

1. Ctrl+Shift+P
2. Input "display"
3. Click "Configure Display Language"
4. Click "日本語 (ja)"
5. restart
6. Ctrl+Shift+P
7. Input "display"
8. Click "Configure Display Language"
9. Click "English (en)"
10. You can see the issue such as the image

**Comment by cristianosuzuki77** [comment]
This seems to be resolved.

**Comment by somoriiin** [comment]
Thank you so much!
