### ISSUE TITLE
Chinese (Simplified) Language Pack for Visual Studio Code don't work

### ISSUE THREAD

**Issue by FangHanZreo** [microsoft/vscode-loc#127]
Issue Type: <b>Bug</b>

File -> New Window make my language pack don't work . I need restart vscode.

Extension version: 1.41.1
VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by janbaltus** [comment]
Please try to update LP to 1.41.2.
Verified on 1.41 version with 1.41.2 LP and no crash for Chinese (Simplified) Language Pack
