### ISSUE TITLE
How to use vscode-loc in a source-code-built vscode ?

### ISSUE THREAD

**Issue by WangXuhaoInSuda** [microsoft/vscode-loc#1272]
Hi!
I can't activate my zh-cn extension by using VSIX for my source-code-built vscode.
Dragging it into the extension folder is also no working. : (
Is that disabled or something wrong with the vscode I built?

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 779281).

**Comment by cristianosuzuki77** [comment]
@TylerLeonhardt Hi, could you assist in here? Thank you.

**Comment by TylerLeonhardt** [comment]
@WangXuhaoInSuda can you please confirm that you built the Code OSS package and are not just running out of sources?

Also, does installing the extension via the UI of Code OSS work? Install from VSIX:

![Image](https://user-images.githubusercontent.com/2644648/221706282-229b785e-aa77-4355-af41-ad59d0310310.png)
