### ISSUE TITLE
[zh-CN] Suggest that "completions" be translated into "补全列表"

### ISSUE THREAD

**Issue by sinsong** [microsoft/vscode-loc#1273]
about config item: `editor.wordBasedSuggestions`

src: https://github.com/microsoft/vscode/blob/be6992bf64edf0c690419986f774a30db926fa33/src/vs/editor/common/config/editorConfigurationSchema.ts#L66

exist translation:

https://github.com/microsoft/vscode-loc/blob/5f6b707a26f76cd999da513efa829ca199afe5b8/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L269

suggestion:

```
控制是否根据文档中的字词计算自动补全列表。
```

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 779282).

**Comment by sinsong** [comment]
seems fixed https://github.com/microsoft/vscode-loc/blob/ddd7174069c9d981d0bacbc23fe74de3112ec706/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L319C44-L319C44
