### ISSUE TITLE
[fr-FR] Why is this one word in all caps?

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-loc#1274]
In `vs/workbench/contrib/logs/common/logsActions` `"off": "DESACTIVÉ",`:

```
      <trans-unit id="off">
        <source xml:lang="en">Off</source>
        <target state="translated">DESACTIVÉ</target>
      </trans-unit>
```

When in the source it is normal cased?

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 779283).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 779283)
