### ISSUE TITLE
[zh-TW] Suggest that "Log/Logging (n.)" be translated into "日誌".

### ISSUE THREAD

**Issue by hwhsu1231** [microsoft/vscode-loc#1275]
### Suggestion

* **English String:** Log/Logging (n.)
* **Current Translation:** 記錄/紀錄
* **Suggested Translation:** 日誌

The detailed reason is based on this article written by @zerng07:

* [Record 紀錄, Log 日誌, Journal 系統日誌/日誌](http://breezymove.blogspot.com/2023/02/record-log-journal.html)

### Version

* **zh-TW:** `v1.75.2023020809`

### Screenshots

![image](https://user-images.githubusercontent.com/71438617/218061222-15d5dca1-92fd-4f3b-be08-d499a55baaec.png)

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 780456).

**Comment by csigs** [comment]
Resolved as Won't Fix.

**Comment by hwhsu1231** [comment]
> Resolved as Won't Fix.

Why?

**Comment by hwhsu1231** [comment]
@csigs 

Another reference data is based on: [國家教育院-樂詞網](https://terms.naer.edu.tw/search/?query_term=log&query_field=title&query_op=&match_type=phrase&filter_bool=and&filter_term=%27%E9%9B%BB%E5%AD%90%E8%A8%88%E7%AE%97%E6%A9%9F%E5%90%8D%E8%A9%9E%27&filter_field=subcategory_1.raw&filter_op=term&tabaction=browse)

As we can see, most of them are translated into "日誌".

![image](https://user-images.githubusercontent.com/71438617/218970184-60536078-d8de-4c0f-8ce8-0c160022f523.png)
