### ISSUE TITLE
[zh-TW] Suggest that "Comment" be translated into "註釋".

### ISSUE THREAD

**Issue by hwhsu1231** [microsoft/vscode-loc#1276]
### Suggestion

* **English String:** Comment
* **Current Translation:** 註解
* **Suggested Translation:** 註釋

The detailed reason is based on this article written by @zerng07:

* [Annotation 註解, Comment 評註](http://breezymove.blogspot.com/2023/02/annotation-comment.html)

> 還有一種常見情況，是程式語言中，撰寫程式碼時可以針對所寫部分程式碼留下文字說明的 Comment。這個情況下和 Annotation 作用相當，都是註解的意思。此時譯者只能自己取捨是要用評註或是註解了，或是選擇改用「註釋」，和註解同義，但至少得以和註解作不明顯的區分，避開可能的碰撞（但不推薦，容易發生混淆）。本人依然推薦優先譯為評註，此時 Comment 為前述第三種意義，代表除了寫下解釋說明外，同時也包含了可以留下評語。

Instead, **"Annotation"** should be the one translated into **"註解"**.

### Version

* **zh-TW:** `v1.75.2023020809`

### Screenshots

![image](https://user-images.githubusercontent.com/71438617/218064031-d6eaa80f-e3b9-42ed-bae7-6f90da5a07bc.png)

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 780646).

**Comment by csigs** [comment]
Resolved as Won't Fix.

**Comment by hwhsu1231** [comment]
> Resolved as Won't Fix.

Why?
