### ISSUE TITLE
[zh-Hans] Wrong translation.

### ISSUE THREAD

**Issue by YaoweiZou** [microsoft/vscode-loc#1286]
I found four translation errors.

setting: workbench.list.horizontalScrolling
english: Controls whether lists and trees support horizontal scrolling in the workbench. Warning: turning on this setting has a performance implication.
error: 控制列表和树是否支持工作台中的水平滚动。警告: 打开此设置影响会影响性能。
suggest: 控制工作台上的列表和树是否支持水平滚动。警告：打开此设置会影响性能。

---

setting: workbench.editor.labelFormat.long
english: Show the name of the file followed by its absolute path.
error: 在文件的绝对路径之后显示文件名。
suggest: 显示文件名后跟其绝对路径。

---

setting: workbench.editor.labelFormat.medium
english: Show the name of the file followed by its path relative to the workspace folder.
error: 在文件相对当前工作区文件夹的路径之后显示文件名。
suggest: 显示文件名及其相对于工作区文件夹的路径。

---

setting: workbench.editor.labelFormat.short
english: Show the name of the file followed by its directory name.
error: 在文件的目录名之后显示文件名。
suggest: 显示文件名后跟其目录名。

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 786518).
