### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by Rmtdi** [microsoft/vscode-loc#1290]
有关错误提示 jsonc(514)的”预期有逗号“，个人感觉翻译的不恰当，第一次见到楞了一会儿才理解原理是前面缺了个逗号。
建议翻译为”附近应该缺少一个逗号“或者”缺少预期的逗号“之类的。望采纳。

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 788897).

**Comment by v-mholloway** [comment]
@Rmtdi can you supply your comments in 
english to allow us to process the issue?

**Comment by pigbayspy** [comment]
> 

the error tip about jsonc(514) is  ”预期有逗号“(Expected comma) which might be incorrect.
”附近应该缺少一个逗号“ or ”缺少预期的逗号“(Expected comma is missing) are easier to be understood
