### ISSUE TITLE
When opening a new window, the language plug-in does not take effect in the new window

### ISSUE THREAD

**Issue by AppleOfGray** [microsoft/vscode-loc#1298]
The first window is in Chinese, and there is no problem. After opening a new window, the new window does not automatically load Chinese plug-ins, but is still an English button

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 795192).

**Comment by cristianosuzuki77** [comment]
@TylerLeonhardt Could you please assist here?

**Comment by TylerLeonhardt** [comment]
@AppleOfGray I'm not able to reproduce this... are you able to see 1 window in Chinese and 1 window in English at the same time?

Did you see this around the same time VS Code updated to a new version?

**Comment by AppleOfGray** [comment]
Now Version Info:
```
版本: 1.76.1 (user setup)
提交: 5e805b79fcb6ba4c2d23712967df89a089da575b
日期: 2023-03-08T16:32:00.131Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19044
沙盒化: No

---

已发布
2018/4/24 01:35:37
上次发布时间
2023/3/8 17:32:49
上次更新时间
2023/3/9 09:12:56
标识符
ms-ceintl.vscode-language-pack-zh-hans
```
After updating to the latest version this morning, 
this phenomenon cannot be repeated. 
I will close this issue .
Thank you for your reply

**Comment by AppleOfGray** [comment]
Now Version Info:
```
版本: 1.76.1 (user setup)
提交: 5e805b79fcb6ba4c2d23712967df89a089da575b
日期: 2023-03-08T16:32:00.131Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19044
沙盒化: No

---

已发布
2018/4/24 01:35:37
上次发布时间
2023/3/8 17:32:49
上次更新时间
2023/3/9 09:12:56
标识符
ms-ceintl.vscode-language-pack-zh-hans
```
After updating to the latest version this morning, 
this phenomenon cannot be repeated. 
I will close this issue .
Thank you for your reply
