### ISSUE TITLE
Korean is not displayed.

### ISSUE THREAD

**Issue by funnycom** [microsoft/vscode-loc#1302]
Type: <b>Bug</b>

It does not switch to Korean menu after updating vs code,. The Korean language pack is installed, and I re-run the program several times, but it does not return to Korean UI. 

![vs-bug](https://user-images.githubusercontent.com/5915404/224619579-306049f7-4b2e-4307-82bb-0741202f17f3.png)

Extension version: 1.76.2023030809
VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.22624
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.90GB (5.38GB free)|
|Process Argv|--crash-reporter-id 007bf942-3ecb-4e92-ab82-faefbf02ac5b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30681850
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
f6dab269:30613381
vscrpc:30673769
pythonsymbol12:30671437
a9j8j154:30646983
6233i204:30672705
vsccsb:30677849
funwalk2:30682974

```

</details>

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 797604).

**Comment by cristianosuzuki77** [comment]
@TylerLeonhardt could you please assist here?

**Comment by TylerLeonhardt** [comment]
@funnycom when you open the command palette (`ctrl`+`shift`+`p`) and run `Configure Display Language`, and choose Korean, does that help?

**Comment by funnycom** [comment]
Finally I can see Korean. I think it should be set automatically since the Korean pack extension is installed,
