### ISSUE TITLE
Specificity translated in HTML but not CSS

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-loc#1307]
Testing microsoft/vscode#172045

From a CSS file
<img width="182" alt="image" src="https://user-images.githubusercontent.com/6561887/214397687-c21ea459-2624-4f54-b3ce-3447e94ef823.png">

From an HTML file
<img width="188" alt="image" src="https://user-images.githubusercontent.com/6561887/214397600-557275f3-de08-43df-a248-e1ccc43aa106.png">

**Comment by TylerLeonhardt** [comment]
<img width="696" alt="image" src="https://user-images.githubusercontent.com/2644648/227057351-1aefb97a-35bd-41bd-b0ca-8c8e97dd03c9.png">

@cristianosuzuki77 to the rescue!

**Comment by TylerLeonhardt** [comment]
Language Pack released. When verifying, ensure you have the lastest language pack.
