### ISSUE TITLE
[ja]: backtick is lacking in some translation（コードブロックが平文字列になっている部分あり）

### ISSUE THREAD

**Issue by manjuu-eater** [microsoft/vscode-loc#1312]
- English:
In description of setting `window.title`, markdown back quote is missing or changed to normal quote.
Some code span is not converted.

- Japanese:
設定の`window.title`の解説文で、マークダウンのバッククォートが消滅orただのクォーテーションに変化しているところがあります。
一部のコードブロックが未変換のままです。

![image](https://user-images.githubusercontent.com/88940383/227910174-742b73c2-b9eb-4244-a134-ef9411915feb.png)

https://github.com/microsoft/vscode-loc/blob/c72c5dac9f5551d317eb1111f8ffd90f2b82725b/i18n/vscode-language-pack-ja/translations/main.i18n.json#L3786

Before:
<details>
		"vs/workbench/browser/workbench.contribution": {
			"activeEditorLong": "`${activeEditorLong}`: ファイルの完全なパス (例: /Users/Development/myFolder/myFileFolder/myFile.txt)。",
			"activeEditorMedium": "`${activeEditorMedium}`: ワークスペース フォルダーに対して相対的なファイルのパス (例: myFolder/myFileFolder/myFile.txt)。",
			"activeEditorShort": "'${activeEditorShort}': ファイル名 (例: myFile.txt)。",
			"activeFolderLong": "'${activeFolderLong}': ファイルが格納されているフォルダーのフルパス (例: /Users/Development/myFolder/myFileFolder)。",
			"activeFolderMedium": "`${activeFolderMedium}`: ファイルを含むフォルダーの、ワークスペースフォルダーからの相対パス(例: myFolder/myFileFolder)。",
			"activeFolderShort": "`${activeFolderShort}`: ファイルが含まれているフォルダーの名前 (例: myFileFolder)。",
			"activityBarIconClickBehavior": "ワークベンチのアクティビティ バー アイコンをクリックする動作を制御します。",
			"activityBarVisibility": "ワークベンチでのアクティビティ バーの表示をコントロールします。",
			"appName": "`${appName}`: 例: VS Code。",
			"centeredLayoutAutoResize": "複数のグループが開かれているとき、中央揃えのレイアウトを自動的に横幅最大にするかどうかを制御します。1 つのグループのみが開かれている場合は、元の中央揃えの横幅に戻ります。",
			"centeredLayoutDynamicWidth": "ウィンドウのサイズを変更するときに、中央のレイアウトで一定の幅を維持するかどうかを制御します。",
			"closeEmptyGroups": "空のエディターのグループにある最後のタブを閉じたときの動作を制御します。有効であるとき、空のグループは自動的に閉じられます。無効であるとき、空のグループはグリッドの一部として残ります。",
			"closeOnFileDelete": "セッション中のファイルを表示しているエディターが、その他のプロセスによって削除されるか名前を変更された場合に、エディターを自動的に閉じるかどうかを制御します。これを無効にすると、このような場合にエディターを開き続けます。アプリケーション内で削除すると、エディターは常に閉じられ、変更が保存されていないエディターのデータを保存して閉じることはありません。",
			"closeOnFocusLost": "フォーカスを失ったときに Quick Open を自動的に閉じるかどうかを制御します。",
			"commandHistory": "コマンド パレットで最近使用したコマンド履歴を保持する数を制御します。0 に設定するとコマンド履歴を無効にします。",
			"confirmBeforeClose": "ウィンドウを閉じる前またはアプリケーションを終了する前に確認ダイアログを表示するかどうかを制御します。",
			"confirmBeforeCloseWeb": "ブラウザーのタブまたはウィンドウを閉じる前に確認ダイアログを表示するかどうかを制御します。有効にされている場合でも、確認されることなくブラウザーのタブやウィンドウが閉じられることがあるため、この設定はすべての場合に機能するわけではない 1 つのヒントにすぎないことにご注意ください。",
			"customMenuBarAltFocus": "Alt キーを押してメニュー バーにフォーカスするかどうかを制御します。この設定は、Alt キーを使用してメニュー バーを切り替える操作には影響しません。",
			"decorations.badges": "エディター ファイルの装飾にバッジを使用するかどうかを制御します。",
			"decorations.colors": "エディター ファイルの装飾に配色を使用するかどうかを制御します。",
			"dirty": "`${dirty}`: アクティブなエディターの変更が保存されていない場合を示すインジケーター。",
			"editorOpenPositioning": "エディターを開く場所を制御します。`left` または `right` を選択すると現在アクティブになっているエディターの左または右にエディターを開きます。`first` または `last` を選択すると現在アクティブになっているエディターとは別個にエディターを開きます。",
			"editorTabCloseButton": "エディターのタブの [閉じる] ボタンの位置を制御するか、'off' に設定された場合に無効にします。`#workbench.editor.showTabs#` が無効な場合、この値は無視されます。",
			"enableMenuBarMnemonics": "Alt キー ショートカットを使用してメイン メニューを開くことができるかどうかを制御します。ニーモニックを無効にすると、これらの Alt キー ショートカットを代わりにエディター コマンドにバインドできます。",
			"enablePreview": "開いているエディターをプレビュー エディターとして表示するかどうかを制御します。プレビュー エディターは開いたままではなく、明示的に (ダブルクリックや編集により) 開いたままに設定されるまで再利用されます。ファイル名は斜体で表示されます。",
			"enablePreviewFromCodeNavigation": "エディターからコード ナビゲーションを開始するときに、エディターをプレビュー状態のままにするかどうかを制御します。プレビュー エディターは開いたままではなく、明示的に (ダブルクリックや編集により) 開いたままに設定されるまで再利用されます。`#workbench.editor.enablePreview#` が無効になっている場合、この値は無視されます。",
			"enablePreviewFromQuickOpen": "Quick Open から開いたエディターをプレビュー エディターとして表示するかどうかを制御します。プレビュー エディターは開いたままではなく、明示的に (ダブルクリックや編集により) 開いたままに設定されるまで再利用されます。有効になっている場合、選択する前に Ctrl キーを押しながらエディターをプレビューでない状態として開きます。 `#workbench.editor.enablePreview#` が無効になっている場合、この値は無視されます。",
			"exclude": "ローカル ファイル履歴からファイルを除外するための [glob パターン](https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options) を構成します。この設定を変更しても、既存のローカル ファイル履歴エントリには影響しません。",
			"focusRecentEditorAfterClose": "最近使用した順序でタブを閉じるか、左から右の順にタブを閉じるかを制御します。",
			"folderName": "${folderName}`: ファイルが含まれているワークスペース フォルダーの名前 (例: myFolder)。",
			"folderPath": "`${folderPath}`: ファイルが含まれているワークスペースの絶対パスです (例: /Users/Development/myFolder)。",
			"fontAliasing": "ワークベンチ内のフォント エイリアシング方法を制御します。",
			"highlightModifiedTabs": "変更が保存されていないエディターのタブで上罫線を描画するかどうかを制御します。`#workbench.editor.showTabs#` が無効な場合、この値は無視されます。",
			"layoutControlEnabled": "レイアウト コントロールをカスタム タイトル バーに表示するかどうかを制御します。この設定は、{0} が {1} に設定されている場合にのみ有効です。",
			"layoutControlEnabledWeb": "カスタム タイトル バーのレイアウト コントロール ボタンを有効にするかどうかを制御します。",
			"layoutControlType": "カスタム タイトル バーのレイアウト コントロールを 1 つのメニュー ボタンとして表示するか、複数の UI の切り替えで表示するかを制御します。",
			"layoutcontrol.type.both": "ドロップダウン ボタンとトグル ボタンの両方を表示します。",
			"layoutcontrol.type.menu": "レイアウト オプションのドロップダウンを含む 1 つのボタンを表示します。",
			"layoutcontrol.type.toggles": "パネルとサイド バーの表示を切り替えるボタンをいくつか示します。",
			"limitEditorsEnablement": "開いているエディターの数を制限するかどうかを制御します。有効にすると、最近使用されていないエディターが閉じられ、新しく開くエディター用にスペースが確保されます。",
			"limitEditorsExcludeDirty": "開いているエディターの最大数が、構成された制限にカウントするためにダーティ エディターを除外するかどうかを制御します。",
			"limitEditorsMaximum": "開いているエディターの最大数を制御します。{0} 設定を使用して、エディター グループごと、またはすべてのグループでこの制限を制御します。",
			"localHistoryEnabled": "ローカル ファイル履歴を有効にするかどうかを制御します。有効にすると、保存されたエディターのファイル コンテンツはバックアップの場所に保存され、後で復元または確認できます。この設定の変更は、既存のファイル履歴エントリには影響しません。",
			"localHistoryMaxFileEntries": "ファイルごとのローカル ファイル履歴エントリの最大数を制御します。ローカル ファイル履歴エントリ数がファイルのこの値を超えると、最古のエントリが破棄されます。",
			"localHistoryMaxFileSize": "ローカル ファイル履歴向けのファイルの最大サイズ (KB 単位) を制御します。より大きなファイルは、ローカル ファイル履歴に追加されません。この設定の変更は、既存のファイル ファイル履歴エントリに影響しません。",
			"menuBarVisibility": "メニュー バーの表示と非表示を制御します。'切り替え' 設定は Alt キーを 1 回押すとメニュー バーの表示と非表示が切り替わることを意味します。'コンパクト' 設定では、メニューがサイド バーに移動します。",
			"menuBarVisibility.mac": "メニュー バーの表示と非表示を制御します。'切り替え' 設定は `アプリケーション メニューにフォーカス` を実行するとメニュー バーの表示と非表示が切り替わることを意味します。'コンパクト' 設定では、メニューがサイド バーに移動します。",
			"mergeWindow": "ローカル ファイル履歴の最後のエントリが追加されるエントリに置き換えられる間隔を秒単位で構成します。これにより、自動保存が有効になっている場合など、追加されるエントリの総数を減らすことができます。この設定は、元のソースが同じエントリにのみ適用されます。この設定を変更しても、既存のローカル ファイル履歴エントリには影響しません。",
			"mouseBackForwardToNavigate": "マウス ボタン 4 と 5 を、それぞれコマンド '前に戻る' と '次に進む' に使用できるようにします。",
			"navigationScope": "'前に戻る' や '次に進む' などのコマンドの履歴ナビゲーションの範囲をエディターで制御します。",
			"openDefaultKeybindings": "キーバインド設定を開いたときに、すべての既定のキーバインド設定を表示するエディターも開くかどうかを制御します。",
			"openDefaultSettings": "設定を開いたときに、すべての既定の設定を表示するエディターも開くかどうかを制御します。",
			"openFilesInNewWindow": "コマンド ラインまたはファイル ダイアログを使用しているときに、ファイルを新規ウィンドウで開くかどうかを制御します。\r\n注、この設定は無視される場合もあります (例: `--new-window` または `--reuse-window` コマンド ライン オプションを使用した場合など)。",
			"openFilesInNewWindowMac": "コマンド ラインまたはファイル ダイアログを使用しているときに、ファイルを新規ウィンドウで開くかどうかを制御します。\r\n注、この設定は無視される場合もあります (例: `--new-window` または `--reuse-window` コマンド ライン オプションを使用した場合など)。",
			"openFoldersInNewWindow": "フォルダーを新しいウィンドウで開くか、最後のアクティブ ウィンドウで開くかどうかを制御します。\r\nこの設定は無視される場合もあります (例: `--new-window` または `--reuse-window` コマンド ライン オプションを使用する場合など)。",
			"panelDefaultLocation": "新しいワークスペース内のパネル (ターミナル、デバッグ コンソール、出力、問題) の既定の場所を制御します。エディター領域の下、右、または左に表示できます。",
			"panelOpensMaximized": "パネルを開くときに最大化するかどうかを制御します。開くときに必ず最大化するか、決して最大化しないか、最後に閉じたときの状態で開くかを選択できます。",
			"perEditorGroup": "開いているエディターの最大数をエディター グループごとに適用するか、すべてのエディター グループに適用するかを制御します。",
			"pinnedTabSizing": "固定されたエディターのタブのサイズ設定を制御します。固定されたタブは、開いているすべてのタブの先頭に表示され、通常、固定が解除されるまで閉じられません。`#workbench.editor.showTabs#` が無効な場合、この値は無視されます。",
			"preserveInput": "コマンド パレットを次回開いたとき、コマンド パレットの最後の入力を復元するかどうかを制御します。",
			"profileName": "`${profileName}`: ワークスペースが開かれているプロファイルの名前 (例: データ サイエンス (プロファイル))。既定のプロファイルが使用されている場合は無視されます。",
			"remoteName": "`${remoteName}`: 例: SSH",
			"restoreViewState": "エディターを閉じた後に再び開いたときに、最後のエディター ビューの状態 (スクロール位置など) を回復します。エディター ビューの状態は、エディター グループごとに保存され、グループが閉じられると破棄されます。エディター グループに以前のビュー状態が見つからなかった場合に、すべてのエディター グループにわたって最後に確認されたビュー状態を使用するには、{0} 設定を使用します。",
			"revealIfOpen": "エディターを開くときに、どこの表示グループにエディターを表示するかどうかを制御します。無効にした場合、エディターは現在のアクティブなエディター グループに優先して開かれます。有効にした場合は、現在のアクティブなエディター グループで開くのではなく、既に開かれた状態のエディターを表示します。特定のグループ内や現在アクティブなグループの横に強制的にエディターを開いた場合などに、この設定が無視される場合もあることにご注意ください。",
			"rootName": "'${rootName}': 利用可能なオプションのリモート名とワークスペース インジケーターのあるワークスペースの名前 (例: myFolder、myRemoteFolder [SSH]、myWorkspace (Workspace))。",
			"rootNameShort": "'${rootNameShort}': サフィックスのないワークスペースの短縮名 (例: myFolder、myRemoteFolder、myWorkspace)。",
			"rootPath": "`${rootPath}`: 開かれたワークスペースまたはフォルダーのファイル パス (例: /Users/Development/myWorkspace)。",
			"scrollToSwitchTabs": "タブの上をスクロールしたときに、それらを開くかどうかを制御します。既定では、スクロール時にはタブは表示されるだけで、開かれることはありません。スクロール中に Shift キーを押したままにすると、その間この動作を変更できます。`#workbench.editor.showTabs#` が無効な場合、この値は無視されます。",
			"separator": "`${separator}`: 値か固定のテキストで囲われたとき、条件付きの区切り記号 (\" - \") を表示します。",
</details>
After:
<details>
		"vs/workbench/browser/workbench.contribution": {
			"activeEditorLong": "`${activeEditorLong}`: ファイルの完全なパス (例: /Users/Development/myFolder/myFileFolder/myFile.txt)。",
			"activeEditorMedium": "`${activeEditorMedium}`: ワークスペース フォルダーに対して相対的なファイルのパス (例: myFolder/myFileFolder/myFile.txt)。",
			"activeEditorShort": "`${activeEditorShort}`: ファイル名 (例: myFile.txt)。",
			"activeFolderLong": "`${activeFolderLong}`: ファイルが格納されているフォルダーのフルパス (例: /Users/Development/myFolder/myFileFolder)。",
			"activeFolderMedium": "`${activeFolderMedium}`: ファイルを含むフォルダーの、ワークスペースフォルダーからの相対パス(例: myFolder/myFileFolder)。",
			"activeFolderShort": "`${activeFolderShort}`: ファイルが含まれているフォルダーの名前 (例: myFileFolder)。",
			"activityBarIconClickBehavior": "ワークベンチのアクティビティ バー アイコンをクリックする動作を制御します。",
			"activityBarVisibility": "ワークベンチでのアクティビティ バーの表示をコントロールします。",
			"appName": "`${appName}`: 例: VS Code。",
			"centeredLayoutAutoResize": "複数のグループが開かれているとき、中央揃えのレイアウトを自動的に横幅最大にするかどうかを制御します。1 つのグループのみが開かれている場合は、元の中央揃えの横幅に戻ります。",
			"centeredLayoutDynamicWidth": "ウィンドウのサイズを変更するときに、中央のレイアウトで一定の幅を維持するかどうかを制御します。",
			"closeEmptyGroups": "空のエディターのグループにある最後のタブを閉じたときの動作を制御します。有効であるとき、空のグループは自動的に閉じられます。無効であるとき、空のグループはグリッドの一部として残ります。",
			"closeOnFileDelete": "セッション中のファイルを表示しているエディターが、その他のプロセスによって削除されるか名前を変更された場合に、エディターを自動的に閉じるかどうかを制御します。これを無効にすると、このような場合にエディターを開き続けます。アプリケーション内で削除すると、エディターは常に閉じられ、変更が保存されていないエディターのデータを保存して閉じることはありません。",
			"closeOnFocusLost": "フォーカスを失ったときに Quick Open を自動的に閉じるかどうかを制御します。",
			"commandHistory": "コマンド パレットで最近使用したコマンド履歴を保持する数を制御します。0 に設定するとコマンド履歴を無効にします。",
			"confirmBeforeClose": "ウィンドウを閉じる前またはアプリケーションを終了する前に確認ダイアログを表示するかどうかを制御します。",
			"confirmBeforeCloseWeb": "ブラウザーのタブまたはウィンドウを閉じる前に確認ダイアログを表示するかどうかを制御します。有効にされている場合でも、確認されることなくブラウザーのタブやウィンドウが閉じられることがあるため、この設定はすべての場合に機能するわけではない 1 つのヒントにすぎないことにご注意ください。",
			"customMenuBarAltFocus": "Alt キーを押してメニュー バーにフォーカスするかどうかを制御します。この設定は、Alt キーを使用してメニュー バーを切り替える操作には影響しません。",
			"decorations.badges": "エディター ファイルの装飾にバッジを使用するかどうかを制御します。",
			"decorations.colors": "エディター ファイルの装飾に配色を使用するかどうかを制御します。",
			"dirty": "`${dirty}`: アクティブなエディターの変更が保存されていない場合を示すインジケーター。",
			"editorOpenPositioning": "エディターを開く場所を制御します。`left` または `right` を選択すると現在アクティブになっているエディターの左または右にエディターを開きます。`first` または `last` を選択すると現在アクティブになっているエディターとは別個にエディターを開きます。",
			"editorTabCloseButton": "エディターのタブの [閉じる] ボタンの位置を制御するか、'off' に設定された場合に無効にします。`#workbench.editor.showTabs#` が無効な場合、この値は無視されます。",
			"enableMenuBarMnemonics": "Alt キー ショートカットを使用してメイン メニューを開くことができるかどうかを制御します。ニーモニックを無効にすると、これらの Alt キー ショートカットを代わりにエディター コマンドにバインドできます。",
			"enablePreview": "開いているエディターをプレビュー エディターとして表示するかどうかを制御します。プレビュー エディターは開いたままではなく、明示的に (ダブルクリックや編集により) 開いたままに設定されるまで再利用されます。ファイル名は斜体で表示されます。",
			"enablePreviewFromCodeNavigation": "エディターからコード ナビゲーションを開始するときに、エディターをプレビュー状態のままにするかどうかを制御します。プレビュー エディターは開いたままではなく、明示的に (ダブルクリックや編集により) 開いたままに設定されるまで再利用されます。`#workbench.editor.enablePreview#` が無効になっている場合、この値は無視されます。",
			"enablePreviewFromQuickOpen": "Quick Open から開いたエディターをプレビュー エディターとして表示するかどうかを制御します。プレビュー エディターは開いたままではなく、明示的に (ダブルクリックや編集により) 開いたままに設定されるまで再利用されます。有効になっている場合、選択する前に Ctrl キーを押しながらエディターをプレビューでない状態として開きます。 `#workbench.editor.enablePreview#` が無効になっている場合、この値は無視されます。",
			"exclude": "ローカル ファイル履歴からファイルを除外するための [glob パターン](https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options) を構成します。この設定を変更しても、既存のローカル ファイル履歴エントリには影響しません。",
			"focusRecentEditorAfterClose": "最近使用した順序でタブを閉じるか、左から右の順にタブを閉じるかを制御します。",
			"folderName": "`${folderName}`: ファイルが含まれているワークスペース フォルダーの名前 (例: myFolder)。",
			"folderPath": "`${folderPath}`: ファイルが含まれているワークスペースの絶対パスです (例: /Users/Development/myFolder)。",
			"fontAliasing": "ワークベンチ内のフォント エイリアシング方法を制御します。",
			"highlightModifiedTabs": "変更が保存されていないエディターのタブで上罫線を描画するかどうかを制御します。`#workbench.editor.showTabs#` が無効な場合、この値は無視されます。",
			"layoutControlEnabled": "レイアウト コントロールをカスタム タイトル バーに表示するかどうかを制御します。この設定は、{0} が {1} に設定されている場合にのみ有効です。",
			"layoutControlEnabledWeb": "カスタム タイトル バーのレイアウト コントロール ボタンを有効にするかどうかを制御します。",
			"layoutControlType": "カスタム タイトル バーのレイアウト コントロールを 1 つのメニュー ボタンとして表示するか、複数の UI の切り替えで表示するかを制御します。",
			"layoutcontrol.type.both": "ドロップダウン ボタンとトグル ボタンの両方を表示します。",
			"layoutcontrol.type.menu": "レイアウト オプションのドロップダウンを含む 1 つのボタンを表示します。",
			"layoutcontrol.type.toggles": "パネルとサイド バーの表示を切り替えるボタンをいくつか示します。",
			"limitEditorsEnablement": "開いているエディターの数を制限するかどうかを制御します。有効にすると、最近使用されていないエディターが閉じられ、新しく開くエディター用にスペースが確保されます。",
			"limitEditorsExcludeDirty": "開いているエディターの最大数が、構成された制限にカウントするためにダーティ エディターを除外するかどうかを制御します。",
			"limitEditorsMaximum": "開いているエディターの最大数を制御します。{0} 設定を使用して、エディター グループごと、またはすべてのグループでこの制限を制御します。",
			"localHistoryEnabled": "ローカル ファイル履歴を有効にするかどうかを制御します。有効にすると、保存されたエディターのファイル コンテンツはバックアップの場所に保存され、後で復元または確認できます。この設定の変更は、既存のファイル履歴エントリには影響しません。",
			"localHistoryMaxFileEntries": "ファイルごとのローカル ファイル履歴エントリの最大数を制御します。ローカル ファイル履歴エントリ数がファイルのこの値を超えると、最古のエントリが破棄されます。",
			"localHistoryMaxFileSize": "ローカル ファイル履歴向けのファイルの最大サイズ (KB 単位) を制御します。より大きなファイルは、ローカル ファイル履歴に追加されません。この設定の変更は、既存のファイル ファイル履歴エントリに影響しません。",
			"menuBarVisibility": "メニュー バーの表示と非表示を制御します。'切り替え' 設定は Alt キーを 1 回押すとメニュー バーの表示と非表示が切り替わることを意味します。'コンパクト' 設定では、メニューがサイド バーに移動します。",
			"menuBarVisibility.mac": "メニュー バーの表示と非表示を制御します。'切り替え' 設定は `アプリケーション メニューにフォーカス` を実行するとメニュー バーの表示と非表示が切り替わることを意味します。'コンパクト' 設定では、メニューがサイド バーに移動します。",
			"mergeWindow": "ローカル ファイル履歴の最後のエントリが追加されるエントリに置き換えられる間隔を秒単位で構成します。これにより、自動保存が有効になっている場合など、追加されるエントリの総数を減らすことができます。この設定は、元のソースが同じエントリにのみ適用されます。この設定を変更しても、既存のローカル ファイル履歴エントリには影響しません。",
			"mouseBackForwardToNavigate": "マウス ボタン 4 と 5 を、それぞれコマンド '前に戻る' と '次に進む' に使用できるようにします。",
			"navigationScope": "'前に戻る' や '次に進む' などのコマンドの履歴ナビゲーションの範囲をエディターで制御します。",
			"openDefaultKeybindings": "キーバインド設定を開いたときに、すべての既定のキーバインド設定を表示するエディターも開くかどうかを制御します。",
			"openDefaultSettings": "設定を開いたときに、すべての既定の設定を表示するエディターも開くかどうかを制御します。",
			"openFilesInNewWindow": "コマンド ラインまたはファイル ダイアログを使用しているときに、ファイルを新規ウィンドウで開くかどうかを制御します。\r\n注、この設定は無視される場合もあります (例: `--new-window` または `--reuse-window` コマンド ライン オプションを使用した場合など)。",
			"openFilesInNewWindowMac": "コマンド ラインまたはファイル ダイアログを使用しているときに、ファイルを新規ウィンドウで開くかどうかを制御します。\r\n注、この設定は無視される場合もあります (例: `--new-window` または `--reuse-window` コマンド ライン オプションを使用した場合など)。",
			"openFoldersInNewWindow": "フォルダーを新しいウィンドウで開くか、最後のアクティブ ウィンドウで開くかどうかを制御します。\r\nこの設定は無視される場合もあります (例: `--new-window` または `--reuse-window` コマンド ライン オプションを使用する場合など)。",
			"panelDefaultLocation": "新しいワークスペース内のパネル (ターミナル、デバッグ コンソール、出力、問題) の既定の場所を制御します。エディター領域の下、右、または左に表示できます。",
			"panelOpensMaximized": "パネルを開くときに最大化するかどうかを制御します。開くときに必ず最大化するか、決して最大化しないか、最後に閉じたときの状態で開くかを選択できます。",
			"perEditorGroup": "開いているエディターの最大数をエディター グループごとに適用するか、すべてのエディター グループに適用するかを制御します。",
			"pinnedTabSizing": "固定されたエディターのタブのサイズ設定を制御します。固定されたタブは、開いているすべてのタブの先頭に表示され、通常、固定が解除されるまで閉じられません。`#workbench.editor.showTabs#` が無効な場合、この値は無視されます。",
			"preserveInput": "コマンド パレットを次回開いたとき、コマンド パレットの最後の入力を復元するかどうかを制御します。",
			"profileName": "`${profileName}`: ワークスペースが開かれているプロファイルの名前 (例: データ サイエンス (プロファイル))。既定のプロファイルが使用されている場合は無視されます。",
			"remoteName": "`${remoteName}`: 例: SSH",
			"restoreViewState": "エディターを閉じた後に再び開いたときに、最後のエディター ビューの状態 (スクロール位置など) を回復します。エディター ビューの状態は、エディター グループごとに保存され、グループが閉じられると破棄されます。エディター グループに以前のビュー状態が見つからなかった場合に、すべてのエディター グループにわたって最後に確認されたビュー状態を使用するには、{0} 設定を使用します。",
			"revealIfOpen": "エディターを開くときに、どこの表示グループにエディターを表示するかどうかを制御します。無効にした場合、エディターは現在のアクティブなエディター グループに優先して開かれます。有効にした場合は、現在のアクティブなエディター グループで開くのではなく、既に開かれた状態のエディターを表示します。特定のグループ内や現在アクティブなグループの横に強制的にエディターを開いた場合などに、この設定が無視される場合もあることにご注意ください。",
			"rootName": "`${rootName}`: 利用可能なオプションのリモート名とワークスペース インジケーターのあるワークスペースの名前 (例: myFolder、myRemoteFolder [SSH]、myWorkspace (Workspace))。",
			"rootNameShort": "`${rootNameShort}`: サフィックスのないワークスペースの短縮名 (例: myFolder、myRemoteFolder、myWorkspace)。",
			"rootPath": "`${rootPath}`: 開かれたワークスペースまたはフォルダーのファイル パス (例: /Users/Development/myWorkspace)。",
			"scrollToSwitchTabs": "タブの上をスクロールしたときに、それらを開くかどうかを制御します。既定では、スクロール時にはタブは表示されるだけで、開かれることはありません。スクロール中に Shift キーを押したままにすると、その間この動作を変更できます。`#workbench.editor.showTabs#` が無効な場合、この値は無視されます。",
			"separator": "`${separator}`: 値か固定のテキストで囲われたとき、条件付きの区切り記号 (\" - \") を表示します。",
</details>

**Comment by v-mholloway** [comment]
@manjuu-eater could you provide resource identifiers for the strings affected...?
e.g.
<img width="389" alt="image" src="https://user-images.githubusercontent.com/77055370/228196000-97363fac-8716-4bde-a492-39d0bfd88d4f.png">

**Comment by manjuu-eater** [comment]
Before:
```
			"activeEditorShort": "'${activeEditorShort}': ファイル名 (例: myFile.txt)。",
			"activeFolderLong": "'${activeFolderLong}': ファイルが格納されているフォルダーのフルパス (例: /Users/Development/myFolder/myFileFolder)。",
			"folderName": "${folderName}`: ファイルが含まれているワークスペース フォルダーの名前 (例: myFolder)。",
			"rootName": "'${rootName}': 利用可能なオプションのリモート名とワークスペース インジケーターのあるワークスペースの名前 (例: myFolder、myRemoteFolder [SSH]、myWorkspace (Workspace))。",
			"rootNameShort": "'${rootNameShort}': サフィックスのないワークスペースの短縮名 (例: myFolder、myRemoteFolder、myWorkspace)。",
```

After:
```
			"activeEditorShort": "`${activeEditorShort}`: ファイル名 (例: myFile.txt)。",
			"activeFolderLong": "`${activeFolderLong}`: ファイルが格納されているフォルダーのフルパス (例: /Users/Development/myFolder/myFileFolder)。",
			"folderName": "`${folderName}`: ファイルが含まれているワークスペース フォルダーの名前 (例: myFolder)。",
			"rootName": "`${rootName}`: 利用可能なオプションのリモート名とワークスペース インジケーターのあるワークスペースの名前 (例: myFolder、myRemoteFolder [SSH]、myWorkspace (Workspace))。",
			"rootNameShort": "`${rootNameShort}`: サフィックスのないワークスペースの短縮名 (例: myFolder、myRemoteFolder、myWorkspace)。",
```

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 807694)
