### ISSUE TITLE
[zh-Hans] Suggest that "Global" be translated into "全局",  "Block" be translated into "块"

### ISSUE THREAD

**Issue by lollipopnougat** [microsoft/vscode-loc#1316]
I find two translation errors in vscode's js debugger .
1.  https://github.com/microsoft/vscode-loc/blob/44f29a528527b811bf0fe605d0c312f16cd6cca5/i18n/vscode-language-pack-zh-hans/translations/extensions/ms-vscode.js-debug.i18n.json#L229
    suggest: `块`

2.  https://github.com/microsoft/vscode-loc/blob/44f29a528527b811bf0fe605d0c312f16cd6cca5/i18n/vscode-language-pack-zh-hans/translations/extensions/ms-vscode.js-debug.i18n.json#L267
    suggest: `全局`

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 812811).
