### ISSUE TITLE
[zh-Hans] Suggest that "Synchronize keybindings for each platform" be translated into "为每个平台各自同步键绑定"

### ISSUE THREAD

**Issue by happyme531** [microsoft/vscode-loc#1331]
https://github.com/microsoft/vscode-loc/blob/ac12566ff0e713814a97f7c69f8981f61e67ec2d/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L2438
Current translation "为每个平台同步键绑定" is misleading as "Synchronize keybindings for **every** platform" but it should have the meaning of sync *separately/individually* for each platform.
Add "各自"(separately) could probably solve the confusion.

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 820121).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 820121)
