### ISSUE TITLE
[de] Wrong quotes on "Commit & Sync" translation

### ISSUE THREAD

**Issue by lkohlg** [microsoft/vscode-loc#1336]
There are two incorrect quotes in the translation of Commit & Sync, which lead to an incorrect display especially if the value of the variable 0 is not set. Namely:  `Commit und Synchronisieren ""`
I would suggest the following change in the Git translation file:
```
"{0} Commit & Sync": "Commit und Synchronisieren \"{0}\"",
"{0} Commit & Sync": "{0} Commit und Synchronisieren",
```

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 821080)
