### ISSUE TITLE
[ja] Typo in "Show Folding Controls"

### ISSUE THREAD

**Issue by Tatsurou-Yajima** [microsoft/vscode-loc#1346]
There's a typo in "i18n/vscode-language-pack-ja/translations/main.i18n.json".

https://github.com/microsoft/vscode-loc/blob/cb3e96e9810a78f80af003b5fab1c8171ae2d53c/i18n/vscode-language-pack-ja/translations/main.i18n.json#L527

![image](https://user-images.githubusercontent.com/44424270/235553082-2c778a04-b621-47a8-8d71-3fd2778d5b7c.png)

"のの" should be "の".

```sugestion
			"showFoldingControls": "とじしろのの折りたたみコントロールを表示するタイミングを制御します。",
```

↑ should be ↓

```sugestion
			"showFoldingControls": "とじしろの折りたたみコントロールを表示するタイミングを制御します。",
```

Thanks.

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 824817).

**Comment by csigs** [comment]
Resolved as Fixed & Verify.
