### ISSUE TITLE
Need for Hindi VS Code

### ISSUE THREAD

**Issue by Shash976** [microsoft/vscode-loc#1347]
Hi, currently, VS Code supports 14 core languages, yet surprisingly, Hindi, one of the most widely spoken languages globally, is not among them. As a coder residing in a country where nearly 40% of the population speaks Hindi, I strongly advocate for the development of a Hindi language extension for VS Code. Such an extension would cater to the needs of millions of Hindi-speaking developers and foster inclusivity and accessibility, promoting greater participation and innovation within the coding community. Additionally, it would empower aspiring programmers to code in their native language, facilitating faster learning and comprehension.

I would like your advice on how to make a new language extension for VS Code. Like is there any sort of format or something which I could copy and replace the texts with hindi translations?

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 826058).

**Comment by Shash976** [comment]
> reference 826058

Thanks a lot.

**Comment by crsuzukimsft** [comment]
Thank you for your information.  Request is being reviewed. For now, this ticket will be mitigated.

**Comment by csigs** [comment]
Resolved as As Designed.
