### ISSUE TITLE
[zh-Hans] Suggest that "thinking" be translated into "思考中"

### ISSUE THREAD

**Issue by gooin** [microsoft/vscode-loc#1348]
https://github.com/microsoft/vscode-loc/blob/cb3e96e9810a78f80af003b5fab1c8171ae2d53c/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L6903

Hi, I am using Github Copilot Chat beta
In zh-Hans:
![image](https://user-images.githubusercontent.com/13775365/236363613-3024cbd2-bea2-4e82-a146-4b385b482cc0.png)
In EN:
![image](https://user-images.githubusercontent.com/13775365/236363768-023a0022-afe9-4e7d-b604-c6cadc6d46be.png)

Suggest that "thinking" be translated into "思考中"

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 827906).

**Comment by cristianosuzuki77** [comment]
827906 closed in May
