### ISSUE TITLE
Creation of a Language Pack for Kiswahili(Kenya/Tanzania)

### ISSUE THREAD

**Issue by furahadamien** [microsoft/vscode-loc#135]
I was going through the available Language Packs and it looks like VS Code is not available in Kiswahili(Kenya/Tanzania). I was so keen to contribute to MLCP in this language but I couldn't find any Strings. I am interested in creating a Language Pack for this Language and hopefully, several other  people can be motivated to contribute to the VS Code Localization of this Language

**Comment by janbaltus** [comment]
based on this Wiki page new localization request for evaluation https://github.com/Microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project

**Comment by uct8086** [comment]
how could i download the old version package ?

**Comment by janbaltus** [comment]
Can you please clarify what you mean by Old version package?
This language is not supported yet

**Comment by furahadamien** [comment]
> based on this Wiki page new localization request for evaluation https://github.com/Microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project

Does this mean that my request for this Localization is being evaluated? Sorry, I didn't get what you meant by your comment. I was looking at the [wiki](https://github.com/Microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project#list-of-languages-currently-being-evaluated) and I couldn't see it in the list of languages being evaluated.

**Comment by shrijap** [comment]
Hi @furahadamien. Thank you for reaching out to us with this request. Currently, we have put new language requests on hold as we have decommissioned MLCP and are working on bringing the community an alternate localization platform which is more robust and better features. Please watch out for the announcement on that on our [Localization Wiki](https://github.com/Microsoft/Localization/wiki). Thank you!

**Comment by danyeh** [comment]
I am closing this. There won't be a community loc platform in near term. 
Current recommendation is to follow wiki in this repo to create language pack separately.
