### ISSUE TITLE
[kaa] New locale: Karakalpak language

### ISSUE THREAD

**Issue by alizhumagaliev** [microsoft/vscode-loc#1356]
Hi! I am from the Republic of Karakalpakstan, I would like to help with the translation of VSCode into Karakalpak language. I have a translators team. Is it possible to add the Karakalpak language?

**Comment by turdibekjumabaev** [comment]
if Karakalpak language is going to be added to VS Code, I will start contributing

**Comment by D4uranbek** [comment]
Let's it. I want to support the team!

**Comment by muxammedqudaynazarov** [comment]
I would be very happy to see the interpretation of the program in the Karakalpak language, and I would actively participate in the translation of the program into the Karakalpak language.

**Comment by Allaniyaz** [comment]
Hi. I am from Republic of Karakalpakstan where Karakalpak is the National language. There are many developers who use VSCode every day so please let us add Karakalpak to this app. I am ready to help with translation into Karakalpak and I know many people who are ready too. Please help us to share the VSCode in more places in our country.

**Comment by OnlineAzamat** [comment]
Let's do it. I want to support the team!

**Comment by Azizbek-007** [comment]
Let's do it. I want to support the team!

**Comment by NurlanPirjanov** [comment]
If Karakalpak language is going to be added to VS Code, I will start contributing

**Comment by Nurik775** [comment]
if Karakalpak language is going to be added to VS Code, I will start contributing

**Comment by urazbaevalisher** [comment]
Keling buni bajaramiz. Men jamoani qo'llab-quvvatlamoqchiman!

**Comment by dauletbaev** [comment]
Ready for contrubition

**Comment by Dawran0112** [comment]
I'm ready to contribute to the Karakalpak language

**Comment by amanliq** [comment]
Ready for contribution

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 833478).

**Comment by cristianosuzuki77** [comment]
Thank you. We will review this ticket internally. Appreciated the feedback and support!
