### ISSUE TITLE
zoom

### ISSUE THREAD

**Issue by CID2006AN** [microsoft/vscode-loc#1358]
Hi, I have grown a page and want to bring it back

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 833480).

**Comment by cristianosuzuki77** [comment]
cc @TylerLeonhardt as it doesn't seem to be a translation issue.
Hello @CID2006AN , could you please be more specific on the issue?

**Comment by csigs** [comment]
Resolved as As Designed.
