### ISSUE TITLE
[de] typo: IPYBN (instead of IPYNB)

### ISSUE THREAD

**Issue by NicoWeio** [microsoft/vscode-loc#1366]
https://github.com/microsoft/vscode-loc/blob/2664ff0a9fc947c15d264a607cb43a973a34b6dc/i18n/vscode-language-pack-de/translations/extensions/vscode.ipynb.i18n.json#L17

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 836772).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 836772)
