### ISSUE TITLE
zh-hans locale wrong translation of "formatting" 

### ISSUE THREAD

**Issue by douxingxiang** [microsoft/vscode-loc#137]
file: `i18n/vscode-language-pack-zh-hans/translations/main.i18n.json`
key: `"vs/workbench/contrib/preferences/browser/settingsLayout"."formatting"`
language pack version: `1.41.2`

"formatting" is translating to  '正在格式化', here it should be a noun, so '格式化' is the right translation.

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
@douxingxiang Is it possible to add screenshot of mentioned issue ?

**Comment by lukaschal** [comment]
Fixed.

new tgt: 格式化
