### ISSUE TITLE
[zh-CN] "step over" should not be translated into "单步跳过"! it should be “逐过程”

### ISSUE THREAD

**Issue by sherlocknieh** [microsoft/vscode-loc#1376]
“单步跳过” 真的令人困惑，误导用户理解。

![image](https://github.com/microsoft/vscode-loc/assets/43476643/08462ff3-4c9b-408b-a8fc-a5fec595c8c6)

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 841430).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 841430)

**Comment by sherlocknieh** [comment]
> The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 841430)

So efficient! You guys are the best : )
