### ISSUE TITLE
[de]: Incorrect translation for the word "lines" as in lines of text

### ISSUE THREAD

**Issue by miphilipp** [microsoft/vscode-loc#1377]
I have shortened the values using "..." in case the rest of the string is without issues.

**"editor.stickyScroll.maxLineCount"**
Currently: "Definiert die maximale Anzahl fixierter Linien, die angezeigt werden sollen."
Improved: "Definiert die maximale Anzahl fixierter Zeilen, die angezeigt werden sollen."

**"editor.stickyScroll.defaultModel"**
Currently: "Legt das Modell fest, das zur Bestimmung der zu fixierenden Linien verwendet wird. ..."
Improved: "Legt das Modell fest, das zur Bestimmung der zu fixierenden Zeilen verwendet wird. ..."

**"suggestLineHeight"**
Currently: "Linienhöhe für das Vorschlagswidget. ..."
Improved: "Zeilenhöhe für das Vorschlagswidget. ..."

**"diffEditorInsertedLines"**
Currently: "Hintergrundfarbe für eingefügte Linien. ..."
Improved: "Hintergrundfarbe für eingefügte Zeilen. ..."

**"diffEditorRemovedLineGutter"**
Currently: "Hintergrundfarbe für den Rand, an dem die Linien entfernt wurden.",
Improved: "Hintergrundfarbe für den Rand, an dem die Zeilen entfernt wurden.",

**"diffEditorRemovedLines"**
Currently: "Hintergrundfarbe für Linien, die entfernt wurden. ...",
Improved: "Hintergrundfarbe für Zeilen, die entfernt wurden. ...",

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 842057).

**Comment by NicoWeio** [comment]
Also `hiddenLines` in `editor/browser/widget/diffEditor/hideUnchangedRegionsFeature` (no clue why the preview doesn't render):
https://github.com/microsoft/vscode-loc/blob/6a00611d9d32ae62e4be0d8b151f66996c193509/i18n/vscode-language-pack-de/translations/main.i18n.json#L255C13

**Comment by TylerLeonhardt** [comment]
@cristianosuzuki77 any conclusion with this one?

**Comment by miphilipp** [comment]
> [@cristianosuzuki77](https://github.com/cristianosuzuki77) any conclusion with this one?

The improved translations seem to be in the latest version of VS Code.

**Comment by TylerLeonhardt** [comment]
Great! I'll close this then
