### ISSUE TITLE
[ru] Incorrect translation for "terminal.copyCommand"

### ISSUE THREAD

**Issue by idma88** [microsoft/vscode-loc#1379]
Incorrect translation displayed on the screenshot
![изображение](https://github.com/microsoft/vscode-loc/assets/7449066/ce9ab9c8-9da5-4d48-992f-8a2f7c283c9d)

The correct translation should be: `Копировать команду`

https://github.com/microsoft/vscode-loc/blob/4c6726d73c2186acf6cda0adbd6fa5c52f8df011/i18n/vscode-language-pack-ru/translations/main.i18n.json#L9928

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 842480).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 842480)
