### ISSUE TITLE
[fr] Incorrect translation of terminal.rerunCommand

### ISSUE THREAD

**Issue by jlemselle** [microsoft/vscode-loc#1387]
The translation of terminal.rerunCommand should be "Réexécuter la commande", not "Commande de réexécution" (a command that re-executes). This matches the grammatical style of copy command "Copier la commande", and better explains what it does.

![Capture d’écran 2023-06-05 à 8 19 53 PM](https://github.com/microsoft/vscode-loc/assets/1987806/dbf005a5-1f70-472b-9c89-181ccbb25444)

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 846736).

**Comment by csigs** [comment]
Resolved as Fixed & Verify.
