### ISSUE TITLE
[ja] transration mistake

### ISSUE THREAD

**Issue by lusingander** [microsoft/vscode-loc#139]
`Group &&Right` is translated to `グループ右(&&R)`, but i think it is better to translate it as `グループ（右）(&&R)`, because the following four menus are the same kind.

![image](https://user-images.githubusercontent.com/31386431/72679124-73a4db00-3aef-11ea-92fd-8bf8d7506368.png)

![image](https://user-images.githubusercontent.com/31386431/72679050-d8ac0100-3aee-11ea-9f23-fc1f06ce97bb.png)

**Comment by lukaschal** [comment]
On review.

src: Group &&Right
tgt: グループ右(&&R)

**Comment by lukaschal** [comment]
Fixed.

new tgt: グループ (右)(&&R)
