### ISSUE TITLE
I am unable to log in to www.cursor.so on one of my Mac computers

### ISSUE THREAD

**Issue by greatany** [microsoft/vscode-loc#1390]
Type: <b>Performance Issue</b>

"I am unable to log in to www.cursor.so on one of my Mac computers. I downloaded the installation file on another computer, but I am still unable to log in to my account."

Extension version: 1.76.2023030809
VS Code version: Cursor 0.2.29 (cf867fe2d5887b67e769bcc8dd62e5899169fa88, 2023-06-08T04:19:16.526Z)
OS version: Darwin arm64 22.5.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   17	   197	  3988	cursor main
    9	    82	  3992	   gpu-process
    1	    49	  3993	   utility-network-service
    0	    33	  3994	   utility-process
    1	   328	  3996	   window (README.md — .cursor-tutor)
    3	   180	  4009	   shared-process
    0	    66	  4011	     ptyHost
    0	    66	  4021	     fileWatcher
    0	     0	  4091	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   164	  4010	   extension-host
    0	    49	  4023	     /Applications/Cursor.app/Contents/Frameworks/Cursor Helper.app/Contents/MacOS/Cursor Helper /Applications/Cursor.app/Contents/Resources/app/extensions/markdown-language-features/server/dist/node/workerMain --node-ipc --clientProcessId=4010
    3	    98	  4082	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (README.md — .cursor-tutor)
|    Folder (.cursor-tutor): 18 files
|      File types: md(3) rs(2) json(2) c(1) ts(1) html(1) js(1) py(1)
|      Conf files: package.json(1);
```

</details>

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 849197).

**Comment by cristianosuzuki77** [comment]
Thank you. Please contact the email support at cursor.so for assistance.

**Comment by csigs** [comment]
Investigated by Loc Team: It's not a translation issue. (Reference id: 849197)
