### ISSUE TITLE
[ru-RU] Show or Show in Explorer

### ISSUE THREAD

**Issue by SowingSadness** [microsoft/vscode-loc#1401]
![image](https://github.com/microsoft/vscode-loc/assets/576443/68e907d7-c47e-4e4f-92c9-7b0f420909fa)
All users always get confuse in this two menu items in russian interface.
In russian language using "explorer"(проводник) term to "File explorer" and "Explorer View". 
In this context "Показать" and "Отобразить" have same translate to english — "show".

I want to suggest my translation.
"_Reveal in File Explorer_" -> "**Открыть в проводнике**" 
Literal translation "open in explorer" and a common term in russian about file explorer.

"_Reveal in Explorer View_" -> "**Показать в панели проводника**" 
Literal translation: reveal in explorer view.

![image](https://github.com/microsoft/vscode-loc/assets/576443/716c6433-9bcd-4dca-a672-858b93bb6fee)

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 857030)
