### ISSUE TITLE
Create a Ukrainian language pack

### ISSUE THREAD

**Issue by mufik-petro** [microsoft/vscode-loc#1402]
I would like to participate in the creation of a language pack for the Ukrainian language, but I do not know how to do it. I could create a copy of the files of another language from this repository with a translation into Ukrainian, if it helps in creating a language pack

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 857252).

**Comment by crsuzukimsft** [comment]
Thank you.  We'll keep it in mind.

**Comment by csigs** [comment]
Resolved as Deferred.
