### ISSUE TITLE
[ja]typo? Restart Message

### ISSUE THREAD

**Issue by yasuking0304** [microsoft/vscode-loc#1407]
The button message of the confirmation dialog when switching the language to something other than Japanese is strange.

### Problem
* with an "と" in front
* has a shortcut(shouldn't use it)

### Target OS
* Windows 10
* macOS Monterey

### Version
* Newest(Japanese Language Pack for Visual Studio Code v1.79.2023061409)

### Screen Shot
![WS000010](https://github.com/microsoft/vscode-loc/assets/111163564/44945faa-6707-4c53-b7bb-82956f612e00)
![スクリーンショット 2023-06-23 10 37 18](https://github.com/microsoft/vscode-loc/assets/111163564/c06fd798-276b-4848-b142-dd26b5766b48)

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 858026).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 858026)
