### ISSUE TITLE
es incorrect translation

### ISSUE THREAD

**Issue by camilosasia** [microsoft/vscode-loc#141]
_Peek problem_ is translated to _Problema de pico_, which doesn't make any sense in Spanish. A better translation would be _Ver problema_.

![peekproblem](https://user-images.githubusercontent.com/18406325/73125416-4dff5200-3f85-11ea-8913-e56a9d24289a.png)

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
Fixed.

new tgt: Ver problema
