### ISSUE TITLE
Install vsix error, not compatible with VS Code '1.76.2'

### ISSUE THREAD

**Issue by vikotse** [microsoft/vscode-loc#1420]
Which version of loc extension is compatible with VSCode '1.76.2' version?
And because of development env policy, I could only install by offline vsix file.

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 865153).

**Comment by crsuzukimsft** [comment]
@TylerLeonhardt perhaps you could assist here? thank you.

**Comment by vikotse** [comment]
> @vikotse you should install the latest 1.76.* version of a loc extension. The first two sections of the version (1.76) are aligned with the version of VS Code that you have.

<img width="1127" alt="image" src="https://github.com/microsoft/vscode-loc/assets/5728396/532b3cff-bba6-40fe-827f-c5cdfe7d01c8">
I could not find any 1.76.* version of vscode-loc in Releases or Tags, where could I find the suitable version?

**Comment by TylerLeonhardt** [comment]
We don't use GitHub releases anymore... but here are some steps that may work...

#### Step 1: Get the version

If you're looking for a recent version, you can go to the Marketplace page and download the VSIX there:
https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-es

However, that only has 5 entries... if you need an older version, you could try this...

On a machine off this network, you can install the language pack you want normally from the Extensions pane in VS Code.

Once you do that you have this option:
<img width="536" alt="image" src="https://github.com/microsoft/vscode-loc/assets/2644648/b095ed7d-b34b-4b80-b99f-df63c2d4a670">

From there, you see a quick pick with all versions:
<img width="630" alt="image" src="https://github.com/microsoft/vscode-loc/assets/2644648/c57aee56-b4cd-4d91-b2c3-75b36c18ab84">

Note the latest version number for the 1.X version of VS Code.

#### Step 2: Download the VSIX

Go back to https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-es to the Version History and right click on one of the Download buttons and hit "Copy link"

That'll give you a link like this:
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/MS-CEINTL/vsextensions/vscode-language-pack-es/1.80.2023070509/vspackage

Notice the version in the URL towards the end.

Now simply replace that version, with the version you got from step one and you should be able to grab the VSIX.

---

I know these aren't the easiest steps... and if I find out a better solution for you, I'll let you know, but it's a solution.

**Comment by vikotse** [comment]
> We don't use GitHub releases anymore... but here are some steps that may work...
> 
> #### Step 1: Get the version
> If you're looking for a recent version, you can go to the Marketplace page and download the VSIX there: https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-es
> 
> However, that only has 5 entries... if you need an older version, you could try this...
> 
> On a machine off this network, you can install the language pack you want normally from the Extensions pane in VS Code.
> 
> Once you do that you have this option: <img alt="image" width="536" src="https://user-images.githubusercontent.com/2644648/252742741-b095ed7d-b34b-4b80-b99f-df63c2d4a670.png">
> 
> From there, you see a quick pick with all versions: <img alt="image" width="630" src="https://user-images.githubusercontent.com/2644648/252742853-c57aee56-b4cd-4d91-b2c3-75b36c18ab84.png">
> 
> Note the latest version number for the 1.X version of VS Code.
> 
> #### Step 2: Download the VSIX
> Go back to https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-es to the Version History and right click on one of the Download buttons and hit "Copy link"
> 
> That'll give you a link like this: https://marketplace.visualstudio.com/_apis/public/gallery/publishers/MS-CEINTL/vsextensions/vscode-language-pack-es/1.80.2023070509/vspackage
> 
> Notice the version in the URL towards the end.
> 
> Now simply replace that version, with the version you got from step one and you should be able to grab the VSIX.
> 
> I know these aren't the easiest steps... and if I find out a better solution for you, I'll let you know, but it's a solution.

Thx a lot, It works! Found the corresponding vsix url by above steps.

https://marketplace.visualstudio.com/_apis/public/gallery/publishers/MS-CEINTL/vsextensions/vscode-language-pack-zh-hans/1.76.2023022209/vspackage
