### ISSUE TITLE
Language package for Ukraine and Ukrainians

### ISSUE THREAD

**Issue by CrazyTapok-bit** [microsoft/vscode-loc#1422]
Hello

[Ukraine](https://uk.wikipedia.org/wiki/%D0%A3%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D0%B0) and [Ukrainians](https://uk.wikipedia.org/wiki/%D0%A3%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%86%D1%96) really need a language package in [Ukrainian](https://uk.wikipedia.org/wiki/%D0%A3%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%81%D1%8C%D0%BA%D0%B0_%D0%BC%D0%BE%D0%B2%D0%B0). How can we contribute to its creation?

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 866866).

**Comment by CrazyTapok-bit** [comment]
> Thank you for your feedback. We are currently reviewing it (reference 866866).

There are about `40 million of us` and we need your support. We would love to hear your good news here

**Comment by cristianosuzuki77** [comment]
Thank you. The team will considers the suggestion and will review further.

**Comment by oleks** [comment]
> > Thank you for your feedback. We are currently reviewing it (reference 866866).
> 
> So what do I do with that number?

You do nothing, and just look through the PRs instead: #1239

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 866866)

**Comment by oleks** [comment]
> The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 866866)

What are "localization platform" and "production repo"?

**Comment by oleks** [comment]
> The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 866866)

This is very unclear. What will you be shipping with the next release?

**Comment by CrazyTapok-bit** [comment]
> The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 866866)

**Comment by CrazyTapok-bit** [comment]
> The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 866866)

It is not clear. It is implied that the Ukrainian language will be added in the new issue. Can you answer in more detail, please?

**Comment by Peluhnya** [comment]
I did it for myself, and I plan to develop it, because there are inconsistencies.
I plan to develop it, of course, if there is no other version of the Ukrainian language.
Tested on VScode - 1.88.0-insider

https://github.com/microsoft/vscode-loc/pull/1592
