### ISSUE TITLE
Should I edit this file, or not?

### ISSUE THREAD

**Issue by oleks** [microsoft/vscode-loc#1424]
Most `*i18n.json` files begin with the words:

```
{
	"": [
		"--------------------------------------------------------------------------------------------",
		"Copyright (c) Microsoft Corporation. All rights reserved.",
		"Licensed under the MIT License. See License.txt in the project root for license information.",
		"--------------------------------------------------------------------------------------------",
		"Do not edit this file. It is machine generated."
	],
```

As I understand it; it is actually the `*i18n.json` files that need to be modified to add a new language pack. If so, it is quite misleading that the file begins with the words `"Do not edit this file. It is machine generated."`. If that is part of a translation, that should be made clear in the documentation on how to do the translations - that one should ignore this particular comment.

Also, most language packs do not edit these words. That is odd, and unnecessarily repetitive. The reader is quite likely to be a bearer of the language, in question, touching this file to make some adjustments to the translation. Are any of the language packs NOT subject to the MIT Licence? Not according to your documentation they're not :smiley:

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 867608).

**Comment by cristianosuzuki77** [comment]
cc @TylerLeonhardt

**Comment by oleks** [comment]
> 



> @oleks in the README we call this out: https://github.com/microsoft/vscode-loc#contributing
> 
> If you want to give feedback or report issue with a translation, please create a [new GitHub issue](https://github.com/microsoft/vscode-loc/issues/new). Please check if a topic about your issue already exists! Translation strings are managed and edited in Microsoft Localization Platform and changes to strings can only be made there. Due to this, pull request fixing translations won't be accepted. All other PRs to things like `README.md`, `package.json`, etc will be accepted at the discretion of the maintainers.

So translations from the community are not accepted?

**Comment by oleks** [comment]
> @oleks translations from the community _are_ "accepted"... or a better word would be "evaluated"... via GitHub issues... as they would need to be updated in an internal tool that can only be done by maintainers.

Okay, thanks; that clarifies the process.

My original question was also, in part, a question/comment about the purpose of the empty key (""). Should it also be translated, or not? My understanding is - no. If not, why is it repeated in each file..

I guess more importantly, is there a way to see the translations in a local VS Code instance and a local clone of the repository?

**Comment by TylerLeonhardt** [comment]
> My original question was also, in part, a question/comment about the purpose of the empty key (""). Should it also be translated, or not?

It's because these files are in JSON, not JSONC. They don't support `// comments`, so this is the relatively standard way of having a comment at the top of the file.

**Comment by CrazyTapok-bit** [comment]
@TylerLeonhardt  Now it's clear that all translations are specified in Microsoft's localization platform. But this raises a new question. The platform is public The community can make changes Is it a closed platform, for a limited group of people If the platform is closed from public access, then I understand that the only way to affect something is to create a new issue and hope it gets accepted!

**Comment by oleks** [comment]
> > My original question was also, in part, a question/comment about the purpose of the empty key (""). Should it also be translated, or not?
> 
> It's because these files are in JSON, not JSONC. They don't support `// comments`, so this is the relatively standard way of having a comment at the top of the file.

Sorry, but that confuses me again. That means that this is a comment for the `*i18n.json` file in question, commandeering me not to modify it. If I don't modify it, then how do I contribute a translation?

**Comment by TylerLeonhardt** [comment]
@oleks 

> That means that this is a comment for the *i18n.json file in question, commandeering me not to modify it. If I don't modify it, then how do I contribute a translation?

You open an issue saying "this translation should be X instead of Y". Then a maintainer will review it and make the change in the backend which will then update the respective file in this repo.

> why is it repeated in each file

Because in practice, folks don't always read the README and historically made changes to these files even though that isn't the process.

@CrazyTapok-bit 

> the only way to affect something is to create a new issue and hope it gets accepted!

Yes. This is correct. Although it's unfortunate we can't use PRs for these files, do keep in mind that in any ordinary open source repo there is still that "hope it gets accepted" aspect because it's up to the maintainer to decide if the suggestion (be it in an issue or PR) is valid... so although our process isn't as direct as just "open a PR", it is direct in that we are looking at issues an acting on them.

**Comment by oleks** [comment]
> @oleks
> 
> > That means that this is a comment for the *i18n.json file in question, commandeering me not to modify it. If I don't modify it, then how do I contribute a translation?
> 
> You open an issue saying "this translation should be X instead of Y". Then a maintainer will review it and make the change in the backend which will then update the respective file in this repo.

Lastly, can you clarify the process of initiating support for a new language?

**Comment by csigs** [comment]
Resolved as As Designed.

**Comment by TylerLeonhardt** [comment]
> Lastly, can you clarify the process of initiating support for a new language?

We can't support anymore languages at the moment. VS Code is bound by what @cristianosuzuki77 and the Microsoft localization platform are willing to do for us.

That said, if you _wanted to go about implementing a language pack yourself, that is possible but it's a bit of rough process... 

You have to:
* Create a language pack extension (copy one of the existing ones)
* clone the VS Code source, install the dependencies and run `yarn gulp vscode-translations-export`
* that exports XML files so we need to turn them into JSON with:
```
yarn run update-localization-extension --location FULLPATHOFXMLFOLDER $LANGUAGE_ID
```

From there you have JSON you can start translating... but keep in mind, strings change over time, so it's going to be a lot to maintain.

This is a process I would love to make easier for folks ... to maintain language packs easier... but I haven't gotten around to it.
