### ISSUE TITLE
[zh-hans]Search panel,`files to include` and `file to exclude` placeholder info use `、`, which is not useful

### ISSUE THREAD

**Issue by shutaozhenzhen** [microsoft/vscode-loc#1428]
```json
{
			"placeholder.excludes": "例如 *.ts、src/**/exclude",
			"placeholder.includes": "例如 *.ts、src/**/include"
}
```

建议使用`, `，因为这个分隔符才真正有效，`、`啥用没有

suggest to use `, `, which is actually useful. `、` is useless, even harmful

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 868238).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 868238)
