### ISSUE TITLE
ru incorrect translation

### ISSUE THREAD

**Issue by qiray** [microsoft/vscode-loc#143]
There is a translation mistake In open URL dialog in VSCode. Last button label is _"Открыто"_ (it means "is opened"). I think it should be _"Открыть"_.

![screenshot](https://user-images.githubusercontent.com/8692517/73342375-7b067a00-428f-11ea-8c36-36da676ce985.png)

**Comment by lukaschal** [comment]
Fixed.

new tgt:  Открыть
