### ISSUE TITLE
[ru-RU] Localization bug in main menu 'View' -> 'Sticky scroll'

### ISSUE THREAD

**Issue by srgmv** [microsoft/vscode-loc#1435]
Type: <b>Bug</b>

1. Open VS Code.
2. Install extension 'Russian Language Pack for Visual Studio Code'.
3. Apply this extension.
4. Open (in Russian) menu View -> Sticky scroll. In Russian before this item there are 3 symbols '&'.
It looks like: "&&Залипание прокрутки", but must be "Залипание прокрутки".
In the file "main.i18n.json" there is parameter "miStickyScroll": "&&&Залипание прокрутки". Maybe this is a problem...

Extension version: 1.80.2023071209
VS Code version: Code 1.80.1

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 870574).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 870574)
