### ISSUE TITLE
pack-ko has the wrong word

### ISSUE THREAD

**Issue by DevooKim** [microsoft/vscode-loc#1437]
[permalink](https://github.com/microsoft/vscode-loc/blob/98256024b9f4102d855a2e056b98499087606ba1/i18n/vscode-language-pack-ko/translations/extensions/vscode.typescript-language-features.i18n.json#L177C45-L177C45)

For now, it looks like this
```
"configuration.suggest.names": "JavaScrip 제안에서 파일의 고유한 이름 포함을 사용하거나 사용하지 않도록 설정합니다. 이름 제안은 `@ts-check` 또는 `checkJs`를 사용하여 의미 체계적으로 확인되는 JavaScript 코드에서 항상 사용하지 않도록 설정됩니다.",
```

But this is how it should be.
```
"configuration.suggest.names": "JavaScript 제안에서 파일의 고유한 이름 포함을 사용하거나 사용하지 않도록 설정합니다. 이름 제안은 `@ts-check` 또는 `checkJs`를 사용하여 의미 체계적으로 확인되는 JavaScript 코드에서 항상 사용하지 않도록 설정됩니다.",
```

- JavaScrip -> JavaScript

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 870575).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 870575)
