### ISSUE TITLE
[german/de] Incorrect Translation in "Open URL" / trustedDomains Dialog 

### ISSUE THREAD

**Issue by robinschreiner** [microsoft/vscode-loc#144]
There is also a translation mistake in the german open URL dialog in VSCode. 
First Button says "Domänen" which is, from language point of view, right but in the technical context not used. Last button "open" is translated to "Eröffnungskurs" which means "opening course".

**Is:** "Eröffnungskurs"
**Should be** "Öffnen"

**Is:** "Domänen"
**Should be** "Domains"

<img width="804" alt="screenshot" src="https://user-images.githubusercontent.com/895586/73787560-d955c000-479b-11ea-876f-ae06f72d0d0b.png">

**LP Information:**
Version: 1.41.2

**VSCode Information**
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Datum: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
Betriebssystem: Darwin x64 19.2.0

**Comment by janbaltus** [comment]
Can you please specify version of LP used?

**Comment by robinschreiner** [comment]
Currently 1.41.2 is installed. According to VS Code, this is the latest available Version.

**Comment by janbaltus** [comment]
Please wait for official release of 1.42 or you can use Insider version where 1.42.2 is already published.
