### ISSUE TITLE
I got a compatibility issue while installing language-pack offline

### ISSUE THREAD

**Issue by gurvey** [microsoft/vscode-loc#1454]
☒ Unable to install extension 'ms-ceintl.vscode-language-pack-zh-hans' as it is not compatible with VS Code '1.80.1'.
 I tried 1.81.2023072609 and then 1.81.2023071909 and then 1.80.2023071209. That works. Is there a place where I can directly see the corresponding of compatibility?

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 876731).

**Comment by crsuzukimsft** [comment]
@TylerLeonhardt Could you please assist here? Thank you.

**Comment by TylerLeonhardt** [comment]
It's the first two digits of the version number. So for VS Code `1.80.1`, you will need the latest `1.80.xxxx` version. For VS Code 1.81.0, you will need the latest `1.81.xxxx` version, and so on.
