### ISSUE TITLE
[zh-Hans]The word "Electron" should not be translated in Simplified Chinese because it doesn't have a proper Chinese name now.

### ISSUE THREAD

**Issue by wxp2840772674** [microsoft/vscode-loc#1457]
Detail Information of Chinese (Simplified) Language Pack:
```
详细信息
已发布
2018/4/24 01:35:37
上次发布时间
2023/8/2 17:25:54
上次更新时间
2023/8/2 22:14:00
标识符
ms-ceintl.vscode-language-pack-zh-hans
```
```
More Info
Published
4/24/2018, 01:35:37
Last released
8/2/2023, 17:25:54
Last updated
8/2/2023, 22:14:00
Identifier
ms-ceintl.vscode-language-pack-zh-hans
```

In the About Form on Microsoft Visual Studio Code. The word "Electron" has been translated in Chinese.
I think that the word "Electron" shouldn't use the translation "电子" because the Electron project doesn't have a proper Chinese name.
This is Simplified Chinese translation of About frame on Microsoft Visual Studio Code.
![image](https://github.com/microsoft/vscode-loc/assets/90772701/4f39cc7a-58fc-4b30-9193-9343fe7bece3)
This is English version of About frame on Microsoft Visual Studio Code.
![image](https://github.com/microsoft/vscode-loc/assets/90772701/9f9a84c2-fa97-4dd5-9c5d-84db6c2c345e)

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 878026).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 878026)
