### ISSUE TITLE
[zh-Hans]The Chinese (Simplified) (简体中文) Language Pack plugin is automatically deleted

### ISSUE THREAD

**Issue by syschars** [microsoft/vscode-loc#1459]
When I installed the plugin, I was prompted to reload the window. However, when I rebooted, the plugin was automatically deleted.

vscode about:
                Version: 1.81.0 (system setup)
                Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
                Date: 2023-08-02T12:37:13.485Z
                Electron: 22.3.18
                ElectronBuildId: 22689846
                Chromium: 108.0.5359.215
                Node.js: 16.17.1
                V8: 10.8.168.25-electron.0
                OS: Windows_NT x64 10.0.22621

plugin version: v1.81.2023080209

**Comment by wzh4464** [comment]
Same issue here. If installing traditional Chinese everything is good.
After updating to new version of VScode may be the reason.
版本: 1.81.0 (Universal)
認可: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
日期: 2023-08-02T12:40:02.782Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.6.0

**Comment by syschars** [comment]
OK, thank you. I have gone back to the previous version of this plugin and it works fine.

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 878976).

**Comment by syvshc** [comment]
same issue: 
版本	Windows 11 专业版
版本	23H2
安装日期	‎2022/‎5/‎12
操作系统版本	22631.2129
体验	Windows Feature Experience Pack 1000.22669.1000.0

Version: 1.81.0 (user setup)
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:37:13.485Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by piwawa** [comment]
I met same problem, and it prompt me to restart to change language every time. When i VSCODE, it display ENG and show this:

![image](https://github.com/microsoft/vscode-loc/assets/46926496/c27707aa-6bbb-45f6-b819-35a28d2138b6)

After it pressed `install and restart`, it became Chinese. But i restart it again, it changes to ENG again!

![image](https://github.com/microsoft/vscode-loc/assets/46926496/e954247d-7b48-493c-8318-a0a24395be36)

What WRONG is it? This creepy BUG appeared after the latest VSCODE update!

**Comment by JackieCode** [comment]
I have the same problem

Version: 1.81.0 (user setup)
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:37:13.485Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by Waldenth** [comment]
> I met same problem, and it prompt me to restart to change language every time. When open VSCODE, it display ENG and show this:
> 
> ![image](https://user-images.githubusercontent.com/46926496/258712773-c27707aa-6bbb-45f6-b819-35a28d2138b6.png)
> 
> After presseing `install and restart`, it became Chinese. But it changes to ENG again if i restart it!
> 
> ![image](https://user-images.githubusercontent.com/46926496/258713473-e954247d-7b48-493c-8318-a0a24395be36.png)
> 
> What WRONG is it? This creepy BUG appeared after the latest VSCODE update! I want to fix Chinese to display!

I have the same problem.

```
Version: 1.81.0 (user setup)
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:37:13.485Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
```

**Comment by zengfan1992** [comment]
When I rollback to 1.81.2023072609, it works.

**Comment by jasinliu** [comment]
same problem, hope fix soon

**Comment by HiroyukiNIshimura** [comment]
日本語もおんなじ

バージョン: 1.81.0 (user setup)
コミット: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
日付: 2023-08-02T12:37:13.485Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by Yurunsoft** [comment]
Me too

**Comment by world0** [comment]
安装上一个版本,暂时解决问题

**Comment by JackieCode** [comment]
是的 退回到1.80版本就没有这个问题了

**Comment by tangyuep** [comment]
I suffer the same problem when I use VScode version 1.81. After rebooted, the Chinese Language Pack plugin disapeared.

**Comment by izoyo** [comment]
This version of the plug-in may even block Remote-SSH.

**Comment by H2Sxxa** [comment]
Same problem,it's awful

**Comment by xtremforce** [comment]
Same issue here on macOS

**Comment by guzy0324** [comment]
the problem seems to be fixed.

**Comment by jasinliu** [comment]
> It seems that the problem has already been fixed.

Sounds good! How do you find this?

**Comment by guzy0324** [comment]
> > It seems that the problem has already been fixed.
> 
> Sounds good! How do you find this?

the extension works fine today, though I don't see any update on the extension or the vscode.

**Comment by jasinliu** [comment]
> > > It seems that the problem has already been fixed.
> > 
> > 
> > Sounds good! How do you find this?
> 
> the extension works fine today, though I don't see any update on the extension or the vscode.

You are so lucky. On my machine, it works fine at the beginning,  but it becomes broken after few days, and nothing gets better now.

**Comment by syschars** [comment]
Today vscode was updated to 1.81.1, this issue does not recur.

版本: 1.81.1 (system setup)
提交: 6c3e3dba23e8fadc360aed75ce363ba185c49794
日期: 2023-08-09T22:22:42.175Z
电子: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by wzh4464** [comment]
Everything works fine now when we catch up with the newest release of vscode. I believe that this issue should be closed.
