### ISSUE TITLE
The Translation Issue of Menu

### ISSUE THREAD

**Issue by RobinPang** [microsoft/vscode-loc#146]
Issue Type: <b>Bug</b>

【运行(&R)】Display as【&运行】

Extension version: 1.43.2
VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

**Comment by lukaschal** [comment]
Actual translations looks like correct in a MLCP.

![image](https://user-images.githubusercontent.com/18324331/76622283-7fca7900-6531-11ea-906c-06b7e876e024.png)

**Comment by janbaltus** [comment]
Fixed in 1.43.7 LP
