### ISSUE TITLE
Request for adding new locale: Karakalpak language (code: kaa)

### ISSUE THREAD

**Issue by alizhumagaliev** [microsoft/vscode-loc#1461]
Hi! I'm a backend developer from the Republic of Karakalpakstan. I'd like to help to translate VSCode into Karakalpak language. Is it possible? I've already created issue about it but I didn't get answer. Thanks!

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 879490).

**Comment by danyeh** [comment]
Technically, it is possible for community to contribute and publish language pack. Please reference https://github.com/microsoft/vscode-loc/wiki on how to.
![image](https://github.com/microsoft/vscode-loc/assets/19785531/d4df99d9-69e3-4d5b-aee6-bde6f5e33b20)
