### ISSUE TITLE
[zh-Hans] Suggest that "workbench.action.inspectKeyMappings" should be "检查按键映射"

### ISSUE THREAD

**Issue by wzh4464** [microsoft/vscode-loc#1465]
In command panel, we can see
<img width="335" alt="image" src="https://github.com/microsoft/vscode-loc/assets/32484940/809b9223-16d6-499c-acdd-07a99d91581a">

For the json one, it is correctly translated, but not for the other one.

I suggest aligning them up to "按键" since it represents the key in the keyboard, not the passphrase.

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 891510).

**Comment by v-mholloway** [comment]
@wzh4464 can you confirm the resource identifier is workbench.action.inspectKeyMappings?
could you provide a link to the file in question?

**Comment by wzh4464** [comment]
Of course.
Here is the link:
https://github.com/microsoft/vscode-loc/blob/d0197c125c6ef689c611d0fb7e1107fd80cee8d8/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L4839

**Comment by csigs** [comment]
Resolved as Fixed & Verify.
