### ISSUE TITLE
[es] Type error - Errata

### ISSUE THREAD

**Issue by manugc** [microsoft/vscode-loc#1466]
The line contains a typo, it has the value "adicionles" instead of "adicionales".

https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-es/translations/main.i18n.json#L10791

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 892469).

**Comment by csigs** [comment]
Resolved as Fixed & Verify.
