### ISSUE TITLE
[ko] Incorrect translation (git)

### ISSUE THREAD

**Issue by Yonggwan07** [microsoft/vscode-loc#1467]
- English String: "Message ({0} to commit on \"{1}\")"
- Current Translation: "메시지(“{1}”에서 커밋하기 위한 {0})"
- Suggested Translation: "메시지({0}로 “{1}“에 커밋)"
---
- English String: "Message ({0} to commit)"
- Current Translation: "메시지(커밋할 {0})"
- Suggested Translation: "메시지({0}로 커밋)"

The current translation is grammatically incorrect.

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 892470).

**Comment by csigs** [comment]
Resolved as Fixed & Verify.
