### ISSUE TITLE
[ko] translation of "dark" should be consistent

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-loc#1468]
For the Korean language pack, you can see that "dark" is handled differently in three ways in the Theme picker:

![Image](https://github.com/microsoft/vscode-loc/assets/2644648/3b1987cc-c0d0-402b-82da-0ced9899e5cf)

* `Dark+` (no localization) - [defined here](https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-ko/translations/extensions/vscode.theme-defaults.i18n.json#L14)
* `Kimbie 어둡게` (dark translated) - [defined here](https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-ko/translations/extensions/vscode.theme-kimbie-dark.i18n.json#L13)
* `다크 모던` (all translated with loan words "daku modeon") - [defined here](https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-ko/translations/extensions/vscode.theme-defaults.i18n.json#L13)

All I ask is that "dark" be handled the same way in all of these instances.

cc @Tyriar

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 896967).

**Comment by csigs** [comment]
Resolved as Fixed & Verify.
