### ISSUE TITLE
The Translation Issue of “Run”

### ISSUE THREAD

**Issue by AFGXF** [microsoft/vscode-loc#147]
Issue Type: __Bug__

The contents of the "Run" menu have not been translated (zh-cn)

Extension version: 1.43.7

VS Code version: Code 1.43.0 

OS version: Windows_NT x64 10.0.18363

![image](https://user-images.githubusercontent.com/54260142/76593693-fc5d5780-6531-11ea-80a9-75e774863976.png)

![image](https://user-images.githubusercontent.com/54260142/76593753-20b93400-6532-11ea-8669-51dee8e6b53d.png)

**Comment by janbaltus** [comment]
&Run issue is fixed in 1.43.7 LP, but unloc issue will be fixed in 1.45 LP
