### ISSUE TITLE
[fr] Missing space in dev container remote indicator

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-loc#1470]
There should be a space after the word "Conteneur"
![Remote indicator in dev container](https://github.com/microsoft/vscode-loc/assets/7199958/769260fe-1469-4502-a2c7-a7d24f28a0cb)

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 898454).

**Comment by v-mholloway** [comment]
@rzhao271 can you please indicare the file/resource where this string exists?

**Comment by v-mholloway** [comment]
closing as we require more information. please open new issue with additional info if you still require a change to be implemented.
