### ISSUE TITLE
[ja] Incorrect translation for "configuration.markdown.copyFiles.destination"

### ISSUE THREAD

**Issue by ryo8000** [microsoft/vscode-loc#1472]
I found a translation error.

i18n/vscode-language-pack-ja/translations/extensions/vscode.markdown-language-features.i18n.json

```
"configuration.markdown.copyFiles.destination"
error: ドロップまたは貼り付けによって作成されたファイルをコピーするする場所を定義します。
suggest: ドロップまたは貼り付けによって作成されたファイルをコピーする場所を定義します。
```

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 900695).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 900695)
