### ISSUE TITLE
Empty workbench hints are localized incorrectly

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-loc#1473]
Shift is localized as `<Shift>`, ctrl is localized as `Ctrl`

![Image](https://github.com/microsoft/vscode/assets/2193314/a310a119-7a18-4f59-af4b-3781855d1f71)

Not sure if it's purely a translation issue or a problem in the `localize` call.

**Comment by TylerLeonhardt** [comment]
I think we should probably not have the `<` and `>` for SHIFT and ALT here.

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 902602).

**Comment by Tyriar** [comment]
The related translations also seem pretty inconsistent:

- Why is ctrlKey.long `제어` but altKey.long is `<Alt>`?
- Why is superKey `슈퍼` but ctrlKey `Ctrl`?

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 902602)

**Comment by Tyriar** [comment]
@csigs is it possible for me to review the changes before the release?

**Comment by Tyriar** [comment]
Ping @csigs

**Comment by TylerLeonhardt** [comment]
@Tyriar, csigs is a bot. @cristianosuzuki77 is probably the best person to help.
