### ISSUE TITLE
[zh-Hans] Suggest translation

### ISSUE THREAD

**Issue by Akaiamerin** [microsoft/vscode-loc#1474]
I hope these can be translated uniformly to make it easier to understand.

https://github.com/microsoft/vscode-loc/blob/d0197c125c6ef689c611d0fb7e1107fd80cee8d8/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L728

suggestion: `背景颜色的高亮范围，喜欢通过快速打开和查找功能。颜色必须透明，以免隐藏下面的修饰效果。`

https://github.com/microsoft/vscode-loc/blob/d0197c125c6ef689c611d0fb7e1107fd80cee8d8/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L730

suggestion: `高亮显示符号的背景颜色，例如转到定义或转到下一个/上一个符号。颜色必须透明，以免隐藏下面的修饰效果。`

https://github.com/microsoft/vscode-loc/blob/d0197c125c6ef689c611d0fb7e1107fd80cee8d8/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L2312

suggestion: `高亮显示符号的背景颜色，例如转到定义或转到下一个/上一个符号。颜色必须透明，以免隐藏下面的修饰效果。`

https://github.com/microsoft/vscode-loc/blob/d0197c125c6ef689c611d0fb7e1107fd80cee8d8/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L2382

suggestion: `当前标题背景的内联合并冲突。颜色必须透明，以免隐藏下面的修饰效果。`

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 902603).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 902603)
