### ISSUE TITLE
[ja] Translation suggestion for committing messages

### ISSUE THREAD

**Issue by AioiLight** [microsoft/vscode-loc#1477]
https://github.com/microsoft/vscode-loc/blob/e9dacb8af327d5dbb6af6b1906c5d54bc34fc8bc/i18n/vscode-language-pack-ja/translations/extensions/vscode.git.i18n.json#L144-L145

My suggestions:
```json
 "Message ({0} to commit on \"{1}\")": "メッセージ ({0} で \"{1}\" にコミット)", 
 "Message ({0} to commit)": "メッセージ ({0} でコミット)", 
```

I think these sentences should start from key-binding.

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 907313).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 907313)
