### ISSUE TITLE
A request has failed from JSON Language Features

### ISSUE THREAD

**Issue by Zyx-A** [microsoft/vscode-loc#148]
> Chinese (Simplified) Language Pack for Visual Studio Code

Problematic Version:
**`v1.43.8`**
Correct Version:
`v1.43.7`

Today when I open a new window I get this message:

![error](https://user-images.githubusercontent.com/2193314/70080486-7ee18d00-15bb-11ea-8738-6290ab22e7f1.png)

> A request has failed. See the output for more information.
> json language features

enable `"json.trace.server": "verbose"` :

``` log
[Trace - 下午9:11:26] Received notification 'window/logMessage'.
Params: {
    "type": 1,
    "message": null
}

[Error - 下午9:11:26] null
[Trace - 下午9:11:26] Sending request 'textDocument/documentSymbol - (1)'.
Params: {
    "textDocument": {
        "uri": "vscode-userdata:/home/lyx/.config/Code/User/settings.json"
    }
}
```

OS Env:
OS Version: `CentOS 7.6`
Kernel Version: `4.12.14-1.el7.x86_64`

**Comment by janbaltus** [comment]
Please update to 1.43.9 which fix this issue
