### ISSUE TITLE
Chinese language pack does not work in vscode 1.43.0

### ISSUE THREAD

**Issue by zhoujin7** [microsoft/vscode-loc#149]
Chinese language pack does not work in vscode 1.43.0

OS: windows 10

![捕获](https://user-images.githubusercontent.com/8288988/76970582-126e7c00-6967-11ea-82cc-6bc622d5c5dd.PNG)

**Install it, Ctrl+Shift+P, config display lang --> zh-cn, restart vscode. but it does not work.**

**Comment by whossun** [comment]
> Chinese language pack does not work in vscode 1.43.0
> 
> OS: windows 10
> 
> ![捕获](https://user-images.githubusercontent.com/8288988/76970582-126e7c00-6967-11ea-82cc-6bc622d5c5dd.PNG)
> 
> **Install it, Ctrl+Shift+P, config display lang --> zh-cn, restart vscode. but it does not work.**

Chinese language pack 1.43.8不起作用，回退到1.43.7能正常使用

**Comment by xylds666** [comment]
Me too.

**Comment by aixiu** [comment]
回退到1.43.7能正常使用

**Comment by wejectchen** [comment]
> 回退到1.43.7能正常使用

我也发现了。。。

**Comment by LeoMiter** [comment]
Me too!!!

Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:34:44.548Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

**Comment by sinsong** [comment]
Same problom, effect after a update...
---
Version: 1.43.1 (user setup)
Commit: fe22a9645b44368865c0ba92e2fb881ff1afce94
Date: 2020-03-18T07:01:20.184Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by cacads** [comment]
Chinese (Simplified) Language Pack for Visual Studio Code

Version | 1.43.9 |  
-- | -- | --
Released on | 2018/4/24 上午1:35:37 |  

Last updated | 2020/3/19 上午3:09:46

已经更新，修复了

**Comment by zhoujin7** [comment]
已经修复了 更新该插件即可
