### ISSUE TITLE
[zh-CN] Suggest that donot translate CMake/Build output in [OUTPUT] table. It's so ugly.

### ISSUE THREAD

**Issue by Elylhance** [microsoft/vscode-loc#1490]

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 914919).

**Comment by v-mholloway** [comment]
@Elylhance Can you please provide more information?
screen shots? english string? resource identifiers?

**Comment by v-mholloway** [comment]
no actionable information available
