### ISSUE TITLE
[ko] Unclear translation about 'command.branch' and 'command.branchFrom'

### ISSUE THREAD

**Issue by whitecloudy** [microsoft/vscode-loc#1491]
"command.branch": "분기 만들기...",
			"command.branchFrom": "분기를 만듭니다...",

These two commands are almost indistinguishable in korean. I would suggest follows.

			"command.branch": "새 분기 만들기",
			"command.branchFrom": "타 분기에서 새 분기 만들기",

This is the related json file.
https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-ko/translations/extensions/vscode.git.i18n.json

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 915239).

**Comment by csigs** [comment]
Resolved as Fixed & Verify.
