### ISSUE TITLE
[es] Incorrect translation for extension installation recommendation

### ISSUE THREAD

**Issue by jruales** [microsoft/vscode-loc#1493]
A better translation would be `¿Desea instalar la extensión 'Rainbow CSV' de mechatroner, recomendada para titanic.csv?`
![image](https://github.com/microsoft/vscode-loc/assets/1588988/60877c71-8682-4309-b2f6-5e4addc0fbdc)

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 917069).

**Comment by v-mholloway** [comment]
@jruales could you provide a resource identifier or filename for the string you want to change?

**Comment by jruales** [comment]
@v-mholloway The relevant strings are the keys "extensionFromPublisher" and "recommended" below. I now realize that the translator isn't to blame here, since they did the best they could with those two strings. The issue is actually in the programmers, who should have just used a single string, but instead they separated this into two strings that they then put together in code, which causes the grammatical error. I think that the programmers will need to treat this as a single string. That would allow the translators to use the proper grammar, especially when matching the grammatical gender of the word "the" in one of the strings with "extension" in the other string.

```json
		"vs/workbench/contrib/extensions/browser/extensionRecommendationNotificationService": {
			"exeRecommended": "Tiene {0} instalado en el sistema. ¿Desea instalar el {1} recomendado para él?",
			"extensionFromPublisher": "'{0}' extensión de {1}",
			"extensionsFromMultiplePublishers": "extensiones de {0}, {1} y otros",
			"extensionsFromPublisher": "extensiones de {0}",
			"extensionsFromPublishers": "extensiones de {0} y {1}",
			"ignoreAll": "Sí, ignorar todo",
			"ignoreExtensionRecommendations": "¿Quiere ignorar todas las recomendaciones de extensión?",
			"install": "Instalar",
			"install and do no sync": "Instalar (no sincronizar)",
			"neverShowAgain": "No volver a mostrar",
			"no": "No",
			"recommended": "¿Desea instalar el {0} recomendado para {1}?",
			"show recommendations": "Mostrar recomendaciones",
			"this repository": "este repositorio"
		},
```

**Comment by jruales** [comment]
I've created this separate issue with VS Code to see if they fix the underlying code issue: https://github.com/microsoft/vscode/issues/195926

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 917069)
