### ISSUE TITLE
[zh-TW] Suggest that "Preserve Case" in the Replace UI is translated to "保留大小寫"

### ISSUE THREAD

**Issue by Enzhihpp** [microsoft/vscode-loc#1495]
**Suggestion:**

- English String: Preserve Case
- Current Translation: 保留案例
- Suggested Translation： 保留大小寫

**Screenshots:**
![image](https://github.com/microsoft/vscode-loc/assets/96558635/17b11377-ec1c-41e5-8fef-96967214f60f)

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 919663).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 919663)
