### ISSUE TITLE
[zh-Hans] 多余的字

### ISSUE THREAD

**Issue by green961** [microsoft/vscode-loc#1498]
![搜狗截图20231102134942](https://github.com/microsoft/vscode-loc/assets/81228933/50394ba2-b8ec-44ef-a68c-1f64f88923ef)
`方` should be redundant

Not just square brackets

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 923366).

**Comment by v-mholloway** [comment]
@green961 can you please make your request in English...?
