### ISSUE TITLE
[fr] incorrect translation for `search settings`

### ISSUE THREAD

**Issue by jd-develop** [microsoft/vscode-loc#1499]
The current translation is « Paramètres de recherche », which means « settings of the search », and not « search in the settings ».

The correct translation should be something like « Rechercher dans les paramètres ».

Moreover, the translation for « Backup and sync settings » should not be « Paramètres de sauvegarde et de synchronisation », but « Sauvegarder et synchroniser les paramètres », for the same reason.

![image](https://github.com/microsoft/vscode-loc/assets/65287945/dac842ba-9a7f-4cb5-a9ac-1b00fb62d495)
![image](https://github.com/microsoft/vscode-loc/assets/65287945/b67f2b6e-2bc1-4c21-8eb2-bca74e0f52a6)

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 923588).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 923588)
