### ISSUE TITLE
Add beautiful Icons for all extended languages

### ISSUE THREAD

**Issue by MaleDong** [Microsoft/vscode-loc#15]
Issue Type: <b>Feature Request</b>

Now we don't have icons for language extensions, it's a default empty icon:
![noicon](https://user-images.githubusercontent.com/6959154/39609143-28d5c372-4f79-11e8-92fe-ee165feed82a.PNG)
Compared with other plug-in extensions, they have a nice icon to identity themselves:
![normalicons](https://user-images.githubusercontent.com/6959154/39609157-41ea23f8-4f79-11e8-9b9f-5d036555ccde.PNG)
So, the request is very easy——Would you mind doing designs of icons for all extended languages (Take Simplified Chinese as an example but for all)?

**Suggestion: The icon can be the name of shortened language names, for Chinese  it would be zh-cn, for traditional Chinese, it should be zh-tn. Something like that (Maybe the background color can be also different)**:

To simplify this, we can use icon generator to generate languages batchly (like what avatars are seen in https://forums.asp.net/).

![languageicon](https://user-images.githubusercontent.com/6959154/39609216-c818ee3c-4f79-11e8-871f-20c6ff914118.png)

Extension version: 1.23.1
VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T16:44:10.813Z)
OS version: Windows_NT ia32 6.3.9600

**Comment by danyeh** [comment]
Thank you for your suggestion! I checked with icon team, guidance is to use same icon for all languages for now. I have conveyed your suggestion to the team.
1.23.3 now has that icon.
