### ISSUE TITLE
[pt-br] Incorrect translation

### ISSUE THREAD

**Issue by Gustavo-gthb** [microsoft/vscode-loc#1500]
Hi, guys. Thank you for your amazing work.

I noticed an incorrect translation for (pt-br), it translates "Select a branch or tag to checkout" to "Selecione um branch ou uma tag para finalizar compra".

- English: Select a branch or tag to checkout.

- Current: Selecione um branch ou uma tag para finalizar compra.

- Correct translation: Selecione uma branch ou uma tag para trocar.

![image](https://github.com/microsoft/vscode-loc/assets/117493006/e58f1300-8891-4797-bbf4-b488cfe074bc).
![image](https://github.com/microsoft/vscode-loc/assets/117493006/43156b6b-aed5-40ff-b9cd-23972dfdb5e5)

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 924154).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 924154)
