### ISSUE TITLE
[ja] Some "以前の" ("previous") should be "前の" because they aren't in the past

### ISSUE THREAD

**Issue by Phroneris** [microsoft/vscode-loc#1501]
At least, these translations should use "前の" rather than "以前の".

- `vs/workbench/browser/parts/editor/editor.contribution`
  - `miPreviousEditorInGroup`: `"グループ内の以前のエディター(&&P)"`
- `vs/workbench/browser/parts/editor/editorActions`
  - `openPreviousEditor`: `"以前のエディターを開く"`
- `vs/workbench/contrib/debug/browser/debugCommands`
  - `prevDebugConsole`: `"以前のデバッグ コンソールへのフォーカス"`
- `vs/workbench/contrib/scm/browser/scm.contribution`
  - `scm view previous commit`: `"ソース管理: 以前のコミットの表示"`

That's because they are entries paired with another "do *next* something" ones.
In Japanese, "以前の" has a nuance of indicating something in the past chronologically, so "前の" should be used to simply indicate "backward next" in a sequence of things.

So, note that not all "以前の" need to be replaced with "前の".
For example, I don't think the following translations need to be modified, because they exactly mean the past:

- `vs/workbench/browser/parts/editor/editorActions`
  - `navigateEditorHistoryByInput`: `"履歴から以前のエディターをすばやく開く"`
- `vs/workbench/contrib/terminal/browser/terminalActions`
  - `workbench.action.terminal.clearPreviousSessionHistory`: `"以前のセッション履歴をクリアする"`

Thanks.

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 924641).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 924641)
