### ISSUE TITLE
Original en-US file?

### ISSUE THREAD

**Issue by Phroneris** [microsoft/vscode-loc#1503]
When I created issues here, I searched for a file like <code>/i18n/vscode-language-pack-**en**</code> - or <code>**en-US**</code> - <code>/translations/main.i18n.json</code> in order to refer to the nuances of the original English strings to improve my issues, but I couldn't find it.

Possibly internal translators have easy access to the original strings, but there seems to be no way for mere external users like me, who only report issues here, to do so.
Of course I can run VS Code with my language pack disabled and go to a place where a target string is displayed, but it's not easy!

How about having the original American English file incuded in this repository?

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 924732).

**Comment by crsuzukimsft** [comment]
@TylerLeonhardt could you please review this ticket?

**Comment by TylerLeonhardt** [comment]
@Phroneris the English strings are found inside of the product:
https://github.com/microsoft/vscode

For example:
https://github.com/microsoft/vscode/blob/4d5652d9bb7f46577fc75be958237aeb08be6092/src/vs/workbench/contrib/localization/common/localization.contribution.ts#L34

Notice the localize calls. Those are the English strings.

If you have issues with a particular English string, you should be able to search for it in the main repo and feel free to open an issue there.

**Comment by Phroneris** [comment]
@TylerLeonhardt Thanks.

Then could you please mention it in the README?

Referencing the nuances of the original text is very important in localization, so it seems unfriendly that there is no direct resource files or even an indirect reference guide here.

**Comment by Phroneris** [comment]
@TylerLeonhardt Thank you for the improvement!
