### ISSUE TITLE
[zh-cn] 问题面版过滤菜单优化

### ISSUE THREAD

**Issue by xiaoxiyao** [microsoft/vscode-loc#1510]
![image](https://github.com/microsoft/vscode-loc/assets/12003562/e68b5e57-1cdb-4689-a935-5005d65da73c)
![image](https://github.com/microsoft/vscode-loc/assets/12003562/d78af7ce-3d60-4512-bdd5-c1faf3d11f1e)
如图，不勾选时翻译比较奇怪，建议不勾选时和勾选时的文字一致。

**Comment by hyzx86** [comment]
Looks like the problem has been fixed.
![image](https://github.com/microsoft/vscode-loc/assets/15613121/40a84d34-9eed-42b2-9139-fa87889e134d)
