### ISSUE TITLE
[ja]debug.unverifiedBreakpoints

### ISSUE THREAD

**Issue by tHyt-lab** [microsoft/vscode-loc#1511]
### debug.unverifiedBreakpoints
https://github.com/microsoft/vscode-loc/blob/523687b9e38410d67e88dab088aa7bd1f10fe2c4/i18n/vscode-language-pack-ja/translations/extensions/ms-vscode.js-debug.i18n.json#L94
[起動構成のトラブルシューング] できます。
 ↓ 
[起動構成のトラブルシュー**ティ**ング] できます。

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 933429).

**Comment by TylerLeonhardt** [comment]
@Phroneris you're right!
