### ISSUE TITLE
No Khmer Language

### ISSUE THREAD

**Issue by raibann** [microsoft/vscode-loc#1512]
Can you add more about khmer language?

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 933430).

**Comment by crsuzukimsft** [comment]
Thank you. Will consider it when planning language extension.

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 933430)
