### ISSUE TITLE
the "question" column will be displayed as english not chinese when in wsl 

### ISSUE THREAD

**Issue by LDYang694** [microsoft/vscode-loc#152]
![捕获1](https://user-images.githubusercontent.com/62846124/77853916-88050280-7219-11ea-9cc8-44e6c41b9589.PNG)
Issue Type: <b>Bug</b>

the "question" column will be displayed as english not chinese when in wsl 

Extension version: 1.44.0
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.79GB (3.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|7.79GB (3.11GB free)|
|VM|0%|
</details>

**Comment by lukaschal** [comment]
@LDYang694 Could you please provide more detailed repro steps, and confirm if any additional component/extension is used to view this screen ?
