### ISSUE TITLE
Change MDN references to spanish

### ISSUE THREAD

**Issue by raggiodev** [microsoft/vscode-loc#1522]
Hi! I have a question. Is there any way to change the language of "MDN reference" (when we point a code and it explains what it is), to Spanish language? Thanks.

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 933431).

**Comment by v-mholloway** [comment]
@JoeTheorium could you please add a screen shot to illustrate the issue?

**Comment by JoeTheorium** [comment]
Of course. Here's what I'm saying. My VSC is in Spanish (my native language), however, when, as shown in the image, I see the reference of the "addEventListener()" method, it is in English (VSC official language).
So, my question is: Does this happen with all languages or this simply cannot be translated?
Thanks for your answer, best regards.

![Screenshot 2023-12-19 201008](https://github.com/microsoft/vscode-loc/assets/25178784/e125233c-be66-4ca9-8fd9-93315ed1398a)

**Comment by v-mholloway** [comment]
@JoeTheorium thank you. I have forwarded this query to the product team.

**Comment by csigs** [comment]
Investigated by Loc Team: It's not a translation issue. (Reference id: 933431)

**Comment by JoeTheorium** [comment]
Ok, thanks a lot.

**Comment by gentrhon666** [comment]
then cannot traslate mdn?

**Comment by JoeTheorium** [comment]
Hi! Correct, the entire VSC interface is translated, however, the references when I hover on an attribute/property/etc are not translated. I think it is because it comes directly from the MDN website those references.

**Comment by salkalero** [comment]
I also think it points to the MDN website. I have searched in the VSC configuration to see if it is possible to change the website where to point to, to indicate that it takes the MDN information in Spanish, since MDN is almost completely available in Spanish, but I have not found anything.
It's been a while since this, is there any news about it? Thank you

**Comment by Ez011-bit** [comment]
then there is no way to change the language of the "MDN references"?

**Comment by raggiodev** [comment]
Hi. Apparently, not at the moment.
