### ISSUE TITLE
[zh-cn] “克隆仓库”按钮在简体中文下无法正确显示。

### ISSUE THREAD

**Issue by Elkeid-me** [microsoft/vscode-loc#1526]
如图：
![image](https://github.com/microsoft/vscode-loc/assets/100071157/748a9630-fead-4f76-9ba5-7c076a6135b6)
在英文版本中，是正常的：
![image](https://github.com/microsoft/vscode-loc/assets/100071157/e696230b-8fce-4345-b468-deb3d8043888)

这一问题似乎在以前出现过，但被标记为关闭 #217

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 933432).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 933432)
