### ISSUE TITLE
Extra `%` in fr locale of `removeLogPoint`

### ISSUE THREAD

**Issue by alex-kinokon** [microsoft/vscode-loc#1527]
Bug:
<img width="297" alt="Capture d’écran, le 2023-11-30 à 23 51 16" src="https://github.com/microsoft/vscode-loc/assets/8125011/b31f48c2-a810-431d-aaa1-2d87f4ff8d8c">

This should also be “Supprimer _le_ point d’arrêt” to be grammatically correct. Since `removeLogPoint` doesn’t know whether the object of the expression is a masculine or feminine noun, I’m not proposing a fix here.

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 933433).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 933433)
