### ISSUE TITLE
"Open Folder" and "Clone Repository" buttons do not appear in home page using Spanish language

### ISSUE THREAD

**Issue by taksumaki** [microsoft/vscode-loc#153]
When installing the **Spanish** language from the ### official Vs Code repository, the **Open Folder and Clone repository buttons disappear** and _only one code text appears_. I am using the **latest available version of Vs Code and the plugin**.

> **Without the Spanish language plugin installed**

![1](https://user-images.githubusercontent.com/56084970/77864892-9850b980-71e8-11ea-8423-c8c1498c2437.JPG)

> **With the Spanish language plugin installed**

![2](https://user-images.githubusercontent.com/56084970/77864894-98e95000-71e8-11ea-85b8-d2f05685ca30.JPG)

**Comment by lukaschal** [comment]
Fixed.

**Comment by janbaltus** [comment]
fixed in 1.44.1 LP for insider version of VScode
