### ISSUE TITLE
vscode 1.85.0在发行文件中大部分ui和功能均没有汉化

### ISSUE THREAD

**Issue by CarftStars** [microsoft/vscode-loc#1530]
比如说
![Code_mgw7mmQJam](https://github.com/microsoft/vscode-loc/assets/148753926/5b0c003b-70c4-4040-84ee-b7059e8444e6)
![image](https://github.com/microsoft/vscode-loc/assets/148753926/f36c5206-db70-4872-8379-04a5fedf347e)
![image](https://github.com/microsoft/vscode-loc/assets/148753926/6e98aa5b-994b-4165-8527-9078acef2c29)
![image](https://github.com/microsoft/vscode-loc/assets/148753926/2483849d-6cbe-46b5-a65a-8b920baab55e)
没有列举全，这只是部分我找到的
谢谢

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 933435).

**Comment by crsuzukimsft** [comment]
@TylerLeonhardt Could you assist in here? It seems this text is translated in extensions repo.

**Comment by sam951013** [comment]
@crsuzukimsft Some places have not been translated into simplified Chinese.
