### ISSUE TITLE
The latest 1.85.1 sinicization seems to have failed

### ISSUE THREAD

**Issue by cMing1997** [microsoft/vscode-loc#1532]
Environment：
```
Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
```
Phenomenon：
![image](https://github.com/microsoft/vscode-loc/assets/40878104/6653f22c-5b01-449d-b370-87434a84cdcf)

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 933437).

**Comment by v-mholloway** [comment]
@cMing1997 can you describe in english, what the issue is here?

**Comment by sam951013** [comment]
是這個language pack有問題嗎？

**Comment by cMing1997** [comment]
> 是這個language pack有問題嗎？ 是这个language pack有问题吗？

I'm not sure it's the language pack

**Comment by sam951013** [comment]
If you think the translation is not good, you can directly open the issue or pull request.

**Comment by sam951013** [comment]
I believe that these two methods can solve your problems, and you can also (if you know) find the contributors listed below.
