### ISSUE TITLE
[ja] `Files: Auto Save` setting description is broken

### ISSUE THREAD

**Issue by lusingander** [microsoft/vscode-loc#1533]
The link in the explanation (`vs/workbench/contrib/files/browser/files.contribution.autoSave`) for the `Files: Auto Save` setting is broken.

https://github.com/microsoft/vscode-loc/blob/ddd7174069c9d981d0bacbc23fe74de3112ec706/i18n/vscode-language-pack-ja/translations/main.i18n.json#L7196

`[自動保存](https://code.visualstudio.com/docs/editor/codebasics#_save 自動保存)`

should be

`[自動保存](https://code.visualstudio.com/docs/editor/codebasics#_save-auto-save)`

<img width="832" alt="image" src="https://github.com/microsoft/vscode-loc/assets/31386431/135ba408-264c-48d0-9c03-2e544e27dac2">

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 934191).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 934191)
