### ISSUE TITLE
Clavo_RD

### ISSUE THREAD

**Issue by ClavoRD** [microsoft/vscode-loc#1534]
Type: <b>Feature Request</b>

Programador

Extension version: 1.85.2023121309
VS Code version: Code - Insiders 1.86.0-insider (9621add46007f7a1ab37d1fce9bcdcecca62aeb0, 2023-12-20T05:36:57.756Z)
OS version: Windows_NT x64 10.0.22621
Modes:
****

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 934235).

**Comment by v-mholloway** [comment]
@ClavoRD can you give more information as to your request here?

**Comment by csigs** [comment]
Resolved as Cant Reproduce.
