### ISSUE TITLE
[fr] Bad translation for Upload and Download

### ISSUE THREAD

**Issue by EnzoDeg40** [microsoft/vscode-loc#1539]
The translation of `upload` and `download` is `télécharger`. But to differentiate between the two, we use `télécharger` for `download` and we use `téléverser` for `upload`.

![image](https://github.com/microsoft/vscode-loc/assets/35306710/a5367d5a-7fe8-41fc-9f04-1e655476be35)

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 938249).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 938249)
