### ISSUE TITLE
Extension Causes A Display Disorder in the Explorer Window of VSCode

### ISSUE THREAD

**Issue by FremdSprach** [microsoft/vscode-loc#154]
Issue Type: <b>Bug</b>

After Installing the Chinese (Simplified) Language Pack Extension, the VSCode Explorer Window comes into a Display Disorder, the latter two items overlap with each other.

Extension version: 1.44.0
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (9.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by janbaltus** [comment]
Please provide screenshot for this issue both on English and CHS

**Comment by FremdSprach** [comment]
@janbaltus 

Please see below, there is an obvious overlapping:

![image](https://user-images.githubusercontent.com/30553808/78012789-1b544a00-7378-11ea-8027-543ac46277ca.png)

**Comment by janbaltus** [comment]
@dbaeumer is this know issue?

**Comment by dbaeumer** [comment]
@janbaltus actually I don't know.

@isidorn have you seen this?

**Comment by isidorn** [comment]
This is a vscode issue which we will fix today https://github.com/microsoft/vscode/issues/93774
