### ISSUE TITLE
New language

### ISSUE THREAD

**Issue by Veydzher** [microsoft/vscode-loc#1541]
Any chance to add Ukrainian to the repository? I'd like to contribute in translating VSCode into Ukrainian.

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 939076).

**Comment by crsuzukimsft** [comment]
Thank you for the suggestion.
This input will be brought up for future planning of new language scope.

**Comment by csigs** [comment]
Resolved as As Designed.
