### ISSUE TITLE
[ja] Incorrect Markdown in "Run & Debug"

### ISSUE THREAD

**Issue by GalvinGao** [microsoft/vscode-loc#1543]
<img width="607" alt="image" src="https://github.com/microsoft/vscode-loc/assets/12567059/602ff50a-f856-4d29-adc6-6816f2d0f615">

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 940129).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 940129)
