### ISSUE TITLE
[zh-cn] Suggest that "Copy id" be translated into "复制 id".

### ISSUE THREAD

**Issue by Elkeid-me** [microsoft/vscode-loc#1551]
![image](https://github.com/microsoft/vscode-loc/assets/100071157/36ab45d8-7005-458c-a3fa-5911a98e4d52)

![image](https://github.com/microsoft/vscode-loc/assets/100071157/e4d701e6-5c21-4d85-b8c2-724ef70faf66)

The current translation of "Copy id" in the "Running Extensions" view is "副本 id". However, in Chinese, "副本" is a noun meaning "copy" or "duplicate", while "复制" is the verb meaning "to copy". Therefore, the correct translation should be "复制 id".

By the way, in zh-tw, the current translation is correct ("複製識別碼").

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 942991).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 942991)
