### ISSUE TITLE
[ja] `insertFinalNewline` - "newline" should be "改行" instead of "最新の行"

### ISSUE THREAD

**Issue by Phroneris** [microsoft/vscode-loc#1553]
https://github.com/microsoft/vscode-loc/blob/a56bbe30c6ad54846107425a908aae5af3c5fd96/i18n/vscode-language-pack-ja/translations/main.i18n.json#L7358

`"insertFinalNewline": "有効にすると、ファイルの保存時に最新の行を末尾に挿入します。"`

"最新の行" means "the latest line" but it makes no sense.
It should be "改行" to mean "character(s) such as CR or LF".

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 943296).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 943296)
