### ISSUE TITLE
[ja] `largeFile` - Translate "folding" as "折りたたみ" instead of "折り返し"

### ISSUE THREAD

**Issue by neokidev** [microsoft/vscode-loc#1556]
https://github.com/microsoft/vscode-loc/blob/f71bddebe23b0cb76901da240f768b36570b5e12/i18n/vscode-language-pack-ja/translations/main.i18n.json#L5280

**Current Translation**
- ...トークン化、折り返し、**折り返し**、コードレンズ、単語の強調表示、固定スクロールが無効になっています。

**Suggested Translation**
- ...トークン化、折り返し、**折りたたみ**、コードレンズ、単語の強調表示、固定スクロールが無効になっています。

In the original text, the word was "folding" ([source code link](https://github.com/microsoft/vscode/blob/1df67c370cc127ec4b4a901c5a17e62147e70ba2/src/vs/workbench/contrib/codeEditor/browser/largeFileOptimizations.ts#L47)). Looking at other Japanese translations, "folding" seems to be translated as "折りたたみ".

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 944119)
