### ISSUE TITLE
[ja] `autoClosingComments` "comments" should be "コメント" instead of "左角かっこ"&"右角かっこ"

### ISSUE THREAD

**Issue by akidon0000** [microsoft/vscode-loc#1561]
https://github.com/microsoft/vscode-loc/blob/f71bddebe23b0cb76901da240f768b36570b5e12/i18n/vscode-language-pack-ja/translations/main.i18n.json#L346

**Original Text**

- Controls whether the editor should automatically close comments after the user adds an opening comment.

**Current Translation**

- エディターで左角かっこを追加した後に自動的に右角かっこを挿入するかどうかを制御します。

**Suggested Translation**

- エディターでコメントを開始した後に自動的にコメントを閉じるかどうかを制御します。

## Description

'左角かっこ' means opening brackets like '[' . 
'右角かっこ' means closing brackets like ']'.

This translation changes "opening comment" to "コメントを開始した" and "automatically close comments" to "自動的にコメントを閉じる"

Thanks.

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 945070).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 945070)
