### ISSUE TITLE
Error in call hierarchy display

### ISSUE THREAD

**Issue by Tamura-Tadashi** [microsoft/vscode-loc#1567]
Type: <b>Bug</b>

Showing call hierarchy display
Reference: Under Caller, select the function with the mouse and right-click to display it.
There is an error in the resource.　

　　着信通話の表示
　　発信通話の表示
　　戻る

　　呼び出し元を表示
　　呼び出し先を表示
　　もどる

I think so.
　　

Extension version: 1.85.2024020709
VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:20.941Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.10GB free)|
|Process Argv|--file-uri file:///c%3A/face/fam_sp/fam3v.DebugTest/fam3v.DebugTest.code-workspace --crash-reporter-id 9d4c727b-67c8-46f6-b34d-65803ad69d89|
|Screen Reader|no|
|VM|33%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
fegfb526:30961430
bg6jg535:30958357

```

</details>

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 946128).

**Comment by v-mholloway** [comment]
@Tamura-Tadashi what is the issue here... are you requesting different translations?

**Comment by v-mholloway** [comment]
could you supply a screen shot comparing the english with the translated version to illustrate the issue?

**Comment by csigs** [comment]
Resolved as Fixed & Verify.
