### ISSUE TITLE
[zh-hans] 文件名 `launch.json` 无需翻译

### ISSUE THREAD

**Issue by 188102836** [microsoft/vscode-loc#1570]
![image](https://github.com/microsoft/vscode-loc/assets/69347367/752d907d-80e9-4e9d-aac2-59c24220a98c)

扩展版本：v1.85.2024021409

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 946455)
