### ISSUE TITLE
[ja] Typo in `$(info) This repository has no stashes.`

### ISSUE THREAD

**Issue by secchanu** [microsoft/vscode-loc#1575]
The Japanese translation for `stashes` is `スタッシュ`, not `スラッシュ`.

https://github.com/microsoft/vscode-loc/blob/b0beccc0d53c8f2353ac6d469cd5f68d2e0806d3/i18n/vscode-language-pack-ja/translations/extensions/vscode.git.i18n.json#L14

```diff
- "$(info) This repository has no stashes.": "$(info) このリポジトリにはスラッシュがありません。",
+ "$(info) This repository has no stashes.": "$(info) このリポジトリにはスタッシュがありません。",
```

**Comment by csigs** [comment]
Resolved as Fixed & Verify.
