### ISSUE TITLE
[Question]Should I report any translation issues regarding the extension here?

### ISSUE THREAD

**Issue by solitary-sails** [microsoft/vscode-loc#1579]
I would like to report a translation feedback about Python extension, should I report it here?

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 949885).

**Comment by crsuzukimsft** [comment]
Hello @solitary-sails . Yes, please open an issue in this repo indicating the text with the existing translation which needs improvement and a text with what the new translation should be.

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 949885)
