### ISSUE TITLE
[ko] typo in the translation for 'remote branches'

### ISSUE THREAD

**Issue by seayurre** [microsoft/vscode-loc#1580]
When I click on the left corner of the window and try to change branches, the Korean translation for 'remote branches' is shown as '원경 분기'. It should be corrected to '원격 분기'. Thank you.

<img width="144" alt="image" src="https://github.com/microsoft/vscode-loc/assets/35357896/85b2b41c-266f-4a70-a452-7ee7082a6e73">

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 949886).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 949886)
