### ISSUE TITLE
[ja]typo makrdown

### ISSUE THREAD

**Issue by KouheiHara** [microsoft/vscode-loc#1588]
Translated content of `pathDeprecated` in `vs/workbench/contrib/welcomeGettingStarted/browser/gettingStartedExtensionPoint` is typo.

https://github.com/microsoft/vscode-loc/blob/2d4f5c7ff76ed9cebb84e0c013abb2106e10fd94/i18n/vscode-language-pack-ja/translations/main.i18n.json#L12259

"非推奨です。代わりに 'image' または 'makrdown' を使用してください",
↓
"非推奨です。代わりに 'image' または 'ma**rk**down' を使用してください",

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 952892).

**Comment by csigs** [comment]
Resolved as As Designed.
