### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by liuyj-vv** [microsoft/vscode-loc#159]
F:\VMware os\share>code -version
Warning: 'e' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'i' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'o' is not in the list of known options, but still passed to Electron/Chromium.
1.44.2
ff915844119ce9485abfe8aa9076ec76b5300ddd
x64

F:\VMware os\share>code --install-extension MS-CEINTL.vscode-language-pack-zh-hans-1.45.0.vsix
Installing extensions...
Unable to install extension 'ms-ceintl.vscode-language-pack-zh-hans' as it is not compatible with VS Code '1.44.2'.
Failed Installing Extensions: MS-CEINTL.vscode-language-pack-zh-hans-1.45.0.vsix

**Comment by janbaltus** [comment]
This is expected 1.45 version of LP can be used only for Insider version of Vs Code.
