### ISSUE TITLE
[de] Incorrect translations for camel case and kebab case

### ISSUE THREAD

**Issue by opplomachus** [microsoft/vscode-loc#1593]
The following two German translations don't make any sense and should be corrected as follows:
| camel case| |
|---------------|------------------------------|
| [en] current  | Transform to Camel Case       |
| [de] current  | In Camel-Fall transformieren |
| [de] proposed | In Camel-Case umwandeln      |

| kebab case| |
|---------------|------------------------------|
| [en] current  | Transform to Kebab Case       |
| [de] current  | Verwandle dich in eine Kebab-Hülle |
| [de] proposed | In Kebab-Case umwandeln      |

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 959778).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 959778)
