### ISSUE TITLE
[pt-BR] Wrong translation of peek

### ISSUE THREAD

**Issue by ArthurLobopro** [microsoft/vscode-loc#1602]
The word "peek" was translated to "Espiar", and, somehow, that translation is correct. But not for the Brazilian context

"Espiar" on Brazilian context means see something undetected, like a spy. In these cases, the work "peek" will be better translated like "see" ("ver") or "view" ("visualizar").

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 967043)
