### ISSUE TITLE
Ukrainian localization

### ISSUE THREAD

**Issue by okineadev** [microsoft/vscode-loc#1604]
I've been trying to make a Ukrainian language pack for vscode for a long time, but I still couldn't finish it, because of your crappy documentation - https://github.com/microsoft/vscode-loc/issues/1535

I don't even know if you will fix it, but I understand that you have some kind of translation platform where you translate lines into different languages.

And I would like you to add me there so that I can help make the Ukrainian localization

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 967341).

**Comment by okineadev** [comment]
I hope...

**Comment by okineadev** [comment]
I hope...

**Comment by v-mholloway** [comment]
There are currently 14 supported languages for Visual Studio Code. See Readme for more information

**Comment by csigs** [comment]
Resolved as As Designed.

**Comment by okineadev** [comment]
Shit, if you don't update the vscode-loc documentation, I'll kill you
