### ISSUE TITLE
和openvscode-server镜像不兼容

### ISSUE THREAD

**Issue by yang123456789** [microsoft/vscode-loc#1618]
镜像是gitpod/openvscode-server:latest，安装vscode-language-pack-zh-hans-1.89.2024050109.vsix插件时，不兼容

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 973751).

**Comment by cristianosuzuki77** [comment]
This is not related to localization.
@TylerLeonhardt could you check this please?

**Comment by TylerLeonhardt** [comment]
You'll have to open an issue on https://github.com/gitpod-io/openvscode-server , this project is not maintained by the VS Code team.
