### ISSUE TITLE
[fr] Fixing inconsistent translation (git tag)

### ISSUE THREAD

**Issue by olivier-maury** [microsoft/vscode-loc#1634]
Hi,

I'd like to submit a change to `i18n/vscode-language-pack-fr/translations/extensions/vscode.git.i18n.json` where *tag* is incorrectly and inconsistently translated to *balise* sometime instead of *étiquette*, 24 times.

The changes can be found at [olivier-maury:vscode-loc:patch-1](https://github.com/olivier-maury/vscode-loc/commit/5863c0c8e08eff284563029f9f090b297c2609db).

Best regards

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 976774).
