### ISSUE TITLE
Is there a way to update strings from te extension itself?

### ISSUE THREAD

**Issue by ArthurLobopro** [microsoft/vscode-loc#1641]
One month ago I suggested some changes on PT-BR translation that were applied, but until today there is no an extension update applying those changes. If there is a server with the updated translations, is there a way to create some API to update the current strings from the extension itself?

I am suggesting something like, the extension one time a day make a request to a server like: https://vscode-translations/PT-br/lastest and the server returns a full JSON with the translations. So the extension updates the local translations database and apply the new changes.

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 978059).

**Comment by crsuzukimsft** [comment]
@TylerLeonhardt would you be able to check on this?

**Comment by ArthurLobopro** [comment]
@TylerLeonhardt when I said I make some suggestions that were applied but there is no a new version with the changes I am referring to the PT BR translation. But with my question I am talking about any translation, if there is a way to the extension update itself using a server with translations, the users will not need to wait a new version of the translation extension with the applied changes.

**Comment by ArthurLobopro** [comment]
@TylerLeonhardt when I said I make some suggestions that were applied but there is no a new version with the changes I am referring to the PT BR translation. But with my question I am talking about any translation, if there is a way to the extension update itself using a server with translations, the users will not need to wait a new version of the translation extension with the apllied changes

**Comment by TylerLeonhardt** [comment]
Thanks for bringing this to my attention, @ArthurLobopro, it looks like we had something blocking the release of new versions of the language packs... that has now been unblocked so you should get a new version of a language pack soon (probably in the next 10min or so). Can you try out the language pack (make sure you grab the latest version) and let me know how it goes?

**Comment by ArthurLobopro** [comment]
@TylerLeonhardt now it's working. The new version implements the fixes correctly!

**Comment by TylerLeonhardt** [comment]
Thank you for helping make the language packs more accurate, @ArthurLobopro!
