### ISSUE TITLE
Wrong russian localization

### ISSUE THREAD

**Issue by SeveR31ru** [microsoft/vscode-loc#1660]
In "help" bar we have "search feature request" button, which lead us to vscode github in inssue pages,where we can check feature requests than already exists:

![изображение](https://github.com/microsoft/vscode-loc/assets/63467961/49815214-2f0b-4e6a-bd6c-70fc9fc87b50)

In rus localization,we have "поиск запросов функций" which doesnt make any sense. It looks like this phrase was run through a translator and inserted as is.

![изображение](https://github.com/microsoft/vscode-loc/assets/63467961/8dc08970-1a48-4673-b3a2-d7aa3a512125)

We are discussing the best translation option, I personally suggest "Посмотреть запросы на улучшение" or "Запрашиваемые пользователями улучшения" .

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 983127).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 983127)
