### ISSUE TITLE
[zh-cn] Chinese localization error: "打开进程资源管理器" instead of  "打开流程资源管理器"

### ISSUE THREAD

**Issue by izdbrave** [microsoft/vscode-loc#1662]
![image](https://github.com/microsoft/vscode-loc/assets/16437804/7c2a55f6-48b5-4220-8182-e58758a2c197)

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 983471).

**Comment by csigs** [comment]
Resolved as As Designed.
