### ISSUE TITLE
[es] Wrong translations in git commands.

### ISSUE THREAD

**Issue by kallookoo** [microsoft/vscode-loc#1664]
I have noticed that several commands have the same translation, generating confusion.

Original commands
```
...
"command.stash": "Stash",
...
"command.stashPopEditor": "Pop Stash",
...
"command.stashStaged": "Stash Staged",
...
```

Translated commands

```
...
"command.stash": "Guardar provisionalmente",
...
"command.stashPopEditor": "Guardar provisionalmente",
...
"command.stashStaged": "Guardar provisionalmente",
...
```

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 983640).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 983640)
