### ISSUE TITLE
[zh-cn] Inconsistent translation for `references-view`

### ISSUE THREAD

**Issue by Lambdaris** [microsoft/vscode-loc#1665]
![图片](https://github.com/microsoft/vscode-loc/assets/40635588/e5fd6c4e-1b0f-4a5e-b06e-fb68db0ee651)
Commands "references-view.prev" and "references-view.next" use different words, "引用" and "参考" for "reference". In this circumstance they would better be unified as "引用".

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 984224).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 984224)
