### ISSUE TITLE
[ru] Wrong Russian word when cloning a repo.

### ISSUE THREAD

**Issue by nico1008** [microsoft/vscode-loc#1666]
![image](https://github.com/user-attachments/assets/26425f82-eb77-42b1-8e58-40edf30aa3ac)
When cloning a repo using VS Code interface a window open asking weather you want to open the cloned repo, The word should be "Открыть" instead of "Открыто".

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 984755).
