### ISSUE TITLE
Translate the editor's interface into Arabic 

### ISSUE THREAD

**Issue by ahmed119amer** [microsoft/vscode-loc#1675]
Due to the popularity of the vscode and the increasing number of Arab programmers, it is important to start translating the interface into Arabic language in support of this language and the wide spectrum of programmers who master it.

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 985821).

**Comment by cristianosuzuki77** [comment]
Thank you, @ahmed119amer.
The product team will consider this request in future planning.
