### ISSUE TITLE
Chinese language pack translation error

### ISSUE THREAD

**Issue by iamliuzhiyu** [microsoft/vscode-loc#169]
Chinese：在设置——常用设置——Files:Autosave中，“脏编辑器”应为“未保存的编辑器”。

English：In Settings-Common Settings-Files: Autosave, "Dirty Editor" should be "Unsaved Editor".

**Comment by lukaschal** [comment]
On review.
[vscode-chs.xlsx](https://github.com/microsoft/vscode-loc/files/4712058/vscode-chs.xlsx)

**Comment by lukaschal** [comment]
![image](https://user-images.githubusercontent.com/18324331/83514416-e5e0ef80-a4d3-11ea-82ab-a9d76ba7e57e.png)

**Comment by LUMOGROUP** [comment]
Good job, just close this issue.
