### ISSUE TITLE
MISTRANSLATION.

### ISSUE THREAD

**Issue by sanx0153** [microsoft/vscode-loc#1690]
https://github.com/microsoft/vscode-loc/blob/7cd95f9067afa138880c026b1423bfac3d56116e/i18n/vscode-language-pack-pt-BR/translations/main.i18n.json#L9917

"Configurações de Pesquisa" should be "Pesquisar Configurações" or "Pesquisar em Configurações"

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 992609).

**Comment by cristianosuzuki77** [comment]
Obrigado pelo feedback.

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 992609)
