### ISSUE TITLE
help ->'open process explorer' translation issue for Chinese simple

### ISSUE THREAD

**Issue by UltraEDXGE** [microsoft/vscode-loc#1693]
Type: <b>Bug</b>

vscode version: 1.91.1

help ->Open Process Explorer -> Chinese simple display -> '流程资源管理器', it's should be '进程资源管理器'.

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.19045
Modes:
![1 91 1_Translation issue](https://github.com/user-attachments/assets/d32601dc-79c6-4c9b-a1e2-272e722e8149)

**Comment by TylerLeonhardt** [comment]
@cristianosuzuki77 looks like this one did not get picked up by the bot?

**Comment by xgdgsc** [comment]
This is already fixed in latest release.

**Comment by TylerLeonhardt** [comment]
Thanks! I'll close it then
