### ISSUE TITLE
"locale": "zh-hans"不工作

### ISSUE THREAD

**Issue by lihua06** [Microsoft/vscode-loc#17]
https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-zh-hans#overview
简体中文介绍页有错误；

locale": "zh-hans"并不被VSCODE所支持；
应修改为：locale": "zh-CN"；

![tim 20180504202409](https://user-images.githubusercontent.com/20437381/39627637-26f3290e-4fd9-11e8-96df-d9425d23ffb7.png)

**Comment by danyeh** [comment]
Thanks @MaleDong and @lihua06 . I just deployed new version 1.3.2. Corrected the readme. Both zh-cn and zh-CN should work. zh-hans support is in backlog.

**Comment by lihua06** [comment]
@danyeh There's no need to thank me. vscode earned my support!
