### ISSUE TITLE
Chinese Language Pack Translation Error: "值必须未数字"

### ISSUE THREAD

**Issue by RungeCC** [microsoft/vscode-loc#170]
Chinese (Simplified) Language Pack for Visual Studio Code version @1.46.0
发生在 Settings-ui 的 input box 早需要数字类型的项若为非数字，则显示“值必须未数字”；
应为“值必须为数字”
即标签:
```html
<div class="setting-item-validation-message">值必须未数字。</div>
```
有误。

**Comment by lukaschal** [comment]
On review.

File: vscode-workbench\vs_workbench_services_preferences.xlf
ID: 0; "src/vs/workbench/services/preferences/common/preferencesValidation.validations.expectedNumeric"
SRC: Value must be a number.
TGT: 值必须未数字。

**Comment by lukaschal** [comment]
Fixed.

new tgt: 值必须为数字。
