### ISSUE TITLE
[ja] terminalPromptCommand*.duration

### ISSUE THREAD

**Issue by ghaaj** [microsoft/vscode-loc#1720]
### terminalPromptCommand*.duration
In [vs/workbench/contrib/terminal/browser/xterm/decorationStyles](https://github.com/microsoft/vscode-loc/blob/c189f59263690bf383fe89bbfdf35ec4f860e7e1/i18n/vscode-language-pack-ja/translations/main.i18n.json#L11949), the translations "コマンドは {0} に実行され、" and "命令は {0} を実行し、" are both mixed up, but the former is more natural. Therefore, all translations should be unified to that one.

**Comment by csigs** [comment]
Thank you for your feedback. We will review the issue (ICX ADO Tracking Reference: 1001308).

**Comment by csigs** [comment]
Resolved as As Designed.
