### ISSUE TITLE
Chinese (Simplified) Translation Mistake for TypeScript.

### ISSUE THREAD

**Issue by fdh1994web** [microsoft/vscode-loc#1728]
VS Code version: 1.93.1
OS version: Windows11
![image](https://github.com/user-attachments/assets/71bb0042-4e0d-439b-bbd3-bbcd08a91b32)
![image](https://github.com/user-attachments/assets/5653531a-004a-40d4-bda2-3d3fa862f313)

It should be '初始化表达式'.

**Comment by csigs** [comment]
Thank you for your feedback. We will review the issue (ICX ADO Tracking Reference: 1002638).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 1002638)
