### ISSUE TITLE
[ja] "Duplicate..." should be translated as "複製..." instead of  "重複..."

### ISSUE THREAD

**Issue by wasavi2424** [microsoft/vscode-loc#1729]
https://github.com/microsoft/vscode-loc/blob/29f27aa4ec89b558897c4461f6106b30b644884b/i18n/vscode-language-pack-ja/translations/main.i18n.json#L13108

## Suggested Fix

Change the translation from:
``` json
  "copyFromProfile": "重複...",
```
to:
``` json
  "copyFromProfile": "複製...",
```

## Description

In the original text, the word was "Duplicate...". ( [source code link](https://github.com/microsoft/vscode/blob/4b7e7ce09884e9472bcfd36c00fd4add7a70a136/src/vs/workbench/contrib/userDataProfile/browser/userDataProfilesEditorModel.ts#L946) ) 

The term "重複" is generally used to refer to a state that something that is unintentionally or unnecessarily duplicated.
On the other hand, "複製" refers to the intentional act of creating a copy.
"Duplicate" in this context refers to the intentional act of copying, so the word "複製" would be a more accurate translation.

Additionally, in the `main.i18n.json`, the term "Duplicate" in sense of intentional act of copying has already been translated as "複製".

**Comment by csigs** [comment]
Thank you for your feedback. We will review the issue (ICX ADO Tracking Reference: 1002639).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 1002639)
