### ISSUE TITLE
Publish extensions to open-vsx

### ISSUE THREAD

**Issue by orblazer** [microsoft/vscode-loc#173]
I'm a [VS Codium](https://github.com/VSCodium/vscodium) user, a FLOSS version of VS Code, it's the same code but without the Microsoft's telemetry and branding.
I want to request if possible to add the _French Language Pack for Visual Studio Code_ extension on the [open-vsx.org](https://open-vsx.org/) market to us doesn't need to works with the Microsoft marketplace as is unclear if it's legal to use it on VS Code forks, see [here](https://github.com/microsoft/vscode/issues/31168).

Additional info:

- This is [how to](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) publish a new extension.

**Comment by weeteckt** [comment]
Thanks for the feedback. You could create a fork from https://github.com/microsoft/vscode-loc and generate language packs that you can then publish to the desired location.
