### ISSUE TITLE
Wrong Italian translation in Chat panel

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-loc#1733]
https://github.com/microsoft/vscode-copilot-release/issues/563#issuecomment-2413863124

_Used References_ is _Unused References_

**Comment by TylerLeonhardt** [comment]
![Image](https://github.com/user-attachments/assets/4dd26181-66f6-415e-9222-422d630fb6ef)

including the screenshot

**Comment by csigs** [comment]
Thank you for your feedback. We will review the issue (ICX ADO Tracking Reference: 1007594).

**Comment by cristianosuzuki77** [comment]
@TylerLeonhardt could you please share the resource id? can't locate with the string as-is.

**Comment by TylerLeonhardt** [comment]
@cristianosuzuki77 here you go!

```
      <trans-unit id="usedReferencesPlural">
        <source xml:lang="en">Used {0} references</source>
        <target state="translated">Riferimenti inutilizzati {0}</target>
      </trans-unit>
```

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 1007594)
