### ISSUE TITLE
[zh-cn] Incorrect Chinese (Simplified) Translation for "Pick a remote to pull the branch from"

### ISSUE THREAD

**Issue by Integral-Tech** [microsoft/vscode-loc#1738]
In [git extension](https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-zh-hans/translations/extensions/vscode.git.i18n.json#L175), "Pick a remote to pull the branch from" is incorrectly translated into "选择要从其拉取分支的远程位置". The correct translation should be "选择要拉取的源远程分支".

**Comment by csigs** [comment]
Thank you for your feedback. We will review the issue (ICX ADO Tracking Reference: 1014835).
