### ISSUE TITLE
Request to add Polish language

### ISSUE THREAD

**Issue by Kociak2115** [microsoft/vscode-loc#1741]
Although Visual Studio Code has been on the market for several years, it still does not have an official version in Polish. I would like to change that and try to add it.

**Comment by csigs** [comment]
Thank you for your feedback. We will review the issue (ICX ADO Tracking Reference: 1014834).

**Comment by TylerLeonhardt** [comment]
@Kociak2115 Hello! We do support Polish via the Polish Language Pack that you can get here:

https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-pl

Let us know if you have any issues with it!
