### ISSUE TITLE
[zh-cn]连接到wsl后部分中文变回英文

### ISSUE THREAD

**Issue by Mobius0526** [microsoft/vscode-loc#1744]
![Image](https://github.com/user-attachments/assets/c1360bc6-7d7d-42c9-bda6-3b5cf591d707)

**Comment by csigs** [comment]
Thank you for your feedback. We will review the issue (ICX ADO Tracking Reference: 1014836).

**Comment by cristianosuzuki77** [comment]
@TylerLeonhardt could I run this through you first? it says strings reverted to EN after connecting to wsl. Not sure if this is a runtime issue.

**Comment by TylerLeonhardt** [comment]
This is actually a duplicate of https://github.com/microsoft/vscode/issues/151000
