### ISSUE TITLE
统一“抓取”翻译

### ISSUE THREAD

**Issue by libukai** [microsoft/vscode-loc#1748]
![Image](https://github.com/user-attachments/assets/389f21bb-b511-4683-8d0c-88d2310f6518)

**拉取，推送**  菜单的最下方的分块中，fetch 同一个词出现了三种不同的翻译：抓取 获取 拉取 

参考其他位置的翻译，应该统一为：抓取

**Comment by csigs** [comment]
Thank you for your feedback. We will review the issue (ICX ADO Tracking Reference: 1015019).

**Comment by csigs** [comment]
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 1015019)
