### ISSUE TITLE
When will Dutch language pack release

### ISSUE THREAD

**Issue by ngohungphuc** [microsoft/vscode-loc#177]
I want to contribute to Dutch language pack but I'm already see it here https://github.com/microsoft/vscode-loc/tree/master/i18n/vscode-language-pack-nl
What will it need to release to market place or what I can help to release it ?
Thank you

**Comment by v-mholloway** [comment]
@danyeh can you provide more info for @ngohungphuc

**Comment by danyeh** [comment]
@ngohungphuc , Microsoft won't host localization project for languages not in scope outlined in the repo. If you are ok to manage the localization project yourself, the path is available to create your own language pack. See how to create language pack topic in the wiki of this repo. Thanks!
