### ISSUE TITLE
Issues with Version 1.23.1 of German language pack

### ISSUE THREAD

**Issue by levrik** [Microsoft/vscode-loc#18]
Version 1.23.1 has two issues in the German translations again that were fixed in 1.23.0
I just checked Transifex. The correct versions are still marked as correct there.

**Comment by levrik** [comment]
I just checked the history of the translations in this repo and couldn't find a commit where it was changed.
I think after installation of the German language pack still the included German translations were used and I just realized the issues after I updated to 1.23.1
Could it be that the German language pack here isn't up to date with the included one in VS Code 1.23.0?

**Comment by danyeh** [comment]
@levrik, thank you for reporting the issue. I re-pulled resources from Transifex and re-published as 1.23.2. Please confirm if this version solve the issue.

**Comment by levrik** [comment]
@danyeh Yes. Looks fine now. Thanks!
