### ISSUE TITLE
Difference between keys in structure of main.i18n.json

### ISSUE THREAD

**Issue by Vinn55** [microsoft/vscode-loc#187]
I check two locales and I found this ![image](https://user-images.githubusercontent.com/59340713/93927042-fe924100-fd20-11ea-9d55-81d8d3fbbe66.png).
Files were downloaded on 14 SEP ‎2020.
Can anyone provide relevant structures for the versions of VS Code?

**Comment by danyeh** [comment]
For languages supported in official release, files/keys will be in sync across languages with some lag of translation process (days).
Some languages were posted by community and could out of sync.
