### ISSUE TITLE
我不会算命

### ISSUE THREAD

**Issue by wobuhuisuanmin** [microsoft/vscode-loc#190]
Issue Type: <b>Bug</b>

我今天3岁，我很乖。

Extension version: 1.49.2
VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (8.50GB free)|
|Process Argv|--crash-reporter-id 1d77a378-7ca6-4646-a4f2-0b659e2ccde5|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by wobuhuisuanmin** [comment]
>iaoliao -11

**Comment by Vinn55** [comment]
不要在這裡沉迷

**Comment by wobuhuisuanmin** [comment]
> 不要在這裡沉迷
代码的世界，太让我上头了

**Comment by danyeh** [comment]
No actionable.
