### ISSUE TITLE
Uncommitted typo

### ISSUE THREAD

**Issue by rheh** [microsoft/vscode-loc#194]
Uncommitted is spelt incorrectly in the following files:

.//i18n/vscode-language-pack-zh-hans/translations/extensions/git.i18n.json:270:"git.timeline.uncommitedChanges": "未提交的更改",
.//i18n/vscode-language-pack-zh-hant/translations/extensions/git.i18n.json:270:"git.timeline.uncommitedChanges": "未認可的變更",
.//i18n/vscode-language-pack-tr/translations/extensions/git.i18n.json:270:	"git.timeline.uncommitedChanges": "Commit İşlemi Uygulanmamış Değişiklikler",
.//i18n/vscode-language-pack-id/translations/extensions/git.i18n.json:214:	"git.timeline.uncommitedChanges": "Uncommited Changes",
.//i18n/vscode-language-pack-fr/translations/extensions/git.i18n.json:270:	"git.timeline.uncommitedChanges": "Changements non validés",
.//i18n/vscode-language-pack-es/translations/extensions/git.i18n.json:270:	"git.timeline.uncommitedChanges": "Cambios no confirmados",
.//i18n/vscode-language-pack-hu/translations/extensions/git.i18n.json:214:	"git.timeline.uncommitedChanges": "Uncommited Changes",
.//i18n/vscode-language-pack-bg/translations/extensions/git.i18n.json:214:	"git.timeline.uncommitedChanges": "Uncommited Changes",
.//i18n/vscode-language-pack-de/translations/extensions/git.i18n.json:270:	"git.timeline.uncommitedChanges": "Nicht committete Änderungen",
.//i18n/vscode-language-pack-ko/translations/extensions/git.i18n.json:270:	"git.timeline.uncommitedChanges": "커밋되지 않은 변경 내용",
.//i18n/vscode-language-pack-en-GB/translations/extensions/git.i18n.json:214:	"git.timeline.uncommitedChanges": "Uncommited Changes",
.//i18n/vscode-language-pack-uk/translations/extensions/git.i18n.json:214:	"git.timeline.uncommitedChanges": "Uncommited Changes",
.//i18n/vscode-language-pack-ru/translations/extensions/git.i18n.json:270:	"git.timeline.uncommitedChanges": "Незафиксированные изменения",
.//i18n/vscode-language-pack-ja/translations/extensions/git.i18n.json:270:	"git.timeline.uncommitedChanges": "コミットされていない変更",
.//i18n/vscode-language-pack-it/translations/extensions/git.i18n.json:270:	"git.timeline.uncommitedChanges": "Modifiche non sottoposte a commit",
.//i18n/vscode-language-pack-cs/translations/extensions/git.i18n.json:270:	"git.timeline.uncommitedChanges": "Nepotvrzené změny",
.//i18n/vscode-language-pack-pt-BR/translations/extensions/git.i18n.json:270:	"git.timeline.uncommitedChanges": "Alterações Não Confirmadas",
.//i18n/vscode-language-pack-pl/translations/extensions/git.i18n.json:270:	"git.timeline.uncommitedChanges": "Niezatwierdzone zmiany"

This refers to the translation key and is potentially going to be corrected here https://github.com/microsoft/vscode/pull/109119/files.  If the proposed PR goes through on the vscode repo the above will need changing.

**Comment by danyeh** [comment]
Process will ensure translation align with source text eventually. Close this issue.
