### ISSUE TITLE
Some russian translate issues

### ISSUE THREAD

**Issue by stlr00** [microsoft/vscode-loc#197]
1) Please delete "&" here.

![image](https://user-images.githubusercontent.com/61075639/99856977-3e4b9c80-2b9b-11eb-8ffa-b6f471a0ef8d.png)

2) Braces = "Фигурные" Brackets = "Квадратные"
![image](https://user-images.githubusercontent.com/61075639/99857222-ce89e180-2b9b-11eb-99fb-325e60974cb8.png)

**Comment by v-mholloway** [comment]
these changes have also been implemented in Fabric - closing

**Comment by stlr00** [comment]
But it steel not fixed

**Comment by stlr00** [comment]
> these changes have also been implemented in Fabric - closing

This is not fixed yet, why closed?

**Comment by v-mholloway** [comment]
These changes were implemented in our localization systems on 8/25...
@danyeh it appears that these changes did not make it into the build... can you have a look...?
"format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces"
"miSplitEditorUp"
![image](https://user-images.githubusercontent.com/77055370/133991574-9d8958bf-a62d-44ec-b6ed-7bacced0f920.png)
![image](https://user-images.githubusercontent.com/77055370/133991842-882bdf99-4a95-4862-8afa-46d5be2814a4.png)

**Comment by stlr00** [comment]
Now fixed
