### ISSUE TITLE
Chinese Language Pack Translation Error

### ISSUE THREAD

**Issue by ha0y** [microsoft/vscode-loc#199]
In the former version of VSCode(e.g. 1.44.1), when a file with extensions available was opened, the message shows

商店中有可以对“xxxx”文件提供帮助的扩展。

![捕获](https://user-images.githubusercontent.com/30557072/102179113-8ed7c080-3ee1-11eb-9a65-fb0df4c70efc.PNG)

But in recent versions, the message was

市场具有可在“xxxx”文件方面提供帮助的扩展

![捕获](https://user-images.githubusercontent.com/30557072/102180162-618c1200-3ee3-11eb-9066-c991cab7e8ba.PNG)

This translation seems to be machine translated and is really awkward. And it mistranslated "Marketplace". The punctuation is also missing.

The original translation ``商店中有可以对“xxxx”文件提供帮助的扩展。``  is just OK.

And please also fix the button text, ``市场``->``商店``,  不再**为**“xxx”文件显示 -> 不再**对**“xxx”文件显示

**Comment by v-mholloway** [comment]
Bug opened [118651](https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/118651)

**Comment by ha0y** [comment]
@v-mholloway I really appreciate that you have resumed the l10n project after nearly one year. I'm suffering from those string translated by machine. Is it possible that we can contribute to translation instead of opening issues, just like the former MLCP? (I am a translator volunteer of [Home Assistant](https://github.com/home-assistant), having contributed 20000+ words.)

**Comment by v-mholloway** [comment]
closing as global bug now resolved
