### ISSUE TITLE
Include list of contributors in the readme of community contributed localizations

### ISSUE THREAD

**Issue by qcz** [Microsoft/vscode-loc#2]
Currently a generic Readme is present for every language. They should list the names of contributors like the VS Code monthly release notes does.

**Comment by danyeh** [comment]
Hi Dániel , thank you for your suggestion! I agree with you. Let's work this out.

**Comment by danyeh** [comment]
@qcz , I revised the readme to include contributors. Please take a look. https://github.com/Microsoft/vscode-loc/blob/release/1.21/i18n/vscode-language-pack-hu/README.md

I think we can author the readme as bi-lingual doc. Hungarian can come first while English in the bottom in same file. If you agree the idea, could you please help to translate it? Create a PR once you finish it. Thank you! 

We will need to do some test on if the localized readme can display well in all places (here, marketplace and in VS code.)

**Comment by qcz** [comment]
This is a very good idea.
The translation is available here: https://github.com/qcz/vscode-loc/tree/patch-1/i18n/vscode-language-pack-hu
Should I make the PR against the `relase/1.21` branch?

**Comment by danyeh** [comment]
Thank you Dániel very much! I picked up your translation and published language pack as v1.21.2. I tested in vscode-loc repo, in Marketplace and in VS Code. All look right. Please help to take a look as well.
Yes, if you want to make change. You can PR against the release/1.21 branch. We will follow branch strategy of vscode.
