### ISSUE TITLE
Request for adding a new locale: Cantonese. We can contribute and help.

### ISSUE THREAD

**Issue by laubonghaudoi** [microsoft/vscode-loc#204]
This issue was originally opened in https://github.com/microsoft/vscode/issues/112607

As @danyeh mentioned, we could make a community-maintained language pack. May we know how to proceed?

Language name in English: Cantonese
Language Name in its own script: 粵語
ISO 693-3 code of the language: yue

#### Reference

ISO 693 Identifier Documentation: https://iso639-3.sil.org/code/yue

**Comment by danyeh** [comment]
General steps could work. Assume you want to publish zh-HK language pack
1. Fork this repo.
2. dup i18n/vscode-language-pack-zh-hant to i18n/vscode-language-pack-zh-hk
3. Modify package.json, readme, changelog to reflect new language.
4. Contribute to translation in .json files
5. Follow https://github.com/Microsoft/vscode-loc/wiki/How-to-publish-to-Marketplace to publish to marketplace.
6. Create issue in vscode repo to add new language code for resource loading.

**Comment by laubonghaudoi** [comment]
@danyeh Thanks for the instructions! However, we would like to point out that this is not a `zh-hk` locale, but a `yue-hant` locale. The language name is Cantonese, without region specifications (Cantonese is used in mainland China, Hong Kong, Macau and overseas) Is this okay?

**Comment by danyeh** [comment]
Thank you for clarify! Then I would suggest i18n/vscode-language-pack-yue-hant in case other contributor would introduce hans in the future.

//    yue          Cantonese
//    yue-Hans     Cantonese
//    yue-Hant     Cantonese

**Comment by laubonghaudoi** [comment]
I see. So to confirm, the language id would be `yue`, and the folder would be named as `i18n/vscode-language-pack-yue-hant`, is this correct?

**Comment by danyeh** [comment]
Better to match:
Language ID: `yue-hant`
Folder: `i18n/vscode-language-pack-yue-hant`

**Comment by laubonghaudoi** [comment]
@danyeh Thanks for the clarifications and we are working on the translation now. But we have another question, where can we find the original `en` texts? They don't seem to be in this repo.

**Comment by danyeh** [comment]
We don't have corresponding en string json file because source strings are embedded in source code.
But I think can use en-GB as reference. @nexue2020 , can you refresh en-GB to latest? Thanks!
https://github.com/microsoft/vscode-loc/tree/master/i18n/vscode-language-pack-en-GB

**Comment by laubonghaudoi** [comment]
@danyeh @nexue2020 We are referring to the translations in `en-GB`, but it seems like it is missing a lot of entries. Many items in the traditional Chinese locale do not exist in `en-GB`, please see the screenshot below:
![2021-02-18 09 17 03](https://user-images.githubusercontent.com/11172180/108394916-1aafe680-71ca-11eb-96b3-3343f108d37e.jpg)

Is this normal? We are curious how the translators of `en-GB` looked up the original texts. Did they just read the source codes? Thanks!

**Comment by nexue2020** [comment]
en-GB is re-published last week. Closing the issue as resolved.
