### ISSUE TITLE
About Releases

### ISSUE THREAD

**Issue by GradyYang** [microsoft/vscode-loc#205]
I notice that the extension repository only has different branchs, Can you create a release (such as 1.45.1) so that I can use your extension as a opensource software to publish my product, you know the opensource software examination is very strict in my company, software without release cannot pass it. Thanks

**Comment by TylerLeonhardt** [comment]
This issue is pretty old but I think we're doing what you want now. We publish GitHub releases:
https://github.com/microsoft/vscode-loc/releases
