### ISSUE TITLE
Weird translation of git related terms in Brazilian Portuguese

### ISSUE THREAD

**Issue by Maxpxt** [microsoft/vscode-loc#209]
There are various weird translations of git-related terms in the source control view.

The guide for what I take to be the correct translation of the git-related terms which don't have and obvious translation is:
* "staged [thing]" should translate to "[thing] preparada". This is the translation currently used -- with some errors -- in the context menus.
* "commit" should, when acting a verb, translate to "confirmar" and, when acting as a noun, translate to "confirmação". This is the translation currently used -- with many errors confusing the verb and noun forms -- throughout the source control view.
* "tag" should be translated to "etiqueta". Currently, "tag" is being translated -- with a minor parallelism issue -- to "marca" and "marcação", which mean "mark" and "marking" (noun), respectively. "etiqueta" is a direct translation of "tag" to Portuguese and I believe it is more appropriate in this context. "marca"/"marcação" isn't too bad, though -- it's mostly as bad as "mark"/"marking" would be.

# List of errors

![image](https://user-images.githubusercontent.com/19475500/111892379-b86d2000-89d9-11eb-963d-cf7a82536e33.png)

1. "Staged Changes"  
  is incorrectly translated to "Alterações em Etapas" (this would translate to "Changes in Stages" in English).  
  The correct translation would be "Alterações Preparadas".

2. The grayed placeholder for the commit message, "Message (Ctrl+Enter to commit on 'master')",  
  is incorrectly translated to "Mensagem (Ctrl+Enter para **confirmação** em 'master')".  
  The correct translation would be "Mensagem (Ctrl+Enter para **confirmar** em 'master')", i.e., using the verb form of the translation of "commit".

![image](https://user-images.githubusercontent.com/19475500/111893747-8cef3300-89e3-11eb-99e1-e54e4903b12e.png)

3. All occurrences of "Commit Staged" ("Commit Staged", "Commit Staged (Amend)", "Commit Staged (Signed Off)")
  are incorrectly translated to "Confirmação Preparada".  
  The correct translation would be "Confirmar Preparadas".  
  There are two errors here. The first error is that the translation of "commit" should be in the verb form, but was in the noun form. The second error is that "staged" is plural in this context ("the staged changes"), but was translated into the singular form "Preparada" instead of the plural form "Preparadas".

4. "Abort Rebase"  
  is incorrectly translated to "Anular Troca de Base".  
  The correct translation would be "Abortar Troca de Base".
  "Anular" means "Nullify", which is somewhat different than "Abort".

5. "corrigir" has a lowercase starting "c" in the "Confirmação Preparada (corrigir)" entry. It should start with an uppercase letter like in all other entries. Note that "Confirmação" here should actually be "Confirmar" (see the error number 3 in the list).

6. Both occurrences of "Sign Off" ("Commit (Signed Off)" and "Commit Staged (Signed Off)")  
  are very incorrectly translated to "Aprovado".
  The correct translation would be "Assinar".
  The current translation, "Aprovado", means "Approved", which both isn't a verb as "Sign Off" is and doesn't indicate that the commit will be signed. The proposed correct translation, "Assinar", is in the verb form and means "to sign".

![image](https://user-images.githubusercontent.com/19475500/111893765-aa240180-89e3-11eb-95cf-affcace99030.png)

7. "Tag" is currently being translated to "Marca"/"Marcação". I believe "Etiqueta", which is a direct translation of "Tag" to Portuguese, would be more appropriate (see the guide in the beginning). In any case, should the current "Marca"/"Marcação" translation be kept, the entries "Marcas", "Criar Marcação" and "Excluir Marca" should, for parallelism, all use "Marca" (the plural is "Marcas") or all use "Marcação" (the plural is "Marcações").

![image](https://user-images.githubusercontent.com/19475500/111891876-f0259900-89d4-11eb-9c98-cb1433e11dbd.png)

8. Finally, "Initialize Repository" isn't translated at all. It should be "Inicializar repositório".

9. Also, was that "[leia nossa documentação] (https://aka.ms/vscode-scm)" supposed to be a link in markdown syntax?

**Comment by v-mholloway** [comment]
@Maxpxt 
where possible could you use this template for strings you want changed...?
could you use this template:
Culture: *****
String Identifier: ***** (e.g. notebookActions.executeAbove)
English String: *****
Current Translation: *****
Requested Translation: ****
Screen Shot: ***** (when applicable)

**Comment by v-mholloway** [comment]
bug opened [120100](https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/120100)

**Comment by v-mholloway** [comment]
closing as global bug now resolved
