### ISSUE TITLE
Weird translation in Chinese Traditional (zh-tw)

### ISSUE THREAD

**Issue by danielcheng80** [microsoft/vscode-loc#210]
Chinese (Traditional) Language Pack for Visual Studio Code @1.54.3
![image](https://user-images.githubusercontent.com/6923624/112088514-eebdc180-8bca-11eb-8ffe-c3cbdee50732.png)
I guess the "轉寄" should be "下一步".

Environment:
版本: 1.54.3 (user setup)
認可: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
日期: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by pan93412** [comment]
@nexue2020 @danyeh I'm curious that could these feedback got noticed by you without any mentions? [There has been a number of feedback now](https://github.com/microsoft/vscode-loc/issues) and most of them are neither replied nor improved. :(

**Comment by v-mholloway** [comment]
@danielcheng80 
Can you provide a string identifier so I can be sure of the correct resource to change?

This is the string I find in our Translation platform (identifier 'simpleBrowserView.control.forward.title')...
![image](https://user-images.githubusercontent.com/77055370/131337535-6655700e-e646-4984-b991-2cc70d4e7be0.png)

**Comment by pan93412** [comment]
Seems like it is. Thanks a lot! :)

**Comment by v-mholloway** [comment]
fix implemented. please allow a few days for the change to get into the build

**Comment by pan93412** [comment]
> fix implemented. please allow a few days for the change to get into the build

Thanks :)

**Comment by v-mholloway** [comment]
closing as changes should be in the build now
