### ISSUE TITLE
How do I contribute?

### ISSUE THREAD

**Issue by wojtekmaj** [microsoft/vscode-loc#211]
I can't seem to find a place where I could actually contribute to the language packs.

In readme, we read:

> Localized resource files are managed and edited in Microsoft Localization Community.

[A quick search](https://www.google.com/search?client=firefox-b-d&q=Microsoft+Localization+Community) returns nothing useful but a... discussion board?

and also:

> Since translation strings are managed and edited in Microsoft Localization Platform. Change can only be made there.

[This search](https://www.google.com/search?q="Microsoft+Localization+Platform") returns nothing useful but the very README I'm reading right now.

I also found something called [Microsoft Localization _Community_ Platform](https://www.google.com/search?q="Microsoft+Localization+Community+Platform") but I'm also unable to find it anywhere.

What's going on here?

**Comment by wojtekmaj** [comment]
Found this... https://envelope-community.azurewebsites.net/ but links to FAQ and so on are also dead here. Also "First week of April..." which year? If 2020, there's no info for almost a year now? If 2021, were changes done ahead of time?

**Comment by v-mholloway** [comment]
@danyeh can you provide more info for @wojtekmaj  ?

**Comment by csigs** [comment]
test...

**Comment by danyeh** [comment]
Hello all, remaining way to contribute is through github issue to give feedback of existing translation. We have made it clear in readme. 
For example, here. 
https://github.com/microsoft/vscode-loc/tree/main/i18n/vscode-language-pack-pt-BR#contributing
