### ISSUE TITLE
Atalhos de teclado da tecla Alt estão em conflito / Conflicting Alt keyboard shortcuts

### ISSUE THREAD

**Issue by leo-carmo** [microsoft/vscode-loc#212]
\
![Alt shortcuts](https://user-images.githubusercontent.com/51187764/112759248-8c98fe00-8fc8-11eb-88f2-efba8ed67517.jpg)
Issue Type: <b>Bug</b>

Não há procedimento sequencial. Basta notar que os menus Arquivo, Acessar e Ajuda estão todos compartilhando a tecla A para acesso via Alt+tecla de atalho, o que é uma inconveniência, especialmente para um aplicativo feito para se usar só com teclado. / There are no sequential steps to reproduce; it's only needed to mention that the translation made the menus Arquivo (File), Acessar (Acesso?) and Ajuda (Help) are sharing the same Alt keyboard shortcut (the "A" key), which is a major inconvenience especially for an application meant to be used via keyboard only.

Extension version: 1.54.2
VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (7.73GB free)|
|Process Argv|--crash-reporter-id 0aea3f91-954f-472c-83c8-831f5200c592 --crash-reporter-id 0aea3f91-954f-472c-83c8-831f5200c592|
|Screen Reader|no|
|VM|40%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
wslfolderdoccf:30280165
vsget980:30279783
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953

```

</details>

**Comment by v-mholloway** [comment]
change implemented - please allow a few days for the fix to get into the build

**Comment by v-mholloway** [comment]
closing as fix should be in the build by now
