### ISSUE TITLE
Issues with Polish translation

### ISSUE THREAD

**Issue by wojtekmaj** [microsoft/vscode-loc#214]
_Please note that this ticket is WIP as I'm currently testing Polish translation heavily in daily use._

## Incorrect translations

| Original phrase (may not be accurate) | Current translation | Suggested translation | Comment |
|--|--|--|--|
| Open editors | Otwórz edytory | Otwarte edytory | (1) |
| Replace preview | Zastąp podgląd | Podgląd zmian | (1) |
| Message (Enter to commit to "master") | Komunikat (Enter do zatwierdzenia na "master") | Opis (Enter by zatwierdzić na "master" | |
| Stage Changes | Zmiany przygotowania | Przygotuj zmiany | Makes no sense in [context](https://github.com/microsoft/vscode-loc/blob/9d550e33b1ddbf3a731eee2397093f116d4fd642/i18n/vscode-language-pack-pl/translations/extensions/git.i18n.json#L25-L28) |
| Stage Change | Zmiana przygotowania | Przygotuj zmianę | Makes no sense in [context](https://github.com/microsoft/vscode-loc/blob/9d550e33b1ddbf3a731eee2397093f116d4fd642/i18n/vscode-language-pack-pl/translations/extensions/git.i18n.json#L32-L33) |

(1) In English, the imperative and the adjective are sometimes identical, and in Polish they can be more easily distinguished. For example, "Open window" can mean "Otwórz okno" (as in: "Hey you, open this window") and "Otwarte okno" (as in: "This window is open").

## Missing translations

| Original phrase | Suggested translation |
|--|--|

**Comment by v-mholloway** [comment]
Bug Opened [120012](https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/120012)

**Comment by v-mholloway** [comment]
global bug resolved - closing
