### ISSUE TITLE
Typo report [fr]

### ISSUE THREAD

**Issue by jdbruxelles** [microsoft/vscode-loc#215]
```
"groupLabel": "Groupe {0}",
----------Remove "r" ^
```
instead of:
https://github.com/microsoft/vscode-loc/blob/9429f6ddf09aeb8fb42b2cc38f7069da14736b8b/i18n/vscode-language-pack-fr/translations/main.i18n.json#L1508

```
"addFolders": "&&Ajouter des dossiers à l'espace de travail",
----------Add "j" ^
```
instead of:
https://github.com/microsoft/vscode-loc/blob/9429f6ddf09aeb8fb42b2cc38f7069da14736b8b/i18n/vscode-language-pack-fr/translations/main.i18n.json#L3656

**Comment by v-mholloway** [comment]
fix implemented. please allow a few days for the change to make it into the build

**Comment by v-mholloway** [comment]
fix should now be in the build - closing
