### ISSUE TITLE
Start page error in zh-cn

### ISSUE THREAD

**Issue by kondongx** [microsoft/vscode-loc#217]
![image](https://user-images.githubusercontent.com/28899471/114711400-79748500-9d61-11eb-9334-0f3707120bde.png)

It should look like this in en

![image](https://user-images.githubusercontent.com/28899471/114711292-5cd84d00-9d61-11eb-966a-f7b4d81f012a.png)

**Comment by Guyutongxue** [comment]
Seems a space is missing from [here](https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-zh-hans/translations/extensions/git.i18n.json#L480).

By the way, "可控存储库" should be "克隆存储库".

**Comment by nexue2020** [comment]
Thank you for the feedback!

Close the ticket and filed internal work item: https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/96620
