### ISSUE TITLE
[German] Translation errors for remove conditional breakpoint dialog

### ISSUE THREAD

**Issue by LinqLover** [microsoft/vscode-loc#223]
> [Window Title]
> Visual Studio Code
> 
> [Content]
> Dieser haltepunkt hat eine Bedingung, die beim Entfernen verloren geht. Deaktivieren Sie stattdessen ggf. den haltepunkt.
> 
> ["Haltepunkt" entfernen] [Deaktivieren Haltepunkt] [Abbrechen]

The following strings are incorrect and need to be replaced:

- `haltepunkt` -> `Haltepunkt` (has to start with first letter everywhere)
- `Deaktivieren Haltepunkt` -> `Haltepunkt deaktivieren`

**Comment by v-mholloway** [comment]
@LinqLover can you provide more information as to the strings that require changing...?
if you could use this template where applicable please...
Culture: *****
String Identifier: ***** (e.g. notebookActions.executeAbove)
English String: *****
Current Translation: *****
Requested Translation: ****
Screen Shot: ***** (when applicable)

**Comment by LinqLover** [comment]
- Culture: de-de
Current translation: "Dieser haltepunkt hat eine Bedingung, die beim Entfernen verloren geht. Deaktivieren Sie stattdessen ggf. den haltepunkt."
Requested translation: "Dieser Haltepunkt hat eine Bedingung, die beim Entfernen verloren geht. Deaktivieren Sie stattdessen ggf. den Haltepunkt."
- Culture: de-de
Current translation: "Deaktivieren Haltepunkt"
Requested translation: "Haltepunkt deaktivieren"

String identifiers/English strings not known.
Screen Shot: See quote from my initial post (this it what Cmd + C on the dialog window produces)

**Comment by v-mholloway** [comment]
@LinqLover unfortunately I cannot find these strings in our localization platform. they may have been fixed since the initial post.
if you still see the issues, please send on some screen shots for us to work with.

**Comment by LinqLover** [comment]
Here it is:

![image](https://user-images.githubusercontent.com/38782922/132558689-8fe72d55-32e8-45e8-b01b-c1d24978a0f3.png)

Raised when clicking on a disabled breakpoint that has a condition.

**Comment by v-mholloway** [comment]
@LinqLover the strings in that dialog are not the same as in your earlier comment... in any case, I still cannot find that dialog string in our translation libraries...
@danyeh might you know?

**Comment by LinqLover** [comment]
Thank you, where else am I supposed to report this problem then?
