### ISSUE TITLE
It is not compatible with vs code '1.56.2'

### ISSUE THREAD

**Issue by SteveChung26** [microsoft/vscode-loc#225]
I downloaded ...zh-hans-1.57.0.vsix and installed it offline, but this line, It is not compatible with vs code '1.56.2', printed on cmd.

**Comment by hjysmi** [comment]
same issue when installed it offline

**Comment by illbebach** [comment]
Same here.  Offline install on Ubuntu fails.


> Installing extensions...
> Unable to install extension 'ms-ceintl.vscode-language-pack-ko' as it is not compatible with VS Code '1.56.2'.
> Failed Installing Extensions: file:///home/user/Downloads/MS-CEINTL.vscode-language-pack-ko-1.57.0.vsix


> Version: 1.56.2
> Commit: 054a9295330880ed74ceaedda236253b4f39a335
> Date: 2021-05-12T16:45:26.313Z
> Electron: 12.0.4
> Chrome: 89.0.4389.114
> Node.js: 14.16.0
> V8: 8.9.255.24-electron.0
> OS: Linux x64 5.8.0-55-generic

**Comment by TylerLeonhardt** [comment]
This is expected. The latest version of the language pack supports VS Code 1.57+. You should get an older version of the language pack if you want to use it with 1.56.

Thankfully the _minor_ versions of the language pack align with the _minor_ versions of VS Code:

1.55 is for 1.55
1.56 is for 1.56
1.57 is for 1.57
etc.

So you can rely on that.
