### ISSUE TITLE
[Korean] Translation error.

### ISSUE THREAD

**Issue by wdrk** [microsoft/vscode-loc#226]
<img width="631" alt="vscode_en" src="https://user-images.githubusercontent.com/81424145/119506493-ec353f00-bda8-11eb-8610-7bfa6f56f854.PNG">
<img width="483" alt="vscode_ko" src="https://user-images.githubusercontent.com/81424145/119506505-ef302f80-bda8-11eb-8525-70f8f1ed47b2.PNG">

Hello.
It's a strange Korean translation.
"이 파일에서 사용할 [프로그래밍 언어를 선택](https://#)하세요. 타이핑을 시작하면 이 메시지는 없어지며, [다시 표시하지 않게끔 설정](https://#)할 수도 있습니다."
I suggest translating like this.
Thanks.

**Comment by TylerLeonhardt** [comment]
This is a duplicate of #241. Thanks!
