### ISSUE TITLE
German: Untitled hint erroneous

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode-loc#241]
The German translation for the hint message of untitled files apparently doesn't replace a provided placeholder:

![German untitled hint](https://user-images.githubusercontent.com/9283914/120938004-fd6b3d80-c710-11eb-889c-b637f08857ac.png)

Apparently, this error is similar to #226.

**Comment by TylerLeonhardt** [comment]
@isidorn to fix this you can "version" the localization id.

**Comment by isidorn** [comment]
Thanks for the ping, fixed via https://github.com/microsoft/vscode/commit/6bf4b4f6ddd5f54dbd1cade463559d1746e9ea0b
