### ISSUE TITLE
[Russian] Опечатка во всплывающем меню расширений

### ISSUE THREAD

**Issue by iSpid3r** [microsoft/vscode-loc#272]
В расширениях при нажатии на троеточие открывается меню, в котором есть пункт "Проверка обновлений расширения".

![11-06-2021 10-40-40](https://user-images.githubusercontent.com/20419104/121649902-ae6f3080-caa1-11eb-8706-40f5560b1b05.png)

Вот только проверяет эта кнопка ВСЕ расширения сразу. Соответственно, корректнее назвать ее "Проверка обновлений расширений" (или лучше даже проще — "Проверка обновлений").

**Comment by nexue2020** [comment]
Sorry we are not able to review ticket with description in non-English language.
