### ISSUE TITLE
[zh-hans] Markdown syntax error

### ISSUE THREAD

**Issue by liyuhang1997** [microsoft/vscode-loc#275]
https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L1502

`"telemetry.enableTelemetryMd": "实现将使用数据和错误发送到 Microsoft 联机服务。在 [此处] 阅读我们的隐私声明({0})。",`

Should be modified to

`"telemetry.enableTelemetryMd": "实现将使用数据和错误发送到 Microsoft 联机服务。在 [此处]({0}) 阅读我们的隐私声明。",`

![image](https://user-images.githubusercontent.com/16591303/121819169-477a9300-ccbe-11eb-9508-be081be4303e.png)

**Comment by nexue2020** [comment]
Close ticket and Filed internal feedback ticket: https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/96618

**Comment by nexue2020** [comment]
Thank you for the feedback.
