### ISSUE TITLE
[Loc] " "" " Double quotes are not localized(zh-cn)

### ISSUE THREAD

**Issue by v-ericawu** [microsoft/vscode-loc#276]
VS Code Version: VS Code 1.56.2

Notes:
There is a certain distance between the Chinese double quotation mark and the content before and after the Chinese double quotation mark

Steps to Reproduce:
1. Open VS Code.
2. Install Simplified Chinese language package.
3. Observe the double quotes drawn in the picture.

Actual:
![01](https://user-images.githubusercontent.com/78774400/122187701-db687c80-cec1-11eb-9111-43082d8716f2.jpg)

Expected:
![02](https://user-images.githubusercontent.com/78774400/122187755-ecb18900-cec1-11eb-962f-56c26f99dccc.png)

**Comment by nexue2020** [comment]
Please provide the source file of the affected strings. Thank you.

**Comment by v-mholloway** [comment]
@danyeh as this is the ReadMe, could you approve this PR?
[https://github.com/microsoft/vscode-loc/pull/441/files](https://github.com/microsoft/vscode-loc/pull/441/files)

**Comment by v-mholloway** [comment]
PR Approved - closing

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 692780)
