### ISSUE TITLE
[LOC] Double quotation marks (" ") become square brackets ([ ]) (zh-tw)

### ISSUE THREAD

**Issue by v-ericawu** [microsoft/vscode-loc#277]
VS Code Version: VS Code 1.56.2

Steps to Reproduce:
1. Open VS Code.
2. Install Chinese(Traditional) Language package.
3. Observe the symbols in the picture.

Actual:
The symbols shown in the figure are square brackets ("")
![01](https://user-images.githubusercontent.com/78774400/122189337-701faa00-cec3-11eb-988a-06bb021adf06.png)

Expected:
The symbol shown in the figure is double quotation marks ("")
![02](https://user-images.githubusercontent.com/78774400/122189417-7ca40280-cec3-11eb-9ce4-2ba72b868bbe.png)

**Comment by nexue2020** [comment]
Please provide the source file of the affected strings. Thank you.

**Comment by v-mholloway** [comment]
@v-ericawu can you confirm that these issues are in the ReadMe...?
[https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-zh-hant/README.md](https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-zh-hant/README.md)

**Comment by ted1030** [comment]
@v-ericawu
The symbols in the first figure are "「" and "」", not square brackets "[" and "]".

**Comment by v-ericawu** [comment]
@v-mholloway Sorry for the late reply, the question is here in the ReadMe:
![image](https://user-images.githubusercontent.com/78774400/132149111-21abeb59-793d-4ed4-819f-f0912def43c7.png)

**Comment by v-ericawu** [comment]
@ted1030 I think we should replace "**「」**" with " **" "** "
as the picture shows:
![image](https://user-images.githubusercontent.com/78774400/132149517-08172d66-5a09-4557-9417-6a9dada37429.png)

**Comment by v-mholloway** [comment]
@v-ericawu can you make the necessary changes to the ReadMe and send on the link to the Pull request so I can get it approved...?

**Comment by v-ericawu** [comment]
@v-mholloway I don't know how to send a pull request, could you help to send a pull request?
The revised part is as follows:
![image](https://user-images.githubusercontent.com/78774400/132272617-2bac7d93-6d17-4aca-aaf4-ed913cb6af20.png)

**Comment by v-mholloway** [comment]
Pull request created with changes...
https://github.com/microsoft/vscode-loc/pull/453

@danyeh @crsuzuki@microsoft.com could you folks approve this PR...?

**Comment by v-mholloway** [comment]
change approved now... closing
