### ISSUE TITLE
[LOC] There should be spaces on both sides of "vscode-loc"(zh-cn)

### ISSUE THREAD

**Issue by v-ericawu** [microsoft/vscode-loc#278]
VS Code Version: VS Code 1.56.2

Steps to Reproduce:
1. Open VS Code.
2. Install Chinese(Simplified) Language package.
3. Observe the "vscode-loc".

Actual:
There are no spaces on both sides of "vscode-loc"
![01](https://user-images.githubusercontent.com/78774400/122190876-cfca8500-cec4-11eb-953b-fbe720e16552.jpg)

Expected:
There are spaces on both sides of "vscode-loc"
![02](https://user-images.githubusercontent.com/78774400/122190907-d6f19300-cec4-11eb-823b-86654b3d771f.png)

**Comment by nexue2020** [comment]
Please provide the source file of the affected strings. Thank you.

**Comment by Colengms** [comment]
@nexue2020 Is it https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-zh-hans/README.md ?

**Comment by v-mholloway** [comment]
@danyeh as this is in the ReadMe, would you be able to approve this PR...?
[https://github.com/microsoft/vscode-loc/pull/441/files](https://github.com/microsoft/vscode-loc/pull/441/files)

**Comment by v-mholloway** [comment]
PR Approved - closing
