### ISSUE TITLE
[LOC] ":" is not localized(zh-cn)

### ISSUE THREAD

**Issue by v-ericawu** [microsoft/vscode-loc#279]
VS Code Version: VS Code 1.56.2

Steps to Reproduce:
1. Install Simplified Chinese language package.
2. Open a .ts file with VS Code.
3. Navigate to "Outline" and click "More Actions...".
4. Observe the ": ".

Actual:
![01](https://user-images.githubusercontent.com/78774400/122194048-a7905580-cec7-11eb-8310-7e46fa05da1f.PNG)

Expected:
": " is localized(There is a certain distance between the Chinese colon and the preceding text)

**Comment by nexue2020** [comment]
Please provide the source file of the affected string to help narrow down the backend queiries.

**Comment by v-mholloway** [comment]
@v-ericawu can you fill out this template so we can target the correct strings...
Culture: *****
String Identifier: ***** (e.g. notebookActions.executeAbove)
English String: *****
Current Translation: *****
Requested Translation: ****
Screen Shot: ***** (when applicable)

**Comment by v-mholloway** [comment]
@v-ericawu looking at the english version of the same text, shouldn't the ': ' be present in Chinese?
![image](https://user-images.githubusercontent.com/77055370/135105197-7f8748d0-5f98-40d2-a3b1-9440b29c4980.png)

**Comment by v-ericawu** [comment]
@v-mholloway I think the ":" sign here is a symbol in the English format, while the Chinese ":" is a certain distance from the text in front of the symbol
![image](https://user-images.githubusercontent.com/78774400/135188871-fd185a7f-0a4d-43a1-b51c-6e8915c028d1.png)

**Comment by v-mholloway** [comment]
@v-ericawu changes implemented and should be in the build in a few days.

**Comment by v-mholloway** [comment]
closing as the change should be in the build now

**Comment by flamott** [comment]
Simplified Chinese [style guide](https://www.microsoft.com/en-us/language/StyleGuides?rtc=1) suggests using English colon mark instead of Chinese full-width colon mark in software, and most importantly this is followed by previous vscode localization effort. So changing this creates an inconsistency issue.
