### ISSUE TITLE
[LOC] "Reveal in Explorer" is not localized

### ISSUE THREAD

**Issue by v-ericawu** [microsoft/vscode-loc#280]
VS Code Version: VS Code 1.56.2
OS Version: WSL on windows

Steps to Reproduce:
1. Install Simplified Chinese language package.
2. Open a .ts file with VS Code.
3. Right-Click the file and observe the "Reveal in Explorer".

Actual:
![01](https://user-images.githubusercontent.com/78774400/122199927-21770d80-cecd-11eb-8d3c-a1cb949dfce4.PNG)

Expected:
"Reveal in Explorer" is localized
![image](https://user-images.githubusercontent.com/78774400/122200370-8f233980-cecd-11eb-8b1e-c3a303eaabb3.png)

**Comment by nexue2020** [comment]
Didn't find a hit in our backend queiries: 
![image](https://user-images.githubusercontent.com/73669577/123312575-65759e00-d4dd-11eb-8374-ee2a1c86db27.png)

Close as not reproducible.
