### ISSUE TITLE
[LOC] Shortcut prompt(R) disappears

### ISSUE THREAD

**Issue by v-ericawu** [microsoft/vscode-loc#281]
VS Code Version: VS Code 1.56.2
OS Version: Win10 and Linux VM

Notes: 
1. Have (R): ja\ko\zh-cn\zh-tw languages
   Not have (R): Remaining other languages 
2. There is no "R" for “Restart” button on the MAC version

Steps to Reproduce:
1. Install all language packages.
2. Open a .ts file with VS Code.
3. Press F1 to open command palette.
4. Choose the "Confugure Display Language" ->en.
5. Observe these "Restart(R)". 

Have (R) : 
![01](https://user-images.githubusercontent.com/78774400/122202858-0659cd00-ced0-11eb-8218-9d2bc4ea90e3.PNG)

Not have (R) :
![02](https://user-images.githubusercontent.com/78774400/122202873-0b1e8100-ced0-11eb-8e39-ae26b337c249.jpg)

**Comment by v-mholloway** [comment]
@v-ericawu we are not seeing this (R) in VSCode translations...
can you advise if you still experience this and where possible fill out this template so we can target the correct strings...
Culture: *****
String Identifier: ***** (e.g. notebookActions.executeAbove)
English String: *****
Current Translation: *****
Requested Translation: ****
Screen Shot: ***** (when applicable)

**Comment by v-mholloway** [comment]
Actually, this is by design for languages with CJK character sets to accommodate shortcut keys
