### ISSUE TITLE
[LOC] Some options are not localized

### ISSUE THREAD

**Issue by v-ericawu** [microsoft/vscode-loc#282]
VS Code Version: VS Code 1.56.2
OS Version: Linux ARM64

Steps to Reproduce:
1. Install Simplified Chinese language package.
2. Open a .ts file with VS Code.
3. Navigate to the top toolbar.
4. Click "运行" and "帮助".
5. Observe "Getting Started", "Open Configurations", "Toggle Breakpoint", "Enable/Disable/Remove All Breakpoints".

Actual:
![image](https://user-images.githubusercontent.com/78774400/122206539-1378bb00-ced4-11eb-896d-1423b593eed7.png)
![image](https://user-images.githubusercontent.com/78774400/122206568-1d9ab980-ced4-11eb-8e30-856a5d3cff82.png)

Expected:
![image](https://user-images.githubusercontent.com/78774400/122206767-29867b80-ced4-11eb-9e87-8b471f414e3d.png)
![image](https://user-images.githubusercontent.com/78774400/122206990-36a36a80-ced4-11eb-9a49-abf75a1e00f7.png)

**Comment by nexue2020** [comment]
We cannot find a hit in our backend queries. Is this still reproducible? If yes, please re-open the ticket and provide the Source File in question.
