### ISSUE TITLE
Inconsistent Korean translation for vs/workbench/contrib/codeEditor/browser/toggleWordWrap/miToggleWordWrap

### ISSUE THREAD

**Issue by saschanaz** [microsoft/vscode-loc#296]
The translation for "Word Wrap" has consistently been "자동 줄 바꿈" but the recent changes made it "자동 래핑". It should be reverted.

I strongly suspect this change was accidental, because it originally was "자동 줄 바꿈", was changed to English and then was translated again. (See how `miToggleWordWrap` has changed.)

https://github.com/microsoft/vscode-loc/blob/bfe580f94a58593aa23fe48ddaf7f87b5f6078d1/i18n/vscode-language-pack-ko/translations/main.i18n.json#L3808-L3814

https://github.com/microsoft/vscode-loc/blob/b29487f4b5ba76eae24b67920c14f8eafb78acc6/i18n/vscode-language-pack-ko/translations/main.i18n.json#L3970-L3976

https://github.com/microsoft/vscode-loc/blob/60047b649e2bd5763ed430cde3bb68eeef9a069b/i18n/vscode-language-pack-ko/translations/main.i18n.json#L3970-L3976

**Comment by saschanaz** [comment]
I'd like to contribute but the README does not provide any good link for me.

**Comment by nexue2020** [comment]
Thank you for the feedback. We submitted an internal feedback ticket to resolve this.

https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/96334
