### ISSUE TITLE
Turkish and Portuguese (Brazil) Language Packs do not work

### ISSUE THREAD

**Issue by ac5er** [Microsoft/vscode-loc#3]
I installed Turkish and Portuguese (Brazil) Language Packs. Enabled them by editing `locale.json` but UI language is still English. Bulgarian and Hungarian Language Packs work but these two does not.

I changed `"languageId": "tr"` to `"languageId": "trk"` in Turkish Language Pack's package.json file. Then activate it as `"locale": "trk"` in `locale.json` and it worked.

Also changed `"languageId": "pt-BR"` to `"languageId": "pt-br"` in  Portuguese (Brazil) Language Pack's package.json file. Then activate it as `"locale": "pt-br"` in `locale.json` and it worked too.

There might be a confusion about language ids.

**Comment by danyeh** [comment]
Hi Adem, thank you very much for reporting the issues and providing solution! I fixed the issues and republished language packs of Turkish and Portuguese (Brazil) as version 1.21.2. I added language id info in readme as well. We will investigate why original id didn't work. Thank you @ac5er !

**Comment by danyeh** [comment]
@ac5er ，code fixed. Now VS Code supports 'tr' as language ID. I have re-published tr language pack and updated readme. It will be great if you can help to translate the readme. You can PR to release/1.21 branch. See example of hu which has localized readme with English in the bottom. https://github.com/Microsoft/vscode-loc/blob/release/1.21/i18n/vscode-language-pack-hu/README.md

**Comment by ac5er** [comment]
Hi @danyeh ,
I made a pull request.
By the way, I don't know if it is right place to tell but [docs](https://code.visualstudio.com/docs/getstarted/locales) page has wrong language id(trk) for Turkish Language Pack.

**Comment by danyeh** [comment]
@ac5er , thank you very much for the translation! And thank you for reporting the docs issue. I created a PR to fix that. There is an edit button on the page. Everyone can contribute.
