### ISSUE TITLE
Run VS Code smoke tests as a part of CI

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-loc#304]
Requirements:
* [ ] Updated VS Code Smoke test to stop using the DOM (@dbaeumer is working on this now)
* [ ] Modify the vscode Localization smoke tests to take in a VSIX file instead of pulling from the marketplace as an option
* [ ] Modify CI to run Localization smoke test with VSIX file that is built in CI

**Comment by fai814** [comment]
Fixes octo-org/octo-repo#100

**Comment by TylerLeonhardt** [comment]
I don't think we'll ever get here frankly
