### ISSUE TITLE
README.md  dead link?

### ISSUE THREAD

**Issue by 7cc** [Microsoft/vscode-loc#31]
In the second paragraph,

Localized resource files are managed in [Transifex](https://www.transifex.com/microsoft-oss/). ← 404

could it be https://www.transifex.com/microsoft-oss/public/ ?

**Comment by 7cc** [comment]
ah,  after I joined one of the translation project, I can visit the link without /public/ in the end of the URL.

**Comment by danyeh** [comment]
good to know you figured it out.
