### ISSUE TITLE
[Russian] Typo in PHP notification / Опечатка в уведомлении PHP

### ISSUE THREAD

**Issue by JoCat** [microsoft/vscode-loc#312]
A typo in the file was most likely translated by mistake.
Specified by: `php.validate.exeКутаблепас`
Correct: `php.validate.executablePath`

---

Опечатка в файле, скорее всего было переведено по ошибке.
Указано: `php.validate.exeКутаблепас`
Правильно: `php.validate.executablePath`

---

https://github.com/microsoft/vscode-loc/blob/6f95a406a49a315581808e081693abfa21fddaf9/i18n/vscode-language-pack-ru/translations/extensions/php-language-features.i18n.json#L14
https://github.com/microsoft/vscode-loc/blob/6f95a406a49a315581808e081693abfa21fddaf9/i18n/vscode-language-pack-ru/translations/extensions/php-language-features.i18n.json#L31

**Comment by nexue2020** [comment]
Thank you for the feedback. Internal ticket has been created to take care of this: https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/96617
