### ISSUE TITLE
Custom en-GB Language Pack is not used

### ISSUE THREAD

**Issue by mjcheetham** [Microsoft/vscode-loc#34]
After following the instructions [here](https://github.com/Microsoft/vscode-loc/wiki/How-to-create-language-pack-extension) on how to build and install a language pack VSIX into the Insiders VS Code, I find that the translations are not actually used.

I had a suspicion that the problem was that I am creating a `en-*` language pack and that Code was deciding to take the `en-US` (or just `en`) strings instead.

See https://github.com/Microsoft/vscode/blob/5dc414c/src/main.js#L267

```js
// Check if we have an English locale. If so fall to default since that is our
// English translation (we don't ship *.nls.en.json files)
if (locale && (locale == 'en' || locale.startsWith('en-'))) {
	return Promise.resolve({ locale: locale, availableLanguages: {} });
}
```

Looks like because `'en-GB'.startsWith('en-')` the 'NLS' file (?) is not being generated, hence the UK strings are not being used.

I tried changing the ID of the language pack to `zz` and that _did_ work correctly, confirming my suspicion.

This issue might be better raised in the vscode repository rather than here in vscode-loc?

cc: @danyeh

**Comment by danyeh** [comment]
@dbaeumer @sandy081 @ramya-rao-a , please take a look and re-assign.
Matthew is building en-GB Language Pack. Please help.
Let us know if need to port the issue to vscode repo.

**Comment by ramya-rao-a** [comment]
The findings above are correct. If user's locale starts with `en`, we dont use any language packs. We use the default english strings. Can you elaborate on the advantages of having different language packs for English this way?

**Comment by danyeh** [comment]
Original request is here. Matthew explained there. https://github.com/Microsoft/vscode/issues/35690
There is a new request concern about current en. https://github.com/Microsoft/vscode/issues/54819

**Comment by mjcheetham** [comment]
@ramya-rao-a, as linked on my original request (Microsoft/vscode#35690) and the new request for an en-AU language pack (Microsoft/vscode#54819), there are a number of differences in spelling and grammar between en-US (the Code default/fallback language) and en-GB/AU.

Many English speakers in Europe are also familiar with the 'British' spellings (and I believe British English is used for official translations in the EU too).

Given the large population of speakers who are familiar with this English variant I would expect en-* languages to be supported in Code. Both the "traditional" and "simplied" variants of Chinese are supported, and I believe (based on the lack of special treatment of `pr-*` languages in Code) that a European Portugese (pr-PT) language pack would work fine alongside the already existing Brazillian Portuguese (pr-BR) language pack.

I don't think it'd be fair to arbitrarily restrict language pack availablity to only one variant of each language.

Would you like me to open an issue in the main Microsoft/vscode repository?

**Comment by ramya-rao-a** [comment]
@mjcheetham You can re-use https://github.com/Microsoft/vscode/issues/54819 to continue this discussion. Closing this issue, as there is nothing more to do from the vscode-loc side here.

**Comment by mjcheetham** [comment]
Thanks!
