### ISSUE TITLE
French translation not ideal for selectLanguage

### ISSUE THREAD

**Issue by bn3t** [microsoft/vscode-loc#342]
This translation is not ideal: `langue` is for spoken languages, `langage` is for programming languages. See https://fr.wikipedia.org/wiki/Langage_de_programmation.

I would suggest to convert:
```
"vs/workbench/contrib/codeEditor/browser/untitledTextEditorHint": {
			"dontshow": "ne plus",
			"selectAlanguage": "Sélectionnez une langue",
			"thisAgain": " afficher ceci.",
			"toGetStarted": " pour démarrer. Commencez à taper pour ignorer, ou "
		},
```

To:

```
"vs/workbench/contrib/codeEditor/browser/untitledTextEditorHint": {
			"dontshow": "ne plus",
			"selectAlanguage": "Sélectionnez un langage",
			"thisAgain": " afficher ceci.",
			"toGetStarted": " pour démarrer. Commencez à taper pour ignorer, ou "
		},
```
Kind regards,
Bernard.

**Comment by v-mholloway** [comment]
looks like this was corrected in Fabric yesterday...
![image](https://user-images.githubusercontent.com/77055370/127509901-ba134170-9bfe-42ce-87c8-4e6ef31b795a.png)

**Comment by v-mholloway** [comment]
closing a fix should now be in the build
