### ISSUE TITLE
[LOC] [ES] Workspace Trust links not working

### ISSUE THREAD

**Issue by moxwel** [microsoft/vscode-loc#343]
In the latest version of VSCode (v1.58), they implemented links in the Workspace Trust page to directly configure settings.
See [version notes](https://code.visualstudio.com/updates/v1_58#_workspace-trust).
![image](https://user-images.githubusercontent.com/49621788/125230021-f605f980-e2a5-11eb-9aca-d7f5ec2129d2.png)

But in the Spanish Translation, they aren't working.
![image](https://user-images.githubusercontent.com/49621788/125230206-5e54db00-e2a6-11eb-9ece-39c7fd43c040.png)

**Comment by v-mholloway** [comment]
removed these spaces to try mitigate this issue...
![image](https://user-images.githubusercontent.com/77055370/127509196-083d2cbf-5301-471e-896f-05da2d7517b6.png)

**Comment by v-mholloway** [comment]
closing as fix should now be in the build
