### ISSUE TITLE
Korean translation not ideal for localization 지역화 -> 현지화

### ISSUE THREAD

**Issue by manudeli** [microsoft/vscode-loc#345]
#344 
[See what diff in this pull request](https://github.com/microsoft/vscode-loc/pull/344/files)

현지화 is more understandable than 지역화 to translate localization.👈

I would suggest to convert: 
```
"LanguagePackTitle": "언어 팩은 VS Code의 지역화된 UI 환경을 제공합니다.",
"LocPlatform": "번역 문자열은 Microsoft 지역화 플랫폼에서 유지 관리됩니다. Microsoft 지역화 플랫폼에서만 내용을 변경할 수 있으며, 변경한 후 vscode-loc 리포지토리로 내보낼 수 있습니다. 따라서 vscode-loc 리포지토리에서 끌어오기 요청은 허용되지 않습니다.",
"Contributed": "이 언어 팩은 \"커뮤니티에 의한, 커뮤니티를 위한\" 커뮤니티 지역화 노력을 통해 기여받은 것입니다. 도움을 주신 커뮤니티 기여자분들께 진심으로 감사드립니다.",
"localizations": "지역화({0})",
"localizations localized language name": "언어 이름(지역화됨)",
"vscode.extension.contributes.localizations": "편집기에 지역화를 적용합니다."
```
To:
```
"LanguagePackTitle": "언어 팩은 VS Code의 현지화된 UI 환경을 제공합니다.",
"LocPlatform": "번역 문자열은 Microsoft 현지화 플랫폼에서 유지 관리됩니다. Microsoft 현지화 플랫폼에서만 내용을 변경할 수 있으며, 변경한 후 vscode-loc 리포지토리로 내보낼 수 있습니다. 따라서 vscode-loc 리포지토리에서 끌어오기 요청은 허용되지 않습니다.",
"Contributed": "이 언어 팩은 \"커뮤니티에 의한, 커뮤니티를 위한\" 커뮤니티 현지화 노력을 통해 기여받은 것입니다. 도움을 주신 커뮤니티 기여자분들께 진심으로 감사드립니다.",
"localizations": "현지화({0})",
"localizations localized language name": "언어 이름(현지화됨)",
"vscode.extension.contributes.localizations": "편집기에 현지화를 적용합니다.",
```

Kind regards,
Jonghyeon.

**Comment by v-mholloway** [comment]
@manudeli can you advise why this was reopened...?

**Comment by manudeli** [comment]
> @manudeli can you advise why this was reopened...?

I closed this issue on my mistake, so I reopened
Do I have anything to do to reflect my suggestion?

**Comment by v-mholloway** [comment]
@manudeli 
perhaps I'm confused, but looking at the commit at the start of this thread, (https://github.com/microsoft/vscode-loc/pull/344/files ) it appears as if your suggested translations have already been implemented.

**Comment by v-mholloway** [comment]
@manudeli my bad... I see your PR require approval

**Comment by manudeli** [comment]
@v-mholloway  Then, Do I have to do anything to reflect my suggestion?
Is waiting what I need to do? Actually, I couldn't be confident that I understand what your comment means
Could you explain what I have to do more, please?

**Comment by v-mholloway** [comment]
@manudeli it's ok, your translations should be fine, but I don't have permissions to check them in. I'll have to leave that to an FTE to do.

**Comment by manudeli** [comment]
@v-mholloway Thanks👍  Got it!

**Comment by v-mholloway** [comment]
@danyeh would you have permissions to approve this https://github.com/microsoft/vscode-loc/pull/344/files to mitigate this issue?

**Comment by manudeli** [comment]
I added change sentence understandable #431

**Comment by danyeh** [comment]
@manudeli , @v-mholloway , thank you for  the feedback and followup!
I merged the PR so readme.md can take effect.
However, even the workbench feedback was merged in same time, the file will be overwritten by translation from loc platform (Fabric). So in the future, please just open 'Issue', don't create PR unless it is readme.md.

@v-mholloway , please help to follow up new workbench feedback (see PR). Then can close this issue.

**Comment by v-mholloway** [comment]
@danyeh string for workbench.editor.languageDetection now updated in Fabric.
