### ISSUE TITLE
[zh-hans] Translation of smoothScrolling is inconsistent

### ISSUE THREAD

**Issue by simonla** [microsoft/vscode-loc#350]
I searched 平滑滚动 in the settings to enable this feature

As shown in the picture, I did not get the right result

This is because the translation of smoothScrolling want to explain it's effect instead of literal meaning

![Snipaste](https://user-images.githubusercontent.com/14934570/126044537-3a58ac3f-a5e3-49d2-97f7-522b809cd86a.png)

SmoothScrolling in the following two items should have consistent translations

I guess it was a mistake

We should translate smoothScrolling to it's literal meaning

`"smoothScrolling": "控制编辑器是否在滚动时使用动画。"`

`"list smoothScrolling setting": "控制列表和树是否具有平滑滚动。"`

**Comment by v-mholloway** [comment]
@simonla can you confirm if these are the product strings you refer to...?
![image](https://user-images.githubusercontent.com/77055370/127488502-6db041e7-4a06-4c13-8276-3287509d190f.png)

**Comment by v-mholloway** [comment]
Note: these are the only matches in the product with the zh-hans strings you provided.

**Comment by simonla** [comment]
> @simonla can you confirm if these are the product strings you refer to...?
> ![image](https://user-images.githubusercontent.com/77055370/127488502-6db041e7-4a06-4c13-8276-3287509d190f.png)

yes

**Comment by v-mholloway** [comment]
Bug opened [111479](https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/111479)

**Comment by v-mholloway** [comment]
closing as bug 111479 now resolved
