### ISSUE TITLE
[zh-hans] Tanslation of "Start Extension Bisect"'s MesageBox content is incorrect

### ISSUE THREAD

**Issue by HiroMuraki** [microsoft/vscode-loc#353]
The "Binary Search" looks like should be translated into "二分查找" or "二分搜索" instead of "二进制搜索"

**Comment by v-mholloway** [comment]
@HiroMuraki can you advise if this is the product string you refer to...?
![image](https://user-images.githubusercontent.com/77055370/127487916-0c6def75-fc56-40b2-8899-428f29815cbe.png)

**Comment by v-mholloway** [comment]
its the only one in the product containing the English string "binary search"

**Comment by HiroMuraki** [comment]
> @HiroMuraki can you advise if this is the product string you refer to...?
> ![image](https://user-images.githubusercontent.com/77055370/127487916-0c6def75-fc56-40b2-8899-428f29815cbe.png)

yes it is. The "... binary search..." in the first sentence should be tranlasted into "二分搜索" or 二分查找" 

Just for instance, the full sentence can be translate into "扩展二等分将通过二分查找的方式确认引起问题的扩展。在此过程中，窗口将会不断重新加载（约{0}次），每次都必须确认是否出现问题“

**Comment by v-mholloway** [comment]
@HiroMuraki change now implemented. will take a few days to migrate to the build

**Comment by v-mholloway** [comment]
closing as fix should now be in the build
