### ISSUE TITLE
Translate telemetry opt-out related strings as soon as possible

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-loc#36]
@danyeh The strings `telemetryOptOut.optOutOption`, `telemetryOptOut.OptOut` and `telemetryOptOut.OptIn` are translated only in 6 locales at the moment. Is there any way to ensure they get translated in the rest and the corresponding extensions get updated in the next few days?

We want to enable an experiment which we can do only when these strings are localized in all the locales.

**Comment by danyeh** [comment]
@ramya-rao-a , I double checked 9 core languages. They are all localized properly. Could you please hint which language(s) have issue? 

Translation in latest language pack can be found here. https://github.com/Microsoft/vscode-loc/tree/release/1.26

**Comment by ramya-rao-a** [comment]
Looks like github search is not reliable :)

I went through the translations manually and found that only the below are missing
- ps
- pt-br
- tr

**Comment by danyeh** [comment]
I will ping community members for these community owned languages. If they contribute, I will re-publish language pack.

**Comment by ramya-rao-a** [comment]
Thanks @danyeh!

**Comment by danyeh** [comment]
I have asked community but these languages still not fully covered. Eventually community contributor will cover this. I close this for now.
