### ISSUE TITLE
[zh-hans] request more appropriate translation for "duplicateWorkspace" and "duplicateWorkspaceInNewWindow""

### ISSUE THREAD

**Issue by wzhli** [microsoft/vscode-loc#362]
**Location**:  "vs/workbench/browser/actions/workspaceActions" - "duplicateWorkspace"
**Translation Now**: "重复工作区"
**Suggested Translation**: "复制工作区到新窗口"

**Location**: "vs/workbench/browser/actions/workspaceActions" - "duplicateWorkspaceInNewWindow"
**Translation Now**: "在新窗口中复制为工作区"
**Suggestion**: I think this is redundant with "duplicateWorkspace" functionally, as when we click "duplicateWorkspace", it will create a new window too.

**Comment by v-mholloway** [comment]
bug opened [111400](https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/111400)

**Comment by v-mholloway** [comment]
closing as bug 111400 now resolved
