### ISSUE TITLE
Spelling mistake in the German Language Pack

### ISSUE THREAD

**Issue by musonius** [microsoft/vscode-loc#382]
Issue Type: <b>Bug</b>

There are some texts containing the misspelled word "Arbeitsbereichsvertrauensstellung" (e.g. "Arbeitsbereichsvertrauensstellung verwalten" in the gear wheel menu and the title "Arbeitsbereichsvertrauensstellung"of the page for managing workspace trusts).

It should be: Arbeitsbereichsvertrauenseinstellung

That is: The part "ein" of "einstellung" at the end of the very long word is missing.

Extension version: 1.58.8
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by v-mholloway** [comment]
bug opened [111395](https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/111395)

**Comment by v-mholloway** [comment]
linguists comments - 
"there's nothing to change here" 
"Trust = Vertrauensstellung and NOT VertrauensEINstellung"
