### ISSUE TITLE
[de] Improve translation of duplicateWorkspace

### ISSUE THREAD

**Issue by fknipp** [microsoft/vscode-loc#386]
In _vs/workbench/browser/actions/workspaceActions_ in _main.i18n.json_, the translation for **duplicateWorkspace** is **Doppelter Arbeitsbereich**.

Doppelter Arbeitsbereich sounds like a state, like _this is a duplicated workspace_. Therefore, I'd suggest to say **Arbeitsbereich duplizieren**.

**Comment by v-mholloway** [comment]
bug opened 116506[https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/116506](url)

**Comment by v-mholloway** [comment]
closing as bug 116506 now resolved
