### ISSUE TITLE
[Italian] small typo in the translation of "copyExtension"

### ISSUE THREAD

**Issue by 3rror** [microsoft/vscode-loc#387]
There is a small typo in the Italian translation of "copyExtension" inside the contextual menu when the user right-clicks on an extension. It should be "Copia" instead of "Coppia".

Steps:
1. Open the extensions panel
2.  Right-click on an extension
3.  See "Coppia" instead of "Copia" 

This is the corresponding line in [main.i18n.json](https://github.com/microsoft/vscode-loc/blob/9945f1a67506d80a7beb953f7e7ae3f7cb7f3679/i18n/vscode-language-pack-it/translations/main.i18n.json#L5002):

`"workbench.extensions.action.copyExtension": "Coppia",`

It should be

`"workbench.extensions.action.copyExtension": "Copia",`

**Comment by v-mholloway** [comment]
change implemented. - it will take a few days to get into the build

**Comment by v-mholloway** [comment]
closing a fix should be in the build now
