### ISSUE TITLE
Wrong meaning in pt-br

### ISSUE THREAD

**Issue by hfabio** [microsoft/vscode-loc#390]
Please, change "Abrir pasta continente" at:
https://github.com/microsoft/vscode-loc/blob/0868ed21eabc9785bbec81ae0475f49b25d57c1c/i18n/vscode-language-pack-pt-BR/translations/main.i18n.json#L5728

to "Abrir pasta que contém"

**Comment by v-mholloway** [comment]
change implemented - will take a few days to make it into the build

**Comment by hfabio** [comment]
Awesome, thank you!

**Comment by v-mholloway** [comment]
closing as change should be in the build now
