### ISSUE TITLE
Traditional Chinese translation of text labels on the notebook toolbar is not correct

### ISSUE THREAD

**Issue by ted1030** [microsoft/vscode-loc#397]
![image](https://user-images.githubusercontent.com/37107237/128621355-3137761e-bebb-48c3-b4a5-0ed1fa164e38.png)
1.In English UI, the red circle above is "code", but it means "verification code" in Traditional Chinese UI. The correct translation is like the red circle below.
2. Some text is not translated.

**Comment by v-mholloway** [comment]
@ted1030 can you provide the Chinese text in this conversation so we can perform a search?

**Comment by ted1030** [comment]
The first is "驗證碼", and the second is "程式碼".

**Comment by ted1030** [comment]
Thanks.

**Comment by v-mholloway** [comment]
closing as change should be in the build now
