### ISSUE TITLE
[RU] Terminal - Move to Editor Area

### ISSUE THREAD

**Issue by darkfessing** [microsoft/vscode-loc#399]
New feature with terminal move: not translated into Russian. See screenshot.

![2021-08-11_19-49-54](https://user-images.githubusercontent.com/78741712/129070342-9b7aa721-06d8-4d38-95dd-dcd677aa0a6d.png)

**Comment by v-mholloway** [comment]
cannot find that string in the VScode subtenant.

**Comment by heartacker** [comment]
FYI: https://github.com/microsoft/vscode/issues/132024 @v-mholloway

**Comment by danyeh** [comment]
Fixed. 
![image](https://user-images.githubusercontent.com/19785531/137057392-1ea9befa-bfe7-4b3d-afa4-3213d5dde691.png)
![image](https://user-images.githubusercontent.com/19785531/137057479-eb52a4f9-76ed-4699-b05f-b5663c3e40fe.png)
