### ISSUE TITLE
[zh-hans] Capitalization of "URL"

### ISSUE THREAD

**Issue by dnicolson** [microsoft/vscode-loc#401]
There is a [single instance](https://github.com/microsoft/vscode-loc/blob/a0d0ad3c704fcb0861cdb4f8295bdf9c9ef45970/i18n/vscode-language-pack-zh-hans/translations/extensions/simple-browser.i18n.json#L14) of "URL" being in lowercase, compared to 44 occurrences where it is uppercase.

**Comment by v-mholloway** [comment]
Change implemented - it will take a few days to make it into the build

**Comment by dnicolson** [comment]
Closed via #403.
