### ISSUE TITLE
Wrong transalation of the token generateColorTheme.label in the spanish language pack

### ISSUE THREAD

**Issue by noeFernandez** [Microsoft/vscode-loc#41]
Hi, 

I found out the translation for the token `generateColorTheme.label` has a typo, it's translated as `General el tema de color desde la configuración actual` when it should be `Generar el tema de color desde la configuración actual`

**Comment by lukaschal** [comment]
On review now.

**Comment by lukaschal** [comment]
Fixed as suggested.

**Comment by janbaltus** [comment]
Issue is fixed. Please verify & close
