### ISSUE TITLE
Language Pack for Hindi

### ISSUE THREAD

**Issue by ZohebMOPO** [microsoft/vscode-loc#411]
Can we start making a language pack for Hindi?. Hopefully I will make a PR

**Comment by v-mholloway** [comment]
@danyeh do you have the relevant info for @ZohebMOPO

**Comment by danyeh** [comment]
@ZohebMOPO  . Microsoft won't host localization project for languages not in scope outlined in the repo. If you are ok to manage the localization project yourself, the path is available to create your own language pack. See how to create language pack topic in the wiki of this repo. Thanks!

CC: @TylerLeonhardt.
