### ISSUE TITLE
Ну что за дела! Предложение:

### ISSUE THREAD

**Issue by electrolom42** [microsoft/vscode-loc#42]
Не лучше для каждого языка сделать описание на этом же языке, лучше/удобнее/круче! Заходишь на страницу расширения "Russian Language Pack for Visual Studio Code", а там описание на английском, шик! 🙄

**Comment by lukaschal** [comment]
@electrolom42 Please, is it possible to add your feedback in ENU language and some screenshots ?

**Comment by yhvicey** [comment]
I guess he/she means language packages' name should be in their target language, like “中文语言包" for Chinese language package. 😄

**Comment by weeteckt** [comment]
The readme associated with each language pack is already translated to help Russian speakers understand the language pack in greater details.
