### ISSUE TITLE
Simplified Chinese un translated 

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-loc#427]
Find all ref and Hierarchy
![image](https://user-images.githubusercontent.com/1876302/130894967-17df7306-4ffb-4425-9b35-64f9d51814f8.png)

same as https://github.com/microsoft/vscode-loc/issues/395

**Comment by v-mholloway** [comment]
@heartacker thanks for pointing that out.
@danyeh I cannot track down these resources in Fabric (https://github.com/microsoft/vscode-references-view/blob/566d5c35ff18f6000f6beb142c6cf108cecd39a2/package.json#L65-L161)
would you know where they can be translated?

**Comment by heartacker** [comment]
hi, maybe we should file a issue to vscode-reference-view and tell her: let's get start to support ` i18n`

**Comment by danyeh** [comment]
I close this as external. This repo only host strings extracted from vscode repo.
