### ISSUE TITLE
ReferenceView not Localization

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-loc#428]
this extension: 
buildin vscode:
https://marketplace.visualstudio.com/items?itemName=ms-vscode.references-view

1. view
![image](https://user-images.githubusercontent.com/1876302/130895697-ee3a5537-4e98-4479-9b54-fb39ad390d9f.png)

2. menu
ref issue:(about reference view)
https://github.com/microsoft/vscode-loc/issues/427
https://github.com/microsoft/vscode-loc/issues/395

**Comment by danyeh** [comment]
I close this as external. This repo only host strings extracted from vscode repo.
