### ISSUE TITLE
cn-zh 建议将notebook 的 `在单元格上方执行` 改为 `执行上方所有单元格` 

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-loc#430]
将notebook 的 `在单元格上方执行` 改为 `执行上方所有单元格 `
#410 
在单元格上方执行： 类似把这个cell 放在别的地址执行，应该是`执行上方的所有单元格，以便于后续执行当前单元格`

**Comment by v-mholloway** [comment]
closing as changes should be in the build now
