### ISSUE TITLE
[zh-cn] A bunch of translation optimization

### ISSUE THREAD

**Issue by ha0y** [microsoft/vscode-loc#434]
Language: Chinese Simplified

---

String Identifier: noFolderHelp
Current Translation: `你尚未打开文件夹。\r\n[打开文件夹](command:{0})`
Requested Translation: `尚未打开文件夹。\r\n[打开文件夹](command:{0})`

---

String Identifier: searchWithoutFolder
Current Translation: `你尚未打开或指定文件夹。当前仅搜索打开的文件 -`
Requested Translation: `尚未打开或指定文件夹。当前仅搜索打开的文件 - `
Note: There should be a space at the end
<img width="378" alt="屏幕快照 2021-08-27 05 52 48 AM" src="https://user-images.githubusercontent.com/30557072/131130481-7dd2f5e3-2246-473e-aa02-7ac0ae396707.png">

---

String Identifier: noTrustedFoldersDescriptions
Current Translation: `你尚未信任任何文件夹或工作区文件。`
Requested Translation: `尚未信任任何文件夹或工作区文件。`

---
### Summary

"You" is not needed to be translated in Chinese in most cases. `你` is not a good expression here.

---

String Identifier: miToggleRenderControlCharacters
Current Translation: `呈现控制字符(&&C)`
Requested Translation: `显示控制字符(&&C)`

---

String Identifier: miToggleRenderWhitespace
Current Translation: `呈现空格(&&R)`
Requested Translation: `显示空格(&&R)`

<img width="183" alt="截屏2021-08-27 上午6 02 57" src="https://user-images.githubusercontent.com/30557072/131131542-3517a3ae-4bc8-403e-9bb7-9a08bdf009ea.png">

**Comment by v-mholloway** [comment]
changes now implemented - please allow a few days for fixes to get into the build

**Comment by v-mholloway** [comment]
closing as changes should be in the build by now
