### ISSUE TITLE
translation issue in vscode-language-pack-zh-hans

### ISSUE THREAD

**Issue by wanningfe** [Microsoft/vscode-loc#44]
![tim 20190104060852](https://user-images.githubusercontent.com/25128272/50664222-48844200-0fe7-11e9-80f6-6b0dd315b28f.png)

In my opinion,translation for 'Format Document' is not '设置文档格式' but '格式化文件'。

**Comment by lukaschal** [comment]
On review.

**Comment by Joelism** [comment]
Oh boy, there's already a round of review in https://github.com/Microsoft/vscode/issues/17120

**Comment by lukaschal** [comment]
Linguistic answer:

Indeed "设置格式" can be interpreted more than one ways, but readers will know the intended meaning in context. So the current translation seems OK.

**Comment by wanningfe** [comment]
我记得在语言包社区化之前，format document 的翻译一直是 “格式化文件”。
所以我习惯性的在命令面板输入Format，却找不到“格式化文件“选项。
所以我觉得，既然”格式化文件“不是一个完全错误的翻译，不如继续使用旧的翻译？
