### ISSUE TITLE
Typo in japanese

### ISSUE THREAD

**Issue by ycrack** [microsoft/vscode-loc#451]
Isn't this "インデント" (indent) rather than "インシデント" (incident) ?
https://github.com/microsoft/vscode-loc/blob/80be8adc469bcac3cbd80805e8b98109e973c7de/i18n/vscode-language-pack-ja/translations/main.i18n.json#L1468

**Comment by v-mholloway** [comment]
@ycrack  yes it is. Can you provide the full translation please
"render tree indent guides": "????????????????????????"

**Comment by ycrack** [comment]
@v-mholloway Sure.
```
"render tree indent guides": "ツリーでインデントのガイドを表示する必要があるかどうかを制御します。"
```

NOTE: I'm not familiar with translation, so I'm not sure about accuracy of this.

**Comment by v-mholloway** [comment]
bug opened [122234](https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/122234)

**Comment by v-mholloway** [comment]
closing as bug is now resolved
