### ISSUE TITLE
Typo in French about Typescript

### ISSUE THREAD

**Issue by edimitchel** [microsoft/vscode-loc#456]
Hi,

An issue was found in the translation of Typescript.

See #455

**Comment by v-mholloway** [comment]
changes implemented in the Fabric system - please allow a few days for fixes to get into the build. 
You can discard your pull request now.

**Comment by v-mholloway** [comment]
changes should be in the build now - closing

**Comment by edimitchel** [comment]
Checked, available in 1.61.1! Thanks!
