### ISSUE TITLE
How to add Persian language?

### ISSUE THREAD

**Issue by amiria703** [microsoft/vscode-loc#459]
Hi!
I can translate MS VS Code in Persian
But I don't know how to do so

**Comment by v-mholloway** [comment]
@danyeh do you have the relevant info for @amiria703 ?

**Comment by danyeh** [comment]
As far as I know, VSCode doesn't support RTL language as display language. So won't be able to add even have contribution on translation.
CC: @TylerLeonhardt.

**Comment by TylerLeonhardt** [comment]
That's correct. We don't support RTL languages at this time.

https://github.com/microsoft/vscode/issues/86667
