### ISSUE TITLE
[zh-cn] Some translation improvements

### ISSUE THREAD

**Issue by ha0y** [microsoft/vscode-loc#468]
Language: Chinese Simplified

---

String Identifier: untitledTextEditorHint
Current Translation: 
```
"dontshow": "不显示",
"selectAlanguage2": "选择语言",
"thisAgain": "询问。",
"toGetStarted": "开始。开始键入以取消或"
```

Requested Translation: 
```
"dontshow": "不再显示",
"selectAlanguage2": "选择编程语言",
"thisAgain": "。",
"toGetStarted": "以开始。输入内容即可消除此提示，或者设为以后"`
```
![image](https://user-images.githubusercontent.com/30557072/133867727-7ecf9620-ccd9-43fb-962a-a6d9c4443f54.png)

---

String Identifier: miCopyLinesUp
Current Translation: `向上复制行(&&C)`
Requested Translation: `向上复制一行(&&C)`

---

String Identifier: miSmartSelectGrow
Current Translation: `展开选定内容(&&E)`
Requested Translation: `扩大选区(&&E)`

---

String Identifier: miSmartSelectShrink
Current Translation: `缩小选定范围(&&S)`
Requested Translation: `缩小选区(&&S)`

![image](https://user-images.githubusercontent.com/30557072/133867782-9ee30b09-0fcf-465f-9233-4072a04b10c2.png)

---

String Identifier: exeBasedRecommendation
Current Translation: `由于当前工作区配置，建议使用此扩展`
Requested Translation: `根据当前工作区的配置，建议使用此扩展`

---

String Identifier: miGotoDeclaration
Current Translation: `转到\"声明\"(&&D)`
Requested Translation: `转到声明(&&D)`
Note: Don't know why `Declaration` is quoted. It is not quoted in English string.

---

String Identifier: miGotoImplementation
Current Translation: `跳转到实现(&&I)`
Requested Translation: `转到实现(&&I)`

![image](https://user-images.githubusercontent.com/30557072/133867890-27edfaaa-467e-4931-99d5-ec1dd782ccbb.png)

---

String Identifier: miNewTerminal
Current Translation: `新终端(&&N)`
Requested Translation: `新建终端(&&N)`

---

String Identifier: closeSidebar
Current Translation: `关闭侧栏`
Requested Translation: `关闭侧边栏`

---

String Identifier: miShowSidebar
Current Translation: `显示侧栏(&&S)`
Requested Translation: `显示侧边栏(&&S)`

---

String Identifier: too many characters
Current Translation: `出于性能原因，对长行跳过令牌化。这可以通过 “editor.maxTokenizationLineLength” 进行配置。`
Requested Translation: `出于性能原因，未对长行进行解析。解析长度阈值可通过“editor.maxTokenizationLineLength”进行配置。`

---

String Identifier: searchScope.includes
Current Translation: `要包含的文件`
Requested Translation: `包含的文件`
Note: There are two strings with the same identifier and both could be relaced.

![image](https://user-images.githubusercontent.com/30557072/133867927-cc33b86e-feaf-4cec-8f27-a747b9fcdf6a.png)

**Comment by v-mholloway** [comment]
bug Opened [127614](https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/127614)

**Comment by v-mholloway** [comment]
bug resolved - closing

**Comment by ha0y** [comment]
@v-mholloway 
I'm using the latest language pack release. It seems that no changes are applied. All strings reported remains the same. And I could not see any localization files updating [commits](https://github.com/microsoft/vscode-loc/commits/main) in recent two weeks. Would you please take a further look at it?

**Comment by v-mholloway** [comment]
@danyeh 
I can see the changes were checked in (e.g. https://dev.azure.com/ceapex/Fabric-Prod/_git/65a58888-d520-4614-90ec-ff7ceab11dae-repo/commit/4a85fb369cfd31832886d74c4304028d7b3f0b1b?refName=refs%2Fheads%2Fmaster&path=%2Floc%2Fecc6327a-afbc-49ed-99bb-e7edac03f97f%2F5ac238c4-780c-424d-9b5b-d5769e23d2c9.lcl&_a=compare)

shouldnt they be in the build by now...?

**Comment by ha0y** [comment]
@v-mholloway @danyeh 
As you can see, the localization files have not been modified for over a month. Not only zh-cn, but all languages. I can see commits like `update localization files microsoft/vscode-loc-drop@xxxxx` before but now I can only see the version number bumping. Does your automation system lost connection to GitHub or...?

![image](https://user-images.githubusercontent.com/30557072/136485459-fd67ee08-34ee-461e-80ca-d48621ba1e75.png)

You may leave this issue open before it is resolved.

**Comment by danyeh** [comment]
@TylerLeonhardt , handoff build down? See comment above.
