### ISSUE TITLE
[Spanish translation] "Workspace" is translated as "Área de trabajo" or as "Espacio de trabajo" in File menu and other places

### ISSUE THREAD

**Issue by BartolomeSintes** [microsoft/vscode-loc#469]
Hi,

In the English VSCode 1.60 there are four options with the "Workspace" word in the File menu:
Open Workspace... 
Add Folder to Workspace...
Save Workspace As...
Duplicate Workspace

These four strings are translated in Spanish VSCode 1.60 as:
Abrir el Espacio de trabajo...
Agregar carpeta al área de trabajo...
Guardar área de trabajo como ...
Área de trabajo duplicada

"Workspace" is translated as "espacio de trabajo" or as "área de trabajo".  I would say that in order to avoid confusion, only one of the translations should be used everywhere (in the menu and in the settings page)... I don't mind which one, but just one. 

By the way, I would say that "Duplicate Workspace" should be translated as "Duplicar área de trabajo" or "Duplicar espacio de trabajo", not as "Área de trabajo duplicada".

Thanking you in advance,
Bartolomé Sintes

**Comment by v-mholloway** [comment]
Bug Opened [128587](https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/128587)

**Comment by v-mholloway** [comment]
bug resolved. closing ticket

**Comment by BartolomeSintes** [comment]
Unfortunately, I can not see the bug 128587. What have you decided?

**Comment by v-mholloway** [comment]
these are the strings now after being reviewed by linguists...
![image](https://user-images.githubusercontent.com/77055370/135437914-ec3ef15c-9bc7-4d37-8264-c3618c7af2ea.png)

**Comment by BartolomeSintes** [comment]
Thanks. I also prefer "área de trabajo" over "espacio de trabajo", but I am surprised to see "Duplicate Workspace" translated as "Área de trabajo duplicada". I believe it should be "Duplicar área de trabajo". I would suggest to ask Benjamin Pasero, for instance. It will only take him one minute to decide which one is the right translation.
By the way, if "workspace" is translated as "área de trabajo", "espacio de trabajo" should be replaced in several configurations.
For instance,
1. CSS: Custom data
"The file paths are relative to workspace and only workspace folder settings are considered."
is translated as
"Las rutas de los archivos son relativas al espacio de trabajo y sólo se consideran las configuraciones de la carpeta del espacio de trabajo."
it shoul be 
"Las rutas de los archivos son relativas al área de trabajo y sólo se consideran las configuraciones de la carpeta del área de trabajo."
2. Grunt: Auto Detect
"Controls enablement of Grunt task detection. Grunt task detection can cause files in any open workspace to be executed."
is translated as
"Controla la habilitación de la detección de tareas de Gulp. La detección de tareas de Gulp puede hacer que se ejecuten archivos en cualquier espacio de trabajo abierto."
it should be
"Controla la habilitación de la detección de tareas de Grunt. La detección de tareas de Grunt puede hacer que se ejecuten archivos en cualquier área de trabajo abierta."
Notice that "Gulp" (instead of Grunt) appears in the Spanish translation.
3. "Controls enablement of Gulp task detection. Gulp task detection can cause files in any open workspace to be executed."
is translated as 
"Controla la habilitación de la detección de tareas de Gulp. La detección de tareas de Gulp puede hacer que se ejecuten archivos en cualquier espacio de trabajo abierto."
it should be
"Controla la habilitación de la detección de tareas de Gulp. La detección de tareas de Gulp puede hacer que se ejecuten archivos en cualquier área de trabajo abierta."
