### ISSUE TITLE
[Spanish translation] Inconsistent capitalization

### ISSUE THREAD

**Issue by BartolomeSintes** [microsoft/vscode-loc#470]
Hi,
In some menu options (in VSCode 1.60) not only the first word is capitalized:
Archivo > Abrir el Espacio de trabajo...
Ver > Mostrar Minimapa
Ir > Ir a Declaración
Ir > Ir a Implementaciones
Ir > Ir a Referencias
Ejecutar > Ejecutar Sin depuración

In every other menu option, only the first word is capitalized (as usual in Spanish).

Best regards,
Bartolomé Sintes

**Comment by v-mholloway** [comment]
@BartolomeSintes can you fill out this template so we can target the correct strings...
Culture: *****
String Identifier: ***** (e.g. notebookActions.executeAbove)
English String: *****
Current Translation: *****
Requested Translation: ****
Screen Shot: ***** (when applicable)

**Comment by BartolomeSintes** [comment]
Hi, v-mhlllowa. 

I am not sure where to find the String identifiers. I have searched English strings in VSCode source code and selected command ids next to them (hoping these are the String identifiers).
I have not included screen shots.

Culture: Spanish
String Identifier: workbench.action.openWorkspace
English String: "Open Workspace..."
Current Translation: "Abrir el Espacio de trabajo..."
Requested Translation: "Abrir el área de trabajo..."

Culture: Spanish
String Identifier: DuplicateWorkspaceInNewWindowAction.ID
English String: "Duplicate Workspace"
Current Translation: "Área de trabajo duplicada"
Requested Translation: "Duplicar área de trabajo"

Culture: Spanish
String Identifier: editor.action.toggleMinimap
English String: "Show &&Minimap"
Current Translation: "Mostrar &&Minimapa"
Requested Translation: "Mostrar &&minimapa"

Culture: Spanish
String Identifier: editor.action.revealDeclaration'
English String: "Go to &&Declaration"
Current Translation: "Ir a &&Declaración"
Requested Translation: "Ir a &&declaración"

Culture: Spanish
String Identifier: editor.action.goToImplementation
English String: "Go to &&Implementations"
Current Translation: "Ir a &&Implementaciones"
Requested Translation: "Ir a &&implementaciones"

Culture: Spanish
String Identifier: editor.action.goToReferences
English String: "Go to &&References"
Current Translation: "Ir a &&Referencias"
Requested Translation: "Ir a &&referencias"

Culture: Spanish
String Identifier: DEBUG_RUN_COMMAND_ID
English String: "Run &&Without Debugging"
Current Translation: "Ejecutar &&Sin depuración"
Requested Translation: "Ejecutar &&sin depuración"

**Comment by v-mholloway** [comment]
@BartolomeSintes thanks for the additional details. these changes are implemented now, but will take a few days to get into the build.

**Comment by BartolomeSintes** [comment]
Thank you for your excellent work!

**Comment by v-mholloway** [comment]
closing as the changes should be in the build by now
