### ISSUE TITLE
Traducción en español texto nuevo archivo "Seleccione un idioma para empezar. Empiece..."

### ISSUE THREAD

**Issue by lumodino** [microsoft/vscode-loc#472]
El texto debería ser "Seleccione un lenguaje para empezar. Empiece..."

**Comment by v-mholloway** [comment]
@lumodino can you fill out this template so we can target the correct strings...
Culture: *****
String Identifier: ***** (e.g. notebookActions.executeAbove)
English String: *****
Current Translation: *****
Requested Translation: ****
Screen Shot: ***** (when applicable)

**Comment by cristianosuzuki77** [comment]
Please re-open with a screenshot. Not able to locate this text.

**Comment by dragonDScript** [comment]
The current text is correct
