### ISSUE TITLE
French - Poubelle > Corbeille

### ISSUE THREAD

**Issue by fxbenard** [microsoft/vscode-loc#473]
Déplacer vers la **Poubelle** > Déplacer vers la **Corbeille**

<img width="315" alt="image" src="https://user-images.githubusercontent.com/802114/134538839-6312e4fc-aad4-403e-8e67-528611fc460c.png">

**Comment by v-mholloway** [comment]
change implemented - should get into the build in a few days

**Comment by v-mholloway** [comment]
closing as item should be in the build by now
