### ISSUE TITLE
Language pack for Telugu

### ISSUE THREAD

**Issue by suneel-eng** [microsoft/vscode-loc#474]
Can we add localization for **Telugu** language...?

**Comment by v-mholloway** [comment]
@danyeh would you be able to provide more information here?

**Comment by suneel-eng** [comment]
may be there is a chance that some of developers ( beginners ) in our region will face difficulty to understand english terms. so, I thought it'll be useful for beginners and people who won't understand english quickly.

**Comment by danyeh** [comment]
@suneel-eng , Microsoft won't host localization project for languages not in scope outlined in the repo. If you are ok to manage the localization project yourself, the path is available to create your own language pack. See how to create language pack topic in the wiki of this repo. Thanks!

CC: @TylerLeonhardt.
