### ISSUE TITLE
After installing korean language package, the setting.json has broken.

### ISSUE THREAD

**Issue by moonjoungyoung** [microsoft/vscode-loc#48]
https://github.com/Microsoft/vscode/issues/66831

**Comment by shawndon** [comment]
Hello. How is the setting.json broken? Can you provide a  little more information so we can troubleshooting? Are you specifically referring to the Visual Studio Code application after installing the Korean Language Pack? Or are you referring to MLCP and the files in GitHub? Please provide some steps. Thanks.

**Comment by moonjoungyoung** [comment]
@shawndon 

Hi, Shawndon.
Thank you for your comments.

1. How is the setting.json broken?
It has no open tag in the middle of the setting.json file at vs code. I can't access to default setting.json directly, so I need to click the problems - error.

2. Are you specifically referring to the Visual Studio Code application after installing the Korean Language Pack?  Or are you referring to MLCP and the files in GitHub?
No. An error occurs without installing another extension, and if I delete that program, the error disappears.

**Comment by shawndon** [comment]
Are you still having issues with the new version of Visual Studio Code. Could you check another language to see if this is Korean specific?

**Comment by danyeh** [comment]
I close the issue here. If you still repro the issue, please open in vscode repo. This vscode-loc only deal with translation issue.
