### ISSUE TITLE
[ja] "grammar" is mistranslated into "文章校正"

### ISSUE THREAD

**Issue by mandel59** [Microsoft/vscode-loc#49]
https://github.com/Microsoft/vscode-loc/blob/master/i18n/vscode-language-pack-ja/translations/main.i18n.json#L2942
"文章校正" means proofreading, not grammar. It should be "文法 (grammar)" or "文法規則 (grammar rule)".

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
Fixed.

SRC Grammar

TGT: 文章校正
New TGT: 文法

**Comment by lukaschal** [comment]
@mandel59 Please verify and close.

**Comment by mandel59** [comment]
I verified the change has been applied. Thank you😁
