### ISSUE TITLE
German language Pack 1.31.1: Translations in menu are partly gone

### ISSUE THREAD

**Issue by Raydir** [Microsoft/vscode-loc#50]
Hi there

I just mentioned, that several Points in the menubar are not translated anymore?

![image](https://user-images.githubusercontent.com/17499573/51962767-9020b100-2461-11e9-8a78-dafc55c9e63a.png)

I did mention this in "Insider-Build" because i tried to press Ctrl+O to open a "Folder" (was configured like that before)

**Comment by lukaschal** [comment]
Due to some merging issues, these menu items needs to be retranslated. Working on solution.

**Comment by Raydir** [comment]
Hey @lukaschal  thanks for your answer

**Comment by lukaschal** [comment]
@Raydir Please verify this on latest version and let us know.

**Comment by Raydir** [comment]
@lukaschal  at the moment the whole "file" aka "Datei" Menu is completely in english.... even "Neue Datei" is "new file" now.

My specs:

> Version: 1.32.0-insider (system setup)
> Commit: bbe40c8cb0901c439b3b61221a0197fb6723783e
> Datum: 2019-02-18T10:48:37.179Z
> Electron: 3.1.3
> Chrome: 66.0.3359.181
> Node.js: 10.2.0
> V8: 6.6.346.32
> Betriebssystem: Windows_NT x64 10.0.17763

*German Language Pack for Visual Studio Code:* 1.31.4

**Comment by lukaschal** [comment]
@Raydir Fixed on version mentioned below.

![image](https://user-images.githubusercontent.com/18324331/54126490-f822c980-4407-11e9-8aa1-48131b4238fd.png)

**Comment by Raydir** [comment]
Thank you @lukaschal 👍
