### ISSUE TITLE
Catalan translation

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-loc#504]
Issue to track VSCode translation to the catalan language.

**Comment by TylerLeonhardt** [comment]
Microsoft won't host localization project for languages not in scope outlined in the repo. If you are ok to manage the localization project yourself, the path is available to create your own language pack. See how to create language pack topic in the wiki of this repo. Thanks!

**Comment by TylerLeonhardt** [comment]
Not at this time as far as I know. Right @danyeh?
