### ISSUE TITLE
[ja] orthographical variants

### ISSUE THREAD

**Issue by EbXpJ6bp** [Microsoft/vscode-loc#51]
「ターミナル」「端末」 (original: terminal) have the same meaning, but different written forms.
I would recommend 「ターミナル」. Because "Integrated Terminal" is known as 「統合ターミナル」.

```
+-- terminal 
| +-- ターミナル 98/126 (77.8%)
| +-- 端末 28/126 (22.2%)
```

**Comment by lukaschal** [comment]
All instances fixed as suggested.
