### ISSUE TITLE
[zh-CN] Git extension translation issues

### ISSUE THREAD

**Issue by flamott** [microsoft/vscode-loc#514]
### 1. Icon syntax incorrectly translated 
**English strings:**
"scm button publish title": "$(cloud-upload) Publish Changes"
"scm button sync title": " Sync Changes $(sync){0}{1}"
**Current:**
"scm button publish title": "$(云上传)发布更改", 
"scm button sync title": " 同步更改 $(同步){0}{1}"
**Suggested:**
"scm button publish title": "$(cloud-upload)发布更改"
"scm button sync title": " 同步更改 $(sync){0}{1}"
### 2. 
**English string:**
"tooManyChangesWarning": "Too many changes were detected. Only the first {0} changes will be shown below."
**Current:**
"tooManyChangesWarning": "检测到过多更改。下面将仅显示第一个 {0} 更改。"
**Suggested:**
"tooManyChangesWarning": "检测到过多更改。下面将仅显示前 {0} 个更改。"

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 502452)
