### ISSUE TITLE
[ja] "{0} of {1}" is mistranslated into "{1} の {0}"

### ISSUE THREAD

**Issue by EbXpJ6bp** [Microsoft/vscode-loc#52]
This string indicates the number of the current search match.

2018:
https://github.com/Microsoft/vscode-loc/blob/17374fc8e0c85e80193610dfdc7f04d38002bbfc/i18n/vscode-language-pack-ja/translations/main.i18n.json#L667

2019:
https://github.com/Microsoft/vscode-loc/blob/2b0238ec21fa11d40eccc9356b22e8227fd9ac10/i18n/vscode-language-pack-ja/translations/main.i18n.json#L549

![86d4dd25059ad6850d5e645f25f2473b](https://user-images.githubusercontent.com/8474118/51966313-81f98180-24af-11e9-8656-e85a5b1137a2.png)

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
Fixed as suggested.
