### ISSUE TITLE
[ja] "extension" is mistranslated into "拡張子"

### ISSUE THREAD

**Issue by EbXpJ6bp** [Microsoft/vscode-loc#53]
```
+-- extension
| +-- 拡張機能 - add-ons, plugin 
| +-- 拡張子 - filename extension (correct: 12/15)
```
The following strings should be 「拡張機能」:

https://github.com/Microsoft/vscode-loc/blob/2b0238ec21fa11d40eccc9356b22e8227fd9ac10/i18n/vscode-language-pack-ja/translations/main.i18n.json#L1144

https://github.com/Microsoft/vscode-loc/blob/2b0238ec21fa11d40eccc9356b22e8227fd9ac10/i18n/vscode-language-pack-ja/translations/main.i18n.json#L1685

https://github.com/Microsoft/vscode-loc/blob/2b0238ec21fa11d40eccc9356b22e8227fd9ac10/i18n/vscode-language-pack-ja/translations/main.i18n.json#L2673

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
Linguistic answer:

拡張子 (TS 335612) is used to refer to "file name extension"  while 拡張機能 (TS 2281655) is for  "extended functionality". Both targets should be appropriately used based on contexts.

**Comment by lukaschal** [comment]
Fixed as suggested.

**Comment by EbXpJ6bp** [comment]
Thank you! (#51 #52 #53 )
