### ISSUE TITLE
Escape character problem

### ISSUE THREAD

**Issue by sxyugao** [Microsoft/vscode-loc#55]
Issue Type: <b>Bug</b>

![](https://i.loli.net/2019/02/09/5c5e4b2137e00.png)

Extension version: 1.31.4
VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (3.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by lukaschal** [comment]
String is localized correctly according to source in a MLCP nad GitHub. 

https://github.com/Microsoft/vscode-loc/blob/9726190550e64767ae816dd3752b16605b8380a4/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json

**Comment by Joelism** [comment]
``&&`` here denotes a mnemonic, doesn't need escaping.
It' MCLP that needlessly escaped `&&`, making translators and machine translation confused.
After referring to original source, I added mnemonics and tweaked some translations here.

Source:
https://github.com/Microsoft/vscode-loc/blob/41463450f8dcdc3872182b3f8247b11c74106bfe/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L422-L423
Translation:
```json
			"miGotoNextProblem": "下一个问题(&&P)",
			"miGotoPreviousProblem": "上一个问题(&&P)"
```
Source:
https://github.com/Microsoft/vscode-loc/blob/41463450f8dcdc3872182b3f8247b11c74106bfe/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L1292
Translation:
```json
			"CreateDesktopIcon": "创建桌面图标(&&D)",
```
Source:
https://github.com/Microsoft/vscode-loc/blob/41463450f8dcdc3872182b3f8247b11c74106bfe/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L4014
Translation:
```json
			"miGotoLine": "转到行/列..."
```

**Comment by lukaschal** [comment]
Fixed in a MLCP.

下一个问题(&amp;&amp;P)
以前的问题(&amp;&amp;P)
创建桌面图标(&amp;&amp;D)

**Comment by sxyugao** [comment]
> Fixed in a MLCP.
> 
> 下一个问题(&&P)
> 以前的问题(&&P)
> 创建桌面图标(&&D)

So what about the problem in the picture?

**Comment by Joelism** [comment]
SRC:
https://github.com/Microsoft/vscode-loc/blob/41463450f8dcdc3872182b3f8247b11c74106bfe/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L4014
NEW:
`"miGotoLine": "转到行/列(&&L)..."`

@lukaschal This one is not mentioned in your comment.

Additionally, 
https://github.com/Microsoft/vscode-loc/blob/41463450f8dcdc3872182b3f8247b11c74106bfe/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L423
should be translated to `上一个问题(&&P)` instead of `以前的问题(&&P)` which is mistranslated in its context.

**Comment by lukaschal** [comment]
On review.

miGotoPreviousProblem	

SRC: Previous &amp;&amp;Problem
TGT: 以前的问题(&amp;&amp;P)

**Comment by lukaschal** [comment]
Fixed as suggested in a MLCP.

SRC: Previous &&Problem
New TGT: 上一个问题(&amp;&amp;P)

**Comment by lukaschal** [comment]
@Joelism Please verify and close.
