### ISSUE TITLE
[zh-hans] should not translate icon name

### ISSUE THREAD

**Issue by NateScarlet** [microsoft/vscode-loc#557]
https://github.com/microsoft/vscode-loc/blob/46ccbc6cd48e4acf49e2348bfabb3a13d3442c84/i18n/vscode-language-pack-zh-hans/translations/extensions/git.i18n.json#L252-L254

![image](https://user-images.githubusercontent.com/21083014/140700971-d61f3096-7a70-435e-8e1f-cd69d4066a6e.png)

`$(云上传)` should be `$(cloud-upload)`
`$(同步)` should be `$(sync)`

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 514442)
