### ISSUE TITLE
插件本地化不支持吗？很多常用都GIT都插件都是英文的

### ISSUE THREAD

**Issue by pgy866** [microsoft/vscode-loc#558]
插件本地化不支持吗？很多常用都GIT都插件都是英文的

**Comment by crsuzukimsft** [comment]
Could you please explain in English?

**Comment by csigs** [comment]
{ body = Resolved as Assigned to External. }Investigated by Loc Team: It's not a translation issue. (Reference id: 515099)

**Comment by danyeh** [comment]
The repo is dealing with localization of strings made localizable from vscode repo.
For inquire or request to support localization of individual extension, need to file inquire or request in corresponding repo hosts the extension.
You can search unique string from extension UI to identify corresponding repo.

**Comment by yaoying-translation2** [comment]
> 该存储库正在处理从 vscode 存储库本地化的字符串的本地化。 对于支持单个扩展本地化的查询或请求，需要在相应的 repo 托管扩展中提交查询或请求。 您可以从扩展 UI 中搜索唯一字符串以识别相应的 repo。

你好，我想尝试 在LINUX 中 尝试 翻译UI，可是我却并没有在本仓库的翻译源中找到要翻译的文本
是否可以提供一些，翻译本地化的文档呢？我应该如何做呢？
![截图_选择区域_20211112144751](https://user-images.githubusercontent.com/94032968/141429715-d12980d2-a3b6-4403-b94a-6340e6f1fbfa.png)

**Comment by yaoying-translation1** [comment]
https://github.com/Axosoft/vscode-gitlens/issues/577

**Comment by danyeh** [comment]
Yes, that is official approach.
1. string code: https://github.com/microsoft/vscode-extension-samples/blob/main/i18n-sample/src/command/sayBye.ts#L11
2. loc resource file: https://github.com/microsoft/vscode-extension-samples/blob/main/i18n-sample/i18n/jpn/out/command/sayBye.i18n.json

To get localized json, one option is to extract to xlf. localize xlf, import to loc json.
Sample code from a live extension:
https://github.com/microsoft/vscode-cpptools/blob/main/Extension/gulpfile.js#L239
https://github.com/microsoft/vscode-cpptools/blob/main/Extension/gulpfile.js#L286
