### ISSUE TITLE
translation suggestion

### ISSUE THREAD

**Issue by zwuis** [microsoft/vscode-loc#56]
https://github.com/Microsoft/vscode-loc/blob/41463450f8dcdc3872182b3f8247b11c74106bfe/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L723

Maybe it's better:
```json
"indentUsingTabs": "使用 \"Tab\" 缩进",
```

**Comment by zwuis** [comment]
https://github.com/Microsoft/vscode-loc/blob/41463450f8dcdc3872182b3f8247b11c74106bfe/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L790

```json
"incompatible": "无法安装扩展名'{0}'，因为它不兼容 VS Code '{1}'。",
```

**Comment by zwuis** [comment]
https://github.com/Microsoft/vscode-loc/blob/41463450f8dcdc3872182b3f8247b11c74106bfe/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L791

```json
"restartCode": "请重新安装{0}之前重新启动 VS Code。",
```

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
Fixed.

SRC:	Please restart VS Code before reinstalling {0}.
Correct TGT:	请在重新安装{0}之前重新启动 VS Code。

SRC:	Unable to install extension '{0}' as it is not compatible with VS Code '{1}'.
Correct TGT:	无法安装扩展名'{0}'，因为它不兼容 VS Code '{1}'。

SRC:	Indent Using Tabs
TGT:	使用 "Tab" 缩进

**Comment by zwuis** [comment]
https://github.com/Microsoft/vscode-loc/blob/de4779977246828feb2ee0561f21e8a3b21cf5fc/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L2581

```
"launch": "全局调试启动配置。应当作为跨工作区共享的 \"launch.json\" 的替代方法。",
```

**Comment by zwuis** [comment]
https://github.com/Microsoft/vscode-loc/blob/de4779977246828feb2ee0561f21e8a3b21cf5fc/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L2884

```
"expression": "表达式",
```

**Comment by lukaschal** [comment]
Fixed as suggested in a MLCP.

"launch": "全局调试启动配置。应当作为跨工作区共享的 \"launch.json\" 的替代方法。",

**Comment by lukaschal** [comment]
Fixed as suggested in a MLCP.

"expression": "表达式",

**Comment by zwuis** [comment]
https://github.com/Microsoft/vscode-loc/blob/8a64ae3be724f9554e110f42a961d75fe7cfc68b/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L3067
```
"workspaceRecommended": "有对于此工作区的扩展建议。",
```
<HR>

https://github.com/Microsoft/vscode-loc/blob/8a64ae3be724f9554e110f42a961d75fe7cfc68b/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L3224
```
"publisher": "发布者",
```
<HR>

https://github.com/Microsoft/vscode-loc/blob/8a64ae3be724f9554e110f42a961d75fe7cfc68b/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L3318
```
"selectAndStartDebug": "停止分析。"
```
<HR>

https://github.com/Microsoft/vscode-loc/blob/8a64ae3be724f9554e110f42a961d75fe7cfc68b/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L3432
```
"eol.auto": "使用该操作系统使用的行末字符。",
```
<HR>

https://github.com/Microsoft/vscode-loc/blob/8a64ae3be724f9554e110f42a961d75fe7cfc68b/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L3453
```
"formatOnSave": "在保存时格式化文件。格式化程序必须可用，延迟后文件不能保存，并且编辑器不能关闭。",
```
<HR>

https://github.com/Microsoft/vscode-loc/blob/8a64ae3be724f9554e110f42a961d75fe7cfc68b/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L3457
```
"autoReveal": "控制资源管理器是否在打开文件时自动显示并选择。",
```
<HR>

https://github.com/Microsoft/vscode-loc/blob/8a64ae3be724f9554e110f42a961d75fe7cfc68b/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L3458
```
"enableDragAndDrop": "控制资源管理器是否允许通过拖放移动文件和文件夹。",
```
<HR>

https://github.com/Microsoft/vscode-loc/blob/8a64ae3be724f9554e110f42a961d75fe7cfc68b/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L3628
```
"install.formatter": "安装格式化程序..."
```
<HR>

https://github.com/Microsoft/vscode-loc/blob/8a64ae3be724f9554e110f42a961d75fe7cfc68b/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L3647
```
"activateLanguagePack": "为了将 VS Code 的显示语言更换为 {0}，需要重新启动 VS Code 。",
```
<HR>

https://github.com/Microsoft/vscode-loc/blob/8a64ae3be724f9554e110f42a961d75fe7cfc68b/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L3717
```
"problems.view.focus.label": "聚焦到问题 (错误、警告、信息) 视图",
```
<HR>

https://github.com/Microsoft/vscode-loc/blob/8a64ae3be724f9554e110f42a961d75fe7cfc68b/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L3719
```
"problems.panel.configuration.autoreveal": "在打开文件时，控制是否在问题视图中对其进行定位。",
```
<HR>

https://github.com/Microsoft/vscode-loc/blob/8a64ae3be724f9554e110f42a961d75fe7cfc68b/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L3939
```
"emptyUserSettingsHeader": "将设置放在此处以覆盖默认设置。",
```
<HR>

https://github.com/Microsoft/vscode-loc/blob/8a64ae3be724f9554e110f42a961d75fe7cfc68b/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L3940
```
"emptyWorkspaceSettingsHeader": "将设置放在此处以覆盖用户设置。",
```
<HR>

https://github.com/Microsoft/vscode-loc/blob/8a64ae3be724f9554e110f42a961d75fe7cfc68b/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L3941
```
"emptyFolderSettingsHeader": "将文件夹设置放在此处以覆盖工作区设置。",
```

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
Fixed as suggested in a MLCP platform.

**Comment by kingphoenix2000** [comment]
[https://github.com/Microsoft/vscode-loc/blob/8a64ae3be724f9554e110f42a961d75fe7cfc68b/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L4148](https://github.com/Microsoft/vscode-loc/blob/8a64ae3be724f9554e110f42a961d75fe7cfc68b/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L4148)

"miGotoNextChange": "下一个更新(&&C)",

should be :

"miGotoNextChange": "下一个更改(&&C)",

and line 6826  ,the same problem 

更新 should be 更改

**Comment by zwuis** [comment]
Explanation of the last comment:

https://github.com/Microsoft/vscode-loc/blob/373fec463c88f44baa7fd0c879a916b05da9bb69/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L4307
```
"miGotoNextChange": "下一个更改(&&C)",
```
<HR>
@kingphoenix2000 where is Line 6837?

**Comment by zwuis** [comment]
https://github.com/Microsoft/vscode-loc/blob/373fec463c88f44baa7fd0c879a916b05da9bb69/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L3075
```
"debugServer": "仅用于调试扩展开发: 如果已指定端口，VS Code 会尝试连接到在服务器模式中运行的调试适配器",
```
<HR>

https://github.com/Microsoft/vscode-loc/blob/373fec463c88f44baa7fd0c879a916b05da9bb69/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L4755
```
"JsonSchema.tasks.promptOnClose": "当 VS Code 与运行的任务一起关闭时是否提示用户。",
```
<HR>

https://github.com/Microsoft/vscode-loc/blob/373fec463c88f44baa7fd0c879a916b05da9bb69/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L4788
```
"JsonSchema.tasks.promptOnClose": "当 VS Code 与运行的任务一起关闭时是否提示用户。",
```
<HR>

https://github.com/Microsoft/vscode-loc/blob/373fec463c88f44baa7fd0c879a916b05da9bb69/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L4797
```
"JsonSchema.promptOnClose": "在具有正在运行的后台任务的情况下关闭 VS Code 时是否提示用户。",
```

**Comment by kingphoenix2000** [comment]
> planation of the last comm

I mean there are 2  "miGotoNextChange"  items, they all should be "下一个更改(&&C)",you can search the whole json file.
[https://github.com/Microsoft/vscode-loc/blob/8a64ae3be724f9554e110f42a961d75fe7cfc68b/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L6837](https://github.com/Microsoft/vscode-loc/blob/8a64ae3be724f9554e110f42a961d75fe7cfc68b/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L6837)

**Comment by KaMingChung** [comment]
https://github.com/microsoft/vscode-loc/blob/release/1.33/i18n/vscode-language-pack-zh-hans/translations/extensions/git.i18n.json#L198
`"create branch from": "$(plus) 创建新的分支机构...",`
↓
`"create branch from": "$(plus) 从现有来源创建新的分支...",`

**Comment by lukaschal** [comment]
Fixed.

ENU: Next &amp;&amp;Change
CHS: 下一个更改(&amp;&amp;C)

**Comment by linsui** [comment]
https://github.com/microsoft/vscode-loc/blob/94a7bfabcf0239d89aa9879fb7964670b483b953/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L62-L63

```json
"disable filter on type": "禁用输入时筛选",
"enable filter on type": "启用输入时筛选",
```

**Comment by zwuis** [comment]
@lukaschal 
@janbaltus 
Please fix it.

**Comment by lukaschal** [comment]
Fixed as suggested in a MLCP.

**Comment by zwuis** [comment]
https://github.com/microsoft/vscode-loc/blob/782f8135997bfcc259ed3d2c5f44b939fee76a84/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L310

Maybe it's better:

```"suggest.filtered": "控制是否应从智能感知中筛选某些建议类型。建议类型的列表可以在这里找到： https://code.visualstudio.com/docs/editor/intellisense#_types-of-completions 。",```
<HR>

https://github.com/microsoft/vscode-loc/blob/782f8135997bfcc259ed3d2c5f44b939fee76a84/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L3600
```"trimTrailingWhitespace": "启用后，将在保存文件时删除文件末尾的空格。",```
<HR>

https://github.com/microsoft/vscode-loc/blob/782f8135997bfcc259ed3d2c5f44b939fee76a84/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L1004
```"automatic keyboard navigation setting": "控制列表和树中的键盘导航是否仅通过键入自动触发。如果设置为 `false` ，键盘导航只在执行 `list.toggleKeyboardNavigation` 命令时触发，您可以为该命令指定键盘快捷方式。"```

**Comment by lukaschal** [comment]
Fixed as suggested in a MLCP.

**Comment by zwuis** [comment]
https://github.com/microsoft/vscode-loc/blob/6decd82c847851424577e945a40f9ea93f72b886/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L1739-L1751
```
"activeEditorShort": "`\${activeEditorShort}`: 文件名 (例如 myFile.txt)。", 
"activeEditorMedium": "`\${activeEditorMedium}`: 相对于工作区文件夹的文件路径 (例如 myFolder/myFileFolder/myFile.txt)。", 
"activeEditorLong": "`\${activeEditorLong}`: 文件的完整路径 (例如 /Users/Development/myFolder/myFileFolder/myFile.txt)。", 
"activeFolderShort": "`\${activeFolderShort}`: 文件所在的文件夹名称 (例如 myFileFolder)。", 
"activeFolderMedium": "`\${activeFolderMedium}`: 相对于工作区文件夹的、包含文件的文件夹的路径 (例如 myFolder/myFileFolder)。", 
"activeFolderLong": "`\${activeFolderLong}`: 文件所在文件夹的完整路径 (例如 /Users/Development/myFolder/myFileFolder)。", 
"folderName": "`\${folderName}`: 文件所在工作区文件夹的名称 (例如 myFolder)。", 
"folderPath": "`\${folderpath}`: 文件所在工作区文件夹的路径 (例如 /Users/Development/myFolder)。", 
"rootName": "`\${rootName}`: 工作区的名称 (例如 myFolder 或 myWorkspace)。", 
"rootPath": "`\${rootPath}`: 工作区的文件路径 (例如 /Users/Development/myWorkspace)。", 
"appName": "`\${appName}`: 例如 VS Code。", 
"dirty": "`\${dirty}`: 表示活动编辑器为脏的脏指示器。", 
"separator": "`\${separator}`: 一种条件分隔符 (\"-\"), 仅在被包含值或静态文本的变量包围时显示。", 
```

**Comment by zwuis** [comment]
https://github.com/microsoft/vscode-loc/blob/6decd82c847851424577e945a40f9ea93f72b886/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L2836
```
"launch": "全局调试启动配置。应当作为跨工作区共享的 \"launch.json\" 的替代方法。",
```

**Comment by zwuis** [comment]
https://github.com/microsoft/vscode-loc/blob/6decd82c847851424577e945a40f9ea93f72b886/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L4427
```
"remote.extensionKind": "覆盖扩展的类型。`ui` 扩展在本地计算机上安装和运行，而 `workspace` 扩展则在远程计算机上运行。通过使用此设置重写扩展的默认类型，可指定是否应在本地或远程安装和启用该扩展。",
```

**Comment by zwuis** [comment]
https://github.com/microsoft/vscode-loc/blob/6decd82c847851424577e945a40f9ea93f72b886/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L840
```
"proxy": "要使用的代理设置。如果未设置，则将从 `http_proxy` 和 `https_proxy` 环境变量中继承。",
```
<HR>

https://github.com/microsoft/vscode-loc/blob/6decd82c847851424577e945a40f9ea93f72b886/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L842
```
"proxyAuthorization": "要作为每个网络请求的 `Proxy-Authorization` 标头发送的值。",
```

**Comment by zwuis** [comment]
@lukaschal

**Comment by lukaschal** [comment]
Correct in a MLCP, but incorrect in a json file.

**Comment by janbaltus** [comment]
To escape "  by \" is  correct. This is the only way how to escape double quote.
Format of json is "resource id": "string"

I am also closing this issue.
