### ISSUE TITLE
[ja] translation suggestion

### ISSUE THREAD

**Issue by m0sh1dawa** [microsoft/vscode-loc#561]
The following are some japanese translation suggestions.
"拡大" -> "ズームイン" or "ズームアウト" -> "縮小"
https://github.com/microsoft/vscode-loc/blob/80be8adc469bcac3cbd80805e8b98109e973c7de/i18n/vscode-language-pack-ja/translations/main.i18n.json#L3665-L3666

I think it is easier to understand if the notation is unified in kanji or katakana.

![image](https://user-images.githubusercontent.com/37267539/141079884-e586861f-12c5-4cfd-b6c0-8915fbc1bff8.png)

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 515952)
