### ISSUE TITLE
转到行列翻译出现字符&amp;

### ISSUE THREAD

**Issue by initialdmg** [Microsoft/vscode-loc#58]
Issue Type: <b>Bug</b>

菜单：
转到 -> 转到`&amp;&amp;`行/列...

Extension version: 1.31.4
VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 6.1.7601

**Comment by initialdmg** [comment]
https://github.com/Microsoft/vscode-loc/blob/41463450f8dcdc3872182b3f8247b11c74106bfe/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L4014

```
"miGotoLine": "转到＆amp;＆amp; 行/列 ..."
```
 应该是这里

**Comment by lukaschal** [comment]
@initialdmg  Localized this way in a MLCP. Is it correct ?

SRC:	Go to &&Line/Column...
TGT:	转到行/列(&amp;&amp;L)...

**Comment by initialdmg** [comment]
![default](https://user-images.githubusercontent.com/22365060/52922573-0a579d80-335d-11e9-986a-7b5b7381ed3d.png)

Yes! :+1:
