### ISSUE TITLE
ko: Translation suggestion

### ISSUE THREAD

**Issue by dudlf** [microsoft/vscode-loc#583]
### i18n key: main.i18n.json > importKeyboardShortcutsFroms

**English**
```plaintext
Migrate Keyboard Shorcuts from...
```

**Current Korean**

```json
"importKeyboardShortcutsFroms": "바로 가기 키를 마이그레이션하는 중..."
```

**Suggestion**

```json
"importKeyboardShortcutsFroms": "바로 가기 키 불러오기"
```

'바로 가기 키를 마이그레이션하는 중...' means 'Migrating shortcuts...' in english, not 'Migrate Keyboard Shorcuts from...'

![importKeyboardShortcutsFroms_en](https://user-images.githubusercontent.com/26514232/142870145-181c805a-cfb6-42dc-85bf-2c1dfdc6c4b9.png)
![importKeyboardShortcutsFroms_kr](https://user-images.githubusercontent.com/26514232/142870175-418690cc-73d7-4a05-be3b-b2c25a550201.png)

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 523372)
