### ISSUE TITLE
MLCP localization problem

### ISSUE THREAD

**Issue by qcz** [Microsoft/vscode-loc#61]
I've tried to continue to localize VS Code to Hungarian on the new MLCP site. I got over the fact that this platform is sub par in every possible aspect as a localization tool compared to Transifex: no easy way to view already localized strings, search for text and expressions in the full localized and non-localized sources, no sub groups, no information about who the translation comes from, and no information about which source file this text comes from exactly (which helped me many times when it was not clear what the expression exactly meant from the entry itself). These in themselves makes localization hard, and "community" localization more harder. It looks like that translating JSON files would be more productive than using the site itself 😞.

However the current problem I face looks like a full showstopper. It seems that I cannot add a suggestion to a text which already has a suggestion:
![firefox_2019-02-15_15-17-47](https://user-images.githubusercontent.com/304384/52862545-cb93ce80-3135-11e9-9292-723aac090d7e.png)
When I try to add it, a suggestion the button is disabled. Only one suggestion is allowed per entry? If so, I cannot continue to localize VS Code as the Hungarian language is full of sub par and wrong suggestions. (For example the entry in the screenshot makes no sense and does not use the already established translation for Activity Bar used everywhere.) Asking to remove every suggestion via GitHub issues would be very time consuming and it would remove the joy of the translation ifself...

**Comment by qcz** [comment]
@janbaltus, @shawndon: The radio silence is worrying. Should I just translate JSON files and send PRs or should I forget any meaningful localization?

**Comment by janbaltus** [comment]
Please do not translate json directly. It would be overwritten by MLCP next export.
For Tool Feedback @shawndon please.

**Comment by janbaltus** [comment]
regarding the Suggestion to add it is possible and I tried just now to add third suggestion to string.
In some browsers submit button do not work correctly please try Ctrl+Right arrow for submit.
If you still face this issue please make a screenshot of error message from the top of the page.

**Comment by shawndon** [comment]
@qcz  Thank you very much for your feedback on the MLCP service. Some of the points you mention have already raised internally, but getting this feedback from the actual users helps to validate the usage scenarios and the asks. We will log these requests and issues, which will be prioritized by our developer/engineering team.

This migration cannot be reverted, but we hope it will not be completely blocking. While we improve MLCP (thanks to customer feedback), stay tuned for further developments on this and thank you again for your support to the Visual Studio community.
