### ISSUE TITLE
"Copy as" has been mistranslated in Japanese

### ISSUE THREAD

**Issue by mandel59** [microsoft/vscode-loc#618]
https://github.com/microsoft/vscode-loc/blob/7bcc9f645e49f612c05ffeff476462c154ee1e41/i18n/vscode-language-pack-ja/translations/main.i18n.json#L679

"Save as" is translated as "名前を付けて保存", which literally means "Name and save", and it's ok. On the other hand, "Copy as" doesn't let you name, so "名前を付けてコピー" ("Name and copy") doesn't make sense.

**Comment by mandel59** [comment]
Japanese phrase "名前を付ける" (literally "attach a name") could only be used to name an anonymous object.
"To specify something" is "指定する".
"形式を指定してコピー" is more appropriate translation for "Copy as".

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 529523)
