### ISSUE TITLE
[ITALIAN] "Open folder" and "Add folder" buttons in left pane are broken if there is an open file

### ISSUE THREAD

**Issue by ayesse** [microsoft/vscode-loc#619]
![image](https://user-images.githubusercontent.com/24982281/145492737-bc1087c3-6ec6-450d-b2cf-11c30600bb87.png)

**Comment by LeandroAlberti** [comment]
This also happens with the Portuguese language:

![image](https://user-images.githubusercontent.com/85653163/145575009-4a9f080d-d292-46e2-b970-0902e4ecf3b4.png)

**Comment by LeandroAlberti** [comment]
> This also happens with the Portuguese (Brazil) language:

And if there is nothing open in the tabs area, some excerpts are not translated: 

![image](https://user-images.githubusercontent.com/85653163/145575768-87a68131-c15e-406f-98de-1bcbe52ad87f.png)

**Comment by cristianosuzuki77** [comment]
Could you narrow down to the file that is exposed for localization? I located these files where the resource 'Open Folder' and 'Add Folder' are present and I do see Italian translations there.

Open Folder:
https://github.com/microsoft/vscode-loc-drop/blob/main/loc/it/src/vscode-workbench/vs_workbench_contrib_watermark.xlf.lcl
https://github.com/microsoft/vscode-loc-drop/blob/main/loc/it/src/vscode-workbench/vs_workbench_contrib_search.xlf.lcl
https://github.com/microsoft/vscode-loc-drop/blob/main/loc/it/src/vscode-workbench/vs_workbench_services_dialogs.xlf.lcl
https://github.com/microsoft/vscode-loc-drop/blob/main/loc/it/src/vscode-editor/vs_platform.xlf.lcl
https://github.com/microsoft/vscode-loc-drop/blob/main/loc/it/src/vscode-workbench/vs_workbench_contrib_welcome.xlf.lcl


Add Folder:
https://github.com/microsoft/vscode-loc-drop/blob/main/loc/it/src/vscode-workbench/vs_workbench_contrib_workspace.xlf.lcl

**Comment by cristianosuzuki77** [comment]
Tyler, could you assist on this issue?
The resource is translated, but it doesn't work as expected in runtime.
The repro happens as well as follow:
1. Start VS in English without any file open.
2. Open 'Explorer'
3.  You will see the screenshot below:
![image](https://user-images.githubusercontent.com/18152472/155762546-20c17a1e-bbab-42ec-8bce-dfbed0e84f2d.png)
4. Install pt-BR language package.
5. Restart VS
6. Open 'Explorer' again.
7. You will see the below:
![image](https://user-images.githubusercontent.com/18152472/155762698-d1324fbc-02f7-4b26-947c-776397dbc85b.png)

Doesn't repro for Japanese.

**Comment by TylerLeonhardt** [comment]
@cristianosuzuki77 this is the fault of the translator. We include a comment that says:
https://github.com/microsoft/vscode/blob/b15eb66b6cef2a06c361f297504cdf5905ac34cc/src/vs/workbench/contrib/files/browser/explorerViewlet.ts#L294-L322

> Please do not translate the word "command", it is part of our internal syntax which must not change

Additionally, the translator is adding characters in between the `[...]` and `(...)` which causes this to break.

I have been meaning to add that syntax that helps enforce this, but haven't gotten time for it.

**Comment by TylerLeonhardt** [comment]
Actually @JacksonKearl made a change to make sure this doesn't happen again. It should be available in [VS Code Insiders](https://code.visualstudio.com/insiders) already and will be in Stable next week.
