### ISSUE TITLE
[ja] "no open repo" is mistranslated into "ソース管理プロバイダーが登録されていません。"

### ISSUE THREAD

**Issue by satoushina** [Microsoft/vscode-loc#62]
The following strings should be "フォルダーやワークスペースが開かれていません。"
https://github.com/Microsoft/vscode-loc/blob/41463450f8dcdc3872182b3f8247b11c74106bfe/i18n/vscode-language-pack-ja/translations/main.i18n.json#L4109

Original: "ソース管理プロバイダーが登録されていません。" means that "Any Prividers are registered".
Proposal: "フォルダーやワークスペースが開かれていません。" means that "No Folders or workspaces hasn't opened yet".

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
It seems ResourceID "no open repo" is confusing in this case. Source for translation "ソース管理プロバイダーが登録されていません。" is "No source control providers registered." so it is correct.

**Comment by lukaschal** [comment]
@satoushina Please confirm translation of sentence "No source control providers registered." is correct and close this issue.

**Comment by satoushina** [comment]
Thank you. I confused. In this case, translation is correct.
This massage is now displayed when both no folders opened and a folder is not initialized yet.
In case when
1-- a folder is not initialized yet    then shown this massage    "Ok,

**Comment by satoushina** [comment]
Thank you. I confused. In this case, the translation is correct.
This massage is now displayed when both no folders opened and a folder is not initialized yet.
In case when
1-- a folder is not initialized yet -- then shown this massage -- "Ok, I'll register(initialize) and creat repo."
2-- no folders opened               -- then shown this massage -- "What could I do???"
I dropped into 2nd case. Thank you for your comment and taking your time.
