### ISSUE TITLE
【Chinese (Simplified)】合并冲突，没有翻译

### ISSUE THREAD

**Issue by jiansite** [microsoft/vscode-loc#620]
低版本正常，升级之后就显示英文了；不知道是兼容性问题还是其他插件影响的，显示如下
![image](https://user-images.githubusercontent.com/33872552/145666603-a3df1cee-bfac-4dfe-8a50-6e0d8853364c.png)
系统及其版本如下
![image](https://user-images.githubusercontent.com/33872552/145666779-c40dcdaf-97f0-4f8b-8b41-214b1c9c9d6b.png)
![image](https://user-images.githubusercontent.com/33872552/145666590-70cb06fb-10cf-4e0f-b35f-5fbdd0f749e8.png)
![image](https://user-images.githubusercontent.com/33872552/145666618-eee48c26-8600-4133-ad94-f2d2f965627c.png)

其他插件如下
![image](https://user-images.githubusercontent.com/33872552/145666701-f57c8023-5196-4cb8-90d7-50166a97107a.png)

**Comment by cristianosuzuki77** [comment]
Hi,
Is this still repro?

**Comment by Jeggery** [comment]
我也遇到了同样的问题，希望官方能够改进

**Comment by TylerLeonhardt** [comment]
This is good now 
![image](https://user-images.githubusercontent.com/2644648/206818587-ac473db7-38de-4163-b99e-98b0f6b8a862.png)

**Comment by Jeggery** [comment]
> 后就显示英文了；不知道是包容性问题还是其他插件影响的，显示如下 系统及其他

Unfortunately, this plug-in library has not been updated
[https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-zh-hans](url)

**Comment by Jeggery** [comment]
@TylerLeonhardt My vscode version is 1.62.3

**Comment by Jeggery** [comment]
@TylerLeonhardt Can't this plugin library be updated separately? Or must it be bound to the vscode version

**Comment by TylerLeonhardt** [comment]
For language packs, you need to have the version of vscode that matches the version of the language pack.

Since you have 1.62, you will need the 1.62 version of the language pack. VS Code is smart enough to install the correct version of the language pack, but do keep in mind that those older versions will not be updated.
