### ISSUE TITLE
[zh-hans] should not translate icon name (again)

### ISSUE THREAD

**Issue by NateScarlet** [microsoft/vscode-loc#621]
https://github.com/microsoft/vscode-loc/blob/2011a39f3b43559ba05ab68d85307c000e4cea63/i18n/vscode-language-pack-zh-hans/translations/extensions/git.i18n.json#L241-L243

same as #557

![image](https://user-images.githubusercontent.com/21083014/145765258-1e190932-d114-462e-bd9d-8471d8f0e583.png)

`$(云上传)` should be `$(cloud-upload)`
`$(同步)` should be `$(sync)`

**Comment by tim4431** [comment]
Yes！I find this bug annoying

**Comment by heartacker** [comment]
![image](https://user-images.githubusercontent.com/1876302/146899368-bc3c7882-aee2-416d-9eed-7c17fcf57ff5.png)

$(xxxx) 一般都是应用icon。翻译团队不要对这样的文字进行翻译

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 531929)
