### ISSUE TITLE
[pt-br] "Language" being translated as "idioma" instead of "linguagem" 

### ISSUE THREAD

**Issue by SheepRock** [microsoft/vscode-loc#622]
When talking about a programming language, you say "linguagem" in portuguese, but in VS Code pt-br translation, it is being translated as "idioma" in many places ("idioma" is only for languages like "portuguese", "english", "french" etc, not for programming languages).

![image](https://user-images.githubusercontent.com/20205505/145829619-690549ad-f95b-4288-b137-818c93b3faeb.png)

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 531930)
