### ISSUE TITLE
How to debug the translation(language pack)?

### ISSUE THREAD

**Issue by laubonghaudoi** [microsoft/vscode-loc#647]
We are [CanCLID](https://github.com/CanCLID) and currently [translating vscode into Cantonese](https://github.com/CanCLID/vscode-loc). As we are actively making progress, we want to load our translation into vscode so as to debug any error. What are the steps of doing this? Thank you!

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 535770)

**Comment by laubonghaudoi** [comment]
@csigs Hi but still, how do we debug the language pack that we are working on? Is there a doc for it?
