### ISSUE TITLE
[es] Unicode characters not displaying properly

### ISSUE THREAD

**Issue by d0vi** [Microsoft/vscode-loc#65]
Hi! I am using VSCode 1.31.1 and the Spanish Language Pack on Windows 10.

Some characters like `´` and `¿` are missing from this language pack version. Some screenshots:

![imagen](https://user-images.githubusercontent.com/24238283/53636107-5e953400-3c1f-11e9-81eb-e0a6bb810e15.png)

![imagen](https://user-images.githubusercontent.com/24238283/53636042-2db4ff00-3c1f-11e9-9c85-39b35c01ae9a.png)

**Comment by janbaltus** [comment]
This issue got fixed in LP 1.32.3.

**Comment by d0vi** [comment]
I am still sitting on v1.31.4, why does this LP doesn't update?

**Comment by janbaltus** [comment]
It is only for insiders build.

Please wait till next release for this fix unless you use insiders version of Vscode https://code.visualstudio.com/insiders/
