### ISSUE TITLE
Convert to tabs incorrectly translated to Polish

### ISSUE THREAD

**Issue by mbamac** [microsoft/vscode-loc#658]
"Convert indentation to tabs" is incorrectly translated to Polish:

Now is: "Konwertuj wcięcia na karty" 

Should be "Konwertuj wcięcia na tabulatory"

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 539266)
