### ISSUE TITLE
Support for community supported locale MN 

### ISSUE THREAD

**Issue by ulziibay** [Microsoft/vscode-loc#66]
https://envelope-community-staging.azurewebsites.net/ does not give any insight into how to create a new community-supported language pack. Specifically my questions are:

1. What is the requirement?
2. How to create a minimum language pack?
3. What support is expected from the community vs MS localization team?

Thank you.

**Comment by janbaltus** [comment]
Please see documentation https://github.com/Microsoft/Localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project
