### ISSUE TITLE
Use German word "Code Schnippsel" instead of "Benutzercodeausschnitte"

### ISSUE THREAD

**Issue by googol7** [microsoft/vscode-loc#671]
Change German translation "Ausschnitt" to "Schnippsel" and avoid words like "Benutzerausschnitte", "Benutzercodeausschnitte" or "Codeausschnittdatei"

**Comment by crsuzukimsft** [comment]
This is being tracked in an internal ticket, since it was initiated via a PR. The fixes will be returned within the 5 days SLA.

**Comment by csigs** [comment]
Resolved as Duplicate.
