### ISSUE TITLE
`detectThenRunAndDebug` link broken in Korean

### ISSUE THREAD

**Issue by alexkoala** [microsoft/vscode-loc#674]
> https://github.com/microsoft/vscode-loc/blob/5266beec64a2b72d1a2fb8114655830c66895156/i18n/vscode-language-pack-ko/translations/main.i18n.json#L4871

`command:{0}` is mistranslated to `명령:{0}`.

**Comment by alexkoala** [comment]
> Hello @alexkoala . Do you have a better suggestion for how 'command:{0}' should be translated?

`[모든 자동 디버그 구성을 표시합니다](command:{0}).`

**Comment by crsuzukimsft** [comment]
Thank you. There were actually more languages impacted with this overtranslation. And for Polish, the link breaks due to extra space. All of these are being fixed now.
