### ISSUE TITLE
Bad brazilian portuguese translation

### ISSUE THREAD

**Issue by fernandoval** [Microsoft/vscode-loc#69]
Multiple menu items with incomplete translation and double &

![image](https://user-images.githubusercontent.com/8930605/54327130-c8cab300-45e7-11e9-9409-bb9473f33a2e.png)

**Comment by ferrelll** [comment]
I'm having the exact same problem for some time. I've been using it without the localization since. It would be awesome to have this fixed!

**Comment by lukaschal** [comment]
All these erros are fixed in a MLCP platform now.
