### ISSUE TITLE
German: JSON examples in Remote settings are invalid

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode-loc#696]
JSON examples für German Remote settings are invalid:

![Remote settings translation invalid](https://user-images.githubusercontent.com/9283914/150843179-b7e77014-a682-43fe-ac1f-98abb839eedc.png)

1. Keywords have been translated
1. German quoting style has been applied

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 548626)
