### ISSUE TITLE
Wrong Translation

### ISSUE THREAD

**Issue by pata0202** [microsoft/vscode-loc#698]
Issue Type: <b>Bug</b>

the word "activate" is now translate as "激活"
but this is not the term used by Traditional Chinese users.
we use "啟動" instead of "激活"
hope you can fix this problem
thx

Extension version: 1.61.5
VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (3.91GB free)|
|Process Argv|--crash-reporter-id 2164d3ce-4368-487e-b27f-d2d7e834316a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30424896
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710:30416614
vsbas813:30426126
vsic-wlc-tsjs:30426436

```

</details>

**Comment by cristianosuzuki77** [comment]
@pata0202 Is this the sentence you refer too: 當VS Code啟動時激發該事件，為了確保最好的使用者體驗，當您的延伸模組沒有其他組合作業時,請激活此事件。

**Comment by pata0202** [comment]
@cristianosuzuki77
yes
in this case , use the word "啟用" is better than "激活"

**Comment by cristianosuzuki77** [comment]
Thank you. Asking for translation review and if needed, fix.

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 548789)
