### ISSUE TITLE
Typo in french translation

### ISSUE THREAD

**Issue by MawsFr** [microsoft/vscode-loc#699]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.1
- OS Version: MacOS Mojave 10.14.6

Steps to Reproduce:

1. Click on menu "Fichier"
2. See "Ouvrir **l'espacede** travail à partir du fichier". It should be "Ouvrir **l'espace de** travail à partir du fichier" so there must be a space between words "L'espace" and "de".

Related to this feature : https://code.visualstudio.com/updates/v1_61#_macos-file-menu-changes
And it doesn't seem to be wrong in the i18n file : https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-fr/translations/main.i18n.json#L1262

![image](https://user-images.githubusercontent.com/4595534/137469801-18c4bd57-49ae-43b4-b97e-5af83e94e13d.png)

**Comment by TylerLeonhardt** [comment]
FYI @crsuzukimsft @danyeh this issue was opened in the vscode repo initially. I used the `L10N` tag and @csigs but it didn't get a response. I just wanna double check that the vscode repo is also showing up in your queries?

**Comment by cristianosuzuki77** [comment]
It was bug it was not sync'd back. Let me update it.

**Comment by csigs** [comment]
Resolved as Duplicate.
