### ISSUE TITLE
Wrong translation on Japanese

### ISSUE THREAD

**Issue by t-hamano** [microsoft/vscode-loc#705]
There is a typo on alert dialog when VSCode is closed while a file is being deleted.

![vscode](https://user-images.githubusercontent.com/54422211/151550324-1ca2a553-12cb-4929-aa27-a734a138b0b6.jpg)

`閉じるしますか?`

to

`閉じますか?`

**Comment by cristianosuzuki77** [comment]
@t-hamano I'm not able to locate it as part of the core strings in vscode.
What is the exact English string for this translation? Is it coming from an extension by any chance?

**Comment by t-hamano** [comment]
I changed the VS Code language to default and reproduced the steps to display the message.


https://user-images.githubusercontent.com/54422211/151903023-0d3f1553-6587-47f9-b454-516c0dd252cc.mp4


The base text is "**Are you sure you want to close window?**".

I determined that it was generated from the VSCode language pack. Because my OS is Japanese, but since this message varies depending on the VS Code language setting,

**Comment by cristianosuzuki77** [comment]
Thank you. I am not familiar with the 'Test' project. Is this a plug-in for vscode?
If I do the same 'Delete' for a folder, I get a different text:
I am showing the version of the Japanese language package I am using.
![image](https://user-images.githubusercontent.com/18152472/155770126-5c3d41d0-161d-4349-a58e-28eaffbf98c2.png)
![image](https://user-images.githubusercontent.com/18152472/155770236-5f62b612-b09c-415c-ae74-bcb298cdc338.png)

**Comment by t-hamano** [comment]
Thanks for the reply.
What you need to check is not the message when deleting unsaved files.
It's the message you get when you try to quit VS Code while the deletion of a file or directory is in progress.

For example, install a huge package with npm, and then delete the node_modules folder on VS Code.
It will take some time for the entire node_modules folder to be deleted, so in the meantime, please try pressing the quit button on VS Code.

**Comment by crsuzukimsft** [comment]
Thanks for clarification.
@TylerLeonhardt This particular string "are you sure you want to close window?" is not being exposed to loc. Not sure if this is part of vs code or OS.

**Comment by t-hamano** [comment]
@cristianosuzuki77
@crsuzukimsft
@TylerLeonhardt

I found where this message is generated from.

`vscode` repo:
https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/bulkEdit/browser/bulkEditService.ts#L264-L268

`vscode-loc` repo:
https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-ja/translations/main.i18n.json#L4063-L4064

At the same time, we noticed that the wording of `changeWorkspace` is also unnatural.

For consistency, I think that the following changes would be necessary:

```json
"areYouSureQuiteBulkEdit": "{0}しますか? '{1}' が進行中です。",
"changeWorkspace": "ワークスペースの変更",
"closeTheWindow": "ウィンドウを閉じる",
```

to

```json
"areYouSureQuiteBulkEdit": "{0}ますか? '{1}' が進行中です。",
"changeWorkspace": "ワークスペースを変更し",
"closeTheWindow": "ウィンドウを閉じ",
```

Therefore, one of the following messages will be generated depending on the status:

- `ワークスペースを変更しますか? '{1}' が進行中です。`
- `ウィンドウを閉じますか? '{1}' が進行中です。`

**Comment by cristianosuzuki77** [comment]
Thank you. The placeholders helped.

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 550780)
