### ISSUE TITLE
"Join in Group" has been mistranslated in Japanese

### ISSUE THREAD

**Issue by DatchLive** [microsoft/vscode-loc#717]
https://github.com/microsoft/vscode-loc/blob/1c553470360e3aee1cbbed77b6883c5059461426/i18n/vscode-language-pack-ja/translations/main.i18n.json#L3114
https://github.com/microsoft/vscode-loc/blob/1c553470360e3aee1cbbed77b6883c5059461426/i18n/vscode-language-pack-ja/translations/main.i18n.json#L3132-L3133
The Japanese translation of "join in group" in the above 3 lines should be "グループ内統合".

`"グループに参加する"` → `"グループ内統合"`

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 553882)
