### ISSUE TITLE
[Italian] Bracket pair colorization says only square brackets are included

### ISSUE THREAD

**Issue by Balastrong** [microsoft/vscode-loc#718]
If I'm not mistaken is the key `bracketPairColorization.enabled`.

In English reads: 
> Controls whether bracket pair colorization is enabled or not. Use [...]

In Italian though, is:
> Controlla see la colorazione delle coppie di parentesi **_quadre_** è abilitata. Usare [...]

The word `quadre` should be removed as it means square.

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 554106)
