### ISSUE TITLE
Chinese (Simplified) (简体中文) Jupyter

### ISSUE THREAD

**Issue by ShiinaKaze** [microsoft/vscode-loc#721]
![QQ截图20220209175216](https://user-images.githubusercontent.com/89641145/153171767-c8d4260b-e7c2-4798-9e0c-77ff026058ad.jpg)
能否不要把Markdown翻译为标记。
Please do not translate Markdown to '标记'.

**Comment by cristianosuzuki77** [comment]
What is the equivalent in the UI in English?

**Comment by ShiinaKaze** [comment]
> What is the equivalent in the UI in English?

Thank you for your reply, I suggest translating it to 'Markdown', which means no translation is needed and it is more easily pronounced. As a foreign word on the internet, it is awkward to read it as a Chinese character, this is my personal opinion. ---- DeepL Translation

**Comment by cristianosuzuki77** [comment]
Thank you for the clarification. I understand that your request is that it doesn't be translated.
I am not seeing an English word 'Markdown' being translated as '标记', but I am seeing the English word 'Tags' being translated to 标记.

**Comment by ShiinaKaze** [comment]
> Thank you for the clarification. I understand that your request is that it doesn't be translated. I am not seeing an English word 'Markdown' being translated as '标记', but I am seeing the English word 'Tags' being translated to 标记.

Hello? I found it for you, at the red mark. Please change the '标记' to Markdown.Thank you XD

**Comment by crsuzukimsft** [comment]
Thank you. @ShiinaKaze The screenshot above is perfect. The fix will be back within 2 to 5 days.

**Comment by ShiinaKaze** [comment]
> Thank you. @ShiinaKaze The screenshot above is perfect. The fix will be back within 2 to 5 days.

Thank you so much.

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 556250)
