### ISSUE TITLE
Path file:///C:/ was converted to file:///C%3A/

### ISSUE THREAD

**Issue by pearwb1235** [microsoft/vscode-loc#727]
[Source Issue](https://github.com/gitkraken/vscode-gitlens/issues/1488#issuecomment-1036002645)

當在 Gitlens version v11.7.0 使用 Open Folder History 時安裝 "[Chinese (Traditional) Language Pack](https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-zh-hant)" 延伸模組，會導致查詢路徑 file:///C:/<path> 轉換成 file:///C%3A/

In Gitlens version: v11.7.0

When I install vscode recommend extension "[Chinese (Traditional) Language Pack](https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-zh-hant)".
Use GitLens "Open Folder History" path "file:///C:/<path>" was converted to "file:///C%3A/<path>" .
However uninstall "Chinese (Traditional) Language Pack" it will work.

(I am not good at English.)

**Comment by cristianosuzuki77** [comment]
@TylerLeonhardt doesn't seem to be translation issue. The same was logged in https://github.com/gitkraken/vscode-gitlens/issues/1488#issuecomment-1036002645 .  Let me know if you have more information about the possible translation error.

**Comment by TylerLeonhardt** [comment]
Looks like we can close this since @pearwb1235 commented in GitLens repo
