### ISSUE TITLE
Wrong french translation / "trustedHeaderFolder"

### ISSUE THREAD

**Issue by ach42** [microsoft/vscode-loc#730]
in https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-fr/translations/main.i18n.json

line 9768 "trustedHeaderFolder"

"Vous faites avez approuvé ce dossier"

Correct : 

"Vous avez approuvé ce dossier"

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 558610)
