### ISSUE TITLE
problemas de rendimiento

### ISSUE THREAD

**Issue by Juanito-boop** [microsoft/vscode-loc#733]
Issue Type: <b>Bug</b>

deshabilitar extension o eliminar 

Extension version: 1.64.6
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A9-9420 RADEON R5, 5 COMPUTE CORES 2C+3G    (2 x 2994)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.95GB (3.03GB free)|
|Process Argv|--crash-reporter-id 9338862a-aede-4928-a49d-aa27ead6a7e4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710cf:30416617
vsbas813:30436447
vscscmwlcmt:30438805
helixcf:30438807

```

</details>

**Comment by cristianosuzuki77** [comment]
@Juanito-boop could you explain the ticket? Is this a translation error?

**Comment by Juanito-boop** [comment]
> @Juanito-boop could you explain the ticket? Is this a translation error?

This extension, makes vscode slow

**Comment by csigs** [comment]
Resolved as Cant Reproduce.
