### ISSUE TITLE
not compatible with VS Code '1.32.3'

### ISSUE THREAD

**Issue by LMZ666** [microsoft/vscode-loc#74]

**Comment by opamine** [comment]
important

**Comment by opamine** [comment]
？？？？？？

**Comment by opamine** [comment]
没有人解决一下么

**Comment by errlot** [comment]
>要下载以前版本，可以通过api链接。但是需要知道语言包的版本号。一般情况下，语言包的最终版会以.2版本号结尾。可以试一下.3有没有，再试.2。例如现在Marketplace页面上的中文语言包官方版已经是1.28.2。要下载匹配上一版的最终版本，用这个链接：https://marketplace.visualstudio.com/_apis/public/gallery/publishers/MS-CEINTL/vsextensions/vscode-language-pack-zh-hans/1.27.2/vspackage

Via https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-zh-hans#review-details 

你可以下载 https://marketplace.visualstudio.com/_apis/public/gallery/publishers/MS-CEINTL/vsextensions/vscode-language-pack-zh-hans/1.32.2/vspackage

**Comment by MaximeLighter** [comment]
Working on VScode v1.33.1 with extension version 1.33.0.
Like @errlot say you can use api link, try https://marketplace.visualstudio.com/_apis/public/gallery/publishers/MS-CEINTL/vsextensions/vscode-language-pack-fr/1.33.0/vspackage

;)

**Comment by gumingqi** [comment]
Unable to install extension 'ms-ceintl.vscode-language-pack-zh-hans' as it is not compatible with VS Code '1.35.1'.

**Comment by weeteckt** [comment]
please re-open issue if you are still facing the same problem.
