### ISSUE TITLE
starange Chinese Simplified Title

### ISSUE THREAD

**Issue by GSRLW** [microsoft/vscode-loc#746]
this happened in V1.64.2
en：
<img width="251" alt="image" src="https://user-images.githubusercontent.com/35130268/155082725-27e37b0b-2ab2-4842-b433-b26878c25432.png">
no change
zh-hans in V 1.63.2：
![17154921278431415](https://user-images.githubusercontent.com/35130268/155082983-114a27d4-1654-4eba-9257-1531f6003dbf.png)

zh-hans in V 1.64.2：
<img width="263" alt="image" src="https://user-images.githubusercontent.com/35130268/155083415-86353787-43f8-4f06-9edd-546a66a73607.png">

“编辑进化”  -> "编辑已进化" 
so strange？
这个操作下次可以考虑来一个 “编辑超进化”，“编辑究极进化”，是不是在庆祝数码宝贝。^_^ 
只能说膜拜！

**Comment by LaoshuBaby** [comment]
Yes, I'm sure this will be very strange, maybe "编辑已进化" can be re-translated as ""

(But stupid MS stuff will not listen to you, and only closed your issue :> )

**Comment by LaoshuBaby** [comment]
There are a lot of mistake/unproper translation in VSC

For example, "Playground" -> "操场"

(it should be "训练场"/“练习场”)

![图片](https://user-images.githubusercontent.com/42690037/155139226-24599d7b-27f1-41af-bd04-03b68729ac90.png)

**Comment by GSRLW** [comment]
ok，I know .  thanks your answer .
