### ISSUE TITLE
Change "révéler" to "afficher" in French

### ISSUE THREAD

**Issue by orkeilius** [microsoft/vscode-loc#759]
# change "révéler" to "afficher"
## I reopen an issue similar to the pull #155 for the following reasons:
- "révéler" mean "disclose" not "display" in French so that weird to "disclose a file in explorer"
- the key "showInExplorer" literary mean "**afficher** dans l'explorateur"
- the German translation already use a word who mean "display" not "reveal" (anzeigen)

## what sould change :
- change "révéler" to "afficher"
- change "révélé" to "affiché"
- change "révélés" to "affichés"

You can see the changes here:
https://github.com/orkeilius/vscode-loc/commit/dc4e6aa23b898a809c3ba68d087f975ae9491f07

**Comment by csigs** [comment]
The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/564546.

**Comment by orkeilius** [comment]
Thanks
Could you please give me an update if this is accepted ?
I can't access to [ceapex.visualstudio.com](https://ceapex.visualstudio.com)

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 564546)
