### ISSUE TITLE
[ja] translation mistake

### ISSUE THREAD

**Issue by EbXpJ6bp** [Microsoft/vscode-loc#76]
https://github.com/Microsoft/vscode-loc/blob/6684a29cead0bd74692a759173441b0438682d02/i18n/vscode-language-pack-ja/translations/extensions/git.i18n.json#L245

無視してコミット

**Comment by lukaschal** [comment]
On review.

SRC: Commit Anyway
TGT: とにかくコミットする

**Comment by lukaschal** [comment]
Fixed as suggested in a MLCP platform.

**Comment by EbXpJ6bp** [comment]
Thank you!
