### ISSUE TITLE
Loc Clarification

### ISSUE THREAD

**Issue by cristianosuzuki77** [microsoft/vscode-loc#761]
For the file vscode-workbench/vs_workbench_contrib_files.xlf, could you explain and share an example of the placeholder below:

"Import {0} resources"

id is fileImportExport.importnFile

152821

**Comment by TylerLeonhardt** [comment]
Found here: https://github.com/microsoft/vscode/blob/05140e0831db7c67208de56e5edfc0ea6bc5f473/src/vs/workbench/contrib/files/browser/fileImportExport.ts#L540

I'm... not entirely sure. @bpaseo, loc folks would like some clarity here. Can you provide that?

**Comment by bpasero** [comment]
@JacksonKearl for explorer

**Comment by JacksonKearl** [comment]
Updated the source with comments. But the substitution will be the number of files that were imported, for instance `Import 5 resources`
