### ISSUE TITLE
[zh-hans] "select a language" translated to "select a programing language"

### ISSUE THREAD

**Issue by NateScarlet** [microsoft/vscode-loc#767]
I am pretty sure plain text is not a programming language,

so this should be `选择语言`:

https://github.com/microsoft/vscode-loc/blob/a55488f2f7163aaaaec63f05f160862141cd8b53/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L4352

`选择编程语言` is introduced by #468

**Comment by csigs** [comment]
The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/567621.

**Comment by cristianosuzuki77** [comment]
@TylerLeonhardt  FYI please consider adding comments in the resource explaining when 'language' refers to programming language and when it does not.
Addressing this issue.

**Comment by cristianosuzuki77** [comment]
@NateScarlet Thank you. This should be resolved within the next days.

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 567621)
