### ISSUE TITLE
[zh-hans] Inconsistent translation of "editingEvolved" caused by a code refactor

### ISSUE THREAD

**Issue by idawnlight** [microsoft/vscode-loc#769]
I noticed that in microsoft/vscode#141138 `.../welcome/gettingStarted/` is moved to `.../welcomeGettingStarted/`, and thus a new field called `.../welcomeGettingStarted/browser/gettingStarted` is generated instead of renaming the original `.../welcome/gettingStarted/browser/gettingStarted` field.

However, the new field is not the same as the previous one, although neither the key nor the context was changed. Originally "gettingStarted.editingEvolved" is translated to "编辑进化", while now it's translated to "编辑已进化" which sounds a bit strange since there is no need to emphasize "evolved".

I don't think it is intended behavior, as it loses consistency, and there are now two same fields translated differently.

https://github.com/microsoft/vscode-loc/blob/aa09576a04d4a42b27c9d3ac3b6da9486f39eb28/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L9233

https://github.com/microsoft/vscode-loc/blob/aa09576a04d4a42b27c9d3ac3b6da9486f39eb28/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L9466

**Comment by csigs** [comment]
The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/569089.

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 569089)
