### ISSUE TITLE
[ja] update syntax of mnemonic 

### ISSUE THREAD

**Issue by EbXpJ6bp** [microsoft/vscode-loc#77]
Can you replace with `\((&[\w])\)` ->`(&$1)`?

`(&[\w])` style seems no longer supported.

![4f4d3b66f5922a3afaae34a6ef8ab76a](https://user-images.githubusercontent.com/8474118/55079274-2f1efd80-50df-11e9-904d-4820b8450565.png)

**Comment by janbaltus** [comment]
We are implementing fix for this issue and fix will be present in 1.33 LP release.

**Comment by lukaschal** [comment]
Fixed in a MLCP platform now.

**Comment by EbXpJ6bp** [comment]
Some text remains:


https://github.com/Microsoft/vscode-loc/blob/94a7bfabcf0239d89aa9879fb7964670b483b953/i18n/vscode-language-pack-ja/translations/main.i18n.json#L2174

https://github.com/Microsoft/vscode-loc/blob/94a7bfabcf0239d89aa9879fb7964670b483b953/i18n/vscode-language-pack-ja/translations/main.i18n.json#L2469

https://github.com/Microsoft/vscode-loc/blob/94a7bfabcf0239d89aa9879fb7964670b483b953/i18n/vscode-language-pack-ja/translations/main.i18n.json#L5035

**Comment by lukaschal** [comment]
Fixed in a MLCP platform now.
