### ISSUE TITLE
Add noRecents ,openFolder, toStart field translation

### ISSUE THREAD

**Issue by liaohongxing** [microsoft/vscode-loc#771]
Due to a recent Fix PR, several fields need to be added 

https://github.com/microsoft/vscode/blob/45b4204501ac1f50b6231af3c996d35f86359ecd/src/vs/workbench/contrib/welcomeGettingStarted/browser/gettingStarted.ts#L878-L881

**Comment by csigs** [comment]
The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/570359.

**Comment by crsuzukimsft** [comment]
@TylerLeonhardt could you review this ask?

**Comment by csigs** [comment]
Resolved as .

**Comment by TylerLeonhardt** [comment]
Do you still need me to do something here?
