### ISSUE TITLE
Re : Change "révéler" to "afficher" in French

### ISSUE THREAD

**Issue by orkeilius** [microsoft/vscode-loc#772]
Sorry to said that,
but in #759 you have updated the "revealInMac" but forgot "revealInWindows" key

**Comment by orkeilius** [comment]
The update was made in the commit #763 
and the "revealInWindows" key should be "Afficher dans l'Explorateur de fichiers"

**Comment by csigs** [comment]
The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/570453.

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 570453)
