### ISSUE TITLE
[ja] translation suggestion

### ISSUE THREAD

**Issue by EbXpJ6bp** [microsoft/vscode-loc#78]
https://github.com/Microsoft/vscode-loc/blob/22cde702f37dbee8b82adb6200e1047091a417e4/i18n/vscode-language-pack-ja/translations/main.i18n.json#L457

```
前の問題箇所(&&P)
```

---

|before|after|
|---|---|
|![ccd77ad6fa0a513000048141cb064c63](https://user-images.githubusercontent.com/8474118/55270551-6a8a1980-52e3-11e9-9c9c-b566e61cb8d6.png)|![ba398ec6cd6d81197d70b5aa0fb277ad](https://user-images.githubusercontent.com/8474118/55270556-7544ae80-52e3-11e9-9519-ce6f3ba82859.png)|

https://github.com/Microsoft/vscode-loc/blob/22cde702f37dbee8b82adb6200e1047091a417e4/i18n/vscode-language-pack-ja/translations/main.i18n.json#L3396
```
フィードバックをつぶやく。
```

https://github.com/Microsoft/vscode-loc/blob/22cde702f37dbee8b82adb6200e1047091a417e4/i18n/vscode-language-pack-ja/translations/main.i18n.json#L3408
```
ステータスバーにフィードバック笑顔文字を表示
```

https://github.com/Microsoft/vscode-loc/blob/22cde702f37dbee8b82adb6200e1047091a417e4/i18n/vscode-language-pack-ja/translations/main.i18n.json#L3409
```
ツイート
```

https://github.com/Microsoft/vscode-loc/blob/22cde702f37dbee8b82adb6200e1047091a417e4/i18n/vscode-language-pack-ja/translations/main.i18n.json#L3410
```
フィードバックをツイート
```

---

feedback: https://twitter.com/okazuki/status/1111076631538335744

https://github.com/Microsoft/vscode-loc/blob/22cde702f37dbee8b82adb6200e1047091a417e4/i18n/vscode-language-pack-ja/translations/main.i18n.json#L3430-L3431

https://github.com/Microsoft/vscode-loc/blob/22cde702f37dbee8b82adb6200e1047091a417e4/i18n/vscode-language-pack-ja/translations/main.i18n.json#L3594-L3595

```
エクスプローラーで表示
Finder で表示
```

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
Fixed in MLCP platform.

**Comment by lukaschal** [comment]
@EbXpJ6bp  Please verify and close

**Comment by EbXpJ6bp** [comment]
@luabud Please re-check `miGotoPreviousProblem`

https://github.com/microsoft/vscode-loc/blob/d7382c4e21503acf8f184d752890d046fdb5802a/i18n/vscode-language-pack-ja/translations/main.i18n.json#L523

![](https://user-images.githubusercontent.com/8474118/57691996-9b9a8f80-7680-11e9-9fbe-4250f7bc4f4d.png)

**Comment by luabud** [comment]
I'm sorry, is it possible that you may have tagged the wrong person?

**Comment by EbXpJ6bp** [comment]
@luabud I am sorry for mistakenly having sent the mention to you.

**Comment by lukaschal** [comment]
Translated as "前の問題箇所(&&P)" now in a MLCP platform.
