### ISSUE TITLE
[ko-kr] Wrong translation on vscode.dev 

### ISSUE THREAD

**Issue by ianychoi** [microsoft/vscode-loc#790]
Hi,

Not sure whether submitting vscode.dev L10n issues here is a good idea or not but let me share in details first and hope that the issue is being investigated and solved very soon. 

- Issue: translation "Visual Studio Code (Preview). 언제, 어디서나, 전적으로 귀하의 브라우저에서." from English: "Visual Studio Code (Preview). Anywhere, anytime, entirely in your browser." is wrong.
- Detail context: direct translation looks very awkward - especially two things 1) '전적으로' direct translation from 'entirely' is a not proper word. It implies as 'solely', 'holistic', and/or 'browser is like a god so that everyone should believe' and 2) '귀하의' from 'your' is a very old term which is not used for the communications with developers. '여러분의' might be used but usually Korean readers can assume that 'your' meaning is contained for such purpose of sentence in Korean.
- Suggestion: i) "언제 어디서나 브라우저에서" <- without '전적으로' can deliver the meaning or ii) "언제 어디서나 모든 개발을 브라우저에서"<- paraphrasing as interpreting 'entirely' as 'entire development'.
- Screenshot (Korean)
<img width="847" alt="image" src="https://user-images.githubusercontent.com/6965982/159610649-6eb6f464-3a73-45ae-a14a-6e0a2da224e8.png">
- Screenshot (English)

![image](https://user-images.githubusercontent.com/6965982/159610700-9fa30137-503b-43dd-8c3b-48973d888ca7.png)

**Comment by csigs** [comment]
The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/577028.

**Comment by cristianosuzuki77** [comment]
@TylerLeonhardt  Could you help locate this resource? I am not seeing it in loc side.

**Comment by TylerLeonhardt** [comment]
@joaomoreno do you know where you got these translations?

**Comment by joaomoreno** [comment]
I _poor-manned_ it, caught red handed: Bing Translate. This was right on the date for shipping vscode.dev and I should've created a follow-up item. What would be the best way to move forward and create a pipeline to fix the current strings and make sure new strings get translated in due time?

**Comment by TylerLeonhardt** [comment]
@cristianosuzuki77 could we have a one-off request to translate some strings until we have a better story for how we will translate the web version of VS Code?

**Comment by cristianosuzuki77** [comment]
Okay. I'm requesting this sentence to be translated across the languages.
I will give them back in this ticket.
If you need similar work, please let me know via email.

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 577028)
