### ISSUE TITLE
A tradução paraportuguês Brasil não esta funcionando no Playground.

### ISSUE THREAD

**Issue by VoodooChacal** [microsoft/vscode-loc#792]
Olá eu quero aprender usar o VSCODE porém esta em inglês, eu entendo algumas coisas mas não é o suficiente para eu ter um bom aprendizado.
Por favor adicionar a tradução PT/BR no playground.
Antecipadamente muito obrigado!

Extension version: 1.65.3
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by csigs** [comment]
The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/578264.

**Comment by cristianosuzuki77** [comment]
Poderia confirmar o que seria o Playground? Uma extensão?

**Comment by csigs** [comment]
Resolved as Cant Reproduce.
