### ISSUE TITLE
[es-ES] Error de traducción en diálogo de borrar múltiples ficheros

### ISSUE THREAD

**Issue by lgleznah** [microsoft/vscode-loc#794]
¡Buenos días!

Hay un pequeño error de traducción en el diálogo de borrado de múltiples ficheros en VSCode. Indico aquí los detalles:

A la hora de elegir múltiples ficheros en el editor e intentar borrarlos, sale un cuadro de texto con la apariencia indicada en la captura de pantalla adjunta:

![imagen](https://user-images.githubusercontent.com/36040102/161241683-c35bbde3-f15d-4916-b7bc-7ea7f99d54bb.png)

El problema es que esta traducción no es correcta del todo: no debería ser "¿Está seguro de que desea eliminar de forma permanente los siguientes archivos 2?", sino "¿Está seguro de que desea eliminar de forma permanente los siguientes **2 archivos**?"

La solución debería ser bastante sencilla: en el `main.i18n.json` de la traducción al español, la entrada `confirmDeleteMessageMultiple` debería pasar de ser:

`¿Está seguro de que desea eliminar de forma permanente los siguientes archivos {0}?`

a:

`¿Está seguro de que desea eliminar de forma permanente los siguientes {0} archivos?`

Muchas gracias, ¡y un saludo 👋!

PD: should the issues be submitted in English, let me know ASAP and I will translate it 🙂

**Comment by csigs** [comment]
The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/583479.

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 583479)
