### ISSUE TITLE
[zh-hans] Variable name that should not be translated

### ISSUE THREAD

**Issue by holazz** [microsoft/vscode-loc#796]
https://github.com/microsoft/vscode-loc/blob/ac085cb3ba336f4a4345d33a2961967222ff394b/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L6049

`$​(捕获)` should be `${capture}`

<img width="1552" alt="截屏2022-04-06 上午11 38 49" src="https://user-images.githubusercontent.com/23100055/161892896-4ea1bf64-b526-4034-b6fa-0e4cdc6ac93e.png">

**Comment by csigs** [comment]
The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/585524.

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 585524)
