### ISSUE TITLE
german translation for command.stageSelectedRanges

### ISSUE THREAD

**Issue by michael-at-mitxp** [microsoft/vscode-loc#797]
line 362 in main/i18n/vscode-language-pack-de/translations/extensions/git.i18n.json

```
  "command.stageChange": "Änderung bereitstellen",
  "command.stageSelectedRanges": "Gewählte Bereiche staffeln",
```
stageSelectedRanges should read "Gewählte Bereiche bereitstellen" with 'stage' translated as in the lines above.

the current translation does not make any sense at all

It would be great if it could be fix. This is one I stumble over regularly ;)

Please let me know if there is a better way I can report bugs/improvements ...

**Comment by csigs** [comment]
The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/586776.

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 586776)
