### ISSUE TITLE
Create Thai Language Pack

### ISSUE THREAD

**Issue by Arplane-SOCITY** [microsoft/vscode-loc#798]
---
-------------Information---------------
* Please Follow The Title For Information
------------End Information-----------
----------------Tasks-------------------
- [ ] Create Thai Language Pack
- [ ] Create Thai Extensions
- [ ] Create Thai Settings
--------------End Tasks----------------
--------------Contact Us---------------
- [Email](mailto:arplane0@outlook.com)
- [GitHub](https://github.com/Arplane-SOCITY)
--------------End Contact Us----------
---

**Comment by csigs** [comment]
The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/587312.

**Comment by crsuzukimsft** [comment]
Thank you.
The request will be considered for future language expansions.

**Comment by csigs** [comment]
Resolved as As Designed.
