### ISSUE TITLE
[zh-tw] I suggest that "task" be translated into "任務" rather than "工作".

### ISSUE THREAD

**Issue by hwhsu1231** [microsoft/vscode-loc#804]
In Chinese, I would translate like the following:

- **job**: 工作
- **task**: 任務

![image](https://user-images.githubusercontent.com/71438617/163524377-20e3f4a7-3e12-4b9e-aacc-6172eae10a24.png)

**Comment by csigs** [comment]
The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/591022.

**Comment by cristianosuzuki77** [comment]
Thank you for the suggestion. Upon reviewing, the suggestion is valid however it will be considered for future updates, since it will require alignment with other translations.
Thank you again.
