### ISSUE TITLE
[zh-tw] I prefer to translate "Repository" into "儲存庫" rather than "存放庫".

### ISSUE THREAD

**Issue by hwhsu1231** [microsoft/vscode-loc#806]
It seems that Microsoft uses **"存放庫"** to translate the **"Repository"** in its related websites and tools, such as Azure, Visual Studio, VSCode...etc.

But in my observation, **"儲存庫"** is the most commonly used translation in **"other"** websites with **zh-TW** locale. For example, Wiki.

By the way, I noticed that **"Git: Close Repository"** is translated with **"儲存庫"** in VSCode.

![image](https://user-images.githubusercontent.com/71438617/163670502-b5570151-1af5-41ab-8c54-fc712134f85c.png)
![image](https://user-images.githubusercontent.com/71438617/163670509-5e1f81f2-1f9b-45f6-911d-ec3bee2aa55d.png)

**Comment by csigs** [comment]
The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/591724.

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 591724)
