### ISSUE TITLE
[zh-cn]  Translation errors occurrencesHighlight

### ISSUE THREAD

**Issue by lqzhgood** [microsoft/vscode-loc#81]
Setting -> occurrencesHighlight

now 
> 控制编辑器是否突出显示语义符号次数

以上翻译有些莫名其妙 【语义符号次数】 是什么？

应该翻译为
> 控制编辑器是否高亮额外的字符

**When Double Click "name"** 

` "editor.occurrencesHighlight": true,`
![image](https://user-images.githubusercontent.com/9134671/55343458-ba343500-54dd-11e9-9c19-bd0696445b1e.png)

` "editor.occurrencesHighlight": false,`
![image](https://user-images.githubusercontent.com/9134671/55343558-ed76c400-54dd-11e9-9bdd-be1f7ae5b653.png)

**Comment by lqzhgood** [comment]
by the way , 
When "editor.occurrencesHighlight": true,
How do I change the backgourn color of "user"

**Comment by errlot** [comment]
原文(Source): Controls whether the editor should highlight semantic symbol occurrences.
行为(Behavior): 
<img src="https://user-images.githubusercontent.com/14136385/55379658-5a2aa680-5550-11e9-9782-2fe93f0b4dfb.png" width="500">
我选中的是红框中的 `Context`，所有包含它的词(语义符号, ExtensionContext)的匹配项均高亮。
I selected `Context` within the red box, and all occurences of its semantic symbol (ExtensionContext) are highlighted.

所以，我建议修改翻译为 / So, My suggestion is
`控制编辑器是否突出显示语义符号的匹配项。`

---

> by the way ,
> When "editor.occurrencesHighlight": true,
> How do I change the backgourn color of "user"

@lqzhgood, put something like this in your settings
```json
"workbench.colorCustomizations": {
	"editor.wordHighlightBackground": "#575757b8"
}
```

**Comment by lukaschal** [comment]
On review.

SRC:	Controls whether the editor should highlight semantic symbol occurrences.
TGT:	控制编辑器是否突出显示语义符号次数。

**Comment by lqzhgood** [comment]
// 由于是中文翻译相关，就直接写中文了。

我仔细研究了一下 好像和上面的认知都不一样。

@errlot 
`occurrencesHighlight` 这个选项和你描述的不一致。

> 所有包含它的词(语义符号, ExtensionContext)的匹配项均高亮。

不是 同文件 中所有匹配的 词 均高亮。而是仅作用于选中位置的 “词”

`occurrencesHighlight:true` 这个选项会造成两种效果
- **单击** 的位置如果是一个 词， 高亮这个 词
-  如果一个词（user_name）被选中其中的一部分
   - 选中的部分是 **单词** 或其中一部分（name 或者 n 或者 ame），高亮整个词，无论这个词是 *驼峰* *下划线* *横杆* 命名（ "userName" "user_name" "user-name"）。
    - 如果选中的部分包含 **标点符号**（er-na 或者 er_na ），不高亮整个词
 


为了排除插件影响，我重新安装了干净的 vscode 并录制了以下 GIF，GIF 中鼠标动作均为 **单击**

![GIF](https://user-images.githubusercontent.com/9134671/55445560-885ec380-55ee-11e9-9509-c8e372886f06.gif)



我建议翻译为以下

> 是否高亮光标处的词`

**Comment by lqzhgood** [comment]
> occurrencesHighlight:true 


```
"workbench.colorCustomizations": {
	"editor.wordHighlightBackground": "#ff0000ff" 
}
```
Can't use



![1](https://user-images.githubusercontent.com/9134671/55446526-97477500-55f2-11e9-87bd-3f1c76bddc92.jpg)

`name` is selected,  `user` not red

**Comment by errlot** [comment]
@lqzhgood 这个是有语义的
![image](https://user-images.githubusercontent.com/14136385/55446793-ba265900-55f3-11e9-8c9b-9b5798a86f99.png)

另外高亮颜色那个，是我搞错了，他们区分了读访问和写访问，你要改的话要两个都得改
```json
	"workbench.colorCustomizations": {
		"editor.wordHighlightStrongBackground": "#ff000069",
		"editor.wordHighlightBackground": "#ff000069"
	}
```
更多的，去他们的官网看吧(https://code.visualstudio.com/api/references/theme-color)

**Comment by lukaschal** [comment]
Translated this way in a MLCP now.

SRC:	Controls whether the editor should highlight semantic symbol occurrences.
TGT:	控制编辑器是否突出显示语义符号的匹配项。
