### ISSUE TITLE
[zh-tw] I suggest that "Commit" be translated into "提交" rather than "認可". (just like zh-cn)

### ISSUE THREAD

**Issue by hwhsu1231** [microsoft/vscode-loc#810]
**"提交"** is more **intuitive** to me, and it is **widely-used** by many blogs and websites in **zh-tw** locale, **except** Microsoft-related tools and websites.

As for **"認可"**, I tend to translate it into **"Recognize"** or **"Accept"**. I seldom hear someone saying **"認可"** to to represent **"Commit"**.

By the way, **"Git: Undo Last Commit"** still uses **"提交"**.

![image](https://user-images.githubusercontent.com/71438617/163701426-cdb25a00-c126-4d7e-a779-ed786162844f.png)

**Comment by csigs** [comment]
The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/592013.

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 592013)
