### ISSUE TITLE
Ukrainian l10n.

### ISSUE THREAD

**Issue by foo4bar** [microsoft/vscode-loc#815]
Hi colleagues.

I've found the closed [issue](https://github.com/microsoft/vscode/issues/26691) related to the subject.
It looks like the job wasn't completed. Also, it looks like [transifex](https://www.transifex.com/home/) is not used for that anymore.
There was no any similar issue here as well, at least, I didn't find any.

So, could anyone here explain me how to create a new l10n for VS Code? What's the **Microsoft Localization Platform** mentioned in the [readme](https://github.com/microsoft/vscode-loc/blob/main/README.md)?

Thanks.

**Comment by foo4bar** [comment]
> The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/594292.

Could you please explain how to request access to the issue?

**Comment by csigs** [comment]
{ body = Resolved as Assigned to External. }Investigated by Loc Team: It's not a translation issue. (Reference id: 594292)

**Comment by foo4bar** [comment]
Colleagues, with the upmost respect, is there anybody here who's not a bot to talk with?

**Comment by danyeh** [comment]
Please checkout wiki: https://github.com/Microsoft/vscode-loc/wiki/How-to-create-language-pack-extension.

**Comment by foo4bar** [comment]
So, this repo is about s.c. core languages only, right? And when someone wants to create another language pack, this could be done as an independent project only, am I correct?

If yes, could it be stated explicitly in the readme? It's really not clear.

Thanks.
