### ISSUE TITLE
[zh-tw] I suggest that "Build" should be uniformly translated into "建置" rather than "組建".

### ISSUE THREAD

**Issue by hwhsu1231** [microsoft/vscode-loc#819]
I suggest that **"Build"** should use a uniform translation in **zh-TW** locale, which is **"建置"**.

- In **Visual Studio**, it is translated into **"建置"**.
- In **Qt Creator**, it is also translated into **"建置"**.
- In **CMake-Tools** plugin, it is translated into **"建置"** mostly.

However, I saw that some places use **"組建"** to translate **"Build"**. Also, I saw the MSDN use **"組建"** to translate **"Build"** somewhere. They should be modified into **"建置"**.

### Screenshots

![image](https://user-images.githubusercontent.com/71438617/164720160-fdf0aa42-80a8-4474-a134-158ef7f92187.png)
![image](https://user-images.githubusercontent.com/71438617/164720292-1a6ab6aa-f80d-4eca-82a8-ccf95554c34b.png)
![image](https://user-images.githubusercontent.com/71438617/164720551-2525b9c7-0ff1-471e-8f6c-2e6156cd78af.png)
![image](https://user-images.githubusercontent.com/71438617/164720569-c71b6585-b7c1-44b0-856b-468252b562e0.png)

**Comment by csigs** [comment]
The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/596372.

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 597723)
