### ISSUE TITLE
What is the function &&?

### ISSUE THREAD

**Issue by rodriggodasilva** [Microsoft/vscode-loc#82]
I would like to help with the translation, but I noticed that in several places of the code there is "&&" in the middle of the words. I wonder if it's mandatory or can I just leave the words?

Example original code:

"actions.clipboard.cutLabel": "Recortar",
"miCut": "Cu&&t",
"actions.clipboard.copyLabel": "Copiar",
"miCopy": "&&Copiar",
"actions.clipboard.pasteLabel": "Colar",
"miPaste": "&&Colar",

Changing to:

"actions.clipboard.cutLabel": "Recortar",
"miCut": "Recortar",
"actions.clipboard.copyLabel": "Copiar",
"miCopy": "Copiar",
"actions.clipboard.pasteLabel": "Colar",
"miPaste": "Colar",

**Comment by lukaschal** [comment]
"&&" represents hotkey/shortcut in a localized version of product. Without these characters in a target strings shortcuts cannot be used.

**Comment by rodriggodasilva** [comment]
Thank you for the explanation.
