### ISSUE TITLE
【Simplified Chinese】“关闭到右侧” is weird

### ISSUE THREAD

**Issue by CrotchBurnt** [microsoft/vscode-loc#830]
"close to the right" should be just "关闭右侧"，“关闭到右侧” sounds weird.

**Comment by CrotchBurnt** [comment]
![image](https://user-images.githubusercontent.com/6418433/165669906-d638d4da-9be7-4237-be69-d63404bd0ff8.png)

**Comment by csigs** [comment]
The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/599408.

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 599408)
