### ISSUE TITLE
【zh-cn】`*.hex` is translated as `*十六进制`, which should not.

### ISSUE THREAD

**Issue by CodeCrazy-ywt** [microsoft/vscode-loc#836]
In the description of `"workbench.editorAssociations"`, `*.hex` is translated as `*十六进制`, however it should not be translated, because it's a file extension name.
![feedback_vscode-loc_translating-hex-zh](https://user-images.githubusercontent.com/62426149/166236712-8f0d4d24-2b08-46f0-ba5e-ce99f180df04.jpg)

**Comment by csigs** [comment]
The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/601227.

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 601227)
