### ISSUE TITLE
Suggestion: sort content of *.i18n.json files

### ISSUE THREAD

**Issue by errlot** [microsoft/vscode-loc#84]
The diff of a *.i18n.json file in a commit is not all about translation changes, sometimes it's just some objects inside `contents` object changing their positions.
I'd love to see translation changes more clearly, please sort the content of those files.

**Comment by danyeh** [comment]
@dbaeumer , could you please comment on this?
I noticed same for diff scenario. It is not a product blocker.

**Comment by dbaeumer** [comment]
I am not sure if the repository is the right place to look at this. Shouldn't the translation tooling support these diffs on a translation level. The vscode-loc repository is only a publishing vehicle to my understanding.

**Comment by danyeh** [comment]
Thank you @errlot for your suggestion! Since Dirk mentioned won't invest on sorting of translation in langauge pack json file. I close this issue here.
