### ISSUE TITLE
[zh-cn] Find result count in terminal

### ISSUE THREAD

**Issue by CodeCrazy-ywt** [microsoft/vscode-loc#843]
“{0} of {1}” should be translated into “第 {0} 项，共 {1} 项”, instead of “{1} 中的 {0}”.
![fdbk_vscode-loc_find-result-count](https://user-images.githubusercontent.com/62426149/167111444-6a0f23e9-4bb7-4821-8af7-a115423ce973.jpg)

**Comment by csigs** [comment]
The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/603816.

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 603816)
