### ISSUE TITLE
Change french translation "prise en main"

### ISSUE THREAD

**Issue by FrankSAURET** [microsoft/vscode-loc#845]
Hi,
I think it's better to call the page "prise en main" "accueil" or "démarrage".

**Comment by csigs** [comment]
The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/605456.

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 605456)
