### ISSUE TITLE
[zh-tw] I suggest that "Help" be translated into "幫助" rather than "說明". (just like zh-cn)

### ISSUE THREAD

**Issue by hwhsu1231** [microsoft/vscode-loc#848]
Ever since I started to use computers, I noticed that **"Help"** is widely translated into **"說明"** in **zh-TW** locale.

- **Visual Studio**
- **Qt Creator**
- **VSCode**
- **Word**, **Excel**, **PowerPoint**... of MSOffice
- **Writer**, **Calc**, **Impress**... of LibreOffice
- **Typora**
- ...etc

However in Chinese, I would translate **"說明"** into **"explain"**, **"illustrate"**,...etc. Anyway, I won't translate **"說明"** into **"Help"**. For example, if I want to translate **"I can help you"** into Chinese, I would say **"我可以幫助你"**. I wouldn't say **"我可以說明你"** (That sounds weird)

- **I can help you:** 我可以幫助你
- **I need you help:** 我需要你的幫助

Even now, I still think that **"Help" translated into "說明"** is not appropriate. Therefore, I suggest using **"幫助"** just like **zh-CN**.

If Microsoft can start to change this translation, I think it might be able to affect others.

## Screenshots

![image](https://user-images.githubusercontent.com/71438617/167865689-72f3586e-4141-47d1-bc3f-81873fce717d.png)
![image](https://user-images.githubusercontent.com/71438617/167865718-99ecd5a9-babf-4ea5-a912-a8af45216fef.png)
![image](https://user-images.githubusercontent.com/71438617/167865740-7d6bd825-b3f0-47d3-b725-87bf37761f97.png)
![image](https://user-images.githubusercontent.com/71438617/167865812-743d58ff-e304-4a46-8265-de0ad984c56b.png)
![image](https://user-images.githubusercontent.com/71438617/167865836-b2a5bbbf-9357-46c6-bec1-4dce1164a614.png)
![image](https://user-images.githubusercontent.com/71438617/167865860-8cd18ac3-0069-45dd-a837-d8b1ac5e6c62.png)

**Comment by csigs** [comment]
The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/606134.

**Comment by cristianosuzuki77** [comment]
Thank you for your feedback. Upon further review, we have decided to keep the current translation for the time being.

**Comment by csigs** [comment]
Resolved as As Designed.
