### ISSUE TITLE
(pt-BR) Tradução na área da Paleta de Comando

### ISSUE THREAD

**Issue by umfelipelima** [microsoft/vscode-loc#849]
Olá, sou o Felipe, diretamente do interior de Pernambuco-BR. Mais um estudante novato na área de Desenvolvimento Web.

Primeiramente, muito grato aos criadores e colaboradores dessa extensão que traduz o VS Code para pt-BR, facilitando demais a vida de quem ainda não domina o idioma Inglẽs.

Acompanhando uma das aulas de um curso HTML5 que estou fazendo, percebi que pode ser que haja uma falta de precisão na tradução de uma das opções encontradas na Paleta de Comandos (**Ctrl + Shift + P**), a _>Wrap with Abbreviation_. Essa opção está traduzida, atualmente, como _Quebrar Linha com Abreviação_. 

Sei somente o básico do básico no Inglês, mas, entendendo a função dessa opção e consultando o Google Tradutor, vi que a expressão _Envolver com Abreviação_ faria mais sentido, substituindo a atual.

Valeu, galera. Por enquanto é só isso.

**Comment by umfelipelima** [comment]
> Olá, sou o Felipe, diretamente do interior de Pernambuco-BR. Mais um estudante novoto na área de Desenvolvimento Web.
> 
> e colaboradores dessa extensão que ainda não foram traduzidos, o que foi traduzido muito para o idioma de quem ainda está em BR, o que foi desenvolvido muito para traduzir o idioma de quem ainda está em inglês.
> 
> Acompanhando uma das aulas de um curso HTML5 que estou fazendo, percebi que pode ser que haja uma falta de precisão na tradução de uma das opções de precisão na Paleta de Comandos ( **Ctrl + Shift + P** ), a _>Wrap with Abbreviation_ . Essa opção está inteligente, atualmente, como _Quebrar Linha com Abreviação_ .
> 
> Sei somente o básico do básico no inglês, mas, entendendo a função dessa opção e consultando o Google Tradutor, vi que a expressão _Envolver com Abreviação_ faria mais sentido, substituindo a atual.
> 
> Valeu, galera. Por enquanto é só isso.

**Comment by umfelipelima** [comment]
> Olá, sou o Felipe, diretamente do interior de Pernambuco-BR. Mais um estudante novoto na área de Desenvolvimento Web.
> 
> e colaboradores dessa extensão que ainda não foram traduzidos, o que foi traduzido muito para o idioma de quem ainda está em BR, o que foi desenvolvido muito para traduzir o idioma de quem ainda está em inglês.
> 
> Acompanhando uma das aulas de um curso HTML5 que estou fazendo, percebi que pode ser que haja uma falta de precisão na tradução de uma das opções de precisão na Paleta de Comandos ( **Ctrl + Shift + P** ), a _>Wrap with Abbreviation_ . Essa opção está inteligente, atualmente, como _Quebrar Linha com Abreviação_ .
> 
> Sei somente o básico do básico no inglês, mas, entendendo a função dessa opção e consultando o Google Tradutor, vi que a expressão _Envolver com Abreviação_ faria mais sentido, substituindo a atual.
> 
> Valeu, galera. Por enquanto é só isso.

**Comment by csigs** [comment]
The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/606399.

**Comment by cristianosuzuki77** [comment]
Obrigado, Felipe.
Sua recomendação está sendo apurada.

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 606399)
