### ISSUE TITLE
Use Crowdin for localization and improvements for language packs

### ISSUE THREAD

**Issue by Andrulko** [microsoft/vscode-loc#854]
Hey everyone,

It's Andriy from the Crowdin team, a localization management platform used by many teams, MakeCode is being translated here too:
https://crowdin.com/project/makecode

Just did some analysis of the current i18n workflow and it feels that GitHub issues reported by the community are not so easy to handle, also new languages may bring new headaches to engineers 😬

The professional and community translators can work together in Crowdin (you decide what exactly combo would be), translations would be delivered as PR via GitHub sync and volunteers can raise issues for problematic strings via Crowdin, so the proofreader can revise them directly.

I'm open to any questions! Unfortunately, I could not find English resources to build a demo project for you, and the **en_GB** package which exists in other branches seems to be outdated... Note that Crowdin is free for Open Source, it would be amazing to support VS Code i18n 😃

**Comment by csigs** [comment]
The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/608825.

**Comment by cristianosuzuki77** [comment]
Thank you for the recommendation.
