### ISSUE TITLE
[question] Can I report other translation suggestions of Microsoft-related platforms, websites, tools as well?

### ISSUE THREAD

**Issue by hwhsu1231** [microsoft/vscode-loc#862]
If I have some translation suggestions about: 

- MSVC compiler messages
- Visual Studio Interface
- MSDN documentation
- ...etc

Which means those translations might not be directly related to VSCode. Can I report them here as well?

**Comment by csigs** [comment]
The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/611943.

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 611943)
