### ISSUE TITLE
`shift` key is translated

### ISSUE THREAD

**Issue by liyuhang1997** [microsoft/vscode-loc#865]
https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-zh-hans/translations/extensions/markdown-language-features.i18n.json#L56

`shift` => `排班`

https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-zh-hant/translations/extensions/markdown-language-features.i18n.json#L56

`shift` => `班次`

I think the shift here should refer to the shift key on the keyboard.

**Comment by csigs** [comment]
The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/613487.

**Comment by crsuzukimsft** [comment]
Thank you for including the location of the resource.

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 613487)
