### ISSUE TITLE
[Suggestion] Localization Group wanted, please

### ISSUE THREAD

**Issue by MaledongGit** [microsoft/vscode-loc#866]
Until now there're many issues sent to Microsoft's inner translation groups and we cannot see both the process and result successfully. So it would be nice for Microsoft to create diff groups of localizations for diff languages. Something like:

vscode/cn : Chinese
vscode/en: English
.....

Thus we can have discussions on translations to make it better. Each group may assign a leader or approver either from Microsoft or from frequently-contributing users.

**Comment by csigs** [comment]
The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/613612.

**Comment by MaledongGit** [comment]
@csigs: This is just the problem: We cannot be redirected to the website because of authentication.....And my aim is to create groups together to work with at GitHub.

**Comment by crsuzukimsft** [comment]
Hello MaledongGit
Could you explain further? What you mean by group?

**Comment by MaledongGit** [comment]
@crsuzukimsft: Simply speaking, just to create some groups in the vscode-loc in "Teams" with proper authentications/authorizations. Something like what you see in Node.js org:
![Teams · nodejs](https://user-images.githubusercontent.com/52018749/170154373-d581ea57-a885-4d00-ae97-cbf76d6af9d2.png)

**Comment by csigs** [comment]
Resolved as As Designed.
