### ISSUE TITLE
[fr] Issues in Mardown Math settings French translation

### ISSUE THREAD

**Issue by Fringale** [microsoft/vscode-loc#867]
Hi!

It seems there are two issues with the French translation of the setting **Markdown>Math:Enabled**, for the Markdown Math built-in extension:

![Screenshot_20220522_013316](https://user-images.githubusercontent.com/2722396/169672997-13fde969-173e-4ee1-9ad3-a7090a60a0d6.png)

  1. The string "_Markdown_" was wrongly translated to "_Démarque_" (this is a literal translation, "_Markdown_" should be kept as is),
  2. The string "_preview_" was roughly translated in French to "_préversion_", but the translation for this VS Code concept in all other settings seems to be "_aperçu_" instead.

=> As such, a better translated **Markdown>Math:Enabled** setting in French would be "_Activer/désactiver le rendu des maths dans l’aperçu intégré Markdown._"

---

_Markdown>Math:Enabled_ setting in English, for reference:
![Screenshot_20220522_014417](https://user-images.githubusercontent.com/2722396/169673010-270de7a8-d631-4887-9aae-5a4ae5881122.png)

**Comment by csigs** [comment]
The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/614657.

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 614657)
