### ISSUE TITLE
[fr] Duplicated French translation for Editor>Unicode Highlight settings

### ISSUE THREAD

**Issue by Fringale** [microsoft/vscode-loc#869]
Hi!

The exact same description is shown in French for both **Editor>Unicode Highlight:Include Comments** and **Editor>Unicode Highlight:Include Strings** settings:
![Screenshot_20220520_142652](https://user-images.githubusercontent.com/2722396/169673623-73b0e801-b489-454a-9677-da23824d7c31.png)

=> The second setting **Editor>Unicode Highlight:Include Strings** should be something like "_Contrôle si les caractères des chaînes de texte doivent également faire l’objet d’une mise en surbrillance Unicode._" instead.

---

**Editor>Unicode Highlight:Include Comments** and **Editor>Unicode Highlight:Include Strings** settings in English for reference:
![Screenshot_20220522_014556](https://user-images.githubusercontent.com/2722396/169673753-62329668-d795-499e-9ecf-14a5f7ff5171.png)

**Comment by csigs** [comment]
The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/614658.

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 614658)
