### ISSUE TITLE
[ru] Extra characters && in keyboard shortcuts

### ISSUE THREAD

**Issue by hd321kbps** [microsoft/vscode-loc#87]
Extra characters && in keyboard shortcuts.
Version: 1.33.1 (system setup)
OS: Windows_NT x64 10.0.17763
![vs](https://user-images.githubusercontent.com/9886849/56035608-4e4e9980-5d33-11e9-9b01-acb842e13493.png)

**Comment by lukaschal** [comment]
Fixed in a MLCP platform.

**Comment by hd321kbps** [comment]
> Fixed in a MLCP platform.

Link please

**Comment by hd321kbps** [comment]
1.34.0 fixed
