### ISSUE TITLE
[zh-tw] "Publish" should be translated into "發布" rather than "發佈" or "發行".

### ISSUE THREAD

**Issue by hwhsu1231** [microsoft/vscode-loc#871]
In Chinese, **"佈"** is a variant of **"布"**. According to the [document](https://www.nutn.edu.tw/personnel/upload/files/1100805fw-3.pdf) I found on browser, it is recommended to use **"布"** for **simplicity**. It is because **"布"** already has **"人"** inside its character.

Therefore, I suggest that **"Publish"** be translated into **"發布"** in **zh-TW** locale.

### Screenshots

![image](https://user-images.githubusercontent.com/71438617/169730012-d0e7c8e9-e736-49ba-ae5f-e47c15c4526e.png)
![image](https://user-images.githubusercontent.com/71438617/169730005-ecd058aa-f833-4277-9b74-2d92e85ffbf3.png)

**Comment by csigs** [comment]
The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/616112.

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 616112)
