### ISSUE TITLE
如何下载到1.33.1版本

### ISSUE THREAD

**Issue by Sun-VanillaSky** [microsoft/vscode-loc#88]
我下载的vscode 和语言包（离线的）版本不对应，安不上

**Comment by nanasama** [comment]
> @Sun-VanillaSky Please could you provide your feedback in a english and add some screenshots ?
The prompt message is “Unable to install extension 'ms-ceintl.vacode-language-pack-zh--hans' as it is not compatible width VS Code '1.33.1'.”

**Comment by Sun-VanillaSky** [comment]
> @Sun-VanillaSky Please could you provide your feedback in a english and add some screenshots ?

how to down 1.33.1 version ？

Now I have solved this problem，just change version code in download url to 1.33.1.

**Comment by danyeh** [comment]
Glad to know you have sorted out the solution.
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/MS-CEINTL/vsextensions/vscode-language-pack-zh-hans/1.33.1/vspackage
