### ISSUE TITLE
[zh-CN] "repository" should be translated into "仓库".

### ISSUE THREAD

**Issue by hwhsu1231** [microsoft/vscode-loc#880]
According to my observation, **"repository"** is translated into **"仓库"** mostly in **zh-CN** locale.

For example: [Gitee](https://gitee.com/)

### Screenshots

![image](https://user-images.githubusercontent.com/71438617/170860247-70346bac-e940-4f4d-9d88-7f713d2c40c4.png)
![image](https://user-images.githubusercontent.com/71438617/170860157-bba2f922-7558-44f5-87a4-4027147dffbe.png)

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 622719).

**Comment by hwhsu1231** [comment]
- English String: **Repository**
- Current Translation: **存储库**
- Suggested Translation: **仓库**

**Comment by v-mholloway** [comment]
@hwhsu1231 thank you for the quick response. we will proceed with the investigation now.
