### ISSUE TITLE
[zh-CN] "upload" should be translated as "上传".

### ISSUE THREAD

**Issue by LinLzis** [microsoft/vscode-loc#886]
According to my observation, "upload" is translated as "上传" mostly in zh-CN locale.

<img width="370" alt="image" src="https://user-images.githubusercontent.com/20831003/171356502-a1cb8593-186e-4c66-84a4-0fb913135ca3.png">

E.g.: coding.net
![企业微信截图_7905baa5-d2f8-4da8-a608-7c9f5ccff5a3](https://user-images.githubusercontent.com/20831003/171357168-6ecfd2c9-fcfc-4709-8814-72eea44b16ba.png)

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 625719).

**Comment by v-mholloway** [comment]
@LinLzis could you provide the following information typed out...
English String: 
Current Translation: 
Suggested Translation:

**Comment by LinLzis** [comment]
> @LinLzis could you provide the following information typed out... English String: Current Translation: Suggested Translation:

English String: "upload"  [vs/workbench/contrib/files/browser/fileActions]
Current Translation: "上载..."
Suggested Translation: "上传..."
