### ISSUE TITLE
@Sun-VanillaSky Please could you provide your feedback in a english and add some screenshots ?

### ISSUE THREAD

**Issue by nanasama** [microsoft/vscode-loc#89]
The prompt message is “Unable to install extension 'ms-ceintl.vacode-language-pack-zh--hans' as it is not compatible width VS Code '1.33.1'.”

**Comment by Sun-VanillaSky** [comment]
> The prompt message is “Unable to install extension 'ms-ceintl.vacode-language-pack-zh--hans' as it is not compatible width VS Code '1.33.1'.”

Thanks! how to download 1.33.1 version .vsix.
But now I have solved this problem.
Just change version code in download url to 1.33.1.

I think my english is very pool
