### ISSUE TITLE
Consistency of README writing style. 

### ISSUE THREAD

**Issue by OSUsatoru** [microsoft/vscode-loc#890]
I noticed that the writing style of translated README documentation is not consistent with the original document. For example, Ctrl+Shift+P are bold text in English but not in Japanese. 

Here is original text.  
![original](https://user-images.githubusercontent.com/72106923/172165035-613a3476-47c9-4d85-a38e-be344f305b99.jpg)
![ogen](https://user-images.githubusercontent.com/72106923/172165848-a125bbe7-c455-4992-8d56-f1691430a7d3.jpg)
![ogjap](https://user-images.githubusercontent.com/72106923/172165876-193d5a02-9cea-4246-a162-2fec98f407b4.jpg)

Here is the change I propose for READMY in Japanese language extension folder.
![git1](https://user-images.githubusercontent.com/72106923/172165058-a3285d3e-8e62-47a1-abab-611a6b83721f.jpg)

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 630029).

**Comment by csigs** [comment]
Resolved as .
