### ISSUE TITLE
[de] Typo in miShowAuxiliaryBar

### ISSUE THREAD

**Issue by stefanhamburger** [microsoft/vscode-loc#891]
The mnemonic text [`miShowAuxiliaryBar`](https://github.com/microsoft/vscode-loc/blob/688cbd1107c85263c5edc20b32d4711171a46859/i18n/vscode-language-pack-de/translations/main.i18n.json#L2993) is missing the "i" character:

```diff
			"hideAuxiliaryBar": "Sekundäre Seitenleiste ausblenden",
-			"miShowAuxiliaryBar": "Sekundäre Se&&ten-Leiste anzeigen",
+			"miShowAuxiliaryBar": "Sekundäre Sei&&ten-Leiste anzeigen",
			"miShowAuxiliaryBarNoMnemonic": "Sekundäre Seitenleiste anzeigen",
```

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 631139).

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 631139)
