### ISSUE TITLE
[question] Should we request the translation of other VSCode plugins (which do not have yet) here?

### ISSUE THREAD

**Issue by hwhsu1231** [microsoft/vscode-loc#894]
I have a question about this plugin. If we have some translation advises for **"other VSCode plugins"**, which do not support international translations yet, should we post an issue **"here"** to request it?

For example, I posted an issue about 2 months ago. It provided some translation advises about [vscode-qt-tools](https://github.com/tonka3000/vscode-qt-tools) in **"zh-TW (cht)"** locale. But it seems no reply from the author. Is [vscode-loc](https://github.com/microsoft/vscode-loc) responsible for this part?

- https://github.com/tonka3000/vscode-qt-tools/issues/78

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 635850).

**Comment by cristianosuzuki77** [comment]
Currently only elements within this repo are addressable. For the ticket attached above, please continue addressing it at that particular repo.
Thank you.
