### ISSUE TITLE
[fr] Improve reference translations consistency 

### ISSUE THREAD

**Issue by JackNUMBER** [microsoft/vscode-loc#896]
Hello, here some changes for the french translation that should be considered for more consistency.

Path `vs/editor/contrib/gotoSymbol/browser/goToCommands`

- `actions.goToTypeDefinition.label`:
"Atteindre la définition de type" ➞ "Atteindre la définition du type" 

-  `actions.peekImplementation.label`:
"Implémentations d'aperçu" ➞ "Aperçu des implémentations"

- `actions.previewDecl.label`:
"Faire un Peek de la Définition" ➞ "Aperçu de la définition"

Path `vs/workbench/contrib/callHierarchy/browser/callHierarchy.contribution`
- `title`:
"Afficher un aperçu de la hiérarchie d'appels" ➞ "Aperçu de la hiérarchie d'appels"

- `error`: 
"L'affichage de la hiérarchie des appels a échoué" ➞ "L'affichage de la hiérarchie d'appels a échoué"

- `showIncomingCallsIcons`: 
"Icône des appels entrants dans la vue de la hiérarchie des appels." ➞ "Icône des appels entrants dans la vue de la hiérarchie d'appels."

- `showOutgoingCallsIcon`: 
"Icône des appels sortants dans la vue de la hiérarchie des appels." ➞ "Icône des appels sortants dans la vue de la hiérarchie d'appels."

- `title.refocus`: 
"Replacer le focus sur la hiérarchie des appels" ➞ "Replacer le focus sur la hiérarchie d'appels"

![image](https://user-images.githubusercontent.com/2306550/173019251-c7033b7a-a9f8-4920-85b6-80241913e3fc.png)

Hope it will help to improve the translation!

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 635852).

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 635852)
