### ISSUE TITLE
[zh-cn] translation of git commands is not correct

### ISSUE THREAD

**Issue by zsynacl** [microsoft/vscode-loc#90]
![图片](https://user-images.githubusercontent.com/4392800/58394830-d258a880-8077-11e9-91f4-39f81d7e6d29.png)
![图片](https://user-images.githubusercontent.com/4392800/58395015-c1f4fd80-8078-11e9-876b-941ff4500e3c.png)
1. 条目对应错误。commit staged和commit staged(Amend)对应的中文顺序错了
2. signed off是“签名”的意思。这里应该翻译为“提交（并添加签名）”

**Comment by zsynacl** [comment]
另外，有如下准确性问题：
- commit All(Amend)  ：提交(修改上次提交)
- commit staged(Amend) 提交已暂存文件（修改上次提交）

**Comment by lukaschal** [comment]
Fixed.

src: Commit Staged (Amend)
new tgt: 提交已暂存文件(修改)
