### ISSUE TITLE
[ru] Incorrect quote escaping

### ISSUE THREAD

**Issue by idma88** [microsoft/vscode-loc#900]
Several strings in Russian localization contain an escaped double quote character (instead of a single quote), which leads to errors in the UI

Example:
![example](https://user-images.githubusercontent.com/7449066/174071004-b0f54975-830f-4ff4-96bf-32e66c0e83ec.png)

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 643291)
