### ISSUE TITLE
Typo mistake on Korean Language Pack for Visual Studio Code

### ISSUE THREAD

**Issue by focus5n** [microsoft/vscode-loc#907]
Typo mistake on Settings.

Setting ID: editor.guides.bracketPairs

Now: 대괄호 쌍 "안내션"의 사용 여부를 제어합니다.
Recommened: 가로 대괄호 쌍 "안내선"의 사용 여부를 제어합니다.

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 640734).

**Comment by v-mholloway** [comment]
@focus5n can you please provide the corresponding english string to enable us to track down the resource?

**Comment by focus5n** [comment]
> @focus5n can you please provide the corresponding english string to enable us to track down the resource?

Sure!

English Version:
Editor › Guides: Bracket Pairs
Controls whether bracket pair guides are enabled or not.

Korean Version Now:
Editor › Guides: Bracket Pairs
대괄호 쌍 안내'션'의 사용 여부를 제어합니다.

Korean Version Recommended:
Editor › Guides: Bracket Pairs
대괄호 쌍 안내'선'의 사용 여부를 제어합니다.

**Comment by v-mholloway** [comment]
@focus5n thank you!
