### ISSUE TITLE
[german/de] Misleading translation: 'Not enough space to split terminal'

### ISSUE THREAD

**Issue by slydor** [microsoft/vscode-loc#91]
The notification hint 'Not enough space to split terminal.' is translated in german with "Nicht genügend Speicherplatz zum Aufteilen des Terminals vorhanden.".

The term "Speicherplatz" is not correct here. The hint want to suggest the user should resize his vs code window to have more space for the terminal. Instead the german reader understands, he would need more memory (RAM) in order to split his terminal.

I would simply suggest the term "Platz" or "Bildschirmbreite".

To reproduce this hint:
- have terminal view open
- from the menu > Terminal > Split Terminal [de: "Terminal teilen"]

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
Fixed. 

New TGT: Nicht genügend Platz auf dem Bildschirm zum Aufteilen des Terminals vorhanden.
