### ISSUE TITLE
[ja-jp]  I would like to improve the translation of "workspace trust"

### ISSUE THREAD

**Issue by 119311** [microsoft/vscode-loc#910]
The workspace trust screen is partially untranslated when it's in Japanese (please see the picture).
![image](https://user-images.githubusercontent.com/92527171/175006240-1e2bb51a-0769-4e68-b670-be2563c33267.png)

I guess "Trust parent" might be changed to "親ディレクトリを信頼".

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 644037).

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 644037)
