### ISSUE TITLE
Add Finnish Support for VS Code

### ISSUE THREAD

**Issue by Anderillo** [microsoft/vscode-loc#914]
I am looking for a translation of VS Code into Finnish (i.e. adding Finnish as an available Display Language). Is this project already underway? How can I help contribute to this?

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 644933).

**Comment by cristianosuzuki77** [comment]
Thank you for the suggestion and offer. Languages are added per alignment with other products. Translations will then go through internal processes.
Appreciate your help!
