### ISSUE TITLE
The characters are separated.

### ISSUE THREAD

**Issue by BearAtKEDU** [microsoft/vscode-loc#924]
When entering Korean, it appears as follows.
"아" > "ㅇㅏ"
I tried changing the language in the Settings->Configure Display Language, but the same thing still happens.

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 649579).

**Comment by v-mholloway** [comment]
@BearAtKEDU can you give more context here...? screen shots...? repro steps...?
If you want translations adjusted, please provide...
-English String
-Current translation
-Suggested Translation

**Comment by csigs** [comment]
Resolved as Cant Reproduce.
