### ISSUE TITLE
fr-FR: Missing space before placeholders

### ISSUE THREAD

**Issue by Tony-Truand** [microsoft/vscode-loc#935]
https://github.com/microsoft/vscode-loc/blob/4a7d2c7467d91ef1d1e178664455baabdd661fff/i18n/vscode-language-pack-fr/translations/extensions/git.i18n.json#L29
According to english display, there should be a space before dynamic arguments

Should be

```
 "scm button sync description": "{0}Synchroniser les modifications {1}{2}", 
```

![image](https://user-images.githubusercontent.com/7480192/177325274-f030fef0-77ed-4b72-bbe4-1c8e8c120168.png)

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 653667).

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 653667)
