### ISSUE TITLE
Italian language change for "kill terminal"

### ISSUE THREAD

**Issue by niccolomineo** [microsoft/vscode-loc#942]
I'd strongly suggest changing this line to something else: 

https://github.com/microsoft/vscode-loc/blob/fb987ff21ae002c918fc0e7039642ae345f279b6/i18n/vscode-language-pack-it/translations/main.i18n.json#L9182

I'd propose either: 

```
Chiudi il terminale
```

or 

```
Esci dal terminale
```

Consequently, this:

https://github.com/microsoft/vscode-loc/blob/fb987ff21ae002c918fc0e7039642ae345f279b6/i18n/vscode-language-pack-it/translations/main.i18n.json#L9183

 could be just: 

```
Chiudi
```

or 

```
Esci
```

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 656217).

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 656217)
