### ISSUE TITLE
de-DE: Bad translation for "branch"

### ISSUE THREAD

**Issue by leMaik** [microsoft/vscode-loc#943]
I was surprised today by a button labeled "Filiale veröffentlichen". A "Filiale" in german is like a branch of some store. But in the context of Git, we either just call them Branches or, if you really want to localize it, it should be "Zweig" (which is a branch of a tree).

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 656589).

**Comment by BaaaZen** [comment]
For sake of consistency you should translate it with "Branch" as this translation is mostly used.
Additionally  there are a few occurrences of "branch" that were translated "Verzweigung" (i.e. https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-de/translations/extensions/git.i18n.json#L21). That is also correct but rarely used for a branch in a VCS.

**Comment by FloEdelmann** [comment]
See also the proposed changes and inconsistencies in #947

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 656589)
