### ISSUE TITLE
Slovak Translation

### ISSUE THREAD

**Issue by mariolacko** [microsoft/vscode-loc#944]
Can you add slovak translation?

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 657097).

**Comment by danyeh** [comment]
Not in current language scope. https://github.com/microsoft/vscode-loc#visual-studio-code-language-packs

Community has the chance to create language pack. See how to topic in wiki.
![image](https://user-images.githubusercontent.com/19785531/181855760-b0007f5a-195d-436f-ad5b-e2d907c2efee.png)
