### ISSUE TITLE
Wrong Japanese translation of "deleteAllLeft"

### ISSUE THREAD

**Issue by nai62** [microsoft/vscode-loc#96]
Issue Type: <b>Bug</b>

The Japanese translation of `deleteAllLeft` in Keyboard Shortcuts is "残りをすべて削除する", which literally means "delete everything that remains," a clear mistranslation of the word "left." For consistency with `deleteAllRight` ("右側をすべて削除"), this should be "左側をすべて削除".

Extension version: 1.36.2
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

**Comment by lukaschal** [comment]
Fixed as suggested in a MLCP:

**Comment by weeteckt** [comment]
New language pack is published.
