### ISSUE TITLE
Cann't install Simplified Chinese extension in browser for VSCode Serer

### ISSUE THREAD

**Issue by mat-wang** [microsoft/vscode-loc#961]
Hello everyone,

These days I am testing the vscode server. I install the Simplified Chinese extension on remote server, all things going well, but when I install the extension for the browser, it shows an error:

```
The 'ms-ceintl.vscode-language-pack-zh-hans' extension is not available in Visual Studio Code for Web.
```

Is it a bug or anything with my environment going wrong? Thanks!

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 663685).

**Comment by cristianosuzuki77** [comment]
@TylerLeonhardt Could you assist here?

**Comment by TylerLeonhardt** [comment]
@mat-wang can you tell me how you are installing this language pack?

**Comment by mat-wang** [comment]
> @mat-wang can you tell me how you are installing this language pack?

Just like installing the language pack in vscode desktop. BTW, it works today with updating the microsoft vscode server.

**Comment by TylerLeonhardt** [comment]
Ok. Then I'll go ahead and close this. If see any issues, don't hesitate to open a new one!
