### ISSUE TITLE
[ko] Incorrect/ambiguous translation

### ISSUE THREAD

**Issue by zhixian001** [microsoft/vscode-loc#963]
![image](https://user-images.githubusercontent.com/22884435/180356646-f83b9b1b-048c-4971-ac66-8c08bea46880.png)

I found an incorrect Korean translation from command palette. The command `Git: 최신 슬래시 표시` should be `Git: 최신 스태시 표시`. (`슬래시` means slash(`/`))

> `Git: 최신 슬래시 표시` -> `Git: 최신 스태시 표시`

---

And while writing this issue, I found the word `표시` from `Git: 최신 스태시 표시` and `Git: 스태시 표시...` is ambiguous.  `표시` means `show` or `display`. This translation may be misleading the Korean users understand as `Show Stash` commands. So I suggest to update these commands as below.

> `Git: 최신 슬래시 표시` -> `Git: 최신 스태시 표시` -> `Git: 최신 스태시 꺼내기`
> `Git: 스태시 표시...` -> `Git: 스태시 꺼내기...`

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 664232).

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 664232)
