### ISSUE TITLE
[zh-Hans] Translation error for setting item `editor.suggest.showDeprecated`

### ISSUE THREAD

**Issue by CyanSalt** [microsoft/vscode-loc#966]
<img width="354" alt="image" src="https://user-images.githubusercontent.com/5101076/180786018-6307ca71-b7bd-404f-88e5-4c1c02e7658d.png">

```
启用后，IntelliSense 将显示“已启用”建议。
```

`已启用`("Enabled") should be `已弃用` ("Deprecated").

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 678242).

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 678242)
