### ISSUE TITLE
Where Can I Start localization language

### ISSUE THREAD

**Issue by muath-ye** [microsoft/vscode-loc#967]
Hi,
I want to start new language for vscode localization , where can I contribute?

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 680109).

**Comment by danyeh** [comment]
Please checkout how to topics in wiki.
![image](https://user-images.githubusercontent.com/19785531/181604441-de72ec47-ee3c-4f84-86d4-4ce49baef0db.png)
