### ISSUE TITLE
[German] Translation issues for Git SCM

### ISSUE THREAD

**Issue by LinqLover** [microsoft/vscode-loc#968]
This is wrong:

![image](https://user-images.githubusercontent.com/38782922/181613671-94808ca4-ddf3-4ada-bd27-8809306f853d.png)

It should be named "Branch veröffentlichen" instead of "Filiale veröffentlichen".

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 680689).

**Comment by danyeh** [comment]
Translation is now '{0} Branch veröffentlichen' by following feedback of https://github.com/microsoft/vscode-loc/issues/943

**Comment by LinqLover** [comment]
Thanks!
