### ISSUE TITLE
[vscode-remote][de] Tippfehler: Remoteverbindung scließen

### ISSUE THREAD

**Issue by gitoni** [microsoft/vscode-loc#97]
Issue Type: [bug][typo]
Language: German [de]
Extension: [vscode-remote]

Wenn ich eine SSH Verbindung geöffnet habe und diese schließen möchte, gibt es neuerdings den Eintrag
Datei->Remoteverbindung scließen
super, das fehlte noch in der letzen Version!

In der Deutschen Version hat es noch einen Tippfehler: "scließen" statt "schließen"

Extension version: 0.44.0
VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)

**Comment by lukaschal** [comment]
"scließen" not occurs in a translated strings in a MLCP platform for now.
