### ISSUE TITLE
[zh-Hans] Translation error for keybinding `workbench.action.lastEditorInGroup`

### ISSUE THREAD

**Issue by HumphreyDotSln** [microsoft/vscode-loc#970]
![image](https://user-images.githubusercontent.com/31343548/182032947-a5dab176-ba1d-4c90-a552-ca73400024db.png)
`上一个编辑器` -> `最后一个编辑器`

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 681842).

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 681842)
