### ISSUE TITLE
[ja]Duplicated menu item translation on Windows Platform

### ISSUE THREAD

**Issue by finok** [microsoft/vscode-loc#971]
When using the Japanese language pack, right-click on a file in the source control view to see that the translations of the two menu items are duplicated.
![Snipaste_2022-08-02_18-36-22](https://user-images.githubusercontent.com/43756043/182358385-58f0c8db-88a1-4bf6-a2ba-d718ceb342f6.png)

**Comment by finok** [comment]
Please ignore the hiragana "する" at the end as it doesn't have any real meaning, in fact these two menu items mean the same thing.

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 684454).

**Comment by crsuzukimsft** [comment]
Hello @finok

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 684454)
