### ISSUE TITLE
[ja] translation suggestion for Command Decoration

### ISSUE THREAD

**Issue by nebocco** [microsoft/vscode-loc#989]
The wording regarding [Command Decoration](https://code.visualstudio.com/updates/v1_69#_decorations) seems unnatural.

![screen shot 1](https://user-images.githubusercontent.com/73807432/183840427-8f0e7349-2d87-46b9-854a-6b9868f4087d.png)
 
![screen shot 2](https://user-images.githubusercontent.com/73807432/183840432-855a2916-055e-43b7-982a-de5206301705.png)

https://github.com/microsoft/vscode-loc/blob/567eeb26e1721dcb9c6d29d59cc9687dfc843114/i18n/vscode-language-pack-ja/translations/main.i18n.json#L8760-L8777

I propose to modify this block as follows:

```json
"vs/workbench/contrib/terminal/browser/xterm/decorationAddon": {
	"changeDefaultIcon": "既定のアイコンを変更",
	"changeErrorIcon": "エラー時のアイコンを変更",
	"changeSuccessIcon": "正常終了時のアイコンを変更",
	"gutter": "コマンド左側のアイコン",
	"overviewRuler": "コマンド右側の概要ルーラー",
	"terminal.configureCommandDecorations": "コマンド装飾の設定を変更",
	"terminal.copyCommand": "コマンドをコピー",
	"terminal.copyOutput": "出力をコピー",
	"terminal.copyOutputAsHtml": "出力を HTML としてコピー",
	"terminal.learnShellIntegration": "シェル統合に関する詳細情報",
	"terminal.rerunCommand": "コマンドを再実行",
	"terminalPromptCommandFailed": "コマンドは {0} に実行され、失敗しました",
	"terminalPromptCommandFailedWithExitCode": "コマンドは {0} に実行され、失敗しました (終了コード {1})",
	"terminalPromptCommandSuccess": "コマンドは {0} に実行されました",
	"terminalPromptContextMenu": "コマンド操作を表示",
	"toggleVisibility": "表示を切り替え"
},
```

Here are the supplementary explanation for each adaptation (in Japanese).

<details>
<summary>supplementary explanation</summary>

### changeXXXIcon, toggleVisibility

「アイコンの変更」では「変更」が名詞的な扱いになるのに対して、ここでは「変更する」という動作を表したいため、助詞を「を」に変更しました。toggleVisibility についても同様です。
また、エラーアイコンやサクセスアイコンという複合語での表現が分かりづらかったため、やや説明的に変更しました。

### gutter, overviewRuler

この箇所はかなり翻訳が難しく、上記の提案は元の文章からはかけ離れたものになっています。
日本語の「デコレーション」原文で「Decoration」と表現されているものが実際に何であるのかを「左側のアイコン」「右側のルーラー」と明確にしました。
もともとの「コマンド デコレーションの余白」は誤った翻訳であり、本来の意図としては「余白に表示する Command Decoration」という意味のはずです。

### terminal.configureCommandDecorations

`main.i18n.json` 全体に「装飾」と「デコレーション」が混在していたため、より個数の多い「装飾」に変更しました。
また、ここでの configure で行う操作を考えると訳語としては「構成」ではなく「設定」あるいは「（設定の）変更」のほうが適切です。

### copyCommand, rerunCommand

翻訳間違いです。

### copyXXX

コピーを行う場合は単に「コピー」と書かれている方が一般的だと思われます。

### terminalPromptCommand

ここでの `{0}` は実行時からの経過時間が入るため、「実行」の目的語ではありません。

### terminalPromptContextMenu
https://github.com/microsoft/vscode/issues/143791 での議論によると、ここでの Show Command Actions は「クリックすることで Command Actions を表示します」という意味のようです。そこで、先の issue で挙げられていた箇所を参考に変更しました。

</details>

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 689365).

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 689365)
