### ISSUE TITLE
不一致翻譯：延伸模組 vs 擴充功能

### ISSUE THREAD

**Issue by MuTsunTsai** [microsoft/vscode-loc#99]
在繁體中文版中，「extension」這個字有兩種翻法存在：「延伸模組」和「擴充功能」，前者出現超過 250 次而後者超過 100 次。我個人認為兩種翻譯都可以接受，但是建議統一使用其中一種，不要混用。

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
Approved change is replace 擴充功能 with 延伸模組.

**Comment by lukaschal** [comment]
Implemented.
