### ISSUE TITLE
[ja] translation suggestion

### ISSUE THREAD

**Issue by nebocco** [microsoft/vscode-loc#990]
The configuration file contains a mixture of 装飾 and デコレーション as translations of "decoration."

https://github.com/microsoft/vscode-loc/blob/567eeb26e1721dcb9c6d29d59cc9687dfc843114/i18n/vscode-language-pack-ja/translations/main.i18n.json#L3471

https://github.com/microsoft/vscode-loc/blob/567eeb26e1721dcb9c6d29d59cc9687dfc843114/i18n/vscode-language-pack-ja/translations/main.i18n.json#L8912

Therefore, I propose to unify them into 装飾 which is more concise expression.

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 689366).

**Comment by cristianosuzuki77** [comment]
fixed
