### ISSUE TITLE
[Italian] commit and Uppercasing

### ISSUE THREAD

**Issue by pizzolante** [microsoft/vscode-loc#991]
Hi,
I'd strongly suggest reverting this line:

https://github.com/microsoft/vscode-loc/blob/567eeb26e1721dcb9c6d29d59cc9687dfc843114/i18n/vscode-language-pack-it/translations/extensions/git.i18n.json#L16
to:
https://github.com/microsoft/vscode-loc/blob/2fe37fbcedaf5f02e4b38edec7ce1d3b608ee7d6/i18n/vscode-language-pack-it/translations/extensions/git.i18n.json#L16

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 689367).

**Comment by csigs** [comment]
{ body = Resolved as Fixed. }The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 689367)
