### ISSUE TITLE
[zh-CN] Wrong translation about `AuxiliaryBar`

### ISSUE THREAD

**Issue by liangjiancang** [microsoft/vscode-loc#994]
The translation of AuxiliaryBar exists in two forms: "辅助**侧**栏", "辅助**边**栏". ("辅助侧栏" is recommended)
And "workbench.action.maximizeEditor" is translated as "视图: 最大化编辑器组并隐藏**边**栏, while most are translated as "**侧**栏" instead of "**边**栏".

![Snipaste_2022-08-14_11-01-53](https://user-images.githubusercontent.com/42267675/184521210-04a577f6-4ccb-4634-b7ee-adf4c286f5f1.png)
![Snipaste_2022-08-14_11-36-03](https://user-images.githubusercontent.com/42267675/184521399-9a1064bf-eaf0-4023-bac3-09dea68d9661.png)
![Snipaste_2022-08-14_11-36-11](https://user-images.githubusercontent.com/42267675/184521401-5411d12f-a208-45f4-9503-4e1ed9b2bcfe.png)

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 692047).

**Comment by cristianosuzuki77** [comment]
Fixed
